### ISSUE TITLE
ChatGPT model version needs to be changed to '0301'

### ISSUE THREAD

**Issue by PlagueHO** [Azure-Samples/azure-search-openai-demo#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Run the `az up` on the sample.

### Any log messages given by the failure
```text
ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '72f18fff-ca05-4848-8786-e08a33fad548'. See inner errors for details.
DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-35-turbo, Version: 1' of account deployment is not supported.
```

### Expected/desired behavior
The demo deploys correctly without error.

### OS and Version?
Windows 11

### Versions
Latest

### Mention any other details that might be useful
To fix, change https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/main.bicep#L109 to `0301`.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pablocastro** [comment]
Thanks for reporting. Fixed in https://github.com/Azure-Samples/azure-search-openai-demo/commit/2d6662963e79f7b3355bab9fe6eb3067f2a940d2

**Comment by sivi3883** [comment]
@pablocastro The demo code works perfectly! Thanks a bunch. 
I am trying to deploy the gpt-35-turbo model 0613 version to see if this model version follows the prompt instruction more aggressively than 0301 (which is referred in the demo code). I changed the version from 0301 to 0613 in the main.bicep file and ran azd up but only the gpt-35-turbo model 0301 keeps getting deployed. Please let me know how to fix this issue.

**Comment by pamelafox** [comment]
@sivi3883 Please see #43
