### ISSUE TITLE
Refresh UX screenshot - still mentions Cognitive Search

### ISSUE THREAD

**Issue by charris-msft** [Azure-Samples/azure-search-openai-demo#1012]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> View the Readme.md

### Expected/desired behavior
> UX screenshot is updated to match current UX and mentions "AI Search" rather than "Cognitive Search"

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
PRs welcome ;-) 

But yeah can update. Do you think it should be a GIF or video while we're at it? Or are they distracting?

**Comment by charris-msft** [comment]
Personally, I think they are distracting when they play over and over.

But it would be nice to have a static image with a play button the user can click if desired. I'm not sure if that's possible though.

Thanks,
Chris

**Comment by john0isaac** [comment]
@pamelafox this issue is done.
Can you please close it?

**Comment by pamelafox** [comment]
good catch, closing!
