### ISSUE TITLE
How You have deployed gpt-3.5-trubo on azure. Because i see from code. You are not making direct call to OPENAI rest apis

### ISSUE THREAD

**Issue by sunnygambit1989** [Azure-Samples/azure-search-openai-demo#1018]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sunnygambit1989** [comment]
@pamelafox  Can you help me here.

**Comment by pamelafox** [comment]
Hm, I do not understand the question. We use the openai package for making calls to OpenAI, and we provision the OpenAI deployments using the Bicep in the infra folder. What are you trying to figure out?

**Comment by sunnygambit1989** [comment]
If i call direct openai api. It is taking time but from this sample code it responds within 2 seconds. 

My question is gpt model is deployed in azure environment or you guys making external api call crom azure. 
as i can see in code that there is no external code. There is deployment id.

**Comment by pamelafox** [comment]
This is the primary call that we make to the ChatCompletion API:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/13e4cd8476c42158e708662539ce101b5b6a9655/app/backend/approaches/chatreadretrieveread.py#L218

By default, this app uses Azure OpenAI, so it is making a call to your Azure OpenAI deployment behind the scenes, whichever deployment is specified. The openai package calls the REST API but wraps it in Python functions.

**Comment by sunnygambit1989** [comment]
Just wanted to get confirmation thanks @pamelafox

**Comment by sunnygambit1989** [comment]
Resolved
