### ISSUE TITLE
When will code support azure-ai-documentintelligence ==1.0.0b1 instead of current azure-ai-formrecognizer==3.3.2

### ISSUE THREAD

**Issue by rebeccaleeasml** [Azure-Samples/azure-search-openai-demo#1036]
> Please provide us with the following information:
> ---------------------------------------------------------------

azure-ai-formrecognizer==3.3.2 has problem in parsing our PDF, azure-ai-documentintelligence ==1.0.0b1 handles our PDF correctly
When can this open source code to support azure-ai-documentintelligence ==1.0.0b1 

Some reference: 

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/MIGRATION_GUIDE.md

https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/changelog-release-history?view=doc-intel-3.1.0&tabs=python#november-2023-preview-release

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by srbalakr** [comment]
@rebeccaleeasml just an heads up. Azure AI search has a new feature adding a vectorizer to index. It takes care of parsing pdf and chunking data to index. It should protect from sdk issues.

**Comment by rebeccaleeasml** [comment]
Hi, Pamela:

I can not share through the open source channel. But if you can pin me through team and through Microsoft, I can share more information with you, since Microsoft and my company has signed NDA.

Rebecca

**Comment by pamelafox** [comment]
Branch for the new azure-ai-documentintelligence package:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1224

Branch for integrated vectorization:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1159

**Comment by pamelafox** [comment]
Closing this, since we merged both those branches.
