### ISSUE TITLE
Azure Developer CLI could not be found for deployed application

### ISSUE THREAD

**Issue by echen101** [Azure-Samples/azure-search-openai-demo#1059]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I deployed the app to Azure App Service through `azd up`. The deployment was successful. However, when sending a query to backend, it shows an error that "Azure Developer CLI could not be found".

### Any log messages given by the failure
>
```
Error: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
```
### Expected/desired behavior
> Expected behavior is to get answers from the backend.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS Ventura 

### azd version?
> run `azd version` and copy paste here.
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

### Versions
>

### Mention any other details that might be useful
It was working but start failing after the most recent deployment. There was no changes of azd environments or anything I could connect with the error.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
When do you get the error? I'm not sure what you mean by "send query to backend"? Is that locally or in production?

**Comment by echen101** [comment]
@pamelafox thanks for the reply. It happened in production azure app service. However, the error was gone after I ran azd up again to redeploy the app.
