### ISSUE TITLE
Index was not created after recent updates about vision support

### ISSUE THREAD

**Issue by freedragon** [Azure-Samples/azure-search-openai-demo#1063]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Just deploy service from scratch.

### Any log messages given by the failure
> Log seems OK. But, the index created after deployment looks empty with default setting using Document Intelligence. No answer was generated due to empty index. I'm using this accelerator during training session. It was reproed consistently.

### Expected/desired behavior
> PDF document should be indexed properly and answer should be generated according to search result.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) Windows 11 WSL2, GitHub Codespaces.

### azd version?
> azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I suspect that we introduced a bug in the prepdocs script. Can you try removing --tenantid from either prepdocs.ps1 or prepdocs.sh, whichever you ran, and then re-running ./scripts/prepdocs.sh or ./scripts/prepdocs.ps1?

**Comment by mattmsft** [comment]
#1064

**Comment by mattmsft** [comment]
@freedragon  can you please try again using the latest main

**Comment by freedragon** [comment]
I just tried it from scratch with tenantId removed.

But, there's no change. It's strange but pdf files were not spliedt in to pages, too. I can only see original PDF files from content container of blob storage.

**Comment by mattmsft** [comment]
We’ve removed the splitting of pages in a previous version. You can run the script successfully now?

**Comment by freedragon** [comment]
Unfortunately, no. I just tried again using latest main on GitHub Codespaces. But the index was empty. (documents count and storage size is 0 from Azure Portal)

Here's the part of logs from console. FIY.

Loading azd .env file from current environment...
Creating Python virtual environment "scripts/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Not updating authentication.
Loading azd .env file from current environment...
Creating Python virtual environment "scripts/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Running "prepdocs.py"
Processing files...
Using local files in ./data/*
Ensuring search index gptkbindex exists
Creating gptkbindex search index
Extracting text from './data/role_library.pdf' using Azure Document Intelligence
Splitting 'role_library.pdf' into sections
        Uploading blob for whole file -> role_library.pdf
Extracting text from './data/Benefit_Options.pdf' using Azure Document Intelligence
Splitting 'Benefit_Options.pdf' into sections
        Uploading blob for whole file -> Benefit_Options.pdf
Extracting text from './data/Northwind_Health_Plus_Benefits_Details.pdf' using Azure Document Intelligence
Splitting 'Northwind_Health_Plus_Benefits_Details.pdf' into sections
        Uploading blob for whole file -> Northwind_Health_Plus_Benefits_Details.pdf
Extracting text from './data/PerksPlus.pdf' using Azure Document Intelligence
Splitting 'PerksPlus.pdf' into sections
        Uploading blob for whole file -> PerksPlus.pdf
Extracting text from './data/Northwind_Standard_Benefits_Details.pdf' using Azure Document Intelligence
Splitting 'Northwind_Standard_Benefits_Details.pdf' into sections
        Uploading blob for whole file -> Northwind_Standard_Benefits_Details.pdf
Extracting text from './data/GPT4V_Examples/Financial Market Analysis Report 2023.pdf' using Azure Document Intelligence
Splitting 'Financial Market Analysis Report 2023.pdf' into sections
        Uploading blob for whole file -> Financial Market Analysis Report 2023.pdf
Extracting text from './data/employee_handbook.pdf' using Azure Document Intelligence
Splitting 'employee_handbook.pdf' into sections
        Uploading blob for whole file -> employee_handbook.pdf
...

**Comment by NarayanamoorthySrinivasan** [comment]
I am also facing same issue.

**Comment by pamelafox** [comment]
Please try the fix here:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1066

Sorry! We'll add more tests.

**Comment by NarayanamoorthySrinivasan** [comment]
That helped. Thanks.

**Comment by mattmsft** [comment]
Thank you @pamelafox !
