### ISSUE TITLE
Difference between chatreadretrieveread.py and chatreadretrievereadvision.py

### ISSUE THREAD

**Issue by waqasjavedkhan** [Azure-Samples/azure-search-openai-demo#1065]
> Please provide us with the following information:
> ---------------------------------------------------------------
Hi @pamelafox, What is the difference between chatreadretrieveread.py and chatreadretrievereadvision.py? Which code file do I need to use for User Query Opmizatization and Response Generation Prompts in the Chat approach?

Sorry, I'm kind of confused between the two. 

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@waqasjavedkhan I've put an explanation in https://github.com/Azure-Samples/azure-search-openai-demo/pull/1067/files but basically, you should only use chatreadretrievereadvision.py if you're planning to use GPT 4 Turbo with Vision, i.e. you have a very image heavy use case. That's fairly experimental and we expect most customers will be sticking with the standard approaches.
