### ISSUE TITLE
Computer Vision key versus managed identity

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo#1076]
It looks like from the /infra that Computer Vision uses a key whereas the rest of the Azure services use managed identity/service principals/roles.

Is it possible to change away from key for this service to use MI/SP/RBAC roles?

**Comment by pamelafox** [comment]
Good question! I am attempting it in this PR:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1062
It works locally but not with the managed identity on App Service. I am awaiting further advice from vision team (in a teams thread).

**Comment by pamelafox** [comment]
Fixed! We use MI now.
