### ISSUE TITLE
The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' or contains blocked QuotaId/Feature

### ISSUE THREAD

**Issue by jroeglin** [Azure-Samples/azure-search-openai-demo#1084]
Hello, 
I face an issue while deploying the infrasture. I want to use the public OpenAI API. I provided the Terminal log below. Have anyone an idea?

### This issue is for a:
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
VS Code Dev Containers or Local environment i tried both and get the same error. 
Branch: main
>azd auth login
>azd init -t azure-search-openai-demo
>azd env set OPENAI_HOST openai
>azd env set OPENAI_ORGANIZATION {My organization id}
>azd env set OPENAI_API_KEY {My OpenAI key}
>azd up

We have a standard subscription & i have Owner access right for the subscription.

### Any log messages given by the failure
>PS C:\Repository\azure-search-openai-demo> azd up
>
>Packaging services (azd package)
>
>
>up to date, audited 260 packages in 875ms
>
>found 0 vulnerabilities
>  |===    | Packaging service backend
>> frontend@0.0.0 build
>> tsc && vite build
>
> |      =| Packaging service backendvite v4.5.1 building for production...
>✓ 4200 modules transformed.
>../backend/static/index.html                             0.77 kB │ gzip:   0.38 kB
>../backend/static/assets/github-fab00c2d.svg             0.96 kB │ gzip:   0.52 kB
>../backend/static/assets/OneShot-0a57a895.css            0.83 kB │ gzip:   0.39 kB
>../backend/static/assets/index-436dc179.css              7.31 kB │ gzip:   2.26 kB
>../backend/static/assets/NoPage-ea4b1efc.js              0.18 kB │ gzip:   0.18 kB │ map:     0.36 kB
>../backend/static/assets/OneShot-0e8347a4.js             4.88 kB │ gzip:   2.06 kB │ map:    21.47 kB
>../backend/static/assets/fluentui-icons-e67e11a4.js      5.67 kB │ gzip:   2.56 kB │ map: 4,322.77 kB
>../backend/static/assets/index-a42e17fe.js              25.00 kB │ gzip:   8.86 kB │ map:   100.40 kB
>../backend/static/assets/fluentui-react-63b3d3f8.js    337.68 kB │ gzip:  95.09 kB │ map: 1,480.88 kB
>../backend/static/assets/vendor-7810ac01.js          1,687.91 kB │ gzip: 535.84 kB │ map: 5,151.39 kB
>
>(!) Some chunks are larger than 500 kBs after minification. Consider:
>- Using dynamic import() to code-split the application
>- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output->manualchunks
>- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
>✓ built in 18.36s
>  (✓) Done: Packaging service backend
>  - Package Output: C:\Users\JANNIS~1.ROE\AppData\Local\Temp\azure-search-openai-demo-backend-azddeploy-1703163532.zip
>Loading azd .env file from current environment
>
>Provisioning Azure resources (azd provision)
>Provisioning Azure resources can take some time.
>
>Subscription: Azure subscription 1 (...)
>Location: West Europe
>
>  You can view detailed progress in the Azure Portal:
>  https://portal.azure.com/#view/HubsExtension/...
>
>  (✓) Done: Resource group: rg-azureTest
>  (✓) Done: Storage account: stbpeqcczeqj5hk
>  (✓) Done: Search service: gptkb-bpeqcczeqj5hk
>  (✓) Done: Log Analytics workspace: log-bpeqcczeqj5hk
>  (✓) Done: App Service plan: plan-bpeqcczeqj5hk
>  (✓) Done: Application Insights: appi-bpeqcczeqj5hk
>  (✓) Done: Form recognizer: cog-fr-bpeqcczeqj5hk
>  (✓) Done: Portal dashboard: dash-bpeqcczeqj5hk
>
>ERROR: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
>
>Deployment Error Details:
>InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is >''. See inner errors for details.
>SpecialFeatureOrQuotaIdRequired: The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' or >contains blocked QuotaId/Feature.
>
>TraceID: 
>
>Suggested Action: The selected subscription has not been enabled for use of Azure AI service and does not have quota for any >pricing tiers. Please visit https://ms.portal.azure.com/ and select 'Create' on specific services to request access.

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.5.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tonybaloney** [comment]
Thanks for the report, please see the comment on a duplicate issue, there is a section in the README about enabling access https://github.com/Azure-Samples/azure-search-openai-demo/issues/114#issuecomment-1511377087
