### ISSUE TITLE
Deployment got succeeded but when browsing the URL getting error 

### ISSUE THREAD

**Issue by rahulsnc3it** [Azure-Samples/azure-search-openai-demo#109]
We are able to deploy the required service and getting the endpoint url after successful deployment in PowerShell.

When trying to browse the URL getting error

![image](https://user-images.githubusercontent.com/54054761/231475764-2ba95f66-0a41-45e0-b7a3-bbd1332be1f2.png)

![image](https://user-images.githubusercontent.com/54054761/231478013-abe88f7a-0030-4f65-8673-1e89a3b39f18.png)

**Comment by jamesearlpace** [comment]
Same error for me. Looks like the app's startup process has not been properly configured

**Comment by jieseattle** [comment]
same problem.

**Comment by ykbryan** [comment]
same for me

**Comment by vhvb1989** [comment]
Can you try running `azd deploy` and see if that fix this for you.  This command deploys the web app into Azure.

**Comment by vhvb1989** [comment]
The link you are trying to open is the url for the `backend` which is not a web app.  The front end app runs only locally and connects to the backend api.

After `azd up`, a browser should have been opened with the front end running locally.

**Comment by jamesearlpace** [comment]
> 

Thanks @vhvb1989 for the reply. Just tried it again and it doesn't open up the page automatically for me.

**Comment by Shazebgk** [comment]
Even I have the similar issue. 
Tried multiple times to deploy and getting stuck on same error

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by gitpsk** [comment]
same problem

<img width="623" alt="image" src="https://user-images.githubusercontent.com/60507965/231567671-f128f834-584b-49a9-a4e5-9d38d13cca99.png">

deployment success

**Comment by Shazebgk** [comment]
gitpsk did it work?

**Comment by jieseattle** [comment]
it now works after another azd deploy,

**Comment by rahulsnc3it** [comment]
gitpsk do we need to run azd deploy after azd up command

**Comment by gitpsk** [comment]
yes right

**Comment by rahulsnc3it** [comment]
Thanks it worked also any idea on how we can add documents and index them after deployment as it is only train on sample docs

**Comment by gitpsk** [comment]
delete the existing index alone in the Azure and add your pdf docs in data folder and then run /Scripts/prepdocs.sh

**Comment by andremcastro** [comment]
same error here.. even after run azd deploy multiple times

**Comment by pamelafox** [comment]
@andremcastro Could you check the default_docker logs in App Service and share what error you see? See the FAQ or troubleshooting for tips on finding the logs (its a bit confusing).

**Comment by andremcastro** [comment]
[dockerlogs.txt](https://github.com/Azure-Samples/azure-search-openai-demo/files/13194161/dockerlogs.txt)
looks like its ok

**Comment by andremcastro** [comment]
fixed, I was using an old version of az cli

**Comment by erykkadziela** [comment]
same issue for me :(

**Comment by SHALINI-2000-416** [comment]
same issue for me can someone send detailed documentation of resolution
