### ISSUE TITLE
Questions about Azure AI Search and other things.

### ISSUE THREAD

**Issue by BlackLight367437** [Azure-Samples/azure-search-openai-demo#1094]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Versions
> GPT 3.5 or GPT 4

### Mention any other details that might be useful

Hi @PamelaFox,

We're wondering if you're able to advise on the below:

1. We've got PDF documents (let's say, on one page there are around 1000 tokens).
How we can make the Chatbot reply with the entire content of that page?
For now, Chatbot seems to be only replying with only partial content of the document. Let's say there's an instruction that covers the whole page (15 points), but Chatbot will reply only with the 5 first points.

2. We've got problems with Azure AI Search not finding the right articles. 
For example, two matches are not relevant and the third match is relevant. (Please refer to the attached screenshot).
<img width="782" alt="Samples" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/147877945/4262fe41-2441-4289-90d1-590798d6de41">
How we can tweak Azure AI Search performance?

3. When the Integrated Vectorisation is going to be available in this codebase/project? (Link for reference: https://learn.microsoft.com/en-us/azure/search/vector-search-integrated-vectorization )
 
4. Is it possible for OCR to ignore the pictures within the PDF documents?

Thank you in advance for your advisory.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by BlackLight367437** [comment]
Hi @pamelafox
Any chance to get your wise advisory on the matters? :)

Best Regards

**Comment by mattmsft** [comment]
Hi @BlackLight367437 ,

1. The Chatbot has a limited amount of words (tokens) that it can reply with. You can edit the system prompt to be more verbose, but please note that this increases the cost as the chatbot is priced by the amount of words (tokens) it replies with. You can use the citation tab to view the rest of the documents it used to answer the question
2. Regarding Search performance - sorry to hear the search isn't finding the right documents. Please review the following articles to understand how search scoring works
https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-cognitive-search-outperforming-vector-search-with-hybrid/ba-p/3929167
https://learn.microsoft.com/en-us/azure/search/index-similarity-and-scoring
https://learn.microsoft.com/en-us/azure/search/vector-search-ranking
https://learn.microsoft.com/en-us/azure/search/hybrid-search-ranking
https://learn.microsoft.com/en-us/azure/search/semantic-search-overview

I also recommend going into developer settings and changing the default hybrid search method to either text or vector and see how that impacts your results.

3. Please track #1020 
4. Yes, this will be easier to do when integrated vectorization is available, or you can edit prepdocs.py to remove any additional scanning functionality you do not want

**Comment by mattgotteiner** [comment]
I hope I answered your question
