### ISSUE TITLE
This repo solution vs Azure OpenAI studio connecting to own data 

### ISSUE THREAD

**Issue by sonphnt** [Azure-Samples/azure-search-openai-demo#1100]
Hi, I have a question about this repo solution and the Preview feature in Azure OpenAI studio where we can connect to our own data and deploy a built-in chat UI to an Azure App Service. Is there any difference between these two solutions?

Thanks

**Comment by marvika** [comment]
Hey @sonphnt, in the FAQ on the repo there is a text explaining the difference:
https://github.com/Azure-Samples/azure-search-openai-demo#faq

**Comment by sonphnt** [comment]
@marvika  thanks. I got it.
