### ISSUE TITLE
unable to authenticate with my non-production tenant 

### ISSUE THREAD

**Issue by mkhazen** [Azure-Samples/azure-search-openai-demo#1105]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request  
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I am trying to authenticate with my non-production tenant - I am prompted to approve the login (I use SSO) on my phone it looks as if it will connect then it returns an error something similar to this: 

_localhost 39927 failed  to connect or refused connection_

If i do not specify my non-production tenant ID It will automatically connect to my production tenant (which is managed by Microsoft) even though i set up my non-production tenant as the default one

I updated the env variable to include all of the information for my non-production tenant it still ignores it and once i specify specifically to use my non-production login  az login --tenant xxxx.onmicrosoft.com then it returns local host failed to connect error 

I created a service principal but i am not able to interactively authenticate with my service principal - In my environment my authentication uses SSO and it is the same email address my (Microsoft email address for both tenant) 

### Any log messages given by the failure
>
localhost 39927 failed  to 

### Expected/desired behavior
>
need to be able to authenticate to my non-production tenant 
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
i am running codespace - i am using the lated supported versions of windows 

### azd version?
> run `azd version` and copy paste here.

### Versions
>
running with codespace. i created a new one only for this repo 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattmsft** [comment]
Is this using the authentication and authorization? Try setting AZURE_TENANT_ID for tenant id where your resources are provisioned, and AZURE_AUTH_TENANT_ID for the tenant id where your Entra apps are provisioned.

**Comment by mkhazen** [comment]
in the environment variable you mean? this is the same variable - i already have AZURE_TENANT_ID in my environment variable i just added the other one too - 
but still same error - as a sidenote i am trying to deploy everythign from scratch

**Comment by mattmsft** [comment]
We discussed this during troubleshooting - there's a conditional access policy set by the tenant admin we have no control over which prevents deployment. Sorry about that!
