### ISSUE TITLE
Save User Input regarding answer quality  

### ISSUE THREAD

**Issue by chazarabriseis** [Azure-Samples/azure-search-openai-demo#1116]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

After someone asked a question on the onshot page, I would like  to get feedback, eg if the answer was helpful, how much time it saved the user, let the user choose from a dropdown what the question was about (to analyse later) and ask for the user initials. I then want to save this information together with the question and answer to an appendblob, so I can analyse the usage&quality regularly and improve the prompt etc. if needed. Is there a code example available on how to do this? I am especially interested in the API call to append to a blob in the context of this repo. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This request is similar to https://github.com/Azure-Samples/azure-search-openai-demo/issues/1116 so I'm going to close this issue as a duplicate. 

You could check out the code in https://github.com/microsoft/sample-app-aoai-chatGPT/pull/396/files which adds feedback buttons to a very similar chat app.
