### ISSUE TITLE
How to add resource tags during deployment?

### ISSUE THREAD

**Issue by kail85** [Azure-Samples/azure-search-openai-demo#1122]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> current `azd up` won't allow add tags during deployment.

### Any log messages given by the failure
> no

### Expected/desired behavior
> Deployed resources have desired tags.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> 1.4.3

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jongio** [comment]
You can add the tags in the bicep found in infra folder.  If you tell me more about your needs I can help further.

**Comment by kail85** [comment]
Thanks. I modified below line in `main.bicep`, hope it's the right place?

`var tags = { 'Project': 'Azure Experiment', 'Phase': 'Research' }`

**Comment by jongio** [comment]
that should work let me know if you run into any issues
