### ISSUE TITLE
Azure OpenAI or Openai.com OpenAI for deployment

### ISSUE THREAD

**Issue by kail85** [Azure-Samples/azure-search-openai-demo#1126]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In the readme section [Existing OpenAI resource](https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F14c5f113-c30b-4b12-a902-98e4ece4a15e%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fkyle-ai-test-1704919472), it's not clear if both Azure OpenAI and openai.com OpenAI are required or just one of them. 

If following [Deploying from scratch](Deploying from scratch), then I noticed slow text embedding from the message

`Rate limited on the OpenAI embeddings API, sleeping before retrying`

Which openai was used, Azure OpenAI or Openai.com OpenAI?
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattgotteiner** [comment]
deploying from scratch uses Azure OpenAI
