### ISSUE TITLE
Unable to launch web app after successful deployment

### ISSUE THREAD

**Issue by kail85** [Azure-Samples/azure-search-openai-demo#1127]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Below are my steps:
1. In Azure Portal, I created a resource group "ai-test"
2. In the Codespaces, I set the environment of the existing resource group and its location
```
azd env set AZURE_RESOURCE_GROUP ai-test
azd env set AZURE_LOCATION "East US"
```
3. Run `azd up`
4. After about 25 mins, all resources were successfully deployed, and an end point url was available.
5. I waited for 30 mins, clicked the endpoint url, the page shows an error message  `:( Application Error`
6. I waited longer, and tried the endpoint url again but the same error message.

### Any log messages given by the failure
> no error messages.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.5.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattgotteiner** [comment]
@pamelafox in case there are any other deployment hints


I would check your app service logs and see if there are any error messages
https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs

Please share them if you find them

**Comment by kail85** [comment]
I deleted the failed deployment before I saw your reply. 

During my second attempt, I did not designate a pre-established resource group, instead allowing the deployment program to generate one. The web application was successfully launched without encountering any problems.

> @pamelafox in case there are any other deployment hints
> 
> I would check your app service logs and see if there are any error messages https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs
> 
> Please share them if you find them
