### ISSUE TITLE
Configuring existing solution with Private endpoints 

### ISSUE THREAD

**Issue by rahulsnc3it** [Azure-Samples/azure-search-openai-demo#1139]
Have configured Private endpoints for all the services that are provisioned by Az up command also able to access all the services via Azure VM with private IPs but when trying to access the application and passing the query getting error cannot connect to Open AI service 

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/54054761/3f266b75-32a4-4183-8275-f30b53f1901b)

Has anyone tried configuring the solution with private endpoint

**Comment by mattgotteiner** [comment]
HI @rahulsnc3it ,

Thanks for the feedback. We have a feature branch which includes private endpoint support, please let me know if this helps

!864

**Comment by rahulsnc3it** [comment]
Hi @mattgotteiner,

Thank you for the update

**Comment by VikashLalit** [comment]
@rahulsnc3it Hi Rahul
I am also facing the same issue , all of my resources are configured for selected network and private endpoint.

please let me know if above suggestions worked for you .

Thanks

**Comment by pamelafox** [comment]
We have now merged the PR that adds support for private endpoints. See the guide for enabling here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_private.md

Please file a new issue if you have questions about that configuration.
