### ISSUE TITLE
KeyError when using QueryType.SEMANTIC in search_client.search()

### ISSUE THREAD

**Issue by nexinteractive** [Azure-Samples/azure-search-openai-demo#115]
I am writing to report an issue I encountered while running "chat-read-retrieve-read.ipynb" in VS notebook. When calling the search_client.search() function with QueryType.SEMANTIC, I receive a KeyError: 'SEMANTIC'. I suspect that the issue might be related to the enumeration class QueryType not having the 'SEMANTIC' member, or there is an issue with the case-insensitivity of the enumeration member lookup.

Here is the code snippet where I call the search_client.search() function:

search_client.search(search, 
                     filter=filter,
                     query_type=QueryType.SEMANTIC, 
                     query_language="en-us", 
                     query_speller="lexicon", 
                     semantic_configuration_name="default", 
                     top=3)

The error message I receive is:

KeyError: 'SEMANTIC'

I would appreciate it if you could help me understand the cause of this error and how to resolve it. If the issue is related to the absence of the 'SEMANTIC' member in the QueryType enumeration class, please let me know the correct member name to use. If there is an issue with the enumeration member lookup, I would appreciate any guidance on how to address it.

Please let me know if you need any additional information to diagnose and resolve this issue.

Thank you for your assistance.

### Minimal steps to reproduce
> run "chat-read-retrieve-read.ipynb" in VS notebook

### OS and Version?
> Windows 11

### Versions
> Python 3.9.2

**Comment by DanielSchripsema** [comment]
I have the same issue

**Comment by DanielSchripsema** [comment]
Nevermind, mine is working now, you just have to install the beta.
You can do that by entering this in your terminal:
"pip install azure-search-documents==11.4.0b3"

if you are using anaconda you have to do the same thing, anaconda doesn't have the right version yet.

[The solution i found](https://stackoverflow.com/questions/75955596/azure-cognitive-search-got-an-unexpected-keyword-argument-query-language-in-p)
