### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Azure-Samples/azure-search-openai-demo#1165]
I still get the following error, when running azd up

 File "C:\Workspace\engenious\azure-search-openai-demo\scripts\prepdocs.py", line 5, in <module>
    from azure.core.credentials import AzureKeyCredential
ModuleNotFoundError: No module named 'azure'

I tried to install all python extension with pip, but nothing worked.
Any ideas?

Regards
Andreas

**Comment by andreas-sommer-engenious** [comment]
Thanks. The main problem was the python version 3.12. Since I downgraded to 3.11. everything works fine. Thanks a lot.

**Comment by prlj13** [comment]
> pip install -r requirements-dev.txt

This fixed it for me with Python 3.13.7, thanks @mattgotteiner
