### ISSUE TITLE
The answer is in english

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Azure-Samples/azure-search-openai-demo#1177]
Hi,
I have a problem with the language of the answers. I set the parameter AZURE_SEARCH_QUERY_LANGUAGE=de-DE. But depending on the questions, the bots ansers in english. How can I change the answering language?
Regards
Andreas

**Comment by pamelafox** [comment]
Hm, our prompt says to answer in the language of the question:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/ce5b9b0d8241f07396a5abfb4f4577bfc57b3260/app/backend/approaches/chatreadretrieveread.py#L57

It might help if you rewrite the prompt in German, if your audience is entirely German speaking. Have you tried that?
