### ISSUE TITLE
Deploy on platform other than Azure App Service Plan?

### ISSUE THREAD

**Issue by thwayant** [Azure-Samples/azure-search-openai-demo#1181]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> Hi, how do i deploy this application on a different platform? is it even possible to run this application without using azure app service plan?

Thank You

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, it is possible, as I have deployed it to Azure Container Apps. You just need an environment which can run Python. Is there a specific platform you're hoping to deploy on?

**Comment by thwayant** [comment]
> Yes, it is possible, as I have deployed it to Azure Container Apps. You just need an environment which can run Python. Is there a specific platform you're hoping to deploy on?

Thanks for the reply, our organization have an internal platform to deploy application, what i did was using "azd package" created a build file and turn that build file into a tar.gz file which we use to deploy apps, this is the error that i got

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/112543050/5f72685d-4abc-4252-ae04-7625f14f6111)

**Comment by pamelafox** [comment]
We now formally support deployment to Azure Container Apps:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-09-19
