### ISSUE TITLE
Error code: 400: context_length_exceeded

### ISSUE THREAD

**Issue by asevillano** [Azure-Samples/azure-search-openai-demo#1199]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Send about 5-6 questions in the chat mode that are generating about 8-10 lines in the answers

### Any log messages given by the failure
> Error code: 400 - {'error': {'message': "This model's maximum context length is 4096 tokens. However, you requested 4201 tokens (3177 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Expected/desired behavior
>Catch this error and reduce the size of the history removing the first question, so the prompt size is under control.
Another approach could be to identify if the last question is related to the previous one (with a call to the LLM model) so if the context has changed send only the last question

### OS and Version?
> Windows 11

### azd version?
> azd version 1.5.1

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
We do already have logic that truncates the message size based on token counts, but there must be a bug in it. Is your conversation in the English language?

**Comment by asevillano** [comment]
Hi Pamela,

In my case, the documents and conversations are in Spanish.

Thanks for your support!

Regards,
Angel

**Comment by pamelafox** [comment]
Fixing in https://github.com/Azure-Samples/azure-search-openai-demo/pull/1233
