### ISSUE TITLE
InvalidTemplateDeployment: The template deployment failed because of a policy violation

### ISSUE THREAD

**Issue by anjuthomas** [Azure-Samples/azure-search-openai-demo#120]
When running **azd up** command I get the following error : 

ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:_

_Deployment Error Details:
InvalidTemplateDeployment: The template deployment failed because of policy violation. Please see details for more information.
RequestDisallowedByPolicy: Resource 'cog-fr-y5qvgpwnkggwk' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyAssignments/35ee869489f24894b32aed2f"},"policyDefinition":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyDefinitions/e98df9f1-b3e4-4c56-9b0a-3fdeb1341a6f"}}]'.
InvalidTemplate: Deployment template validation failed: 'The template resource 'cog-y5qvgpwnkggwk/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1735' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.

**Comment by ian-t-adams** [comment]
@anjuthomas , @Ayo-faks 

I think you are both in an Azure subscription with policies that are blocking the deployment of Forms Recognizer. Since the policy blocks the deployment, you also get a segment length failure for the name since it does not get created.

**Comment by lehmus** [comment]
The latest commit has added parameters _gptDeploymentName_ and _chatGptDeploymentName_ to `main.parameters.json` and sets these values to `${AZURE_OPENAI_GPT_DEPLOYMENT}` and `${AZURE_OPENAI_CHATGPT_DEPLOYMENT}`, respectively. It seems that these environment variables are not set during the deployment. I was able to deploy successfully by changing the variables to point to existing instances of Azure OpenAI Service.

**Comment by chuwik** [comment]
I've reverted the latest commit, which appears to be root cause of these issues, there's more folks hitting problems in another issue thread.

**Comment by Ayo-faks** [comment]
Thanks @chuwik it deployes successfully.

**Comment by nirmalpatil** [comment]
I am getting the same error. 
Deployment template validation failed: 'The template resource 'cog-5ad5xqbyb5u4y/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1699' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'. (Code: InvalidTemplate)

What is the solution here?

**Comment by gizim79** [comment]
Same issue here. I've deployed before, this seem new?

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplate: Deployment template validation failed: 'The template resource 'cog-r3as5dqh7mcos/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1705' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name.

**Comment by tonybaloney** [comment]
I've reverted the last change, please try again by cloning the repository from scratch or doing `git pull` before a deployment

**Comment by mattmsft** [comment]
Sorry about that - my commit reintroduced this issue.

My suspicion is the root cause is here
https://github.com/Azure-Samples/azure-search-openai-demo/blob/868d238f0174551f3d6e87994ee9b470fa298e02/infra/core/ai/cognitiveservices.bicep#LL28C24-L28C24

> @batchSize(1)
resource deployment 'Microsoft.CognitiveServices/accounts/deployments@2023-05-01' = [for deployment in deployments: {
  parent: account
  name: deployment.name
  properties: {
    model: deployment.model
    raiPolicyName: contains(deployment, 'raiPolicyName') ? deployment.raiPolicyName : null
  }
  sku: {
    name: 'Standard'
    capacity: deployment.capacity
  }
}]

If the name is an empty string, it would fail with the incorrect segment length error.

Happy to help create a fix for this if necessary

**Comment by mattmsft** [comment]
#338

**Comment by onwudinjoonyekachi5-hash** [comment]
{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment failed because of policy violation. Please see details for more information.",
  "details": [
    {
      "code": "RequestDisallowedByAzure",
      "target": "univoteserver",
      "message": "Resource 'univoteserver' was disallowed by Azure: This policy maintains a set of best available regions where your subscription can deploy resources. The objective of this policy is to ensure that your subscription has full access to Azure services with optimal performance. Should you need additional or different regions, contact support.."
    }
  ]
}


please I need help.
