### ISSUE TITLE
Website as data source

### ISSUE THREAD

**Issue by pope-llamas0g** [Azure-Samples/azure-search-openai-demo#1210]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

This is not a bug but an inquiry. We have lots of documentation on Confluence, it would be great to feed all of the internal documentation into the private chatbot.

Any idea how to handle that kind of use case?

**Comment by pamelafox** [comment]
Yes, I actually talked about that in our live stream today-
Video - https://aka.ms/hacktogether/chatapp/session3 
Slides - https://speakerdeck.com/pamelafox/customizing-your-rag-chat-app

So, what I've done in the past is just converted the webpages to PDFs, fed those in the usual way, and then reversed the PDF filenames to figure out what URLs to show in the web UI. I used Playwright to save as PDF, per this blog post: https://blog.pamelafox.org/2024/01/converting-html-pages-to-pdfs-with.html

There are better approaches than that that involve more code, however.

1. Use Azure Document Intelligence to parse HTML. According to their docs, they now support HTML, so you would just need to modify the prepdocs filestrategy.py script to also look for .html files
2. Use a local HTML parser, and bring that into the prepdocs scripts. You can see how [PR 1195](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1195) adds a JSONParser, and make the same change to bring in an HTML parser. Here's a [possible HTML parser class](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/1e401acec3a713b528a1b9b83ee6e70fce10e208/scripts/data_utils.py#L299) you could use.

**Comment by pope-llamas0g** [comment]
Thank you Pamela, great video, it helped me a lot on understanding more the code.
