### ISSUE TITLE
Hide 'Citation' tab

### ISSUE THREAD

**Issue by en-coded** [Azure-Samples/azure-search-openai-demo#1212]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In most cases when a document (PDF) is not found the 'Citation' tab returns the following message:

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### Any log messages given by the failure
>

### Expected/desired behavior
> Can the 'Citation' tab be hidden from the Analysis Panel tabs? The links on the response on the Chat window can direct users to the 'Supporting Content' or the 'Thought Process' tab instead of linking to the 'Citation' tab which is blank most of the times when data in the index is not uploaded via PDFs.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Sure, you'd make these changes.

In AnalysisPanel.tsx: remove the Citation tab, this code:

```
            <PivotItem
                itemKey={AnalysisPanelTabs.CitationTab}
                headerText="Citation"
                headerButtonProps={isDisabledCitationTab ? pivotItemDisabledStyle : undefined}
            >
                {activeCitation?.endsWith(".png") ? (
                    <img src={citation} className={styles.citationImg} />
                ) : (
                    <iframe title="Citation" src={citation} width="100%" height={citationHeight} />
                )}
            </PivotItem>
```

In Chat.tsx, change onShowCitation to:

```
  const onShowCitation = (citation: string, index: number) => {
    if (
      activeCitation === citation && activeAnalysisPanelTab === AnalysisPanelTabs.SupportingContentTab && selectedAnswer === index
    ) {
      setActiveAnalysisPanelTab(undefined);
    } else {
      setActiveCitation(citation);
      setActiveAnalysisPanelTab(AnalysisPanelTabs.SupportingContentTab);
    }

    setSelectedAnswer(index);
  };
```

In Ask.tsx, change onShowCitation to:

```
  const onShowCitation = (citation: string) => {
    if (
      activeCitation === citation && activeAnalysisPanelTab === AnalysisPanelTabs.SupportingContentTab
    ) {
      setActiveAnalysisPanelTab(undefined);
    } else {
      setActiveCitation(citation);
      setActiveAnalysisPanelTab(AnalysisPanelTabs.SupportingContentTab);
    }
  };
```
