### ISSUE TITLE
search-service never completes deployment

### ISSUE THREAD

**Issue by evogelpohl** [Azure-Samples/azure-search-openai-demo#1218]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
using github spaces with project code version as of 2/1/24 (today)
successfully run `azd auth login`
run `azd env new` - use a new project name/rg.
run `azd up` with no changes to code.
select `east us` for both the services and openai.
starts to build deployment, gets to `search-service` - runs for > 1 hour, never completes.
in azure portal, I killed the deployment and tried over again. same. 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
:( When you get that error, could you try to log a support ticket from the Portal? Oftentimes the folks that respond to those support inquiries can look up more detailed logs. That sort of error looks like service flakiness to me, to be honest, so I would suggest retrying or trying a different region.

**Comment by evogelpohl** [comment]
Was a glitch w/ that region. Moved to westus and it worked.
