### ISSUE TITLE
Deployment failed: BadRequest: NetworkAcls is required for this resouce

### ISSUE THREAD

**Issue by mousaab** [Azure-Samples/azure-search-openai-demo#122]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
After successfully deploying hte Form recognizer, I get this error
***ERROR***: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
**BadRequest**: NetworkAcls is required for this resouce.
### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TheMLman** [comment]
I get the same error after successfully deploying App Service plan. I'm deploying from scratch without using any existing resources. 

The only things I changed are additional tags in the "var tags" variable of the "main.bicep" file because my company requires these to deploy new resources. I also hardcoded "param resourceGroupName string" in the "main.bicep" file, so the name of the new resource group complies with the naming conventions my company is using.

**Comment by TheMLman** [comment]
I found the issue. I had to clean the variables set up in the .env file of the .azure folder

**Comment by pauldj54** [comment]
Hi @TheMLman ,
I'm running into the same issue (I guess).
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/706754/7a1b9489-46ec-461b-8210-66f136ae2ec6)

I would like to know what do you mean with cleaning the variables in the .env file. Does it mean delete all of them?
In the .env I set:
AZURE_ENV_NAME="xxx"
AZURE_LOCATION="westeurope"
AZURE_OPENAI_RESOURCE_GROUP="xxx"
AZURE_OPENAI_SERVICE="xxx"
AZURE_PRINCIPAL_ID="xxx"
AZURE_SUBSCRIPTION_ID="xx"

If I delete them I don't think the application can run.

**Comment by mousaab** [comment]
it worked for me by starting from scratch with empty env file, thank you

**Comment by tetsuyasodo** [comment]
Hi. I got the same error in West Europe region. debug message didn't give me a clue to solve this issue.
For me, a fresh installation with an empty env file didn't work.
But deleting the env file AND changing the region to South Central US region worked fine.
I'm wondering whether this occurs only in West Europe.
Anyway, thank you for sharing your thoughts.

**Comment by Dag-Calafell-MCA** [comment]
Pull request 200 fixed this for me... it should be merged.

https://github.com/Azure-Samples/azure-search-openai-demo/pull/200
