### ISSUE TITLE
Logging all chat requests in backend

### ISSUE THREAD

**Issue by rupamGH** [Azure-Samples/azure-search-openai-demo#1226]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

Is there any possibility to log and store all chat requests (Questions + Answers) made by different users in the backend? Or at least all the questions they asked. 
If this feature is not there, would you please recommend the best way to do it by extending the code? 

Thanks in advance.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattgotteiner** [comment]
I do think we have logging on the following line, but it sounds like you want some kind of chat history feature? CC @pamelafox 

https://github.com/Azure-Samples/azure-search-openai-demo/blob/0ee189d6f6fd87e80a8b650fea5938ff017a87b9/app/backend/app.py#L400-L422

**Comment by pamelafox** [comment]
I think this is a fairly common feature that developers add to the app once they put in production, so they can better monitor answer quality. I think the most popular storage location is CosmosDB, but I think I saw someone use APIM as well.

I think you should keep in mind whether you need to strip any PII from the questions, and remember that you'll need to "un-stream" the streamed answers. Our logic for extracting followup_questions might help for the un-streaming aspect.

Other than that, I think you can stick them in the database of your choice.

**Comment by pamelafox** [comment]
Here's an APIM solution that does logging: https://learn.microsoft.com/en-us/azure/architecture/ai-ml/openai/architecture/log-monitor-azure-openai
And it's related repo:
https://github.com/Azure-Samples/openai-python-enterprise-logging

**Comment by zeltml01** [comment]
> Thank you. We tried, it works well.

Did you get this running within this app? If so, any help you can offer?
