### ISSUE TITLE
Error on running the deployed web app using the URL ":( Application Error If you are the application administrator, you can access the diagnostic resources."

### ISSUE THREAD

**Issue by junepochara** [Azure-Samples/azure-search-openai-demo#1227]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> - Open the project using VS code DevContainers: https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/azure-samples/azure-search-openai-demo
> - Run auth login
> - Run azd up
> - When asked to select locations during azd up, set the locations to northcentralus
> - Click on the link: https://app-backend...
> - Encounter the error (even after waiting for 5-10 minutes and refresh as suggested in the README.md inside the repo

### Any log messages given by the failure
> :( Application Error
If you are the application administrator, you can access the diagnostic resources.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/157505436/e7fd3a55-e0dc-4359-bbec-0c30ed61ee46)

### Expected/desired behavior
> I want to be able to run the web app using the link: https://app-backend... besides running locally

### OS and Version?
> Windows 11

### azd version?
> azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

### Mention any other details that might be useful
> I can run this on the locally on my machine. However, I cannot run the web app using the link: https://app-backend...
> Below are the steps I used to run locally with no errors: 
> - cd app
> - ./start.sh

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Sometimes that's because the app is still starting up. Have you waited 5-10 minutes? If it's still erroring, please go through my steps at https://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html to figure out if its a failed deployment or a failed server start.

**Comment by junepochara** [comment]
@pamelafox 
Thank you for your help in advance,

After following your steps, the script only ends with "Running pip install...". It seems like "Running pip install..." did not find packages installed as shown in the pasted text below the line. In your blog, you mentioned that "if it didn't find your requirements.txt, then you won't see the packages installed."
 
What are the actions I can further do to resolve this problem?

Note that the screenshots show where I got the pasted script below the line.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/157505436/606b2bcb-dfc0-48cf-8085-f2f2f920f9bc)


![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/157505436/143e4ffc-81c6-4652-9a86-ec02bc00e69d)

----------------------------------------------------------
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.11 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8dc2411cd297369 --compress-destination-dir | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1

Build Operation ID: 40705c42b0382d15
Repository Commit : b4fdb06e-79b3-4159-a248-b24ae8ebb970
OS Type           : bullseye
Image Type        : githubactions

Detecting platforms...
Detected following platforms:
  python: 3.11.7
Version '3.11.7' of platform 'python' is not installed. Generating script to install it...

Using intermediate directory '/tmp/8dc2411cd297369'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /tmp/8dc2411cd297369
Destination directory: /home/site/wwwroot


Downloading and extracting 'python' version '3.11.7' to '/tmp/oryx/platforms/python/3.11.7'...
Detected image debian flavor: bullseye.
Downloaded in 3 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: python...
Done in 23 sec(s).

image detector file exists, platform is python..
OS detector file exists, OS is bullseye..
Python Version: /tmp/oryx/platforms/python/3.11.7/bin/python3.11
Creating directory for command manifest file if it does not exist
Removing existing manifest file
Python Virtual Environment: antenv
Creating virtual environment...
Activating virtual environment...
Running pip install...

**Comment by pamelafox** [comment]
That was indeed a failed deployment. Have you tried running "azd deploy" to deploy again?

**Comment by jhic** [comment]
I had the same issue and running "azd deploy" fixed it.

**Comment by junepochara** [comment]
Running "azd deploy" fixed the issue.

Thank you, @pamelafox and @jhic!
