### ISSUE TITLE
azd up failure on openai resource deployment TemplateViolation InvalidTemplate

### ISSUE THREAD

**Issue by ehalsey** [Azure-Samples/azure-search-openai-demo#123]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
running 'azd up' fails on openai resource.  Same error on 2 different desktops as well as Codespaces.

### Any log messages given by the failure
>
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplate",
        "message": "Deployment template validation failed: 'The template resource 'cog-kww4kfsimmfle/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1738' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.",
        "additionalInfo": [
            {
                "type": "TemplateViolation",
                "info": {
                    "lineNumber": 1,
                    "linePosition": 1738,
                    "path": "properties.template.resources[1].type"
                }
            }
        ]
    }
}

### Expected/desired behavior
>
openai resource deployed successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11 and Codespace referenced in README.md.

### Versions
>
main branch

### Mention any other details that might be useful
![image](https://user-images.githubusercontent.com/14900980/232637080-187e7f47-2ab5-456a-9063-bfb583292595.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by legalgates** [comment]
I am getting the same error now, It was working fine until yesterday.

**Comment by ehalsey** [comment]
@legalgates do you know what commit worked for you by chance?

**Comment by BoldEnthusiast** [comment]
Facing the same issue.

**Comment by glenn-zarb** [comment]
Facing the same issue.

**Comment by waimanhui** [comment]
encountered the same error, the commit on Apr 13,2023 works instead
SHA: 40e547804645ea0907e5c792cd200a15cbb80929

**Comment by Velociraptorvelraptor** [comment]
Facing the same issue.

**Comment by AGTGreg** [comment]
I'm also facing the same issue. Could this be an authorization issue?

**Comment by gebla** [comment]
Same issue for me

**Comment by Ayo-faks** [comment]
I have the same issue , any solution yet?

**Comment by Shazebgk** [comment]
I am also facing same error while trying deployment for multiple customers today.

Deployment template validation failed: 'The template resource 'cog-eolab3vxcwqyk/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1738' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see [https://aka.ms/arm-syntax-resources]

**Comment by manuelgarciagonz** [comment]
I have the same failure

**Comment by mbadgujar** [comment]
Facing same issue, any resolution?

**Comment by raemone** [comment]
Same issue, I tried using the previous version of the azure.yaml file without success

**Comment by ekode** [comment]
I have the same problem

**Comment by pjirsa** [comment]
I also experienced this issue. The latest commit (2570644a1) adds a couple of parameters to the main.parameters.json which expect values to be set in your local environment.

Workaround:
remove these parameters from the main.parameters.json file
```
    "gptDeploymentName": {
      "value": "${AZURE_OPENAI_GPT_DEPLOYMENT}"
    },
    "chatGptDeploymentName": {
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT}"
    }
```

**Comment by 2tacos99cents** [comment]
removing those parameters didn't work. they just get written back to the main.parameters.json file after deploying again?

**Comment by lizozom** [comment]
I am getting the same error again

```
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplate: Deployment template validation failed: 'The template resource 'cog-tmepcsa3oh3qm/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '1689' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.
```
