### ISSUE TITLE
Deployment fails after updating to latest commit (integrated vectorisation)

### ISSUE THREAD

**Issue by zedhaque** [Azure-Samples/azure-search-openai-demo#1254]
> Please provide us with the following information:
> ---------------------------------------------------------------

After updating to latest commit (integrated vectorisation) deployment fails. 
 
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>  azd auth login
azd env set USE_FEATURE_INT_VECTORIZATION false
azd up

### Any log messages given by the failure
> From the Azure portal deployment screen :
The template output 'principalId' is not valid: The language expression property 'identity' doesn't exist, available properties are 'apiVersion, location, sku, tags, properties, condition, isConditionTrue, subscriptionId, resourceGroupName, scope, resourceId, referenceApiVersion, existing, isTemplateResource, isAction, isExtensibleResourceReference, provisioningOperation'.. (Code: DeploymentOutputEvaluationFailed, Target: principalId)

### Expected/desired behavior
> Successful deployment. 

### OS and Version?
> macOS

### azd version?
> run `azd version` and copy paste here.
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Comment by rahul-r3** [comment]
I've been using these change(in search-services.bicep file) on the free tier and they seem to be working well so far.
![Try_This](https://github.com/Azure-Samples/azure-search-openai-demo/assets/108130892/95ffbeec-544e-4c1b-b869-5c8df91887e2)

**Comment by pamelafox** [comment]
Ah thanks for filing, that line needs a conditional.
