### ISSUE TITLE
Citation - Forbidden - when ACL and AZURE_ENFORCE_AUTHENTICATION=True

### ISSUE THREAD

**Issue by Recco23** [Azure-Samples/azure-search-openai-demo#1264]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> following this guide with automatic setup https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md
Error only showing when AZURE_ENFORCE_AUTHENTICATION=True. But as mentioned in the guide above, "False" allows everyone logged in to search and show all documents which is not desired.

### Any log messages given by the failure
>
Logs:
<img width="1645" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/c20e3e3f-90c0-4f0a-b8b6-84f6fb4be3d9">
Corresponding UI-State (with Forbidden at the citation):
<img width="1844" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/72137b23-fcfc-4abe-bdd4-d43f659ac609">
Corresponding UI-Sate (everything fine at Supporting Content)
<img width="1824" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/52e551f7-1711-44b2-bc0c-4f8d55d975ec">
Corresponding UI-State (everything fine at Thought Process)
<img width="1831" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/7f078fc3-ad1e-460f-840f-2250f3fd7d00">
Developer Settings (1/2):
<img width="227" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/d91e9bc2-f591-44ec-99c0-99debcc40169">
Developer Settings (2/2):
<img width="246" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/7eccd14f-5e54-4e66-afda-9f6ff1159eb8">

### Expected/desired behavior
> showing the citation as usual but restricted to the acl rules as the search is doing

### OS and Version?
> Windows 10. but running in codespaces (free tier - Linux)

### azd version?
>  $ azd version
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

### Versions
>

### Mention any other details that might be useful
i also tried to go with maximum rights under the manage acl in my storage account (Azure Data Lake Gen2)
<img width="949" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/9297e3b4-fc38-41ba-9f2a-37522ac5fa86">
I set the following set of rights to root directory as well as every folder and file directory of content and gptkbcontainer as follows.
<img width="417" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/c3ba4947-8c99-48f2-b04f-6609238ab602">
(red circles was manually added to maximize rights and alle the other settings were set from following the guide and using the first optional script for Azure Data Lake Storage Gen2 Setup.

since i run this in linux in codespaces i have to mention i had to swap this code
<img width="1082" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/82dc6d71-a37b-42e0-9dee-e2800c69284d">
the original code in the repo has and -n instead of a -z in line 5 which made the script (./scripts/adlsgen2setup.sh) stop when a name for AZURE_ADLS_GEN2_STORAGE_ACCOUNT is set.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
cc @mattgotteiner who the access control code and may have insights here.

**Comment by mattgotteiner** [comment]
Correct - if you have access to the search result you should be able to see the supporting citation. will check this

**Comment by mattgotteiner** [comment]
Thank you for reporting. This is an interesting problem - essentially, we aren't accounting for the fragments in the URL and we also need to check both sourcefile and sourcepage due to how GPT-4V support was added. Will open a PR soon
