### ISSUE TITLE
Upload documents 

### ISSUE THREAD

**Issue by carlaelisa** [Azure-Samples/azure-search-openai-demo#1269]
Will it be possible to upload documents as well?

**Comment by carlaelisa** [comment]
Hello @pamelafox, yes exactly the PR 478 looks like exactly what we need :)

**Comment by charlie-hssrr** [comment]
@carlaelisa I built an upload feature referencing this PR, but instead it uses a Redis message / job queue that fires the prepdocs script to process and index the files. It then uses a websocket to tell the client when the async script processing is done.

I can link you my repo should you be interested.

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/50207699/3cab5bd4-23ed-41aa-a099-66b263272a41)

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/50207699/fb9ee21b-87d4-444e-b0a5-86472d88f571)

**Comment by carlaelisa** [comment]
Hi @charlie-hssrr  Thank you very much for your message. I would be very interested in your repo. Have you been successful integrating it in this repo as well?

**Comment by carlaelisa** [comment]
Hi @charlie-hssrr thank you for your message. 

I would be very interested in your repo.

**Comment by charlie-hssrr** [comment]
@carlaelisa sent you an invite
Let me know once you've grabbed a copy

**Comment by superpoussin22** [comment]
> ou my repo should you be interested.

@charlie-hssrr I'm also interested in

**Comment by carlaelisa** [comment]
@charlie-hssrr 
I was able to clone the code and i am running it locally. 

At the moment i'm having the following error: 
api.ts:57 
POST http://127.0.0.1:50505/upload 500 (Internal Server Error)

UploadFiles.tsx:60 Upload error: Error: Uploading files failed: 
    at dt (api.ts:63:15)
    at async j (UploadFiles.tsx:57:46)
    
   __ 
   i am trying to find out where the problem can be. Would you have an idea? 
   
   Also, does this work when deploying to azure?

**Comment by charlie-hssrr** [comment]
@carlaelisa ya there's a few prerequisites to get it working.

I had to convert my storage to data lake gen2. Make sure not to enable ACL or auth.
Also ensure that you have Owner rights on the blob container (your Entra user).
Make sure you're signed in with azd, the prepdocs script will use the auth'd user.
Make sure to have your packages correctly installed in your .venv (or backend_env for the backend).

Hope this helps.

**Comment by charlie-hssrr** [comment]
Add this to your .azure .env file:

REDIS_COMPLETION_CHANNEL="script_completion_channel"
REDIS_QUEUE_NAME="script_queue"
REDIS_URL="redis://localhost"

**Comment by carlaelisa** [comment]
thanks @charlie-hssrr 
the issue with redis doesnt seem to be resolved by this: 
redis.exceptions.ConnectionError: Error 22 connecting to localhost:6379. 22.

**Comment by charlie-hssrr** [comment]
@carlaelisa the redis server is running locally so you should be able run and hit it.
FYI I removed the data directory in the project due to IP in there. You should make sure your data directory exist in the project root.

I'm happy to help you get this running - you can reach out to me directly via a dm

**Comment by superpoussin22** [comment]
thanks @charlie-hssrr

**Comment by beouk** [comment]
@charlie-hssrr would also be interesting in trying this.

**Comment by charlie-hssrr** [comment]
@beouk @carlaelisa @superpoussin22 I use this pattern for file uploads with Redis queues and then firing prepdocs.sh for the processing to Azure storage. 

You can run the project standalone and it will allow for uploads. For firing prepdocs.sh, you need to either retrofit this code  into the azure demo app, or figure out how to access the scripts directory from this project:

https://github.com/charlie-hssrr/az-search-file-upload
