### ISSUE TITLE
Is it possible to use only the gpt4 model?

### ISSUE THREAD

**Issue by Glaxier** [Azure-Samples/azure-search-openai-demo#127]

**Comment by anderl80** [comment]
Just took a quick look at the backend code, but it seems like https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/app.py lines 21 and 22 describe the environment variables that needed to be changed pointing to GPT-4 instead.

**Comment by kishorerv93** [comment]
@anderl80 check this PR #394

**Comment by pamelafox** [comment]
You can now use gpt-4 by changing a single line in the Bicep file, see the FAQ here:
https://github.com/Azure-Samples/azure-search-openai-demo#faq
