### ISSUE TITLE
prepdocs.ps1 doesn't work with pre-defined DataLake Gen2 Filesystem and Path

### ISSUE THREAD

**Issue by egor-yudkin** [Azure-Samples/azure-search-openai-demo#1270]
[LoginAndAclSetup.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#azure-data-lake-storage-gen2-prep-docs) refers to `AZURE_ADLS_GEN2_FILESYSTEM` and `AZURE_ADLS_GEN2_FILESYSTEM_PATH` variables, but the script is actually using `ADLS_GEN2_FILESYSTEM` and `ADLS_GEN2_FILESYSTEM_PATH` variables respectively

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Set `AZURE_ADLS_GEN2_FILESYSTEM` and `AZURE_ADLS_GEN2_FILESYSTEM_PATH` variables
2. Run `prepdocs.ps1`
3. The script ignores `AZURE_ADLS_GEN2_FILESYSTEM` and `AZURE_ADLS_GEN2_FILESYSTEM_PATH` variables and calls `prepdocs.py` without `--datalakefilesystem` and `--datalakefilesystempath` arguments

### Any log messages given by the failure
> n/a

### Expected/desired behavior
> `prepdocs.py` should be called with `--datalakefilesystem` and `--datalakefilesystempath` argument values from `AZURE_ADLS_GEN2_FILESYSTEM` and `AZURE_ADLS_GEN2_FILESYSTEM_PATH` variables when they are set in environment

### OS and Version?
> Ubuntu 22.04 LTS

### azd version?
> n/a

### Mention any other details that might be useful
- prepdocs.sh has correct environment variables mapping
- [Environment Variables reference of LoginAndAclSetup.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#environment-variables-reference) has variable names that are not used anywhere at all. The **STORAGE** part needs to be removed
>- AZURE_ADLS_GEN2_**STORAGE**_FILESYSTEM: (Optional) Name of existing [Data Lake Storage Gen2 filesystem](https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-introduction) for storing sample data with [access control lists](https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-access-control). Only used with the optional Data Lake Storage Gen2 [setup](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#azure-data-lake-storage-gen2-setup) and [prep docs](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#azure-data-lake-storage-gen2-prep-docs) scripts.
> - AZURE_ADLS_GEN2_**STORAGE**_FILESYSTEM_PATH: (Optional) Name of existing path in a [Data Lake Storage Gen2 filesystem](https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-introduction) for storing sample data with [access control lists](https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-access-control). Only used with the optional Data Lake Storage Gen2 [prep docs](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#azure-data-lake-storage-gen2-prep-docs) script.

**Comment by pamelafox** [comment]
Thanks for the report! Assigning to @mattgotteiner as the recent author of those variables.

**Comment by mattgotteiner** [comment]
Will fix this. Appreciate your feedback

**Comment by abin-tiger** [comment]
+1
