### ISSUE TITLE
Cannot deploy 'gpt-4 vision-preview'

### ISSUE THREAD

**Issue by mmarahrens** [Azure-Samples/azure-search-openai-demo#1274]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Following the README to setup an environment.
2. Create an RG in region  'westus' and update via `azd env set [...]`.
3. Set `azd env set USE_GPT4V true` and run `azd up`:

```bash
azd up
[...]
? Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter:  [Use arrows to move, type to filter]
[...]
8. (US) East US (eastus)
9. (US) East US 2 (eastus2)
11. (US) North Central US (northcentralus)
```

4. Missing region `westus`.
5. Created service `Azure OpenAI` via portal and set region to `westus`.
6. Tear down env via `azd down`.
7. Following [Existing OpenAI resource - Azure OpenAI](https://github.com/Azure-Samples/azure-search-openai-demo#azure-openai) to set variables. Retry `azd up`.
8. Failing again, see log message

### Any log messages given by the failure
> Deployment Error Details:
> InvalidResourceLocation: The resource 'xyz' already exists in location 'westus' in resource group 'RG-xyz'. A resource with the same
> name cannot be created in location 'eastus'. Please select a new resource name.

### Expected/desired behavior
> Deployment should run without issues.

### OS and Version?
> Windows 10 with WSL2

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

### azd version?
> run `azd version` and copy paste here.

### Versions
> azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Ah, that's tricky, it's hard to support locations for both GPT-3.5 and GPT-4. So, I'd suggest you either:
1) Change the location directly in main.bicep, hard-coding openAiResourceGroupLocation='westus', and remove @allowed
2) Go into .azure/YOUR-ENV-NAME/config.json and change openAiResourceGroupLocation to 'westus'

**Comment by mmarahrens** [comment]
Thanks for the reply, @pamelafox. Your [solution](https://github.com/Azure-Samples/azure-search-openai-demo/issues/1274#issuecomment-1949426269) led to another error:

```bash
InvalidResourceProperties: The specified SKU 'Standard' for model 'gpt-35-turbo 0613' is not supported in this region 'westus'.
```

I had to change the model version 0613 in `main.bicep` to

```bash
param chatGptModelVersion string = '1106'
```

Maybe the initial model selection during deployment should be coded more dynamically. 

Anyhow, the deployment is working now 💯. 🚀
