### ISSUE TITLE
Can I 'add' to the data folder, without rerunning all (prepdocs.ps1)?

### ISSUE THREAD

**Issue by suetholen** [Azure-Samples/azure-search-openai-demo#128]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Just wondering if (and if so, how) I could upload additional documents to the data folder and have them indexed without repreating that for all the documents.  Similarly, to replace one document with a newer version.  Thinking that most companies will want to know how to keep this up to date if they find it helpful initially.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aymiee** [comment]
What works for me is only placing new pdfs in the /data folder that I want indexed and then I run prepdocs.ps1.  I haven't replaced a new version, yet.  I used the flag args.removeall = True to remove.  But I noticed there's a flag args.remove that might be used to "Remove references to this document from blob storage and the search index".  That could be what you are looking for.

**Comment by davendrapatel** [comment]
I answer my own question :

 ./scripts/prepdocs.ps1

**Comment by suetholen** [comment]
So once the initial setup is done and documents indexed, if I want to add additional new information, I should remove the initial set of files from the /data folder, add the new ones, then run prepdocs.ps1.  If I want to remove an older version of a file to replace with a new one, I should set the remove flag.  I'm not sure where to do that or if it's at the folder or file level, but could probably figure that out with a little digging.  What if I simply add a newer version of a file or newer information without realizing that it supersedes something so I don't explicitly remove it.  Is the underlying AI smart enough to recognize when there is contradictory information and use the more recent version as a tiebreaker?

**Comment by bot4pro** [comment]
it said: bash: ./scripts/prepdocs.ps1: Permission denied

when I run ./scripts/prepdocs.ps1

any idea how to solve?

**Comment by bot4pro** [comment]
> it said: bash: ./scripts/prepdocs.ps1: Permission denied

when I run ./scripts/prepdocs.ps1

any idea how to solve?

**Comment by bot4pro** [comment]
> [davendrapatel](/davendrapatel)

it said: bash: ./scripts/prepdocs.ps1: Permission denied

when I run ./scripts/prepdocs.ps1

any idea how to solve?

**Comment by david-an-tran-pham** [comment]
I got the same error message using bash. However, I think you are supposed to run it using powershell because it worked for me once I switched 🍡

**Comment by david-an-tran-pham** [comment]
@michelltang001 
I got the same error message using bash. However, I think you are supposed to run it using powershell because it worked for me once I switched 🍡

**Comment by jasonchanhku** [comment]
> use powershell to run it instead of bash

**Comment by ramvemireddy** [comment]
I tried with both bash and pwsh. I still get permission denied. Please help

/bin/sh: 1: ./scripts/prepdocs.sh: Permission denied
ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '126', Path: './scripts/prepdocs.sh'. : exit code: 126
