### ISSUE TITLE
Use existing App Service and App Service Plan

### ISSUE THREAD

**Issue by daptatea** [Azure-Samples/azure-search-openai-demo#1288]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
Hi, is it possible to use an existing App Service and App Service Plan from a previous deployment. Mainly to use the same URL as before. The same way we can use existing resources such as Azure OpenAI, AI Search, Document Intelligence and so on?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, we haven't exposed that via environment variables yet, but you can modify the parameters at the top of main.bicep:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/1c32a28fae8b45b631d619c4fac2e24fab34ee38/infra/main.bicep#L12

**Comment by pamelafox** [comment]
@giterinhub has a PR that does this: https://github.com/Azure-Samples/azure-search-openai-demo/pull/1389/files
