### ISSUE TITLE
Documentation of the feature "Use query-contextual summaries instead of whole documents"

### ISSUE THREAD

**Issue by giuliotosato** [Azure-Samples/azure-search-openai-demo#1294]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Is there any explanation of "Use query-contextual summaries instead of whole documents" feature?
It seems that it's related to semantic search and changes the output with semantic results. But I cannot determine the complete idea of this.

<img width="236" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/108023394/2a8f681a-843c-4490-a55d-310951f11541">

**Comment by pamelafox** [comment]
Good question! It uses semantic captions for the answers, which are described here: 
https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/introducing-semantic-search-bringing-more-meaningful-results-to/ba-p/2175636

You should be able to see the difference in the "supporting content", the answers would be relevant subsets of the cited sources. I haven't personally used this for my deployments, but if you do use it, please share whether it works well for you. The semantic captions team would love feedback about the caption generation.

**Comment by pamelafox** [comment]
We now have tooltips that explain this better, closing this issue.
