### ISSUE TITLE
InvalidTemplateDeployment: The template deployment failed with multiple errors. 

### ISSUE THREAD

**Issue by anjuthomas** [Azure-Samples/azure-search-openai-demo#130]
Looks like the Azure subscription provided by my team is causing the following deployment issues. Is there another already existing Azure subscription with open ai access I can use to run this? Am getting the following issue even after updating to latest changes in the git repo.

ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment failed with multiple errors. Please see details for more information.
RequestDisallowedByPolicy: Resource 'cog-y5qvgpwnkggwk' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyAssignments/35ee869489f24894b32aed2f"},"policyDefinition":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyDefinitions/e98df9f1-b3e4-4c56-9b0a-3fdeb1341a6f"}}]'.
RequestDisallowedByPolicy: Resource 'davinci' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyAssignments/35ee869489f24894b32aed2f"},"policyDefinition":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyDefinitions/e98df9f1-b3e4-4c56-9b0a-3fdeb1341a6f"}}]'.
RequestDisallowedByPolicy: Resource 'chat' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyAssignments/35ee869489f24894b32aed2f"},"policyDefinition":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyDefinitions/e98df9f1-b3e4-4c56-9b0a-3fdeb1341a6f"}}]'.
InvalidTemplateDeployment: The template deployment failed because of policy violation. Please see details for more information.
RequestDisallowedByPolicy: Resource 'cog-fr-y5qvgpwnkggwk' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyAssignments/35ee869489f24894b32aed2f"},"policyDefinition":{"name":"Not allowed resource types","id":"/subscriptions/30bde84e-2129-4879-b8e9-0dc5d794a01c/providers/Microsoft.Authorization/policyDefinitions/e98df9f1-b3e4-4c56-9b0a-3fdeb1341a6f"}}]'.

**Comment by nubgamerz** [comment]
Looks like you have policies active in your tenant which is blocking the deployment.

You will need to add exemptions or not scopes to your 'Not allowed resource types" policy to allow the deployment.
