### ISSUE TITLE
Change exsisting deployment model from 35 to 4

### ISSUE THREAD

**Issue by gregorcvek** [Azure-Samples/azure-search-openai-demo#1330]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Changing line 90 in main.bicep -> change from gpt-35-turbo to gpt-4 and then run azd up on all exsisting resources (gpt 35 already deployed and I want to upgrade to gpt-4).

### Any log messages given by the failure
> InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '14a61b11-c9d2-464c-a234-010ac5a10c37'. See inner errors for details.
CannotChangeDeploymentModel: The model of deployment cannot be changed.

### Expected/desired behavior
> Should upgrade model on gpt-4

### OS and Version?
> Windows 10

### azd version?
> azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)

### Versions
>

### Mention any other details that might be useful
Should I remove azd down & purge and then deploy with new resources if I want to use gpt-4? what is the procedure here. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by codevladdo** [comment]
Hi - i am having the same issue and get the same response when trying to upgrade to gpt-35-turbo-16k. 

Any insights would be helpful! Thank you:)

**Comment by pamelafox** [comment]
It sounds like you'll need to change the deployment name as well, can you try that?

```
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT chat4
```

**Comment by gregorcvek** [comment]
Hi Pamela,
Thanks for your help. That did the trick, although I had to delete the previous 3.5model deployment in Azure AI studio. First I deployed w/o deleting 35, and then my webapp won't show up (didn't debug why). When I deleted 3.5 in Azure AI studio, and then specified new v4 deployment name, it worked. Have gpt-4 now deployed. Response time for v4 is as already noticed by others, slower, reaching avg server response time around 45sec. Although the quality of answer is much better.

**Comment by codevladdo** [comment]
Hi Pamela, 

I've tried following your advice but still running into trouble. I'm trying to deploy gpt-4 0125-preview on EastUS, which i believe should be available to all subscription holders. Would really appreciate any guidance here. Thanks in advance.

This is my configuration: 

**Main.bicep file**
param chatGptModelName string = (openAiHost == 'azure') ? 'gpt-4' : 'gpt-4'
param chatGptModelVersion string = '0125-preview'

**.env file**
AZURE_ENV_NAME="trytrytry"
AZURE_LOCATION="eastus"
AZURE_OPENAI_CHATGPT_DEPLOYMENT="chat4"  //(edited as you suggested)
AZURE_SUBSCRIPTION_ID="censored"

The error i'm getting is: 

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'a47336af-0272-43d8-8c7f-2cca528cee47'. See inner errors for details.
DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-4, Version: 0125-preview' of account deployment is not supported.

ERROR: error executing step command 'provision': deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'a47336af-0272-43d8-8c7f-2cca528cee47'. See inner errors for details.
DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-4, Version: 0125-preview' of account deployment is not supported.

**Comment by codevladdo** [comment]
Zedhaque - thank you! That worked, i really appreciate your guidance and wish you the best. 

Vlad

**Comment by pamelafox** [comment]
I will work on making it more easily configurable, sorry for the pain. Will close this as I'm tracking in another issue: https://github.com/Azure-Samples/azure-search-openai-demo/issues/1352
