### ISSUE TITLE
Add tool tips to settings in Developer Settings

### ISSUE THREAD

**Issue by charris-msft** [Azure-Samples/azure-search-openai-demo#1334]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Watch a new user in a study struggle with understanding what the settings like Temperature and Exclude category mean, and how to use them.

### Any log messages given by the failure
>

### Expected/desired behavior
>Each setting has a tooltip that briefly explains what the setting means and how to use it.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by john0isaac** [comment]
I would like to work on fixing this.

**Comment by pamelafox** [comment]
@john0isaac That'd be great! I gave it a quick go based on the original PR from @diberry but I was having a hard time with the fluent components or something, and then gave up. Here's Dina's PR: https://github.com/Azure-Samples/azure-search-openai-demo/pull/856
You can go off that or try your own spin.  Thank you!
