### ISSUE TITLE
Error when opening dev container: there is no registered task type 'dotenv'

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo#1339]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Open dev container locally.
2. Output window shows 'Error: there is no registered task type 'dotenv'. Did you miss installing an extension that provides a corresponding task provider?'
3. Verify `./vscode/tasks.json` has a type property with a value of `dotenv`. 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That should be provided by the azd extension, I believe. Did your azd extension install okay? I do sometimes see that but typically blame it on extension order.
