### ISSUE TITLE
Restrict GitHub workflows run according to trigger on related changes

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/azure-search-openai-demo#1356]
> Please provide us with the following information:
> ---------------------------------------------------------------

The Python workflows runs on docs changes which I don't think is very efficient and not the best scenario.
We should restrict workflow runs to relevant changes

I can work on this btw if you want.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by pamelafox** [comment]
Yes, I agree. I'd love a PR, I think you've made similar PRs elsewhere.
