### ISSUE TITLE
Question about this app's deployment in Azure Portal from the playground

### ISSUE THREAD

**Issue by synergiator** [Azure-Samples/azure-search-openai-demo#1364]
Dear @pamelafox, @srbalakr & all,

thank you very much for this example app!

There is one thing I'd like to know: how does this codebase relate with what is deployed from the Azure Portal's playground?

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/1834666/12f48edf-ff7b-4ed5-bbcd-6f4127e819cd)

What I have observed so far:

* (side note )"_View code_" opens a code example which is based on an openai version < 1.0
* the "_Deploy to_" feature creates a WebApp with a file tree very similar to this app, however with several differences. I would like to find out more details with the intention, being able to build/deploy same version locally as well as relate to this codebase.

So, in this codebase there is no Dockerfile; static content is slightly different. Also, the upstream version uses the up to date openai package (1.12.0 in "main" vs. 1.6.1 in the web app)*.   So I assume, Azure Portal offers deployment of a slightly modified historical git tag of this codebase. But why is the current upstream version does not feature a Dockerfile?

```
(antenv) root@a109adf98336:/tmp/8dc3b09d799448a# tree -L 1
.
├── antenv
├── app.py
├── azure.yaml
├── backend
├── CODE_OF_CONDUCT.md
├── data
├── frontend
├── gunicorn.conf.py
├── infra
├── infrastructure
├── LICENSE
├── notebooks
├── __pycache__
├── README_azd.md
├── README.md
├── requirements-dev.txt
├── requirements.txt
├── scripts
├── SECURITY.md
├── start.cmd
├── start.sh
├── static
├── SUPPORT.md
├── TEST_CASE_FLOWS.md
├── tests
├── WebApp.Dockerfile
└── WebApp.dockerignore
```

\* Whereas [in this commit on Jan 30th 2024](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1206/commits/9bff805d3eb06fabb4908ce52f6cd04c103f89eb) there has been a version bump for the openai package from 1.3.7. to 1.10.0. That is, this codebase never had a 1.6.x dependency.

**Comment by synergiator** [comment]
yeah thanks a lot @zedhaque !

**Comment by synergiator** [comment]
@zedhaque still, a side question.. "software archeology hat on" is there an "original seed concept" where the Answer.tsx etc appears for the first time? And both codebases originate from? Is there a documentation, given that these both apps are very spartanic in terms of architecture documentation?

* Considerations: maybe from the perspective of an experienced FluentUI/Typescript developer the app is just a "write-up" on top of this framework: still if you are both new to AI/GPT and Typescript as such, some words on the architecture/design might be helpful as part of the doc.

**Comment by pamelafox** [comment]
@synergiator In terms of docs, we have more docs here:
https://github.com/Azure-Samples/azure-search-openai-demo/tree/main/docs
We also have done many streams, see https://www.youtube.com/playlist?list=PL5lwDBUC0ag6_dGZst5m3G72ewfwXLcXV
I think you're right that I could add additional docs on architecture design decisions.
I sometimes blog about general decisions at https://blog.pamelafox.org/

And yes there's a lot of overlap between the apps, but that repo has the specific use case of being deployable from the studio, so that influences their decisions.
