### ISSUE TITLE
Make it easy to switch ada embedding models via azd environment variables

### ISSUE THREAD

**Issue by Estrogenetics** [Azure-Samples/azure-search-openai-demo#1369]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd up

### Any log messages given by the failure
> The model 'Format: OpenAI, Name: text-embedding-3-small, Version: 2' of account deployment is not supported. (Code: DeploymentModelNotSupported)

### Expected/desired behavior
> I'd like to move to either the large or small embedding model on a new deployment, but receive this error after changing the embedding model. I've seen issues in the past where I needed to change the case sensitivity of a single letter of a model, but that doesn't seem to apply here. Any help would be greatly appreciated for the roll out!

### OS and Version?
> Windows 11 Pro

### azd version?
> azd version 1.6.1

### Versions
>

### Mention any other details that might be useful
> My only change was the following in main.bicep:
param embeddingModelName string = 'text-embedding-ada-002'
to
param embeddingModelName string = 'text-embedding-3-small'

**Comment by pamelafox** [comment]
Please try changing version to 1 here:

  {
    name: embeddingDeploymentName
    model: {
      format: 'OpenAI'
      name: embeddingModelName
      version: '1'
    }
    sku: {
      name: 'Standard'
      capacity: embeddingDeploymentCapacity
    }
  }

**Comment by Estrogenetics** [comment]
Hi Pamela, you're a legend! That worked. I was eyeing that version number, but wasn't sure where to change it. Thank you! However, I notice that after changing the model to **text-embedding-3-large** I get the following error after running prepdocs :

Exception Details:      (IndexDocumentsFieldError) 0: The vector field 'embedding' dimensionality must match the field definition's 'dimensions' property. Expected: '1536'. Actual: '3072'. Parameters: actions

I tried changing all the fields that included **text-embedding-ada-002** to **text-embedding-3-large** and also changed the field vector_search_dimensions=**1536** to **3072**, but still same error. I tried redeploying everything post changes and same thing. I'll keep digging and working with Copilot to figure it out, but the last bit of help will get us moving with a production environment on the new embedding model. Guess I'm a bit deprecation worried lol. Thank you!

**Comment by pamelafox** [comment]
Did you delete the current index? I did assume there'd be some issues with dimension hard-coding, but making a fresh index with the correct dimension seems like it should work. I'll see if I can try it today.

**Comment by Estrogenetics** [comment]
I did not, since I didn't add anything to it. I'll give that a go next!

**Comment by pamelafox** [comment]
Ah yeah then that's the error. You're trying to index a field with more dimensions than you set it up with.

**Comment by Estrogenetics** [comment]
Got it, and prepdocs completed at the default of 3072 dimensions. I found the dimensions under **Fields** in the **Search Service**. Super helpful to match them from both ends like that. Now if I originally deployed with 1536 and Azure's default is 3072, is there no way to change the default set by Azure in AI Studio or somewhere else? It seems the initial deployment's custom dimension of 1536 conflicted with what is set as the default in Azure. No worries if it's passed my original ask, ideally 1536 large would be nice.

**Comment by pamelafox** [comment]
Hm, I don't see dimensions in the deployment options, where is that? I was assuming you could specify it when calling embeddings.create(). Here's a notebook that created multiple dimension sizes using the same deployment:
https://github.com/farzad528/azure-ai-search-python-playground/blob/main/azure-ai-search-text-embedding-3-large.ipynb

**Comment by Estrogenetics** [comment]
I found these two field where you could change dimension before deploying. I had to change 1536 to 3072 to get the new large model to work without the error you solved above.

  ),
                SearchField(
                    name="embedding",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    hidden=False,
                    searchable=True,
                    filterable=False,
                    sortable=False,
                    facetable=False,
                    vector_search_dimensions=**1536**,
                    vector_search_profile_name="embedding_config",
                ),
                SimpleField(name="category", type="Edm.String", filterable=True, facetable=True),
                SimpleField(
                    name="sourcepage",
                    type="Edm.String",
                    filterable=True,
                    facetable=True,
                ),
                SimpleField(
                    name="sourcefile",
                    type="Edm.String",
                    filterable=True,
                    facetable=True,
                ),
            ]
            if self.use_acls:
                fields.append(
                    SimpleField(
                        name="oids",
                        type=SearchFieldDataType.Collection(SearchFieldDataType.String),
                        filterable=True,
                    )
                )
                fields.append(
                    SimpleField(
                        name="groups",
                        type=SearchFieldDataType.Collection(SearchFieldDataType.String),
                        filterable=True,
                    )
                )
            if self.use_int_vectorization:
                fields.append(SearchableField(name="parent_id", type="Edm.String", filterable=True))
            if self.search_images:
                fields.append(
                    SearchField(
                        name="imageEmbedding",
                        type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                        hidden=False,
                        searchable=True,
                        filterable=False,
                        sortable=False,
                        facetable=False,
                        vector_search_dimensions=**1024**,
                        vector_search_profile_name="embedding_config",
                    ),
                )

**Comment by Estrogenetics** [comment]
> Hm, I don't see dimensions in the deployment options, where is that? I was assuming you could specify it when calling embeddings.create(). Here's a notebook that created multiple dimension sizes using the same deployment: https://github.com/farzad528/azure-ai-search-python-playground/blob/main/azure-ai-search-text-embedding-3-large.ipynb

Thanks I'll read through this, I'm still working through CS50/CS50P, so will take some time to figure out. Appreciate the title change to make it easier. Gen AI is very inspiring and thanks for making this accessible!
