### ISSUE TITLE
Authentication and Authorization Failure When Updating Package 2024-03-01)

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#1370]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

Follow the below steps
Run `azd env set AZURE_USE_AUTHENTICATION true` to enable the login UI and App Service authentication.
Ensure access control is enabled on your search index. If your index doesn't exist yet, run prepdocs with `AZURE_USE_AUTHENTICATION` set to true. If your index already exists, run `pwsh ./scripts/manageacl.ps1 --acl-action enable_acls.`
(Optional) To require access control when using the app, run `azd env set AZURE_ENFORCE_ACCESS_CONTROL` true.
Run `azd env set AZURE_AUTH_TENANT_ID <YOUR-TENANT-ID>` to set the tenant ID associated with authentication.
Run azd up to deploy the app.

once deployed when you load the WebApp, you will notice the error
```
azurewebsites.net is currently unable to handle this request.
HTTP ERROR 500
```
<img width="1358" alt="Screenshot 2024-03-04 at 5 49 05 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/89c9830f-c864-40e1-9a39-83ec138a7eb0">

When i start app locally it is working without any issues.
>

### Expected/desired behavior

>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vrajroutu** [comment]
@mattgotteiner

**Comment by pamelafox** [comment]
Was it a non-issue?

**Comment by vrajroutu** [comment]
@pamelafox  Yes this is a non issue anymore, i just did clean up all the resources and ran `azd up` everything is working as expected.
