### ISSUE TITLE
Ability to set an existing App Service Plan

### ISSUE THREAD

**Issue by M0inUddin** [Azure-Samples/azure-search-openai-demo#1371]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 11

### azd version?
> 1.6.1

### Versions
> Using Free trail of Azure

### Mention any other details that might be useful
Deployed app with `azd up`, faced App Service Plan provisioning issue due to location constraints. Workaround: Created App Service Plan in another location. `azd up` did not recognize manual resource assignment. Request: Manual assignment option in `main.parameters.json`.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Good idea, I've marked this as an open issue for anyone who would like to work on it.
