### ISSUE TITLE
Index created but no indexer in AI search

### ISSUE THREAD

**Issue by beouk** [Azure-Samples/azure-search-openai-demo#1376]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> When running `azd up`, new AI search resources are created without errors or warnings, along with the index containing the docs. However there is no indexer present relating to the index, so when adding new docs to the storage container, I cannot run the reindex command.

### Versions
> 1.6.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Did you enable the optional integrated vectorization feature? That's the only situation that would create an indexer.

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md#enabling-integrated-vectorization

More deets in: 

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md

**Comment by beouk** [comment]
Yup that was it. It could be worth including the enabling-integrated-vectorization link inside that data_ingestion doc?
