### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Vaishnavi-Kocherla** [Azure-Samples/azure-search-openai-demo#138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>The app is running when I try to use the chat it displays SyntaxError: Unexpected end of JSON input

### Any log messages given by the failure
>Failed to load resource: the server responded with a status of 500 (Internal Server Error)
>SyntaxError: Unexpected end of JSON input is displayed as a response

### Expected/desired behavior
> It is expected to give me a response for my question

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Axel-Zouebi** [comment]
Any news about it ? Thx

**Comment by itmilos** [comment]
Probably you have some sort of error on infrastructure side...
