### ISSUE TITLE
Unable to set my gpt-4 deployment as the env variable

### ISSUE THREAD

**Issue by billigproton** [Azure-Samples/azure-search-openai-demo#1383]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request 
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run azd init -t azure-search-openai-demo to initialize the solution locally, azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT gpt-4
> in Azure Portal, create a resource group with Azure OpenAI resource. In that Azure OpenAI resource, create a gpt-4 deployment

### Any log messages given by the failure
> CannotChangeDeploymentModel: The model of deployment cannot be changed.

### Expected/desired behavior
> sample solution uses gpt-4 instead of gpt 3.5 turbo

### OS and Version?
> Windows 11

### azd version?
>azd version 1.6.1

### Mention any other details that might be useful

> Hi, I was trying to use my gpt-4 deployment in this solution but have hard time setting it in the code. What's the way to do that? Thanks in advance!

**Comment by beouk** [comment]
Main.bicep 

```
:90 param chatGptModelName string = (openAiHost == 'azure') ? 'gpt-4' : 'gpt-4'
:91 param chatGptModelVersion string = '0125-Preview'
```

Also in your .env
```

AZURE_OPENAI_CHATGPT_DEPLOYMENT="gpt-4"
AZURE_OPENAI_CHATGPT_MODEL="gpt-4"
```
