### ISSUE TITLE
azd deployment fails over Cognitive Service domain creation

### ISSUE THREAD

**Issue by qudarr** [Azure-Samples/azure-search-openai-demo#14]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> deploy via "azd up -t azure-search-openai-demo" 

### Any log messages given by the failure
```
{
    "status": "Failed",
    "error": {
        "code": "CustomDomainInUse",
        "message": "Sub domain name 'cog-xejrw6segqcvq' is already in use. This condition is caused by sub domain name being taken at the same time."
    }
}
```

### Expected/desired behavior
> sub domain should be created successfully

### OS and Version?
> macOS Ventura

### Versions
> current

### Mention any other details that might be useful
I tried re-deploying several times. every time the auto-generated domain name is claimed to be already existing although it is different each time.

**Comment by pablocastro** [comment]
Perhaps you have a service with that name already (e.g. from a previous run)?

The resource name suffixes are derived from your azd environment name. You could remove any resource groups created in previous attempts, and then run azd with the -e parameter and a new environment name, e.g. `azd up -t azure-search-openai-demo -e env2`. The name is used as part of the resource group that will get created, and also hashed and added to the names of individual service resources.

**Comment by qudarr** [comment]
No, the name is generated randomly each time, but still every time it says that the domain name already exists. My subscription has no pre-existing domain names

Viele Grüße
Martin Duschek
________________________________
Von: Pablo Castro ***@***.***>
Gesendet: Wednesday, March 15, 2023 3:40:30 PM
An: Azure-Samples/azure-search-openai-demo ***@***.***>
Cc: qudarr ***@***.***>; Author ***@***.***>
Betreff: Re: [Azure-Samples/azure-search-openai-demo] azd deployment fails over Cognitive Service domain creation (Issue #14)


Perhaps you have a service with that name already (e.g. from a previous run)?

The resource name suffixes are derived from your azd environment name. You could remove any resource groups created in previous attempts, and then run azd with the -e parameter and a new environment name, e.g. azd up -t azure-search-openai-demo -e env2. The name is used as part of the resource group that will get created, and also hashed and added to the names of individual service resources.

**Comment by qudarr** [comment]
Thanks, using your parameters solved the issue :)
