### ISSUE TITLE
Using Public OpenAI API instead of Azure OpenAI service

### ISSUE THREAD

**Issue by ablockchainfan** [Azure-Samples/azure-search-openai-demo#140]
- [x ] feature request

### Minimal steps to reproduce
> I still do not have the OpenAI Service enabled in my Azure account. I want to test this but changing the api to point to external OpenAI API via API Key.

Did anyone try this and have the code changes that will make this temporarily work, so I can test the functionality?

**Comment by aorlowskiddm** [comment]
What steps did you take to try to get the repo to point at the public openai API?

**Comment by anderl80** [comment]
Easiest way would be to use the notebook https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/notebooks/chat-read-retrieve-read.ipynb.
Delete all `openai.` lines and only keep `openai.key=<yourkey>` with your OpenAI API key.´
```python
Probably you need to tweak here and there like in the Completion function:

completion = openai.Completion.create(
        engine=AZURE_OPENAI_GPT_DEPLOYMENT, #this is not needed I guess with OpenAI or call it 'text-davinci-003'
        prompt=summary_prompt_template.format(summary="\n".join(history), question=user_input),
        temperature=0.7,
        max_tokens=32,
        stop=["\n"])
```

**Comment by pamelafox** [comment]
This is now officially supported, closing.
