### ISSUE TITLE
Update or Parameterize Azure OpenAI Service preview API Version to Prevent Future Deprecation Issue

### ISSUE THREAD

**Issue by sogue** [Azure-Samples/azure-search-openai-demo#1409]
I've noticed that in the current implementation, the API version for the AsyncAzureOpenAI client is hard-coded as "2023-07-01-preview" :

```
 # Store on app.config for later use inside requests
        openai_client = AsyncAzureOpenAI(
            api_version="2023-07-01-preview",
            azure_endpoint=endpoint,
            azure_ad_token_provider=token_provider)
```

To prevent potential issues from using retiring Azure OpenAI API versions, it's important to update the code to use version 2024-02-15-preview or newer by 2 April 2024. [Link](https://learn.microsoft.com/azure/ai-services/openai/reference)

I have created a pull request that outlines two possibilities:

PR for updating the hardcoded API version: [Link to PR 1399](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1399)
PR for defining the API version as an environment variable: [Link to PR 1397](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1397)

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by pamelafox** [comment]
Thanks for the fix, closing!
