### ISSUE TITLE
Similar Sample request for C# and Dot net 6 Application 

### ISSUE THREAD

**Issue by hsonparo** [Azure-Samples/azure-search-openai-demo#141]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>Can we have similar set up/demo for any c# dot net 6 application .

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by randriana** [comment]
Would love to have an example written in .NET 6!

**Comment by jontysouvik** [comment]
C# .Net Exaple will be very helpful

**Comment by eric-king** [comment]
Adding my support

**Comment by pablocastro** [comment]
We now have a C# / .NET version here: https://github.com/Azure-Samples/azure-search-openai-demo-csharp
