### ISSUE TITLE
 Using Integrated Vectorization, the Citations reference the document name and not the page

### ISSUE THREAD

**Issue by Adeelku** [Azure-Samples/azure-search-openai-demo#1413]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use Integrated Vectorization and deploy `azd env set USE_FEATURE_INT_VECTORIZATION true`

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> File page in the result, but only the document is referenced in the citation

### OS and Version?
>  Linux Ubuntu 22.04  - WSL2

### azd version?
> azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f).

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That was filed here, please follow this thread: https://github.com/Azure-Samples/azure-search-openai-demo/issues/1380
