### ISSUE TITLE
Add minimum score criteria for AI search results

### ISSUE THREAD

**Issue by sogue** [Azure-Samples/azure-search-openai-demo#1418]
A filtering mechanism based on minimum score criteria for documents. By setting a minimum value for both `search_score` and `reranker_score`. This aims to improve the relevance of documents sent to the AI, that only the most relevant information is sent for further processing.

Suggested change: [https://github.com/Azure-Samples/azure-search-openai-demo/pull/1417](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1417)

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for the PR! We can close this now since you implemented it. :)
