### ISSUE TITLE
[Issue] Broken Relative paths

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/azure-search-openai-demo#1422]
These files / heading references no longer exist on the repo.
Need to reference correct files

| File Full Path | Issues |
|--------|--------|
| `./docs/productionizing.md` | 1. `../README.md#enabling-authentication` |
| `./docs/deploy_features.md` | 1. `../README.md#deploying` |
| `./docs/login_and_acl.md` | 1. `./app/backend/core/authentication.py` <br/> 2. `./scripts/adlsgen2setup.ps1` <br/> 3. `./scripts/sampleacls.json` <br/> 4. `./scripts/sampleacls.json` <br/> 5. `./scripts/sampleacls.json` <br/> 6. `./scripts/sampleacls.json` <br/> 7. `./scripts/prepdocs.py` <br/> 8. `./scripts/manageacl.ps1` <br/> 9. `./scripts/manageacl.ps1` <br/> 10. `./scripts/manageacl.sh` |
| `./docs/azd.md` | 1. `../README.md#deploying-from-scratch` |
| `./docs/deploy_existing.md` | 1. `../README.md#deploying` |
| `./docs/deploy_lowcost.md` | 1. `../README.md#deploying` <br/> 2. `../README.md#existing-azure-ai-search-resource` <br/> 3. `../README.md#deploying-from-scratch` |
| `./docs/localdev.md` | 1. `../README.md#azure-deployment` |
| `./.github/PULL_REQUEST_TEMPLATE.md` | 1. `../CONTRIBUTING.md#submit-pr` |

_Originally posted by @github-actions[bot] in https://github.com/Azure-Samples/azure-search-openai-demo/issues/1386#issuecomment-1992538667_

**Comment by pamelafox** [comment]
I'll fix those up now, thanks!

**Comment by john0isaac** [comment]
@pamelafox there is a bug, I have dealt with links that have # at the end of them.
please ignore these errors. I will release a fix now to stop these errors.

**Comment by pamelafox** [comment]
I noticed that they weren't all actually broken. I did decide to change all those to absolute URLs, seems more robust for the future anyway?

**Comment by john0isaac** [comment]
Yeah, It is.
I also removed the # from the cached URL.
releasing it to Pypi now.

**Comment by john0isaac** [comment]
I didn't realize that's what you meant by absolute URLs.

The Script won't catch these URLs now..
It needs the relative path to either start with ./ or ../ to be able to evaluate it.

**Comment by pamelafox** [comment]
Ohh interesting. It cant see URLs starting with "/" and know that they're repo links?

**Comment by john0isaac** [comment]
I'm skipping if it doesn't have a . or .. in front of the URL.

But even If I don't skip (which will produce other problems)

The script won't be able to evaluate the URL as it won't know which folder is parent to it.
It won't know how to access it.
How it works is that It takes the current path + relative path AND evaluates them and tries to access the generated path if it doesn't exist it will be flagged as broken.

If we don't provide the relative path either . or .. it won't be able to evaluate suff
