### ISSUE TITLE
Prepdocs.py with ADLS Gen2 enabled re-uploads documents to the storage

### ISSUE THREAD

**Issue by egor-yudkin** [Azure-Samples/azure-search-openai-demo#1424]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow the instructions in `login_and_acl.md`, "Optional Scripts" section

### Any log messages given by the failure
>

### Expected/desired behavior
Documents are uploaded to directories as defined in `sampleacls.json`, then ingested into index with "sourcefile" value including directory where the blob is.

### OS and Version?
Ubuntu 22.04

### azd version?
azd version 1.6.1

### Versions
>

### Mention any other details that might be useful
After initial ADLS Gen2 setup and running `./scripts/asldgen2setup.ps1`, the storage container is populated with files in directories according to mapping in `sampleacls.json`.
When running `prepdocs.py` it re-uploads the file to the storage and prints "Uploading blob for whole file" in the output.
The index entries also have `sourcefile` value without any reference to the directory. This renders document-level security via directory ACL useless.

**Comment by pamelafox** [comment]
Assigning to @mattgotteiner as this is quite related to https://github.com/Azure-Samples/azure-search-openai-demo/issues/1403
