### ISSUE TITLE
I cant change the model name/Deployment Name  

### ISSUE THREAD

**Issue by aropenai** [Azure-Samples/azure-search-openai-demo#1429]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
 I ran the azd env set 
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT XXXXXX

### Any log messages given by the failure
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '5cdfee6f-acd0-4c51-afb4-3586479bd341'. See inner errors for details.
CannotChangeDeploymentModel: The model of deployment cannot be changed.

### Expected/desired behavior
Must be able to change the model name 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by giterinhub** [comment]
Are you deploying for the first time, or is this a redeployment? 
Is your deployment using Azure Openai { OPENAI_HOST=azure } ?

**Comment by aropenai** [comment]
I am deploying for the first time using azure open ai. But I already have existing resources and would like to use the same. Kindly advise.

**Comment by aropenai** [comment]
Fixed by changed the values in main.bicep

**Comment by Amit515** [comment]
What changes do we need to do in main.bicep, to use existing openai model or other resource? I am assuming once we set enivornment variable using azd env set AZURE_OPENAI_SERVICE { } it will dynamically assign value in main.biceps thru main.parameter.json
