### ISSUE TITLE
tagging policy violation error

### ISSUE THREAD

**Issue by X-Cooper** [Azure-Samples/azure-search-openai-demo#1432]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
our environment has a policy to enforce a required tagging for deployment. I tried to use an existing resource group that met the tagging requirement. The "azd up" deployment still throws the error as shown below.  Is there an option I can add tagging to the deployment ?

### Any log messages given by the failure
>
"message": "Resource 'rg-openaidemo-dev' was disallowed by policy. Reasons: 'Please provide 'bu' Tag while creating Resource Group. 'bu' (Business Unit) is a mandatory tag as per Governance Standard.
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Window 10

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.7.0

### Mention any other details that might be useful
Is there a way to add tagging to the deployment process ?  

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Could you add the tags in the Bicep? We already pass in some tags but you could add any additional tags needed-

https://github.com/Azure-Samples/azure-search-openai-demo/blob/d4871044e1f0de44df5df3830ee62b15cecb8d78/infra/main.bicep#L130

**Comment by X-Cooper** [comment]
yes, that works. Thanks a lot !
var tags = { 'azd-env-name': environmentName, **'bu': 'Finopt-1025'** }
