### ISSUE TITLE
which release that does not use the preview version of Document Intelligence ?

### ISSUE THREAD

**Issue by X-Cooper** [Azure-Samples/azure-search-openai-demo#1433]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I deployed the latest release [2024-03-14](https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-03-14) that uses the preview version of Document Intelligence. The regions for the preview version are only available in `East US`, `West US2`, and `West Europe`. My company set a policy to deploy resource only to limited regions that does not include these three regions. 

### Any log messages given by the failure
> Deployment Error Details:
InvalidTemplateDeployment: The template deployment failed because of policy violation. Please see details for more information.
RequestDisallowedByPolicy: Resource 'cog-di-4rdq3com2wcxk' was disallowed by policy. Reasons: 'Deployment of Azure resource in this region is not allowed.

### Expected/desired behavior
> Looking for a release that has option to deploy Document Intelligence service in East US2 region.  It does not have to use the preview version.

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.7.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This is the version that upgraded to the new version of Document Intelligence:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-02-15b
So you would need to pull the commit before that:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-02-15

**Comment by X-Cooper** [comment]
Thank you !
