### ISSUE TITLE
Sourcepage when using Sharepoint Indexer

### ISSUE THREAD

**Issue by B4tzz** [Azure-Samples/azure-search-openai-demo#1445]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I performed  steps described in this following documentation to index Sharepoint files: https://learn.microsoft.com/en-us/azure/search/search-howto-index-sharepoint-online. Then I created fields to store documents data and metadata. Now, I'm stuck to get sourcepage field in this datasource type.  /document/metadata_storage_name doesn't work because of the datasource type. I tried to replace it  with /document/metadata_spo_item_name, the corresponding metadata from Sharepoint, but the source page is not there, just the file name. I noticed that document id generated by index projection  contains the page number of the chunk. I tried to get this  attribute in index projections and indexer output field mapping but it doesn't works, it returns null. Does anybody know how to get it?

Chunk stored:
{
      "@search.score": 0.01666666753590107,
      "@search.rerankerScore": 2.6711089611053467,
      "@search.captions": [
        {
          "text": "<content caption>",
          "highlights": "<content caption>"
        }
      ],
      "id": "...NVZRQg2_pages_3",
      "parent_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "content": "<chunk content>",
      "filepath": "<file name>",
      "title": "<file name>",
      "sourcepage": null,
      "url": "<file web uri>",
      "last_updated": "03/18/2024 17:30:37 +00:00",
      "contentVector": [<embedding>],
      "contentValidated": "<boolen flag>"
    }

Skillset:

{
  "name": "<index name>-skillset",
  "description": "",
  "skills": [
    {
      "@odata.type": "#Microsoft.Skills.Text.SplitSkill",
      "name": "#1",
      "description": "Split skill to chunk documents",
      "context": "/document",
      "defaultLanguageCode": "pt-BR",
      "textSplitMode": "pages",
      "maximumPageLength": 2048,
      "pageOverlapLength": 20,
      "maximumPagesToTake": 0,
      "inputs": [
        {
          "name": "text",
          "source": "/document/content"
        }
      ],
      "outputs": [
        {
          "name": "textItems",
          "targetName": "pages"
        }
      ]
    }
  ],
  "cognitiveServices": {
    "@odata.type": "#Microsoft.Azure.Search.DefaultCognitiveServices",
    "description": null
  },
  "knowledgeStore": null,
  "indexProjections": {
    "selectors": [
      {
        "targetIndexName": "<index name>",
        "parentKeyFieldName": "parent_id",
        "sourceContext": "/document/pages/*",
        "mappings": [
          {
            "name": "content",
            "source": "/document/pages/*",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "url",
            "source": "/document/metadata_spo_item_weburi",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "title",
            "source": "/document/metadata_spo_item_name",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "filepath",
            "source": "/document/metadata_spo_item_name",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "last_updated",
            "source": "/document/metadata_spo_item_last_modified",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "contentValidated",
            "source": "/document/Validado",
            "sourceContext": null,
            "inputs": []
          },
          {
            "name": "sourcepage",
            "source": "/document/id",
            "sourceContext": null,
            "inputs": []
          }
        ]
      }
    ],
    "parameters": {
      "projectionMode": "skipIndexingParentDocuments"
    }
  },
  "encryptionKey": null
}

### Any log messages given by the failure
> No logs, because debug session is not supported when using index projections :/

### Expected/desired behavior
>  N/A

### OS and Version?
> N/A

### azd version?
> N/A

### Versions
> N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
So you are trying to get the page number, not just the filename? I do not know if it is possible with the Sharepoint indexer. CC @srbalakr @mattgotteiner from search team.

**Comment by B4tzz** [comment]
Yeah, I think it's not possible either. I had to develop a custom skill to do this and other operations not supported by SharePoint Indexer, like filter which folder paths from the library should be used to index documents. Closing it! 

Thank you very much for your attention @pamelafox . 😊

**Comment by aadnegture** [comment]
Could you elaborate on the custom skill you built for this @B4tzz ?

**Comment by cforce** [comment]
Would be great tzo have sich skillset published at https://github.com/Azure-Samples/azure-search-power-skills
