### ISSUE TITLE
'Copy to clipboard'  and 'Share answer as email' Feature  in answers

### ISSUE THREAD

**Issue by nits-aidev** [Azure-Samples/azure-search-openai-demo#1454]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>'Copy to clipboard'  and 'Share answer as email' Feature  in answers, So users can copy response directly 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hammadilyes** [comment]
We manage to develop the copy to clipboard feature.

@pamelafox do you want me to share the code for it ?

**Comment by pamelafox** [comment]
Sure! We love seeing modifications. You can share as code copied here, in a gist, or in a branch or pull request. Not sure whether we'd merge it since I don't know whether it's a popular request, but it's helpful for folks who do want it.

**Comment by nits-aidev** [comment]
I have enabled this feature in my code 
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/128786992/b5a92713-9e98-4534-9930-aed9a8e85ab9)

**Comment by nits-aidev** [comment]
Modification required in Answer.tsx file in app\frontend\src\components\Answer\

const copyToClipboard = () => {
    const el = document.createElement("textarea");
    el.value = parsedAnswer.answerText;
    document.body.appendChild(el);
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
    setCopiedAnswer(parsedAnswer.answerText);
    setShowCopySuggestion(true);
    setTimeout(() => {
        setShowCopySuggestion(false);
    }, 2000);
};

const handleShareClicked = async () => {
    const shareData = {
        title: `Share Answer - ${selectedQuestion}`, 
        text: parsedAnswer.answerText,
        url: window.location.href, // Add your URL here if required  
    };

    if (navigator.canShare && navigator.canShare(shareData)) {
        try {
            await navigator.share(shareData);
            console.log("Answer shared successfully!");
        } catch (error) {
            console.error("Error sharing answer:", error);
        }
    } else {
        console.log("Share dialog not supported in this browser.");
    }
};



{copiedAnswer === parsedAnswer.answerText ? (
    <span style={{ color: "green" }}>Copied!</span>
) : (
    <React.Fragment>
        <IconButton
                style={{ color: "#ef6449" }}
            iconProps={{ iconName: "Copy" }}
            title="Copy to clipboard"
            ariaLabel="Copy to clipboard"
            onClick={copyToClipboard}
        />
        {showCopySuggestion && (
            <span style={{ color: "blue" }}>Copied to clipboard!</span>
        )}
    </React.Fragment>
)}

<IconButton
    style={{ color: "#ef6449" }}
    iconProps={{ iconName: "Share" }}
    title="Share answer"
    ariaLabel="Share answer"
    onClick={handleShareClicked}
/>

**Comment by hammadilyes** [comment]
looks clean yes I would love to see the code related.

**Comment by nits-aidev** [comment]
@pamelafox , Please review and if looks good you can push this features.
