### ISSUE TITLE
INclude sample of ChatCompletion for ChatGPT,GPT4

### ISSUE THREAD

**Issue by EricHunsberger** [Azure-Samples/azure-search-openai-demo#146]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> Can ChatCompletion used in ChatGPT and GPT-4 be included in the demo?

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> ChatGPT, GPT4

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sk1136** [comment]
any update on this?

**Comment by kishorerv93** [comment]
@sk1136  Here is my PR for GPT-4 and chat-completion #394

**Comment by pamelafox** [comment]
This sample now uses ChatCompletion API everywhere, and I've added an FAQ about using GPT-4 (it's a one-line change):
https://github.com/Azure-Samples/azure-search-openai-demo#faq
