### ISSUE TITLE
Possible error in Azure Pricing calculator from README

### ISSUE THREAD

**Issue by trevor87** [Azure-Samples/azure-search-openai-demo#1468]
### This issue is for a:
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Open the Azure Pricing calculator linked in the README page (https://azure.microsoft.com/en-us/pricing/calculator/?shared-estimate=8ffbe5b1919c4c72aed89b022294df76)
2. Estimated monthly cost is shown as $3,152.94

### Expected/desired behavior
I assume that the actual cost should be $210.11

### Mention any other details that might be useful

The problem seems to be that in the section "Azure Form Recognizer" the entered value is 261 instead of 0.261. Thereby the calculation is made for 261.000 pages instead of 261.

**Comment by pamelafox** [comment]
Thank you! I've sent a PR to fix at https://github.com/Azure-Samples/azure-search-openai-demo/pull/1480
