### ISSUE TITLE
azure.core.exceptions.HttpResponseError while  using integrated vectorization.

### ISSUE THREAD

**Issue by christ25442544** [Azure-Samples/azure-search-openai-demo#1469]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I use the integrated vectorization to read and index my documents, after I use that the chatbot cannot respond, It saids httpresponse error.

### Any log messages given by the failure
>
<img width="566" alt="Screenshot 2567-03-29 at 14 51 49" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/124753618/5f98f4e5-6b9c-4f84-b688-585fe33762ca">

### Expected/desired behavior
> It should work fine.

### OS and Version?
> macOS Sonoma
### azd version?
> run `azd version` and copy paste here.
azd version 1.7.0

### Mention any other details that might be useful
<img width="730" alt="Screenshot 2567-03-29 at 14 54 05" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/124753618/41f2ee42-0cda-40ff-947d-24c55c47c9be">
The gptkbindex indexer looks fine.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by christ25442544** [comment]
I already know the problem, I use text embedding-3 model with integrated vectorization, but it didn't support right now.

**Comment by marceloricciardi** [comment]
@christ25442544 Please how did you solve this problem?
