### ISSUE TITLE
prepdoc.sh possible bug? with ADLS Gen2 file system path

### ISSUE THREAD

**Issue by hfaouaz-rcg** [Azure-Samples/azure-search-openai-demo#1477]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
setup an adls gen 2 storage account with all nececessary enviornment on MacOS

### Any log messages given by the failure
>
Running "prepdocs.py"
/Users/hfaouaz/development/rcg-search-openai/./scripts/prepdocs.py:231: SyntaxWarning: invalid escape sequence '\d'
  epilog="Example: prepdocs.py '..\data\*' --storageaccount myaccount --container mycontainer --searchservice mysearch --index myindex -v",
usage: prepdocs.py [-h] [--datalakestorageaccount DATALAKESTORAGEACCOUNT] [--datalakefilesystem DATALAKEFILESYSTEM]
                   [--datalakepath DATALAKEPATH] [--datalakekey DATALAKEKEY] [--useacls] [--category CATEGORY] [--skipblobs]
                   [--storageaccount STORAGEACCOUNT] [--container CONTAINER] [--storageresourcegroup STORAGERESOURCEGROUP]
                   [--storagekey STORAGEKEY] [--tenantid TENANTID] [--subscriptionid SUBSCRIPTIONID] [--searchservice SEARCHSERVICE]
                   [--searchserviceassignedid SEARCHSERVICEASSIGNEDID] [--index INDEX] [--searchkey SEARCHKEY]
                   [--searchsecretname SEARCHSECRETNAME] [--searchanalyzername SEARCHANALYZERNAME] [--openaihost OPENAIHOST]
                   [--openaiservice OPENAISERVICE] [--openaideployment OPENAIDEPLOYMENT] [--openaimodelname OPENAIMODELNAME]
                   [--openaidimensions OPENAIDIMENSIONS] [--novectors] [--disablebatchvectors] [--openaikey OPENAIKEY]
                   [--openaiorg OPENAIORG] [--remove] [--removeall] [--localpdfparser] [--localhtmlparser]
                   [--documentintelligenceservice DOCUMENTINTELLIGENCESERVICE] [--documentintelligencekey DOCUMENTINTELLIGENCEKEY]
                   [--searchimages] [--visionendpoint VISIONENDPOINT] [--keyvaultname KEYVAULTNAME]
                   [--useintvectorization USEINTVECTORIZATION] [--verbose]
                   [files]
prepdocs.py: error: unrecognized arguments: --datalakefilesystempath

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS Silicon Sonoma
### azd version?
> run `azd version` and copy paste here.

### Versions
>azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)

### Mention any other details that might be useful

I fixed it by updating the prepdoc.sh to 
```python
if [ -n "$AZURE_ADLS_GEN2_FILESYSTEM_PATH" ]; then
    adlsGen2FilesystemPathArg="**--datalakepath** $AZURE_ADLS_GEN2_FILESYSTEM_PATH"
fi
```

I can gladly do a PR if this is indeed a bug not a enviornment issue.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thank you for the report! I made a PR here to make your suggested fix in both the sh and ps1 script: https://github.com/Azure-Samples/azure-search-openai-demo/pull/1478
