### ISSUE TITLE
How to deploy this solution to existing resources?

### ISSUE THREAD

**Issue by ericthomas1** [Azure-Samples/azure-search-openai-demo#149]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

I already have an active Azure OpenAI resource deployed to a specific Resource Group. I want this deployment to use both the existing AOAI and Resource Group. 

How do I edit in the `main.bicep` and/or `main.parameters.json` file to deploy to existing resources?

Thank you

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Alec13355** [comment]
@ericthomas1 are you looking for something different than this https://github.com/Azure-Samples/azure-search-openai-demo#use-existing-resources ?

**Comment by wtyeung** [comment]
are you deploying to an existing resource group and existing OAI resource?  try https://github.com/Azure-Samples/azure-search-openai-demo/issues/4#issue-1619906532

**Comment by ericthomas1** [comment]
@Alec13355 was that there the whole time! Jeez! Thank you for pointing that out. I should have slowed down and looked through the docs more thoroughly.
