### ISSUE TITLE
Deploying to VM

### ISSUE THREAD

**Issue by Izzatullohh** [Azure-Samples/azure-search-openai-demo#1505]
I want to deploy this app to my VM using Nginx. 
is there any instruction on this?

Thank you:)

**Comment by pamelafox** [comment]
Sorry, we don't have any particular instruction for that. If it's helper, this is a Dockerfile for running the app:

**Comment by pamelafox** [comment]
The Bicep files in the infra folder set up a ton of resources and RBAC roles, so you would want to start with provisioning that Bicep, and then see how you can swap out App Service with a VM. You'd need to make a managed identity for that VM and assign it all the roles we currently assign to the app service, and also make sure to set all the environment variables we set on the App Service app.

**Comment by Izzatullohh** [comment]
Thank you for the help, Pamela. I appreciate it :)

**Comment by pamelafox** [comment]
Closing as we provide a Dockerfile in the repo now as well.
