### ISSUE TITLE
Principal does not have access to API/Operation

### ISSUE THREAD

**Issue by samin-batra** [Azure-Samples/azure-search-openai-demo#1519]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have run the azd up command in Azure. While running prepdocs.py, it calls Azure Doc Intelligence service to chunk the documents. 

### Any log messages given by the failure
>  Message: Principal does not have access to API/Operation.

### Expected/desired behavior
>It should chunk the documents and complete without any errors

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### azd version?
> run `azd version` and copy paste here.
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)

### Versions
>

### Mention any other details that might be useful
When I inspect the error logs, it mentions the error happening in doc intelligence. I have reviewed permissions to my application and the permissions are all there. There was a similar issue in which @pamelafox was mentioning that 3 permissions need to be there for the app to function well - all those permissions exist:

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/12857930/2b0f7e76-9452-4d1f-a43b-54192590847a)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Is this happening when "azd up" calls prepdocs.py locally, or is it happening when a user is uploading documents in the app UI?

If it's during local ingestion, then you need to check the access of your own logged in account, not the access of the backend app.

**Comment by samin-batra** [comment]
This is fixed now. I was passing a document intelligence key, but it seems it wasn't needed. Removed it, and it worked. Thanks!

**Comment by pamelafox** [comment]
Ah, no, we use your Entra credential by default. Glad it's fixed!

**Comment by thracian2015** [comment]
I have the same error. I enclose the full stack below. I'm have Owner role permissions to the Document Intelligence service. 

Also, I appreciate the end-to-end sample but it's too much for me to digest. Granted I'm not up to Python skills, but I spent a day trying to set it up locally and I got it running to a point but I still have a clue how all this works. For example, how do I call prepdocuments outside "azd up"? Do you happen to have a simplified code sample detailing the basic steps required to prep a document, index a document (manually or automated), and then use LLM for text2search?

Running "prepdocs.py"
./scripts/prepdocs.py "C:\Projects\AzureSearchOpenAI/data/*" --verbose --subscriptionid dc9a5b0e-3f65-466b-9dc9-16258235d9e7 --storageaccount stnejioursfhmeq --container content --storageresourcegroup rg_azureaisearch --searchservice prologika-aisearch --index gptkbindex  --searchsecretname searchServiceSecret --openaihost "azure" --openaimodelname "text-embedding-ada-002" --openaiservice "prologika-ai" --openaideployment "embedding" --openaikey "" --openaiorg "" --documentintelligenceservice prologika-docintelligence         --tenantid e7b81d0a-a949-4103-83dc-feff6277c109 --useacls    --keyvaultname kv-nejioursfhmeq
C:\Projects\AzureSearchOpenAI\scripts\prepdocs.py:253: SyntaxWarning: invalid escape sequence '\d'
  epilog="Example: prepdocs.py '..\data\*' --storageaccount myaccount --container mycontainer --searchservice mysearch --index myindex -v",       
Processing files...
Using local files in C:\Projects\AzureSearchOpenAI/data/*
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Skipping C:\Projects\AzureSearchOpenAI/data\Benefit_Options.pdf, no changes detected.
Skipping C:\Projects\AzureSearchOpenAI/data\Contoso_Electronics_Company_Overview.md, no changes detected.
Skipping C:\Projects\AzureSearchOpenAI/data\employee_handbook.pdf, no changes detected.
Parsing 'Financial Market Analysis Report 2023.pdf'
Extracting text from 'C:\Projects\AzureSearchOpenAI/data\GPT4V_Examples\Financial Market Analysis Report 2023.pdf' using Azure Document Intelligence
Traceback (most recent call last):
  File "C:\Projects\AzureSearchOpenAI\scripts\prepdocs.py", line 429, in <module>
    loop.run_until_complete(main(ingestion_strategy, azd_credential, args))
  File "C:\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\AzureSearchOpenAI\scripts\prepdocs.py", line 247, in main
    await strategy.run(search_info)
  File "C:\Projects\AzureSearchOpenAI\scripts\prepdocslib\filestrategy.py", line 64, in run
    pages = [page async for page in processor.parser.parse(content=file.content)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\AzureSearchOpenAI\scripts\prepdocslib\pdfparser.py", line 58, in parse
    poller = await document_intelligence_client.begin_analyze_document(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\AzureSearchOpenAI\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py", line 77, in wrapper_use_tracer      
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\AzureSearchOpenAI\scripts\.venv\Lib\site-packages\azure\ai\documentintelligence\aio\_operations\_operations.py", line 372, in begin_analyze_document
    raw_result = await self._analyze_document_initial(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\AzureSearchOpenAI\scripts\.venv\Lib\site-packages\azure\ai\documentintelligence\aio\_operations\_operations.py", line 130, in _analyze_document_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Projects\AzureSearchOpenAI\scripts\.venv\Lib\site-packages\azure\core\exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: (PermissionDenied) Principal does not have access to API/Operation.
Code: PermissionDenied
Message: Principal does not have access to API/Operation.
