### ISSUE TITLE
azure-dev.yml failure to provision app service and openai deployment error 

### ISSUE THREAD

**Issue by achu152** [Azure-Samples/azure-search-openai-demo#1520]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Trying to provision resources via Azure devops . Leveraged  .azdo/pipelines/azure-dev.yml . However , the app service is not getting deployed . and getting below error for openai deployment 

At least one resource name segment is invalid according to the Resource Provider specification. (Code: InvalidResourceNameFormat)

### Any log messages given by the failure
>Openai deployment 
At least one resource name segment is invalid according to the Resource Provider specification. (Code: InvalidResourceNameFormat)

### Expected/desired behavior
>App service is not deployed . 

### OS and Version?
>Linux

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, interesting. CC @vhvb1989 who wrote azure-dev.yml in case he has ideas.

I recommend:

* Looking at your GitHub Actions secrets/variables (Settings > Secrets and variables) and verifying that everything looks correct, and that there's no unexpected empty/near-empty/weird strings.
* Looking at the deployment in the Azure Portal and checking the inputs for the failed stage of the deployment to get a hint for what parameter is set incorrectly.

**Comment by achu152** [comment]
@pamelafox thanks for the update. The issue is resolved. missed out few env variables. Its working as expected now .
