### ISSUE TITLE
not able to access the application deployed via spn -AADSTS500011: The resource principal named api:// was not found in the tenant

### ISSUE THREAD

**Issue by achu152** [Azure-Samples/azure-search-openai-demo#1529]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Tried to deploy the app using SPN , however am not able to access the application . Getting below Error 
AADSTS500011: The resource principal named api:// was not found in the tenant named ***. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

### Any log messages given by the failure
>AADSTS500011: The resource principal named api:// was not found in the tenant named ***. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by achu152** [comment]
This issue is resolved

**Comment by cforce** [comment]
@achu152  How??
