### ISSUE TITLE
Provide a way to set documents as "globally accessible"

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/azure-search-openai-demo#1532]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Currently, when you use access control, you must explicitly set acls/oids for every document in the index, otherwise they won't be found from searching. However, some developers may want to make it so that acl-less documents are considered globally accessible. @mattgotteiner has some ideas for how we can do that best.

**Comment by mattgotteiner** [comment]
I will work on this ASAP

**Comment by lokeshkri** [comment]
In the listFileStrategy.py to the ADLSGen2ListFileStrategy class added the following read access grant to others, now am able to chat with user uploaded content, issue I am facing is with clickedCitations are not being opened in the prop section.                     

# Set the ACL to grant read access to others
acl = 'other::r--'
await file_client.set_access_control(acl=acl)

**Comment by pamelafox** [comment]
@lokeshkri Re clickedCitations not opening in prop section, is that due to the known issue of non-PDFs getting downloaded? Or is the auth_claims decorator to the content route not properly recognizing access to the files, and giving 400s instead?

**Comment by lokeshkri** [comment]
@pamelafox After making the changes related to other:: r above in listFileStrategy.py, am able to view other users upload document, however, in this specific instance when I chat on the topics related to user-uploaded documents am getting the following error - 
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/168208653/93caf9e5-c927-436e-8bf4-737fecc1ab92)

**Comment by mo-albaba** [comment]
is there an update regarding this request?

**Comment by laneparton** [comment]
@mo-albaba It seemed like this is working for me - but I'm still testing!

```oid_security_filter = (
            "oids/any(g:search.in(g, '{}'))".format(auth_claims.get("oid", "")) if use_oid_security_filter else None
        )
        groups_security_filter = (
            "groups/any(g:search.in(g, '{}'))".format(", ".join(auth_claims.get("groups", [])))
            if use_groups_security_filter
            else None
        )

        public_docs_filter = "not oids/any() and not groups/any()"

        # If only one security filter is specified, return that filter
        # If both security filters are specified, combine them with "or" so only 1 security filter needs to pass
        # If no security filters are specified, don't return any filter
        filters = [f for f in [oid_security_filter, groups_security_filter, public_docs_filter] if f]

        if len(filters) == 1:
            return filters[0]
        elif len(filters) > 1:
            return " or ".join(filters)
        else:
            return None```

**Comment by pamelafox** [comment]
We merged a change that uses environment variables to enable this:

https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-05-15

I'll close this issue, please file a new issue if you are having issues with the merged feature. Thank you!
