### ISSUE TITLE
ERROR: deployment failed due to form recognizer that was soft-deleted?

### ISSUE THREAD

**Issue by ericthomas1** [Azure-Samples/azure-search-openai-demo#155]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Install the solution once 
Remove all resources
Try to install again

### Any log messages given by the failure
```
(✓) Done: Resource group: MYRG
(✓) Done: Storage account: MYSTORAGEACCT
(✓) Done: App Service plan: MYAPPSVCPLAN
(✓) Done: Azure OpenAI: MYOPENAI
(✓) Done: Search service: MYSEARCHSVC
(✓) Done: App Service: MYAPPBACKEND

ERROR: deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'formrecognizer' is not valid according to the validation procedure. The tracking id is 'GUID'. See inner errors for details.
FlagMustBeSetForRestore: An existing resource with ID '/subscriptions/MYSUB/resourceGroups/MYRG/providers/Microsoft.CognitiveServices/accounts/MYCOGSVC' has been soft-deleted. To restore the resource, you must specify 'restore' to be 'true' in the property. If you don't want to restore existing resource, please purge it first.

  |       | Creating/Updating resources
```

### Expected/desired behavior
Deployment would be reproducable without issue.

### OS and Version?
Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ericthomas1** [comment]
I'm unsure where to "purge". I successfully deleted the resource from Azure Portal. 

```
If you don't want to restore existing resource, please purge it first. 
```

**Comment by liamFerris** [comment]
Encountered the same issue. 

There should be a button 'manage deleted resources' in Azure on the main page for each resource, beside the create button. 

In my case it was the form recogniser and the openAI resources I had to manually purge this way.

**Comment by ericthomas1** [comment]
Hm... I don't see a `manage deleted resources` button anywhere. I looked on the "main page" in portal.azure.com, in the resource group, etc. 

Even searching for the term showed no results in my tenant.
I'll try to redeploy again. Its been ~24hrs, maybe the cache has cleared(?)

**Comment by ericthomas1** [comment]
Ok. Figured it out. Thanks @liamFerris .

- Docs: https://learn.microsoft.com/en-us/azure/cognitive-services/manage-resources?tabs=azure-portal#purge-a-deleted-resource 
- It was actually trickier to find the button than to just issue the `az cli` call.

Ended up with:

- `az login`
- `az resource delete --ids /subscriptions/{my-sub-id}/providers/Microsoft.CognitiveServices/locations/{my-location}/resourceGroups/{my-rg}/deletedAccounts/{my-cog-svc-resource}`

Then just `azd up` and it deployed the missing resources and configured them.

**Comment by simonlkch** [comment]
> Ok. Figured it out. Thanks @liamFerris .
> 
> * Docs: https://learn.microsoft.com/en-us/azure/cognitive-services/manage-resources?tabs=azure-portal#purge-a-deleted-resource
> * It was actually trickier to find the button than to just issue the `az cli` call.
> 
> Ended up with:
> 
> * `az login`
> * `az resource delete --ids /subscriptions/{my-sub-id}/providers/Microsoft.CognitiveServices/locations/{my-location}/resourceGroups/{my-rg}/deletedAccounts/{my-cog-svc-resource}`
> 
> Then just `azd up` and it deployed the missing resources and configured them.

i try the az cli and azure portal way to purge the resource - azure openai, it throw this error.

```
(RequestConflict) Cannot modify resource with id '/subscriptions/{my-sub-id}/resourceGroups/{rg-name}/providers/Microsoft.CognitiveServices/accounts/{openai resource}' because the resource entity provisioning state is not terminal. Please wait for the provisioning state to become terminal and then retry the request.
Code: RequestConflict
```

**Comment by vhvb1989** [comment]
This PR makes `azd` to purge cognitive services: https://github.com/Azure/azure-dev/pull/2257
