### ISSUE TITLE
Answer won't search global content blob

### ISSUE THREAD

**Issue by kk0205** [Azure-Samples/azure-search-openai-demo#1562]
> Please provide us with the following information:
> ---------------------------------------------------------------
Using user upload and set to enforce login the answer from openai won't search global content blob but only the user blob

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, this is true. You would currently need to put all users in a group. We're tracking this issue here:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/1532

Closing this as a duplicate.
