### ISSUE TITLE
I am not able to change the "Retrieval mode" in the UX

### ISSUE THREAD

**Issue by biancat821** [Azure-Samples/azure-search-openai-demo#1587]
### This issue is for a:
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
When I change the "Retrieval mode" in the "Developer settings" the parameter return always to its default value.

### Any log messages given by the failure
--

### Expected/desired behavior
I would like to have the possibility to change the value of this parameter.

### OS and Version?
Windows 11

### azd version?
azd version 1.8.2 (commit 14600c7a54edac4f54397413f8638431f5c16327)

**Comment by pamelafox** [comment]
This was fixed by @john0isaac in https://github.com/Azure-Samples/azure-search-openai-demo/pull/1609 which was merged today.
