### ISSUE TITLE
Supporting files with apostrophy / punctuation mark in the file name

### ISSUE THREAD

**Issue by JayKidd81** [Azure-Samples/azure-search-openai-demo#1591]
### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Upload a file containing a ' such as: John's Menu.pdf
2. Wait for file to process
3. Message displayed: Error uploading file - please try again or contact admin.File uploaded successfully

### Any log messages given by the failure
Message: Invalid expression: ')' or operator expected at position 169 in '(oids/any(g:search.in(g, '<REMOVED GUID>')) or groups/any(g:search.in(g, '<REMOVED GUID>'))) and ((sourcefile eq '<REMOVED FILENAME>') or (sourcepage eq '<REMOVED FILENAME>'))'.
Parameter name: $filter 

Can see that its not escaping the the filename, so the code looks something like this:
sourcefile eq 'John's Menu.pdf'

### Expected/desired behavior
No error

### OS and Version?
Linux (deployed by azd)

### azd version?
azd version 1.8.1 (commit 88369c36ce2a0d60794389aad9b10de938f587e1)

### Versions
Apologies, don't have the exact commit#
Was pulled 2024-04-10 2:39am GMT from main branch
Likely after this pull request: https://github.com/Azure-Samples/azure-search-openai-demo/pull/1512

### Mention any other details that might be useful
Application insights end-to-end transaction:
SearchClient.search
DocumentsOperations.search_post
Posts to https://<REMOVED>.search.windows.net/indexes('<REMOVED>')/<REMOVED>/search.post.search?api-version=2023-10-01-Preview
Then returns an exception - latest (more detailed) one below:
Call Stack: Traceback (most recent call last):
  File "/tmp/8dc643f8284d926/decorators.py", line 25, in auth_handler
    authorized = await auth_helper.check_path_auth(path, auth_claims, search_client)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/core/authentication.py", line 262, in check_path_auth
    async for _ in results:
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 28, in __anext__
    return await self.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 31, in __anext__
    self._page = await self._page_iterator.__anext__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 108, in _get_next_cb
    return await self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc643f8284d926/antenv/lib/python3.11/site-packages/azure/search/documents/_generated/aio/operations/_documents_operations.py", line 417, in search_post
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Invalid expression: ')' or operator expected at position 169 in '(oids/any(g:search.in(g, '<REMOVED>')) or groups/any(g:search.in(g, '<REMOVED>'))) and ((sourcefile eq '<REMOVED>') or (sourcepage eq '<REMOVED>'))'.
Parameter name: $filter
Code: 
Message: Invalid expression: ')' or operator expected at position 169 in '(oids/any(g:search.in(g, '<REMOVED>')) or groups/any(g:search.in(g, '<REMOVED>'))) and ((sourcefile eq '<REMOVED>') or (sourcepage eq '<REMOVED>'))'.
Parameter name: $filter
, Message: Exception in /content: () Invalid expression: ')' or operator expected at position 169 in '(oids/any(g:search.in(g, '<REMOVED>')) or groups/any(g:search.in(g, '<REMOVED>'))) and ((sourcefile eq '<REMOVED>') or (sourcepage eq '<REMOVED>'))'.
Parameter name: $filter
Code: 
Message: Invalid expression: ')' or operator expected at position 169 in '(oids/any(g:search.in(g, '<REMOVED>')) or groups/any(g:search.in(g, '<REMOVED>'))) and ((sourcefile eq '<REMOVED>') or (sourcepage eq <REMOVED>'))'.
Parameter name: $filter

**Comment by JayKidd81** [comment]
_FYI... I removed the values denoting with triangular brackets with the value REMOVE, but was removed by the markup :(_

**Comment by pamelafox** [comment]
Taking a look at this, thanks for the report!

**Comment by pamelafox** [comment]
I've merged a fix for this, thanks for raising!
