### ISSUE TITLE
Error in login_and_acl.md when using ./script/manage.acl should be --document, not --url

### ISSUE THREAD

**Issue by adp-douglaswross** [Azure-Samples/azure-search-openai-demo#1594]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
In login_and_acl.md, the example speaks to --url when it should be --document

./scripts/manageacl.ps1 -v --acl-type groups --acl-action view --url https://st12345.blob.core.windows.net/content/Benefit_Options.pdf  SHOULD BE

./scripts/manageacl.ps1 -v --acl-type groups --acl-action view --document https://st12345.blob.core.windows.net/content/Benefit_Options.pdf

### Any log messages given by the failure
>
scripts fails with error

### Expected/desired behavior
>
script works if use --document

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Not relevant
### azd version?
> run `azd version` and copy paste here.
Not relevant
### Versions
>
Not relevant
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Probably my fault as I did a rename in there recently, looking.

**Comment by pamelafox** [comment]
Hm, I think you may be using an older version of the repo? I updated the scripts to use URL several weeks ago, since we now recommend referring to documents by their full URL, to reduce ambiguity between globally stored documents and user uploaded documents. I get an error with main when I use --document. You can continue using --document if you have an older version of the repo.

**Comment by adp-douglaswross** [comment]
Sorry, that is bad news, I thought I was up to date. Sorry for the waste of time. My git tells me I am up to date with main branch, however I can see that what is in github and what I have is not the same, so I am out of sync (somehow)... Sorry will close.

**Comment by pamelafox** [comment]
Your git may be saying you're up to date with your own fork (thats what it tells me, and then I go to Github to sync with the parent). There may be a fancier way of checking status with upstream.
