### ISSUE TITLE
when hit azd up, it shows /bin/sh: ./scripts/auth_init.sh: Permission denied

### ISSUE THREAD

**Issue by christ25442544** [Azure-Samples/azure-search-openai-demo#1610]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> just do as the same step on docs and when try to run and up, the error occurs.

### Any log messages given by the failure
>/bin/sh: ./scripts/auth_init.sh: Permission denied

ERROR: error executing step command 'provision': failed running pre hooks: 'preprovision' hook failed with exit code: '126', Path: './scripts/auth_init.sh'. : exit code: 126

### Expected/desired behavior
>
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by B-Kluss** [comment]
The problem is probably that you copied the files and the permissions are not set correctly. Try running chmod -R -x . in the main directory of the project. This has worked for me.
