### ISSUE TITLE
OpenAI Resource Access restricted --> "Key based authentication is disabled for this resource."

### ISSUE THREAD

**Issue by advanced-flow** [Azure-Samples/azure-search-openai-demo#1617]
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
- Merge release "2024-04-25: Bugfixes for free sku, ADLS2, storageUrl" 
- Run a indexer with embedding Skill in Azure AI Search or a Search Query with enabled vector search in the integrated search explorer.

### Any log messages given by the failure
**Azure AI Search Indexer**
Operation: Enrichment.AzureOpenAIEmbeddingSkill.#2
Message: Could not execute skill because the Web Api request failed.
Details: Web Api response status: 'Forbidden', Web Api response details: '{"error":{"code":"AuthenticationTypeDisabled","message": "Key based authentication is disabled for this resource."}}'

### Expected/desired behavior
I work with several datasources and indexers and need the option to set it up and test in the Azure Portal. 
After the release with #1555 which sets a parameter to the Azure OpenAI resource to disable OpenAI key access I receive above mentioned error.

**Comment by pamelafox** [comment]
I assume these are additional skills besides the ones setup with our standard integrated vectorization? If they require keys, then you need to set disableLocalAuth: false on the OpenAI resource. We will add an azd environment variable to make that easier to do per-environment, but you can change your main.bicep for now and do a re-deploy.

**Comment by advanced-flow** [comment]
Yes, I use the script with integrated vectorization as a starting point and then created a custom index fed by multiple indexers (SQL DB, image interpretations, video transcripts, etc.) with unique skillsets. 
So I think it's good to add an environment variable to enable LocalAuth; because there is no option in the Azure portal.

Anyway, I have now re-enabled local authentication with an Azure CLI command:
```
az resource update --resource-group {Name of the RG which contains the Azure OpenAI resource} --name {Name of the OpenAI Resource} --resource-type "Microsoft.CognitiveServices/accounts" --set properties.disableLocalAuth=false
``` 

I will close this issue.

**Comment by pamelafox** [comment]
Got it, okay! Yes, we'll add a boolean, as multiple developers have asked.

**Comment by pranayroni** [comment]
> I assume these are additional skills besides the ones setup with our standard integrated vectorization? If they require keys, then you need to set disableLocalAuth: false on the OpenAI resource. We will add an azd environment variable to make that easier to do per-environment, but you can change your main.bicep for now and do a re-deploy.

I've been blocked on this issue for a while, where in main.bicep would I have to change to update my existing AzureOpenAI resource?

**Comment by smithk4** [comment]
Was this azd environment variable ever added?  Thank you!

**Comment by pamelafox** [comment]
I've just made a PR for it here:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/2280
