### ISSUE TITLE
Incorrect Environment Variables name in main.bicep for GLOBAL_DOCUMENTS

### ISSUE THREAD

**Issue by zedhaque** [Azure-Samples/azure-search-openai-demo#1627]
Hi, 

Found a bug in main.bicep when it comes environment variables. 

Currently: 
AZURE_ENABLE_GLOBAL_DOCUMENTS

It should be:
AZURE_ENABLE_GLOBAL_DOCUMENTS_ACCESS

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

By the way did I mention UNAUTHENTICATED_ACCESS is the best feature ever 🥇 
I have revert back all my hacks and now back in sync with the repo :D :D

**Comment by pamelafox** [comment]
Thanks @zedhaque, assigning to @mattgotteiner
