### ISSUE TITLE
Search Results are Empty after Browsersession is inactive for a while

### ISSUE THREAD

**Issue by Recco23** [Azure-Samples/azure-search-openai-demo#1639]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use the app with login and document-level access control enabled. Interact with the app via chat. Then, leave the browser session open but idle for some time (3 hours should be sufficient, but a shorter period might also work).

### Any log messages given by the failure
> No

### Expected/desired behavior
> Browsersession should deliver Search Results as expected even after the Session idles for a longer time or a Message, that for example a Relog is needed must be displayed.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
tested with Windows 10 and Windows 11 in Chrome, Edge and Firefox

### azd version?
> run `azd version` and copy paste here.
azd version 1.9.2
### Versions
>Latest from Main branch

### Mention any other details that might be useful
The problem occurs when you chat with the web app and then leave it idle for an extended period (for example, 3 hours). When you start chatting again, the search results are always empty, even if the answers are present in the documents and would normally be retrieved.
<img width="445" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/69e57982-f920-433b-b859-2e04ad7298e3">
<img width="470" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/a0df94db-10b9-4904-ad06-03642d381230">
After refreshing the browser session (by pressing F5, clicking the refresh button), the system works as intended again. Opening the chatbot in a new browser tab even makes the old, non-functional tab work again.
<img width="466" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/14a46baf-10f6-4e87-995e-c2ca7642a74c">
<img width="476" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/5775591/c982a657-29a3-42fa-a182-7d9afb6344ef">

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
cc @mattgotteiner 

It feels like it could be an issue with the ID token expiring and needing a refresh, but thats speculation based on the issue description.

**Comment by mattgotteiner** [comment]
Agreed that it could be a token refresh issue. I'll try to see if we can check to refresh the token before it's used
