### ISSUE TITLE
gpt-4o

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/azure-search-openai-demo#1644]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>
May I know how to deploy the new gpt-4o model? Should it be the same as with the gpt-4 model? Thanks.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mirojs** [comment]
@mattgotteiner That's good news, thanks.

**Comment by Estrogenetics** [comment]
> @pamelafox is working on this. It did require other changes AFAIK

This is correct, I got it to work by deleting gpt-4 turbo chat and then deploying gpt-4o from the Azure Openai service interface after the model was made generally available at Microsoft Build. Deploying with azd up caused the web interface to fail loading after changing the model from gpt-4 to gpt-4o. Nice work around though and really loving the improvements of gpt-4o so far! Was such an exciting announcement!

**Comment by mirojs** [comment]
Right. Ideally, the vision feature is preferred. If there would be too much
effort, a temporary replacement for Turbo would also work due to the
language processing capability difference.

**Comment by pamelafox** [comment]
Okay, I'm going to test it out with the vision feature today. I did actually test the repo already with the OpenAi.com gpt-4o (and saw [good performance improvements](https://x.com/pamelafox/status/1790141116677058901)), but I'm going to test it with an Azure OpenAI deployment now that those are available.

**Comment by pamelafox** [comment]
You can see gpt-4o related changes in this branch:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1656/files

I'll continue doing performance and quality testing over next few days.
Unfortunately, as mentioned in the PR, its annoyingly difficult to simply swap to a gpt-4o deployment due to the region differences.

For an existing deployment:

* Check out that branch
* Change the .azure/ENV-NAME/config.json file so that "openAiResourceGroupLocation" has a gpt-4o compatible location like "eastus"
* Delete the current OpenAI resource (dont do this if you're live, of course!). Go into Portal and purge the resource as well (OpenAI > Manage deleted resources > Purge).
* Re-run azd up

Then it should create a new OpenAI resource in that location with the gpt-4o deployment.

**Comment by Lawndemon** [comment]
> > @pamelafox is working on this. It did require other changes AFAIK
> 
> This is correct, I got it to work by deleting gpt-4 turbo chat and then deploying gpt-4o from the Azure Openai service interface after the model was made generally available at Microsoft Build. Deploying with azd up caused the web interface to fail loading after changing the model from gpt-4 to gpt-4o. Nice work around though and really loving the improvements of gpt-4o so far! Was such an exciting announcement!

how did you get the web interface working again? I'm running into the same problem so any advice would be appreciated!

**Comment by pamelafox** [comment]
What error are you getting with the web interface?

**Comment by Lawndemon** [comment]
I was getting the blank site with no errors during build + deploy. Did a bit of digging and found some version mismatches in requirements. txt as well as a couple other spots that needed to be updated in main.bicep as well as some tweaks required in modelhelper.py and config.py. I managed to track down the errors by tuning the app insights implementation and it showed the app service wasn't starting properly. Working great with GPT4o now though!

**Comment by Lawndemon** [comment]
> What error are you getting with the web interface?

I was getting the blank site with no errors during build + deploy. Did a bit of digging and found some version mismatches in requirements. txt as well as a couple other spots that needed to be updated in main.bicep as well as some tweaks required in modelhelper.py and config.py. I managed to track down the errors by tuning the app insights implementation and it showed the app service wasn't starting properly. Working great with GPT4o now though!

**Comment by pamelafox** [comment]
@Lawndemon Ah yes if you still have modelhelper.py from the older version of the repo, that would need tweaks. The repo now uses a packaged version of modelhelper that I specifically upgraded for gpt-4o compatibility.

Closing this issue since the repo now defaults to gpt-4o for vision.

**Comment by YIN-Renlong** [comment]
@pamelafox @mirojs 

The official documentation has written the steps to update the gpt version, and the steps seem to be different from the tutorial here. Although only examples for gpt4 are written, they are also applicable to gpt-4o. For your reference:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md
