### ISSUE TITLE
This repo and commercial purposes

### ISSUE THREAD

**Issue by billigproton** [Azure-Samples/azure-search-openai-demo#1654]
Hello,
I have a question about the licensing of this solution. Does it have some sort of a license that it prevents from using it commercially?

Thanks!

Best regards,
Daniel

**Comment by pamelafox** [comment]
We use MIT license:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LICENSE
That generally does permit commercial use, but check with a lawyer if you have doubts.
