### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by stefan-ellenrieder** [Azure-Samples/azure-search-openai-demo#168]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Used GitHub codespaces
- Used existing resources and set their environment variables
- Error when running 'azd up'
>

### Any log messages given by the failure
Problem: Error when running 'azd up'
Received the following error, but the client has the role 'owner' for the used resource group.

Response: 403 Forbidden
Error code: Authorization Failed
Message: 
The client does not have authorization to perform action 'Microsoft.Resources/deployments/write'.
>

### Expected/desired behavior
Succesful deployment
>

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tickx-cegeka** [comment]
I have the same issue. I think this is because it makes a deployment under the subscription level, where you (we) don't have the necessary rights. I don't have any solution for it yet, I would appreciate a solution which only requires to be owner of a resource group.

**Comment by zhongshuai-cao** [comment]
I am working on my local environment and got the same error message when I run
```bash
azd init -t azure-search-openai-demo
```
A detailed permission list can be provided to run the demo.

**Comment by wtyeung** [comment]
refer https://github.com/Azure-Samples/azure-search-openai-demo/issues/4#issue-1619906532

**Comment by szelesaron** [comment]
+1 this, I have the perms but still the same issue

**Comment by stefan-ellenrieder** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data
