### ISSUE TITLE
Error with "Login" button

### ISSUE THREAD

**Issue by biancat821** [Azure-Samples/azure-search-openai-demo#1697]
### This issue is for a:
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Enable the authetication as described in 
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md#automatic-setup

The optional steps 3, 4 and 5 for ACL were skipped.

### Any log messages given by the failure
AADSTS900144: The request body must contain the following parameter: **'client_id'.**

![Screenshot (1095)](https://github.com/Azure-Samples/azure-search-openai-demo/assets/152168319/34db1df0-860f-412f-bfc0-0c780a6c84e5)

### Expected/desired behavior
The system allowed the user to login

### OS and Version?
Windows 11

### azd version?
azd version 1.8.1 (commit 88369c36ce2a0d60794389aad9b10de938f587e1)

**Comment by pamelafox** [comment]
Hm, I wonder if the environment variables aren't set correctly. Can you check AZURE_CLIENT_APP_ID and AZURE_SERVER_APP_ID on your deployed App Service app and confirm they match the application registrations? Are you seeing this error on local dev server or deployed app?

**Comment by mattgotteiner** [comment]
Can you also please check the app in the portal that was setup and tell us what platforms are configured?

https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app#configure-platform-settings

**Comment by evan2k** [comment]
same issue here. Neither AZURE_CLIENT_APP_ID nor AZURE_SERVER_APP_ID  were setup in either dev or deployed. I thought azd up should have filled those up. Right? Thanks.

**Comment by biancat821** [comment]
First of all, thank you Pamela and Matt.
As Evan, that is having my same issue, I do not have the AZURE_CLIENT_APP_ID nor AZURE_SERVER_APP_ID setup in.
Moreover I also checked the app in the portal following the instructions in the link provided by Matt.
I have the following configuration

![Screenshot (1111)](https://github.com/Azure-Samples/azure-search-openai-demo/assets/152168319/79e65f01-2da9-4b42-a34f-b0610bd850c7)

Copying and pasting the link provided in the screenshot above I am returned with the following message.

![Screenshot (1110)](https://github.com/Azure-Samples/azure-search-openai-demo/assets/152168319/1cc27025-0ad4-4ee5-babd-66999f2e9566)

However, when I enter the chat-app and I press the "Login" button, I am returned with the same error.

**Comment by biancat821** [comment]
We finally managed to solve the issue.
Actually in the area _Registrations App_ of Azure we did not have the:
- Azure Search OpenAI Chat Client
- Azure Search OpenAI Chat Server

The problem was due to the fact that, when launching the command 

> azd up

the two applications mentioned above were not created.

This was caused by an error due to **long path not enabled**.

Therefore our solution was:
1. Enable the long path in Windows (e.g. following instructions in [Make Windows accept File Paths over 260 characters (thewindowsclub.com)](https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10))
2. Adding in the **.env** file the environmental variable **AZURE_TENANT_ID** that was set equal to **AZURE_AUTH_TENANT_ID**
3. Running the script **auth_init.ps1** with the command  

> pwsh .\scripts\auth_init.ps1

4. At this point the two apps mentioned above appeared in the area _Registrations App_ of Azure.
5. Finally we launched the command

> azd up

6. It took a while to have the chat app running again (at least 1 hour), so be patient after point 5.

**Comment by milind-devlok** [comment]
Followed same process of what @biancat821 has mentioned, the env variables are set, but the azd up is taking too long, have waited 3-4 hrs ,Can someone pleas suggested how to resolve ths?Thanks

**Comment by pamelafox** [comment]
It should not take 3-4 hours, unless you're ingesting a huge amount of data. That sounds like a failed deploy to me. Have you checked the deployment center in App Service to see what the status is?  See my docs here about debugging deployments:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/appservice.md
I'd cancel it and run it again.
