### ISSUE TITLE
Stuck on azd deploy

### ISSUE THREAD

**Issue by bp3000bp** [Azure-Samples/azure-search-openai-demo#1708]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Unsure how to reproduce but could be hitting Ctrl + C during a deployment from Powershell.

### Any log messages given by the failure
>No failures shown

### Expected/desired behavior
>On Friday I hit ctrl + C for the first time on an azd deploy. That's the only thing I can remember doing differently. Since then, when I do azd deploy, it shows that my deployment went through with no issues or warnings on the Deployment Center logs, but it gets stuck and never gives me the link to the deployed site in Powershell like it used to. Not sure how to fix, just want to make sure that I haven't completely messed up the deployment process. The site still deploys and shows as successful in the Deployment Center. Should I just keep working as normal or is there something I need to fix? 

### OS and Version?
> Windows 11 Pro 

### azd version?
> azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, this sounds like it could be an azd issue. Perhaps it'd help to run with --debug next time and share the logs from when it's stuck?
