### ISSUE TITLE
ADLSG2 - Deployment Error, The property 'isHnsEnabled' was specified in the input, but it cannot be updated as it is read-only.

### ISSUE THREAD

**Issue by tlievre** [Azure-Samples/azure-search-openai-demo#1710]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run azd up after following steps from https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md#azure-data-lake-storage-gen2-setup to create ADLSG2.

### Any log messages given by the failure
> 
Packaging services (azd package)

  (✓) Done: Packaging service backend
  - Package Output: xxxx\azure-search-openai-demo-backend-azddeploy-xxxxxx.zip
Loading azd .env file from current environment
Creating python virtual environment ".venv"
Error: [Errno 13] Permission denied: xxxx/python.exe
Installing dependencies from "requirements.txt" into virtual environment
Requirement already satisfied: ...
...

Setting up authentication...                                                                                                                                                 
Checking if application xxxx exists
Application already exists, not creating new one
Setting up server application permissions...
Checking if application xxxx exists
Application already exists, not creating new one
Setting up server known client applications...
Authentication setup complete.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: xxxxx (xxxxx)
Location: West Europe

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/xxxx
    
(✓) Done: Resource group: xxxxx
  (✓) Done: Search service: xxxxx
  (✓) Done: App Service plan: xxxxx
  (✓) Done: Log Analytics workspace: xxxxx
  (x) Failed: Storage account: xxxxx
  (✓) Done: Azure OpenAI: xxxxx
  (✓) Done: Application Insights: xxxxx
  (✓) Done: Document Intelligence: xxxxx
  (✓) Done: Portal dashboard: xxxxx
  |====   | Creating/Updating resources

**ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:
Deployment Error Details:
AccountPropertyCannotBeUpdated: The property 'isHnsEnabled' was specified in the input, but it cannot be updated as it is read-only. For more information, see - https://aka.ms/storageaccountupdate  
TraceID: xxxxx**

### Expected/desired behavior
> Deployment succeed

### OS and Version?
> Windows 10

### azd version?
> 1.9.3

### Versions
>

### Mention any other details that might be useful
I have migrated the original storage account to ADLS2. I'm not sure if we should keep the storage account and create another one with ADLS2 to make it work. I would like to know if the process I am following is the typical one.

> Thanks a lot !

**Comment by pamelafox** [comment]
Yeah you'll have to make a new storage account, as Azure doesn't let you migrate an existing one. You can either delete current storage account or maybe just set a new name via

```
azd env set AZURE_STORAGE_ACCOUNT newstacctname
```
