### ISSUE TITLE
Azd up - unsupported node version error in Github codespace

### ISSUE THREAD

**Issue by SakuJ** [Azure-Samples/azure-search-openai-demo#1722]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
ERROR: error executing step command 'package --all': failed packaging service 'backend': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '1', Path: '/tmp/azd-prepackage-2903021198.sh'. : exit code: 1, stdout: , stderr: npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: marked@13.0.0
npm ERR! notsup Not compatible with your version of node/npm: marked@13.0.0
npm ERR! notsup Required: {"node":">= 18"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}

### Expected/desired behavior
I get this error message when I try to run the "azd up" command in Github Codespace. I open the codespace from the documentation link. 

### OS and Version?
> Windows 11

### azd version?
1.9.3

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Sorry about that, please make this change and rebuild the Codespace:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1721/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L6

**Comment by pamelafox** [comment]
Fixed in https://github.com/Azure-Samples/azure-search-openai-demo/pull/1721
