### ISSUE TITLE
feat: Update orphaned modules to use avm instead of `azd/infra/core`

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/azure-search-openai-demo#1754]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> We are finding orphaned modules in azd/infra/core and getting them to move to avm.

In the repo: https://github.com/Azure-Samples/azure-search-openai-demo,

there are two orphaned modules should move to avm:

- [Cognitive Services](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/main.bicep#L394)
- [Search Services](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/main.bicep#L459)

You can find the corresponding modules in avm here:

- [Cognitive Services in avm](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cognitive-services/account/main.bicep)
- [Search Services in avm](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/search/search-service/main.bicep)

@jongio, @pamelafox for notification.

**Comment by pamelafox** [comment]
Sorry, what does orphaned model mean? As in azd no longer has them? Or that ours have diverged from azd? We did diverge them when we added vnet, intentionally, as it was a large change and this is the first sample to use vnet heavily. We're happy to use avm if it supports all the same parameters, however. I think we would need to do a --dryrun to see if it changed anything about the parameters.

**Comment by zedy-wj** [comment]
Sorry, we are not yet fully ready to migrate to avm. We will close this issue first and reopen it when we are ready.
