### ISSUE TITLE
Running npm run dev gives blank page

### ISSUE THREAD

**Issue by AxelQSam** [Azure-Samples/azure-search-openai-demo#1788]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Go to app/
Execute $ ./start.sh

Open new terminal

Go to app/frontend/.
Execute $ npm run dev.
Navigate to the provided address in the browser.
See blank page in the browser.

### Any log messages given by the failure
>Can't find any errors

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
I took a break from my project and before the break it used to work. Now I can't hot reload. I have the same problem with sample-app-aoai-chatGPT. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, it might be due to a recent vite/Docker issue: https://github.com/vitejs/vite/issues/16522

Does it help if you make this change to package.json?

    "dev": "vite --host 127.0.0.1",

There are also other suggestions in that thread.
We can make that change to the repo if it improves the situation. 

Also, are you working inside a Dev Container?

**Comment by AxelQSam** [comment]
> Hm, it might be due to a recent vite/Docker issue: [vitejs/vite#16522](https://github.com/vitejs/vite/issues/16522)
> 
> Does it help if you make this change to package.json?
> 
> ```
> "dev": "vite --host 127.0.0.1",
> ```
> 
> There are also other suggestions in that thread. We can make that change to the repo if it improves the situation.
> 
> Also, are you working inside a Dev Container?

Changing package.json solved the issue. Thank you @pamelafox 👍 

And yes, I was working in a Dev Container.

**Comment by pamelafox** [comment]
Okay, I will make that change for the repo.
