### ISSUE TITLE
Ingest pdf document from blob storage, and change default values of "Retrieve this many search results"

### ISSUE THREAD

**Issue by samrere** [Azure-Samples/azure-search-openai-demo#1794]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> 1. process and upload pdf documents from blob storage, 2. change the default value of "Retrieve this many search results" from 3 to 5

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.9.3

### Mention any other details that might be useful
Hi Azure team,
Is there a native way to ingest the pdf documents from blob storage? Currently we can only copy those docs to local data folder, then run scripts/prepdoc. Also, can we also change the default values too (i.e. "Retrieve this many search results")? Thank you!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
For changing default values, see this section in the customization guide:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/customization.md#making-settings-overrides-permanent

For ingesting PDF documents, you can use integrated vectorization:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md#overview-of-integrated-vectorization
That feature does not yet track page numbers of PDFs, however, so you'd need to write a custom skill for that if that is needed.

**Comment by pavsingh7** [comment]
Hi @pamelafox 

Has any skills been added that are able to track page numbers on PDFs (in integrated vectorisation), or are they in the pipeline :)

Thanks in advance for your work.
