### ISSUE TITLE
Response citation: Requested URL not found 

### ISSUE THREAD

**Issue by poonkuzhali** [Azure-Samples/azure-search-openai-demo#1798]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I deployed the default code with almost no changes except for the data. The citation name generated in the chat does not match the file name in the blob which gives an error
> The chatbot gives the right answer. The thought process is right too. Just the citation name is generated different

### Any log messages given by the failure
Traceback (most recent call last):
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 546, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 289, in _setup
    self._response = await self._initial_request()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 384, in _initial_request
    process_storage_error(error)
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 182, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 338, in _initial_request
    location_mode, response = await self._clients.blob.download(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 203, in download
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/tmp/8dc9ad09b4a44f0/antenv/lib/python3.11/site-packages/azure/core/exceptions.py", line 161, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
RequestId:b3736148-d01e-0004-7738-d1ea8c000000
Time:2024-07-08T13:13:59.7491340Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:b3736148-d01e-0004-7738-d1ea8c000000
Time:2024-07-08T13:13:59.7491340Z</Message></Error>

### Expected/desired behavior
> The document for the citation should be viewable on clicking the citation link. The citation name should match the file stored in blob. But the citation name is different from the file stored in blob. Therefore, blob not found error while trying to view citation. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Python 3.11, Linux

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
I am not sure why the citation name is not the same as the file in blob. Any help would be appreciated.

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/12248032/da297eb7-e730-4bf3-ba73-f718e4de2161)

**Comment by tlievre** [comment]
Hi @poonkuzhali,
I encountered a similar issue (#1723) due to incorrect environment configuration when setting up ADLSG2 for ACL. The root cause was misconfigured AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_CONTAINER environment variables. To resolve this, ensure that both variables are properly defined in your `.env` file and refer to an existing deployed resource/container name.

**Comment by pamelafox** [comment]
Can you check to see whether the issue is that the LLM has hallucinated the wrong name, or whether we've parsed the name incorrectly? Please check:

1) The thought process tab shows the correct name in the Sources: list
2) The response from the LLM contains the correct citation (turn off streaming, and find the response in your Network tab)

If the LLM hallucinated, then the main approach would be prompt engineering. However, if the LLM correctly generated the citation, then there is presumably a parsing error in our code somewhere.

**Comment by poonkuzhali** [comment]
@tlievre @pamelafox Thanks for the response!

I added some own files to the data folder. The file name had spaces. For example: Store Manual.pdf instead of Store_Manual.pdf. 

When the file name had spaces, during citation retrieval, the file name gets ignored and instead the first line of text from the content is retrieved as file name. 

Hence the not found error while trying to view citation, because the file name retrieved by citation and the actual file name in blob differs. After I changed the file name (after removing space from the file name), the citation works as expected.

**Comment by pamelafox** [comment]
Interesting, I just tried a filename with spaces, and I wasn't able to replicate the issue. Is your code up to date with main? If you can figure out where the error is happening, then we can fix it. 

![Screenshot 2024-07-10 at 2 39 17 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/a36179a4-6315-4b7d-ad0e-53c1af99c07c)

**Comment by poonkuzhali** [comment]
File name parsing error is fixed once the code was updated to the recent version. Closing the issue. Thank you for the help @pamelafox
