### ISSUE TITLE
Problem with Azure Deployment (Failed: Packaging service backend)

### ISSUE THREAD

**Issue by volsh-smart-it** [Azure-Samples/azure-search-openai-demo#1834]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> folowing readme on deployment up to the point of "azd up"

### Any log messages given by the failure
>Packaging services (azd package)

  (x) Failed: Packaging service backend

ERROR: error executing step command 'package --all': failed packaging service 'backend': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '1', Path: 'C:\Users\volsh\AppData\Local\Temp\azd-prepackage-4040297706.ps1'. : exit code: 1, stdout: , stderr: npm: C:\Users\volsh\AppData\Local\Temp\azd-prepackage-4040297706.ps1:4
Line |
   4 |  cd ../frontend;npm install;npm run build
     |                 ~~~
     | The term 'npm' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.

### Expected/desired behavior
I want my app with RAG deployed

### OS and Version?
Windows 10

### azd version?
azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)

**Comment by pamelafox** [comment]
Do you have Node installed? That's required, per the local setup guide here:
https://github.com/Azure-Samples/azure-search-openai-demo?tab=readme-ov-file#local-environment

Please open a new issue if you still have an error after installing Node. Thanks!
