### ISSUE TITLE
ERROR: deployment failed: error deploying infrastructure: deploying to subscription:

### ISSUE THREAD

**Issue by IhebGhazala** [Azure-Samples/azure-search-openai-demo#184]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>running azd up 

### Any log messages given by the failure
>ERROR: deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
Conflict: No available instances to satisfy this request. App Service is attempting to increase capacity. Please retry your request later. If urgent, this can be mitigated by deploying this to a new resource group.
- No available instances to satisfy this request. App Service is attempting to increase capacity. Please retry your request later. If urgent, this can be mitigated by deploying this to a new resource group.

### Expected/desired behavior
>the app service plan is expected to deploy with no error

### OS and Version?
> Windows 11

### Versions
>22H2

### Mention any other details that might be useful
nothing to mention the error detail provides all the info,also i tried making a new resource group just as it recommended but i got the same error
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FunkyDialUpDude** [comment]
I am receiving the same error when trying to deploy to East US. Any update on this issue?
