### ISSUE TITLE
Word Source is included in the citation of PNG files when Vision is enabled.

### ISSUE THREAD

**Issue by hfaouaz-rcg** [Azure-Samples/azure-search-openai-demo#1842]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Enable GPT4V,  prepdocs a pdf, then when asking a question, the citation in the completion is including the word Source in the link which breaks the link.

### Any log messages given by the failure
>
File not found when clicking on the citation.

### Expected/desired behavior
>
citation link should be correct.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOs Sonoma 
### azd version?
> run `azd version` and copy paste here.
azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
### Versions
>

### Mention any other details that might be useful

To fix, I added the following to the system prompt in chatreadretrievervisio

```
 Don't include the word source in the citation.

```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Sorry, can you give a more precise example? Like the JSON returned? 
What do you mean by word source?

**Comment by hfaouaz-rcg** [comment]
Hi @pamelafox,  ugh!! can't reproduce now.   But here is a detail description.  When the citation is rendered, the url link contains the word SOURCE:<filename>   markup   http://host/SOURCE:%20<filename>
