### ISSUE TITLE
Citations - File Download Blocked

### ISSUE THREAD

**Issue by kyle-bosley** [Azure-Samples/azure-search-openai-demo#1843]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Delete sample data from the data folder and upload personal company data.

### Any log messages given by the failure
>The file you are trying to download has been blocked in accordance with company policy. Please contact your system administrator if you believe this is an error.
>File name: Company Manual.pdf
>Please click  to download/upload the file.

### Expected/desired behavior
>To display the citation for our data the same way as the sample data. 

### OS and Version?
> Windows 11 Enterprise

### azd version?
> azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)

### Mention any other details that might be useful
>I followed the guide for data customization and uploaded my Company Manual's PDF. The program can answer questions about the document and the 'Supporting Content' is displayed but the citations are currently being blocked. I made sure to confirm that the Azure blob storage is accessible. I also checked to see if there was any similar issues, and did not see. However I saw this [PR](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1765) and thought it might be related.

>![Screenshot 2024-07-19 135142](https://github.com/user-attachments/assets/40d52de8-58f4-4e19-9781-22da91853fbe)

> ---------------------------------------------------------------
> Any information about this would be greatly appreciated.

**Comment by pamelafox** [comment]
Hm, that looks like an error from your Operating System - we do not have an error message like that in our code. Perhaps your OS is running software that looks at the binary data and decides whether it can be shown?

We do not serve the blob links as direct URIs, we instead use the SDK to download them and send them to the browser, so the blocking must be happening based on either the app path (/content/Company Manual.pdf) or the actual content of the file. Given the path seems pretty innocent, I would assume it's reviewing the actual content of the file.

cc @mattgotteiner in case he recognizes this error as a Windows security mechanism (I use a Mac)

**Comment by kyle-bosley** [comment]
Thank you for your clarification. I did some investigation with my team and my Firewall was detecting the pdf as encrypted which is it not. Our IT guy made an exception, and all worked as expected. Thank you!!
