### ISSUE TITLE
"Azd auth login" fails in Github Codespaces

### ISSUE THREAD

**Issue by GiuseppeGalilei** [Azure-Samples/azure-search-openai-demo#1855]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run `azd auth login` from github codespace

During the login phase you get redirected to a localhost webpage that doesn't exist, which causes the login to fail.
instead, using `azd auth login --use-device-code`  seems to work fine.
A similar issue has been reported here:  https://github.com/Azure/azure-cli/issues/20315

To fix it, I guess it would be enough to provide this alternative command on the README, for codespace users.

**Comment by pamelafox** [comment]
The azd CLI is meant to autodetect that device code must be used. Can you file an issue at https://github.com/Azure/azure-dev/ or comment on https://github.com/Azure/azure-dev/issues/1250 that you found yourself needing to use device code?
