### ISSUE TITLE
Error Running prepdocs.py

### ISSUE THREAD

**Issue by sqlshep** [Azure-Samples/azure-search-openai-demo#189]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>. Follow the steps in the git repo for new or for existing services.  Fails at azd up

### Any log messages given by the failure
>Running "prepdocs.py"
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "./scripts/prepdocs.py", line 299, in <module>
    create_search_index()
  File "./scripts/prepdocs.py", line 237, in create_search_index
    if args.index not in index_client.list_index_names():
  File "/Users/shepsheppard/scripts/.venv/lib/python3.8/site-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/Users/shepsheppard/scripts/.venv/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/shepsheppard/scripts/.venv/lib/python3.8/site-packages/azure/search/documents/indexes/_generated/operations/_indexes_operations.py", line 520, in get_next
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Authorization failed.
Code: 
Message: Authorization failed.

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: './scripts/prepdocs.sh'. : exit status 1

### Expected/desired behavior
> Not fail

### OS and Version?
>  macOS Ventura 

### Versions
> 13.3.1(a)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Goro2030** [comment]
Same error here. Maybe has to do with permissions?

**Comment by vikramhn** [comment]
https://github.com/Azure-Samples/azure-search-openai-demo/issues/79#issuecomment-1507899444 
"Search Index Data Contributor" role was already there. What fixed it for me was to add "Search Service Contributor" role to my ID.

**Comment by Goro2030** [comment]
What solved it to me, was to add me as "OWNER" of the "gptkb-d3v5axy2dfrvs" service. That fixed the problem!

**Comment by pchurak** [comment]
I have this error on free pricing tier even when OWNER role is presented.
