### ISSUE TITLE
Deploying GPT-4o mini instead of 3.5 Turbo

### ISSUE THREAD

**Issue by bnerbz** [Azure-Samples/azure-search-openai-demo#1891]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Just looking for anyway to deploy on the newest model

### Any log messages given by the failure
> no failure

### Expected/desired behavior
> Would like to be able to deploy using gpt 4o mini instead of 3.5 turbo anyway way of doing this?

### OS and Version?
> Windows 10

### azd version?
> 1.9.5

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, it's just been documented here!
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md#using-gpt-4

Please file a new issue if you have any issues following those instructions.

**Comment by DuboisABB** [comment]
This is not officially supported by this code base at this moment. This will need to be addressed first :
https://github.com/pamelafox/openai-messages-token-helper/issues/16

**Comment by DuboisABB** [comment]
Doesn't openai-messages-token-helper need to be updated to support gpt-4o-mini? get_token_limit() errors out.

**Comment by pamelafox** [comment]
Ah, you should be able to pass in a boolean to `build_messages` to say you're okay with it defaulting to the standard encoding (`fallback_to_default=True`), but yes, that boolean isn't set in this repo. I'll add support for mini ASAP.

**Comment by bnerbz** [comment]
I followed the outlined procedure for changing models and was left with this error:

ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '*********************'. See inner errors for details.
CannotChangeDeploymentModel: The model of deployment cannot be changed.
InvalidTemplateDeployment: The template deployment 'documentintelligence' is not valid according to the validation procedure. The tracking id is '***********************'. See inner errors for details.
FlagMustBeSetForRestore: An existing resource with ID '/subscriptions/8f60847c-f418-44e3-b989-9f5e042dc0db/resourceGroups/rg-*******/providers/Microsoft.CognitiveServices/accounts/***********' has been soft-deleted. To restore the resource, you must specify 'restore' to be 'true' in the property. If you don't want to restore existing resource, please purge it first.

Let me know if I'm missing something

**Comment by pamelafox** [comment]
@bnerbz I think you need to change the deployment name, it looks like you have a deployment with same name but different model.

I'm close to getting the gpt-4o-mini token counting change released. It has a 33.3333x multiplier for image token costs, which was apparently added to compensate for the cheaper text token costs. So you won't see cost savings for vision requests, if that's what you're using it for (but you will for text).
https://github.com/pamelafox/openai-messages-token-helper/pull/17

**Comment by bnerbz** [comment]
Any other ideas? As soon as I run azd up after setting the environment I get: 

The model of deployment cannot be changed. (Code: CannotChangeDeploymentModel), along with the same error as before

**Comment by pamelafox** [comment]
You're still getting the error after setting a new deployment name? Can you check your Azure OpenAI account and see what deployment names are currently there, and see what the value of AZURE_OPENAI_CHATGPT_DEPLOYMENT is for you.  (Run `azd env get-value AZURE_OPENAI_CHATGPT_DEPLOYMENT`)
