### ISSUE TITLE
Feature: Generate text to speech on demand

### ISSUE THREAD

**Issue by TaylorN15** [Azure-Samples/azure-search-openai-demo#1892]
It seems that TTS is run for all answers automatically, and users are given the option to play the stream. Most of my users wouldn't use the feature, so we would be unnecessarily calling the Speech Service API in many cases. I'd like to be able to call this on demand only. I.e. a user clicks the play button on a message, and _then_ it calls the API to synthesize the speech.

**Comment by pamelafox** [comment]
I think we did this so that the experience feels fast when you actually click the button, but that's true that it's wasteful if most users aren't using it. 

We need to decide if this is something all developers want, or if it's yet another option. I'm fine with making the change across the board, given that we should generally lean towards *not* wasting computational resources unnecessarily. 

I don't think the speech icon has a proper loading state currently, just a disabled/enabled, if I remember correctly, so it would need a loading state. 

@john0isaac Any interest in taking this on, given your familarity with the TTS features?

**Comment by john0isaac** [comment]
sure

**Comment by TaylorN15** [comment]
@john0isaac - I mean in either case (web speech API or Azure Speech). I prefer using the Azure Speech SDK as I can use neural voices. But I don't want to call the API pre-emptively and generate TTS for all the answers, if the user isn't even going to use the feature, as this will incur unnecessary costs. Right now, I have my own version implemented using `react-text-to-speech` and `useSpeech` so when a user clicks on a "Play" button under the response, it will render and play using the web speech API. Basically I'd like this same functionality, but using Azure Speech.

**Comment by john0isaac** [comment]
It was implemented like that because the answer card is a component that why we pre-populate it with everything to not maintain any state about moving forward in the conversation.
Let me see what I can do, do you mind sharing your code here?

**Comment by TaylorN15** [comment]
My code is highly customised. But here's the gist. 

I've created an `AnswerOptionsPanel` component with some buttons/actions at the bottom of each `Answer`.

```
interface Props {
...
handleSpeechAction: (action: 'play' | 'pause' | 'stop' | 'restart') => void;
speechStatus: SpeechStatus;
...
}
...
{speechStatus === 'started' ? (
	<>
		<div
			className={isStreaming ? styles.disabled : ''}
			onClick={isStreaming ? undefined : () => handleSpeechAction("pause")}
			title="Pause">
			<Pause16Filled className={styles.adjustInputIcon} />
		</div>
		<div
			className={isStreaming ? styles.disabled : ''}
			onClick={isStreaming ? undefined : () => handleSpeechAction("stop")}
			title="Stop">
			<Stop16Filled className={styles.adjustInputIcon} />
		</div>
	</>
) : speechStatus === 'paused' ? (
	<>
		<div
			className={isStreaming ? styles.disabled : ''}
			onClick={isStreaming ? undefined : () => handleSpeechAction("play")}
			title="Play">
			<Play16Filled className={styles.adjustInputIcon} />
		</div>
		<div
			className={isStreaming ? styles.disabled : ''}
			onClick={isStreaming ? undefined : () => handleSpeechAction("stop")}
			title="Stop">
			<Stop16Filled className={styles.adjustInputIcon} />
		</div>
	</>
) : (
	<div
		className={isStreaming ? styles.disabled : ''}
		onClick={isStreaming ? undefined : () => handleSpeechAction("play")}
		title="Play">
		<Play16Filled className={styles.adjustInputIcon} />
	</div>
)}
```

Then in `Answer.tsx`

```
    const [textForSpeech, setTextForSpeech] = useState<string>("");
    const [ttsAction, setTtsAction] = useState<string>('');
    const { speechStatus, start, stop, pause } = useSpeech({
        text: textForSpeech,
        pitch: 1,
        rate: 1,
        volume: 1,
        lang: "en-AU",
        voiceURI: "Microsoft James - English (Australia)",
    });



    const handleSpeechAction = async (action: "play" | "pause" | "stop" | "restart") => {
        setTtsAction(action);
        const plainText = answerRef.current?.textContent || "";

        switch (action) {
            case "play":
                setTextForSpeech(plainText);
                break;
            case "pause":
                pause();
                break;
            case "stop":
                stop();
                break;
            case "restart":
                stop();
                setTtsAction("play");
                break;
            default:
                break;
        }
    };

    useEffect(() => {
        if (ttsAction === "play" && textForSpeech) {
            start();
            setTtsAction(''); // Reset ttsAction after starting
        }
    }, [textForSpeech, ttsAction]);
```

**Comment by john0isaac** [comment]
I traced the code and I think that you are definitely speaking about the AzureSpeech service as the WebSpeechAPI is never called unless you click on the button.
I will see what I can do for the Azure Speech option.

**Comment by TaylorN15** [comment]
My code is quite different to this codebase. The sample I provided is used to generate TTS only when you press the play button. I'm hoping for an option like that but using Azure Speech instead.

**Comment by john0isaac** [comment]
I meant this repo's code not your code. I was just updating the status of the issue that now the only change required is for the Azure Speech Service implementation.
