### ISSUE TITLE
After Deployment, I am not able to see upload or Login features

### ISSUE THREAD

**Issue by amityoko** [Azure-Samples/azure-search-openai-demo#1896]
Recently I have cloned the git & tried to deploy the app as per the instructions, but after deploying the app I am unable to find the Upload or Login features. Can you please help me to understand if i need to do something else to enable login & upload file functionality. Please find the image for your reference.

![image](https://github.com/user-attachments/assets/7db047c7-02a2-42ad-8a66-ad41b28bd97f)

**Comment by pamelafox** [comment]
Those are both optional features. See the guides here for information on enabling them:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md

Please open a new issue if you encounter errors while following those guides. Sorry for the confusion!

**Comment by amityoko** [comment]
I tried to follow readme https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md
After following above article, i tried to run this script "pwsh ./scripts/manageacl.ps1 --acl-action enable_acls" but getting below error, what should i do to resolve it

![image](https://github.com/user-attachments/assets/d59531af-2000-413c-873c-2580f74ec613)
