### ISSUE TITLE
Getting long path error, while installing requirements.txt

### ISSUE THREAD

**Issue by amityoko** [Azure-Samples/azure-search-openai-demo#1898]
I tried to follow readme https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md
After following above article, I tried to run , azd up command...I am getting below error, any idea how to resolve it...I have enabled long path in my registry, still getting same error

![image](https://github.com/user-attachments/assets/5fcac152-d90d-4e9b-b28d-6c561c78a0ea)

**Comment by pamelafox** [comment]
You followed that instruction? https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

If that doesn't work, am not sure. Maybe you need to restart the shell or computer?

CCing @mattgotteiner who has more Windows familarity

**Comment by amityoko** [comment]
I have resolved it, Anyone getting similar error please follow below url

[https://helpdeskgeek.com/how-to/how-to-fix-filename-is-too-long-issue-in-windows/#:~:text=cannot%20guarantee%20that.-,Make%20Windows%2010%20Home%20Accept%20Long%20File%20Paths,-To%20make%20Windows](url)
