### ISSUE TITLE
[Issue] Wrong Pricing Strategy in Cost Estimate

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/azure-search-openai-demo#1911]
### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open Cost Estimate
> Look at GPT Model Pricing Strategy

The GPT pricing strategy is Standard (On Demand) not Provisioned Throughput (PTU)

@pamelafox can the person who created the cost estimate modify this in the shared link instead of creating a new estimate?

<img width="1273" alt="Screenshot 2024-08-16 at 1 46 14 AM" src="https://github.com/user-attachments/assets/86cb3fee-72ae-4103-b219-9755d81647d0">

**Comment by john0isaac** [comment]
fixing this issue brings down the total cost from **US$1,791.66** to **US$331.72**.

**Comment by pamelafox** [comment]
Whoah, wonder if it changed. Working on it, it's my link.
