### ISSUE TITLE
Error: KeyError 'sourcepage' after running the indexer (after initial indexing is complete)

### ISSUE THREAD

**Issue by gevans6** [Azure-Samples/azure-search-openai-demo#192]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the project locally using a storage account with a single PDF file. Everything works and I can search through the PDF file without issue. Adding a new PDF file to the storage account container and letting the indexer run (it is on a 5 minute timer), then the application breaks.

### Any log messages given by the failure
> KeyError: 'sourcepage'

### Expected/desired behavior
> The Azure Cognitive Services call should be able to use both documents that are in the storage account container.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lusk33** [comment]
Same problem here

**Comment by VitorRibeiroPrim** [comment]
Same problem here. Someone managed to solve it?

**Comment by lusk33** [comment]
> Same problem here. Someone managed to solve it?

I redeployed it from scratch and it worked. I believe the problem was the naming of the index of cognitive search.
The first time we tried deploying manually and that happend, try deploying it automatically.

**Comment by gevans6** [comment]
I found my issue was with my index. I had set up a separate indexer that connected to the created index that was on a timer. Since the correct metadata was not found on the document that I had inserted (because it wasn't set in the metadata in the blob), then I received this error. Using the prepdocs.sh script correctly and indexing it that way fixed this issue.
