### ISSUE TITLE
Switching to Layout Model

### ISSUE THREAD

**Issue by vlangloisx3** [Azure-Samples/azure-search-openai-demo#1922]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Upload a pdf with a table where one or more columns span across multiple lines. I've marked this as a bug also, since the GPT doesn't register some of the values inside a table with empty columns

### Any log messages given by the failure
> None

### Expected/desired behavior
> Read table cell as one item.

### OS and Version?
> Windows 11

### azd version?
> azd version 1.9.6

### Versions
> n/a

### Mention any other details that might be useful
Basically, is there any way to switch the Document Intelligence Model to Layout? Sorry if this is such a basic question, but I couldn't find anything on it in the docs or the issues here.

Right now, the GPT ignores any row that is separated by whitespace due to a merged cell or a cell that spans across two or more lines. I think because when the document is analyzed, the table is marked as closed when the next line encountered is blank (which happens when one column in the previous row spans two lines).

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This is where we call the Document Intelligence function to parse the document:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/prepdocslib/pdfparser.py#L54

We do actually use the layout model here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/8fe6429b49d1bd78f66e54913782e33c889e3490/app/backend/prepdocslib/pdfparser.py#L42

So it must be an issue with the layout model as well, or its an issue with our table parsing code. If you can provide an example document that doesn't have sensitive data which demonstrates the issue, we may be able to add it to our test suite. But if its an issue with Document Intelligence itself, there's probably not much we can do in this repo.
