### ISSUE TITLE
Stuck on the Python Developer welcome page, config problem

### ISSUE THREAD

**Issue by Codyerd** [Azure-Samples/azure-search-openai-demo#194]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I followed every step of the instruction and deployed the web app successfully. However, it seems that I can't interact with the application since the website from the endpoint URL is always stuck on the welcoming page like below.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/123194952/4f7a7984-0080-459e-9264-8ece8da437b5)

### Any log messages given by the failure
> The debugging console shows that "DevTools failed to load source map: Could not load content for https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE" I searched it up and it seems to be affected by the extensions in Chrome. But I switched to Edge and disabled all my extensions it still didn't work. 

### Expected/desired behavior
> I was hoping to see the frontend and interact with the chat bot in the endpoint website.

### OS and Version?
> Windows 10.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Lownex** [comment]
We've the same issue it terms of seeing the Python Startup Page. The application was working before but we had to stop the app in Azure and now it's not coming up again. Is there any startup command that we have to put in the the backend to be able to come up the app again?

**Comment by btindol** [comment]
anyone figure this out?

**Comment by pamelafox** [comment]
Going to close this issue since we haven't heard back. Please comment or open a new issue if you find an error in the logs that you need help deciphering. Thanks!
