### ISSUE TITLE
When Click Citation files, always encounter Internal Server Error?

### ISSUE THREAD

**Issue by TheoDoreW** [Azure-Samples/azure-search-openai-demo#20]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/26006532/225487480-d976286b-8740-44de-869c-d38f3f285cd2.png">

**Comment by pietheinstrengholt** [comment]
Same issue here. How did you solve this?

**Comment by legalgates** [comment]
same issue here. Any ideas on how to solve this?

**Comment by Ce0u1150** [comment]
Same for me, was working. loaded more files in and now not

**Comment by AshokAndani** [comment]
above Internal Server Error for citation resolved...?

**Comment by pamelafox** [comment]
Please check the logs for the web server and see if you can see a precise error. Please paste the error here.

**Comment by shulkx** [comment]
> Please check the logs for the web server and see if you can see a precise error. Please paste the error here.

Hi, here is my error log. The strange thing is that I can use the citation locally but cannot view it after deploy it. Any suggestions? Thanks.
```
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
```

**Comment by pamelafox** [comment]
Locally, the app uses your user credential, but when deployed, the app uses the app service's managed identity, so its certainly possible for a permission error to happen.

Here is the corresponding infrastructure from main.bicep that sets up the managed identity for acessing storage:

```
module storageRoleBackend 'core/security/role.bicep' = {
  scope: storageResourceGroup
  name: 'storage-role-backend'
  params: {
    principalId: backend.outputs.identityPrincipalId
    roleDefinitionId: '2a2b9908-6ea1-4ae2-8e65-a410df84e7d1'
    principalType: 'ServicePrincipal'
  }
}
```

Please double check that your app has that role assigned to it.

**Comment by shulkx** [comment]
> 

Hi Pamela,
Thanks for the reply.
If the blob storage and web app has already set up, how to set up the managed identity to access storage?
- Is it inside the `Access control (IAM)`? 
- I need to change the setting for blob storage or web app? 
- Which setting should I change?

**Comment by thwayant** [comment]
> > 
> 
> Hi Pamela, Thanks for the reply. About `Please double check that your app has that role assigned to it.`: If the blob storage and web app has already set up, how to set up the managed identity to access storage?
> 
>     * Is it inside the `Access control (IAM)`?
> 
>     * I need to change the setting for blob storage or web app?
> 
>     * Which setting should I change?
> 
> 
> Update: Figure it out by myself, no like the role assignment to user, after deploying online, it relays on the `Identify` of the web app (also the entry name). For more details, I make the changes based on following link: https://tech-tutes.com/2021/03/18/access-azure-blob-storage-using-azure-ad-managed-identity/

can please provide more details on what you did, i already have the identity added but it is still showing me the internal server error. Thanks.

**Comment by pamelafox** [comment]
If you are seeing an internal server error, please first check the App Service logs (see FAQ for how to do that) to see the exact error. Once you have the exact error, share that here or in a new issue if you need help understanding it.
