### ISSUE TITLE
Is it possible to use api/key for Azure OpenAI service rather than Entra ID?

### ISSUE THREAD

**Issue by amirj** [Azure-Samples/azure-search-openai-demo#2001]
I know that the app is using Entra ID authentication to access Azure OpenAI services. Is it possible to leverage legacy api/key instead? which part of the app should be adjusted?

**Comment by pamelafox** [comment]
Yes it is possible, run:

```
azd env set OPENAI_HOST azure_custom
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT gpt-35-turbo
azd env set AZURE_OPENAI_EMB_DEPLOYMENT text-embedding-ada-002
azd env set AZURE_OPENAI_API_KEY_OVERRIDE YOUR-KEY-HERE
azd env set AZURE_OPENAI_CUSTOM_URL https://YOUR-ENDPOINT-HERE/api/v1
```

You'll need to modify the values of the last two commands, then run "azd up".

Or you can manually change the code in app.py that sets up the AsyncAzureOpenAI client, but these parameters should work. I used it with keys for this workshop:
https://github.com/Azure-Samples/ai-app-templates-workshop/blob/main/rag-on-ai-search.md

**Comment by pamelafox** [comment]
It will still use Entra managed identity for everything else, however.
