### ISSUE TITLE
Error while azd up - Managing env variables "AZURE_TENANT_ID" and "AZURE_AUTH_TENANT_ID" 

### ISSUE THREAD

**Issue by gaborvar** [Azure-Samples/azure-search-openai-demo#2003]
### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Follow documentation https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md to set up authentication through env variables:

@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_SEARCH_SERVICE_SKU free
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_OPENAI_CHATGPT_MODEL gpt-4o
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION 2024-08-06
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set ENABLE_LANGUAGE_PICKER true
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_USE_AUTHENTICATION true
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_ENABLE_GLOBAL_DOCUMENT_ACCESS true
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd env set AZURE_AUTH_TENANT_ID *redacted*
@gaborvar ➜ /workspaces/azure-search-openai-demo (main) $ azd up

Rationale why I chose these settings: a fair level of security from outsiders but minimal configuration overhead within the organization.

### Any log messages given by the failure
>
  File "/workspaces/azure-search-openai-demo/./scripts/auth_init.py", line 172, in main
    auth_tenant = os.getenv("AZURE_AUTH_TENANT_ID", os.environ["AZURE_TENANT_ID"])
                                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'AZURE_TENANT_ID'

ERROR: error executing step command 'provision': failed running pre hooks: 'preprovision' hook failed with exit code: '1', Path: './scripts/auth_init.sh'. : exit code: 1


### Expected/desired behavior
> azd up completes without error if the user follows the documentation for authentication.

### OS and Version?
> Windows 11
Codespaces

### azd version?
> run `azd version` and copy paste here.
azd version 1.10.1 
(in codespaces)

### Versions
>

### Mention any other details that might be useful
The doc (Setting up Microsoft Entra applications / Automatic Setup) discusses AZURE_AUTH_TENANT_ID, however does not state that AZURE_TENANT_ID should also be present.
Consider either changing the code (/scripts/auth_init.py", line 172) to mitigate the absence of AZURE_TENANT_ID or instruct the user to set it.

**Comment by pamelafox** [comment]
Hm, when did you check out the code? I made changes last week, and now the code uses this line:

```
    auth_tenant = os.getenv("AZURE_AUTH_TENANT_ID", os.getenv("AZURE_TENANT_ID"))
```

So now it should be good. Let me know if you think otherwise.

**Comment by gaborvar** [comment]
Thanks for addressing this.
