### ISSUE TITLE
where to change prompts in azure

### ISSUE THREAD

**Issue by michelltang001** [Azure-Samples/azure-search-openai-demo#203]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> I changed the prmopts about the assistant role but it didnt shows on the endpoint after deployment. 
Can I change them in azure? where should I change it? 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by PTTrazavi** [comment]
For my case I changed the default prompts locally (ex: chatreadretrieveread.py), and execute "azd deploy" to deploy again, and it worked.

**Comment by aero-girl** [comment]
I've got the same question. If using Github codespaces or Remote Containers, then how you go about changing the default prompts in notebooks/chat-read-retrieve-read.ipynb.

Thanks

**Comment by michelltang001** [comment]
> For my case I changed the default prompts locally (ex: chatreadretrieveread.py), and execute "azd deploy" to deploy again, and it worked.

Thanks for your answer.
I opened the py file and chagned the prompt and run azd deploy as well, but when I open tje web app endpoint, the origianl prompt were still there. :(

**Comment by Tibap** [comment]
@michelltang001 Depending on the approach you choose, you have different prompts hard-coded in different python files. Chances are, you updated a prompt from an approach you don't use... Check the prompts in the following files:

- retrievethenread.py
- readretrieveread.py
- chatreadretrieveread.py

**Comment by pamelafox** [comment]
Yes, you should be able to change the prompt in the appropriate file, as @Tibap says. Closing this issue, please comment if you were unable to find the correct file.
