### ISSUE TITLE
Codespaces: Error: there is no registered task type 'dotenv'. Did you miss installing an extension that provides a corresponding task provider?

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure-Samples/azure-search-openai-demo#2033]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Start the Codespackes, check the Tasks log.

### Any log messages given by the failure
> Error: there is no registered task type 'dotenv'. Did you miss installing an extension that provides a corresponding task provider?

### Expected/desired behavior
> No error message.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Could you file an issue in the azd repo?
https://github.com/Azure/azure-dev
I don't know of what we could do on our side here, since that dotenv task comes from the azd VS Code extension.

**Comment by MiguelElGallo** [comment]
> Could you file an issue in the azd repo? https://github.com/Azure/azure-dev I don't know of what we could do on our side here, since that dotenv task comes from the azd VS Code extension.

Hello,
Now it is open: https://github.com/Azure/azure-dev/issues/4460
