### ISSUE TITLE
App Fails to Launch After Enabling Microsoft Entra Authentication via azd env

### ISSUE THREAD

**Issue by jeannot-prvlimburg** [Azure-Samples/azure-search-openai-demo#2047]
### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
azd env set AZURE_USE_AUTHENTICATION true
azd env set AZURE_AUTH_TENANT_ID <YOUR-TENANT-ID>
azd up

### Any log messages given by the failure
> The app deploys succesfully, but returns the following error:
:( Application Error
If you are the application administrator, you can access the diagnostic resources.

### Expected/desired behavior
> The app should open normally and require the user to login.

### OS and Version?
> Github Codespaces

### Mention any other details that might be useful
The issue appears to be triggered by the changes to the authentication environment variables (AZURE_USE_AUTHENTICATION and AZURE_AUTH_TENANT_ID). Running azd up without these changes works as expected

**Comment by jeannot-prvlimburg** [comment]
If you give it enough time, the issue will eventually resolve on its own, but it may take several hours before that happens.

**Comment by Cristian-turing** [comment]
Scale-app your app service to P0V3 or P1V3.
