### ISSUE TITLE
Request: Ability to import CSV files

### ISSUE THREAD

**Issue by gentawang** [Azure-Samples/azure-search-openai-demo#205]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>Importing sales data in csv format through script, prompting that the format is not supported, and then I import csv data through blob storage, can APP clearly can not retrieve the relevant content

### Expected/desired behavior
>I hope that with the introduction of the document, you can import SQL or other data, and the application will give results based on the sales data, not just import PDF files.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
cc @dmore123

prepdocs.py currently only handles PDF files, so one would need to write CSV handling there or use a CSV indexer in Azure Cognitive Search

**Comment by zhongshuai-cao** [comment]
In addition to handling the csv file, the following request may be how to render the source as the PDF. I guess that may involve office 365 services?

**Comment by pamelafox** [comment]
The repo includes a CSV parser now:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-10-02
