### ISSUE TITLE
detect language by browser

### ISSUE THREAD

**Issue by cforce** [Azure-Samples/azure-search-openai-demo#2057]
Instead of manually selecting language via ENABLE_LANGUAGE_PICKER, how wabout setting language based on browser language settings

// Get the browser's language setting
const userLanguage = navigator.language || navigator.userLanguage; // For older browsers

// Display the language
console.log("Browser language:", userLanguage);

**Comment by pamelafox** [comment]
Hm, I think we're already supporting that, via https://github.com/i18next/i18next-browser-languageDetector ?
I know I definitely can use localStorage to change languages, by changing the i18nNextLang.
I haven't tested using the browser to change languages yet though. Does that not work for you?

**Comment by cforce** [comment]
sry, my fault. Maybe it was assuming that the toggle ENABLE_LANGUAGE_PICKER implicates that it has to be set manual. So it shall  pick automatically even when ENABLE_LANGUAGE_PICKER=false, does it?

**Comment by pamelafox** [comment]
Yep, I just tested by changing my browser language to Spanish, deleting the localStorage key, and reloading. The UI is then in Spanish. 
So I think that we're good here, but feel free to send a PR for a doc rewording if something could be clearer.
