### ISSUE TITLE
submit question  button is disabled

### ISSUE THREAD

**Issue by cforce** [Azure-Samples/azure-search-openai-demo#2071]
The Submit question  button "mouse over  is disabled" -always . No matter  with or without text.
It still works with Return key to send a message
Using latest Chrome

**Comment by pamelafox** [comment]
I'm unable to replicate this, here's what I see in Edge:
![Screenshot 2024-10-25 at 4 02 41 PM](https://github.com/user-attachments/assets/bbd4fb98-a041-4795-8a6e-19f4a8565849)

Is this with user login enabled or other features?

**Comment by cforce** [comment]
AZURE_ENABLE_GLOBAL_DOCUMENT_ACCESS="true"
AZURE_ENABLE_UNAUTHENTICATED_ACCESS="false"
AZURE_ENFORCE_ACCESS_CONTROL="true"

**Comment by jeannotdamoiseaux** [comment]
This doesn't seem logical. @pamelafox, should I create a quick fix with a PR?

**Comment by pamelafox** [comment]
Yes please, thank you @jeannotdamoiseaux
