### ISSUE TITLE
conflicting openapi default api  versions

### ISSUE THREAD

**Issue by cforce** [Azure-Samples/azure-search-openai-demo#2090]
Shouldn't this be the same everywhere?

https://github.com/Azure-Samples/azure-search-openai-demo/blob/0946893fe904cab1e89de2a38c4421e38d508608/app/backend/prepdocslib/embeddings.py#L199

https://github.com/Azure-Samples/azure-search-openai-demo/blob/0946893fe904cab1e89de2a38c4421e38d508608/app/backend/app.py#L576

https://github.com/Azure-Samples/azure-search-openai-demo/blob/0946893fe904cab1e89de2a38c4421e38d508608/app/backend/approaches/approach.py#L258

And by the way. the most recent is 2024-08-06, isn't it? See #1484

Additionally, embedding.py and approach.py shall use $AZURE_OPENAI_API_VERSION env var

**Comment by pamelafox** [comment]
I'll send a PR to make embeddings and app more consistent.

approach.py is for the computer vision SDK, however, which is a different SDK than OpenAI, so it should not use the same env var.

The hope is that the Azure OpenAI class will eventually default to the latest GA version, as that's what happens in the .NET and JS SDK, but they haven't made that change yet, so we must keep updating ourselves.
