### ISSUE TITLE
Insufficient Quota || Can I reduce the required amount of tokens for the Azure OpenAI resource?

### ISSUE THREAD

**Issue by Citizen-XX** [Azure-Samples/azure-search-openai-demo#2091]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
azd auth login
azd up

Setting the .env variables:
AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION="turbo-2024-04-09"
AZURE_OPENAI_CHATGPT_MODEL="gpt-4"

### Any log messages given by the failure
Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '4ea75276-7e89-4c9e-9211-b99a8b737c43'. See inner errors for details.
InsufficientQuota: This operation require 30 new capacity in quota Tokens Per Minute (thousands) - GPT-4-Turbo, which is bigger than the current available capacity 8. The current quota usage is 0 and the quota limit is 8 for quota Tokens Per Minute (thousands) - GPT-4-Turbo.

TraceID: bb560b3c777dbc4c9a1dee23e0031bac

### Expected/desired behavior
> Successful creation of the Azure OpenAI resource.

### OS and Version?
> Windows 11 Pro

### azd version?
> azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)

### Versions
>{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "init": "0.1.0"
  }
}
Bicep CLI version 0.30.23 (ec3612efc7)
PowerShell 7.4.5

### Mention any other details that might be useful
I'd like to reduce the tokens per minute amount for any OPENAI_CHATGPT model that I try to deploy. I don't understand why I need at least 30k tokens every time I deploy a resource.
Also, the Free SKU for the gpt-35-turbo model is in full use and I'd like to know how to successfully change the sku to another one with these parameteres:
      "value": "${AZURE_OPENAI_CHATGPT_MODEL}"
    },
    "chatGptDeploymentName": {
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT}"
    },
    "chatGptDeploymentVersion":{
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION}"
    },
    "chatGptDeploymentSkuName":{
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT_SKU}"
    },
    "chatGptDeploymentCapacity":{
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY}"
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, you can set:

```
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY 8
```

The default is 30 as most folks have that capacity available. However, if you're a Microsoft employee, ours often default to 8 TPM.

**Comment by Citizen-XX** [comment]
> Yes, you can set:
> 
> ```
> azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY 8
> ```
> 
> The default is 30 as most folks have that capacity available. However, if you're a Microsoft employee, ours often default to 8 TPM.

Thank you so much, I'd been unsure as how to manage it. It seems to be working properly now.
Have a good one!
