### ISSUE TITLE
New pdf files do not get recognized as a provided source

### ISSUE THREAD

**Issue by Joran-Vergauwen** [Azure-Samples/azure-search-openai-demo#21]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Not sure if this belongs to the intended purpose of this demo, but this is what I tried to do:
> Upload a random pdf file to the storage account in the 'content' container
> Restart the Web App
> Ask a question about information provided in the uploaded pdf

### Output provided in the Web App
The newly uploaded pdf file doesn't seem to be in scope. 
![image](https://user-images.githubusercontent.com/56868447/225659596-6bf3f717-a17b-4b59-a02b-5ad80e321ab6.png)

### Expected/desired behavior
> The new pdf gets recognized and the questions about content in the pdf get answered. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by briansmi** [comment]
Did you use prepdocs.ps1 to upload the pdf to the storage account?  The documents need to be uploaded to both the Search index as well as the container and prepdocs.ps1 should handle that for you.
