### ISSUE TITLE
Issue running prepdocs.ps1 (Mac user)

### ISSUE THREAD

**Issue by sigglep** [Azure-Samples/azure-search-openai-demo#213]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> (On Mac)
> Init project and azd up
> run pwsh prepdocs.ps1

### Any log messages given by the failure
>

PS /Users/glende/Documents/Jobb/Ironstone/Repositories/azure-search-openai-test/scripts> pwsh prepdocs.ps1

Loading azd .env file from current environment

MethodInvocationException: /Users/glende/Documents/Jobb/Ironstone/Repositories/azure-search-openai-test/scripts/prepdocs.ps1:10:3
Line |
  10 |    [Environment]::SetEnvironmentVariable($name, $value)
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "SetEnvironmentVariable" with "2" argument(s): "The value cannot be an empty string. (Parameter 'variable')"
Environment variables set.
Creating python virtual environment "scripts/.venv"
Installing dependencies from "requirements.txt" into virtual environment
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './scripts/requirements.txt'
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
You should consider upgrading via the '/Users/glende/Documents/Jobb/Ironstone/Repositories/azure-search-openai-test/scripts/scripts/.venv/bin/python -m pip install --upgrade pip' command.
Running "prepdocs.py"
Documents/Jobb/Ironstone/Repositories/azure-search-openai-test/scripts/scripts/.venv/bin/python: can't open file '/Users/Documents/Jobb/Ironstone/Repositories/azure-search-openai-test/scripts/./scripts/prepdocs.py': [Errno 2] No such file or directory

### Expected/desired behavior
>
Actually run the prepdocs.ps1 correctly

### OS and Version?
> macOS (Ventura 13.0)

### azd version?
> azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zhongshuai-cao** [comment]
I am curious what is the benefit to run powershell script on Mac while POSIX shell script(.sh) is provided? I am using Mac and I run the .sh without any issue.
