### ISSUE TITLE
InvalidTemplateDeployment: The template deployment 'aca-web-update' is not valid according to the validation procedure.

### ISSUE THREAD

**Issue by WahbiBOUJEMAA** [Azure-Samples/azure-search-openai-demo#2139]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> when I execute azd up i have this error

### Any log messages given by the failure
>

ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'aca-web-update' is not valid according to the validation procedure. The tracking id is '8f1fab8c-f185-4a0d-9247-c7069df2cce2'. See inner errors for details.
ValidationForResourceFailed: Validation failed for a resource. Check 'Error.Details[0]' for more information.
ContainerAppInvalidRegistryServerValue: Property 'registries.server' has an invalid value 'TestdemoAiacrwf5dg3jvychc6.azurecr.io'. A value consist of hostname and custom port(if present). Hostname must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character. If there is a custom port, use ':' to concat the hostname and port. Port value should be in the range [1,65535].

TraceID: fe0321618af76196646b824323a126c8

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
azd version 1.10.4

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please try changing this line in main.bicep to include the lower function:

```
param containerRegistryName string = deploymentTarget == 'containerapps'
  ? '${lower(replace(environmentName, '-', ''))}acr'
  : ''
```

**Comment by WahbiBOUJEMAA** [comment]
It didn't work with this change


ERROR: error executing step command 'provision': initializing provisioning manager: failed to compile bicep template: failed running bicep build: exit code: 1, stdout: , stderr: D:\ProjectOpaliaAI\Opaidemo\infra\core\host\container-apps.bicep(11,7) : Warning no-unused-params: Parameter "applicationInsightsName" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
D:\ProjectOpaliaAI\Opaidemo\infra\core\storage\storage-account.bicep(62,23) : Warning use-safe-access: Use the safe access (.?) operator instead of checking object contents with the 'contains' function. [https://aka.ms/bicep/linter/use-safe-access]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(37,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep 
Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(41,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(68,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep 
Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(72,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(99,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep 
Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(140,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(181,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(239,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(301,15) : Warning BCP037: The property "isAdapter" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(302,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(306,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it 
to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(365,15) : Warning BCP037: The property "isAdapter" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(366,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(370,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it 
to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(456,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\core\monitor\applicationinsights-dashboard.bicep(460,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it 
to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(37,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(41,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(68,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(72,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(110,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(172,15) : Warning BCP037: The property "isAdapter" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(173,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(177,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(236,15) : Warning BCP037: The property "isAdapter" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(237,15) : Warning BCP037: The property "asset" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\backend-dashboard.bicep(241,15) : Warning BCP037: The property "defaultMenuItemId" is not allowed on objects of type "Extension/HubsExtension/PartType/MarkdownPart". Permissible properties include "settings". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
D:\ProjectOpaliaAI\Opaidemo\infra\main.bicep(237,8) : Error BCP057: The name "lower" does not exist in the current context.

**Comment by pamelafox** [comment]
Apologies, toLower() is the correct function for Bicep

**Comment by pamelafox** [comment]
Fix is in https://github.com/Azure-Samples/azure-search-openai-demo/pull/2182/files

**Comment by sanjay-shukla-2024** [comment]
I am still getting the same issue, even though it has following - 
param containerRegistryName string = deploymentTarget == 'containerapps'
  ? '${replace(toLower(environmentName), '-', '')}acr'
  : ''
