### ISSUE TITLE
Azure OpenAI resource creation failed - timeout

### ISSUE THREAD

**Issue by ndriyo** [Azure-Samples/azure-search-openai-demo#215]
Try to deploy the script using Github Codespace for a few times with no luck.
The script is stuck during creation/update Azure OpenAI for more than 1.5 hours.
The remaining resources has been created under 20 minutes.
Is this normal to create resources for more than 1.5 hours?

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run azd up

### Any log messages given by the failure
> N/A

### Expected/desired behavior
>

### OS and Version?
> Github CodeSpace

### azd version?
> 0.9.0-beta.2

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Enmming** [comment]
same issue here

**Comment by pamelafox** [comment]
I just experienced this as well, and times really improved when I tried a different location. Could you try a lesser used location like "francecentral"?

**Comment by bruno-trivellato** [comment]
Same here, using US East

**Comment by mathieumack** [comment]
Hi, same problem for me.
By using another region it works. Ex : francecentral.
So probably an issue with eastus region.

**Comment by smallangi** [comment]
Hi @pamelafox  I am able to create OpenAI service in francecentral from portal. But when I try to do that from this rep, it fails with this error  "{"code":"InvalidTemplateDeployment","message":"The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '39717c2e-4fe0-4d37-aefc-9ff0bea65064'. See inner errors for details.","details":[{"code":"DeploymentModelNotSupported","message":"The model Format: OpenAI, Name: text-davinci-003, Version: 1, Source:  is not supported in current region."}]}  .. Looks like some of the models leveraged by this solution are not available in that region

**Comment by ndriyo** [comment]
Success after switching to southcentralus location. It seems capacity problem on Azure, not on the deployment script.

Already try to swith to francecentral with no luck. Different error message
DeploymentModelNotSupported: The model Format: OpenAI, Name: text-davinci-003, Version: 1, Source:  is not supported in current region.
Which seems align with the readme.md saying that only support East US or South Central US.

**Comment by MahdiSheikhi** [comment]
Same problenm - US East - 2h timeout
