### ISSUE TITLE
Speech service authentication error (401)

### ISSUE THREAD

**Issue by amirj** [Azure-Samples/azure-search-openai-demo#2152]
I'm getting the following error once trying to use speech out service:

```
[2024-11-13 12:48:25 +0000] [64472] [INFO] 127.0.0.1:50920 POST /chat/stream 1.1 200 - 8681717
Error: Time:Wed Nov 13 12:48:31 2024 File:/Users/runner/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:on_underlying_io_bytes_received Line:1239 Bad status (401) received in WebSocket Upgrade response
Error: Time:Wed Nov 13 12:48:31 2024 File:/Users/runner/work/1/s/external/azure-c-shared-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_close_async Line:383 NULL on_io_close_complete
ERROR:app:Speech synthesis canceled: CancellationReason.Error WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name. USP state: Sending. Received audio size: 0 bytes.
ERROR:app:Exception in /speech
Traceback (most recent call last):
  File "/Users/aj896572/codes/Repo-PharmaDA-R-ViiV-GenAI-Violet/app/backend/app.py", line 331, in speech
    raise Exception("Speech synthesis canceled. Check logs for details.")
Exception: Speech synthesis canceled. Check logs for details.
Error: Time:Wed Nov 13 12:48:31 2024 File:/Users/runner/work/1/s/external/azure-c-shared-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_destroy Line:196 tlsio_appleios_destroy called while not in TLSIO_STATE_CLOSED.
```

I setup the required env variables  (AZURE_SPEECH_SERVICE_ID, AZURE_SPEECH_SERVICE_RESOURCE_GROUP and AZURE_SPEECH_SERVICE_LOCATION); is there anything else I have missed?

**Comment by pamelafox** [comment]
Did you set that up manually, or by using the azd up process? If you set it up manually, you'll need to replicate everything done by the Bicep, like the roles:


module speechRoleUser 'core/security/role.bicep' = {
  scope: speechResourceGroup
  name: 'speech-role-user'
  params: {
    principalId: principalId
    roleDefinitionId: 'f2dc8367-1007-4938-bd23-fe263f013447'
    principalType: principalType
  }
}


module speechRoleBackend 'core/security/role.bicep' = {
  scope: speechResourceGroup
  name: 'speech-role-backend'
  params: {
    principalId: (deploymentTarget == 'appservice')
      ? backend.outputs.identityPrincipalId
      : acaBackend.outputs.identityPrincipalId
    roleDefinitionId: 'f2dc8367-1007-4938-bd23-fe263f013447'
    principalType: 'ServicePrincipal'
  }
}

**Comment by pamelafox** [comment]
Closing this as I see from other issue that you set everything up in the Portal. You'll need to add the roles, as described above.
