### ISSUE TITLE
Environment name with upper case causes ACA deployment to fail

### ISSUE THREAD

**Issue by mkennten** [Azure-Samples/azure-search-openai-demo#2179]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Name the environment with a mix of upper and lower case, e.g. demoAOAIRAG
- deploy using azd up (and other basic instructions)
- Step "Container Apps Environment" will fail with the following:

### Any log messages given by the failure
> 
![image](https://github.com/user-attachments/assets/8465df64-151c-48ec-9461-b8de7fb99e86)

### Expected/desired behavior
> Either document and enforce naming conventions or adjust the variable containerRegistryName to contain only lower case.

### OS and Version?
> Windows 11

### azd version?
> azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)

### Versions
>

### Mention any other details that might be useful
I changed lines 247-249 in main.bicep as follows and this way it works (enforcing lower case for the ACR):
param containerRegistryName string = deploymentTarget == 'containerapps'
  ? toLower('${replace(environmentName, '-', '')}acr')
  : ''
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Fix is in https://github.com/Azure-Samples/azure-search-openai-demo/pull/2182/files
Thanks for filing!
