### ISSUE TITLE
start service failed

### ISSUE THREAD

**Issue by jokerjoey** [Azure-Samples/azure-search-openai-demo#22]
When I tried to run start.cmd to start up the service, I got below issue:
vite v4.1.1 building for production...
✓ 1250 modules transformed.
../backend/static/index.html                    0.49 kB
../backend/static/assets/github-fab00c2d.svg    0.96 kB
../backend/static/assets/index-184dcdbd.css     7.33 kB │ gzip:   2.17 kB
../backend/static/assets/index-41d57639.js    625.76 kB │ gzip: 204.86 kB │ map: 5,057.29 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

Starting backend

Failed to start backend

**Comment by chuwik** [comment]
There have been some recent changes to the start scripts (e.g. start.cmd is now deprecated in favor of start.ps1), could you please go again through the latest instructions? I'm assuming you're trying to run it locally, so it'd be [these ones](https://github.com/Azure-Samples/azure-search-openai-demo#running-locally).
