### ISSUE TITLE
Upload button is not appearing in the website

### ISSUE THREAD

**Issue by Meghna-kanthraj** [Azure-Samples/azure-search-openai-demo#2201]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
![image](https://github.com/user-attachments/assets/23c9ac61-7c0b-4032-b74f-c12d10aee96a)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jeannotdamoiseaux** [comment]
The upload button is an optional feature, as outlined in the [deploy_features.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md) document.

To enable it, you'll first need to [configure login and document-level access control](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md). After that, set the environment variable azd env set USE_USER_UPLOAD true to activate the feature.

**Comment by pamelafox** [comment]
That's right, thanks @jeannotdamoiseaux for sharing the links. Closing this issue.
