### ISSUE TITLE
Web app is running and waiting for content

### ISSUE THREAD

**Issue by dmore123** [Azure-Samples/azure-search-openai-demo#230]
I was able to deploy the app on my azure subscription. It deployed successfully a "App Service", "Form Recognizer", "Search Service", "App service plan" , and " Storage Account"

I can upload my data in the "Storage Account" and create an Indexers and Index. 

When I ran the app from the "App Service"  I get the following message 

_Your web app is running and waiting for your content
Your web app is live, but we don’t have your content yet. If you’ve already deployed, it could take up to 5 minutes for your content to show up, so come back soon._

But nothing happens. Any idea?

Thanks

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
azd version 0.8.0-beta.2

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Is this after running `azd up` or just `azd provision`? `azd up` should have also included the deployment step, after uploading all the data for the index, and should have shown the website URL at the end. You could check the deployment logs to see if something failed - I have tips on doing that here: https://blog.pamelafox.org/2023/01/tips-for-debugging-django-app.html

**Comment by dmore123** [comment]
Hi Pamela, Thank you

I tried to redeploy and get the following error 

Executing postprovision hook => .\scripts\prepdocs.ps1
'pwsh' is not recognized as an internal or external command,
operable program or batch file.

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: '.\scripts\prepdocs.ps1'. : exit status 1

Any suggestions on how to fix it? 

On the Azure side I got no error on the deployment. 

Thanks

**Comment by pamelafox** [comment]
What operating system are you using? The pwsh command is triggered to run on Windows machines, per the postprovision hook section in https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/azure.yaml

If you're on a Windows machine and pwsh does not work, then you'll need to fix up your Powershell installation.

**Comment by dmore123** [comment]
Hi - I am on Windows. 
I upaded the azd to 1.0.1 and powershell to 7.3.4. Then updated the PATH and executed azd up from after pwsh. 
I do not get any more errors but installation. 
But now the script is stuck. Is there a way to check what is exactly doing? 
Thanks

Executing postprovision hook => .\scripts\prepdocs.ps1

Loading azd .env file from current environment

**Comment by dmore123** [comment]
Thank you. I fixed the Powershell PATH as you suggested.

I got a successful deployment:

Deploying services (azd deploy)

  (✓) Done: Deploying service backend
  - Endpoint: https://app-backend-p6vm57r657yt4.azurewebsites.net/

SUCCESS: Your application was provisioned and deployed to Azure in 38 minutes 40 seconds.

However, when I click on the link I get a "404 Not Found" page

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.


Thank you

**Comment by pamelafox** [comment]
Hm, that's interesting. What should have happened is that App Service auto-recognized the app as a Flask app (based off requirements.txt) and used gunicorn to run the app inside app.py.  

Then the / route should have been handled by this in app.py:

```
@app.route("/", defaults={"path": "index.html"})
@app.route("/<path:path>")
def static_file(path):
    return app.send_static_file(path)
```

Considering that didn't happen, I wonder if the index.html file was not built. The building should have happened at the beginning of the `azd up` process, and the files should be in backend/static. Look for an index.html file there.

Other things you could do:

* Check deployment (Oryx) logs to make sure it successfully realized it was a Flask app.
* Using the Advanced Tools, SSH into the server and see what the files look like.

**Comment by dmore123** [comment]
I redeployed - success !  Thank you!

**Comment by pamelafox** [comment]
Woot! Seems safe to close this issue now, in that case.

**Comment by blackboxdelta** [comment]
I am having the exact same issue! tried azd up- No luck. Is there a easier fix?

**Comment by pamelafox** [comment]
If you do not yet see the website content, please go through the debugging steps in http://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html 

* Confirm the deployment was successful
* Assuming it was, download the logs from Advanced Tools and look for issues in default_docker.txt

**Comment by mohapatras** [comment]
> Hm, that's interesting. What should have happened is that App Service auto-recognized the app as a Flask app (based off requirements.txt) and used gunicorn to run the app inside app.py.
> 
> Then the / route should have been handled by this in app.py:
> 
> ```
> @app.route("/", defaults={"path": "index.html"})
> @app.route("/<path:path>")
> def static_file(path):
>     return app.send_static_file(path)
> ```
> 
> Considering that didn't happen, I wonder if the index.html file was not built. The building should have happened at the beginning of the `azd up` process, and the files should be in backend/static. Look for an index.html file there.
> 
> Other things you could do:
> 
> * Check deployment (Oryx) logs to make sure it successfully realized it was a Flask app.
> * Using the Advanced Tools, SSH into the server and see what the files look like.

Is the routing needed changing the backend route codes also ?
