### ISSUE TITLE
Error line 35  , 39  on start process prepdocs.ps1 using windows 11 

### ISSUE THREAD

**Issue by nitedan** [Azure-Samples/azure-search-openai-demo#233]
> Please provide us with the following information:
Error line 35  , 39  on start process prepdocs.ps1 using windows 11 

Os: windows 11
folder details :  C:\gpt
Azure details : West Europe 

Prerequisites
all install last version

[Azure Developer CLI]
[Python 3+]  folder C:\Python311
Node.js
Git
Powershell 7+ (pwsh) 

follow steps

Project Initialization
Create a new folder  c:\gpt  and switch to it in the terminal
Run azd auth login
Run azd init -t azure-search-openai-demo

Starting from scratch:
azd up

Error line 35  , 39  on start process prepdocs.ps1 using windows 11 

  Start-Process: C:\gpt\scripts\prepdocs.ps1:35
Line |
  35 |  Start-Process -FilePath $venvPythonPath -ArgumentList "-m pip install …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.
Running "prepdocs.py"
Start-Process: C:\gpt\scripts\prepdocs.ps1:39
Line |
  39 |  Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prep …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nitedan** [comment]
I check also pip  in specific folder and is ok 

C:\gpt\scripts\.venv\Scripts>pip help

Usage:
  pip <command> [options]

C:\gpt\scripts>pip help

Usage:
  pip <command> [options]

 C:\gpt\scripts\.venv\Scripts>pip --version
pip 22.3.1 from C:\gpt\scripts\.venv\Lib\site-packages\pip (python 3.11)

**Comment by nitedan** [comment]
I replicate everything in a win10 os and was ok .

**Comment by TheRichCarey** [comment]
I am also encountering this on W11 machine. Your ticket suggests your W10 machine was fine? What was the difference other than OS, as if its OS specific and not a library version this ticket should be re-opened.
