### ISSUE TITLE
How to integrate the repo to Azure Devops 

### ISSUE THREAD

**Issue by gpnikhil** [Azure-Samples/azure-search-openai-demo#236]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Do you mean Azure DevOps pipelines? If so, this PR has some examples: https://github.com/Azure-Samples/azure-search-openai-demo/pull/329/files
