### ISSUE TITLE
how do we lock down the demo to only users within my company azure domain?

### ISSUE THREAD

**Issue by JTYEG** [Azure-Samples/azure-search-openai-demo#237]
> Please provide us with the following information:
> What steps would we need to do to only authenticate to our Azure AD users?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by anderl80** [comment]
You could use Azure "Easy Auth" https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization. The easiest way what you can do in the Azure Portal is to resrtrict access within the same tenant. If it's ok, that the weg page is shared within the whole tenant, than it's straigt forward. If you want to fine-grain the restricitions, you should do security groups and / or build the login into the application logic.

**Comment by pamelafox** [comment]
This repo now has authentication as an optional feature, so this issue is resolved.
