### ISSUE TITLE
WICH RECOMENDATION TO FORMATTING?

### ISSUE THREAD

**Issue by phfontes** [Azure-Samples/azure-search-openai-demo#246]
Hello everyone,
I implementing the aplication, but i have some questions.
how should the documents be written?
Can't have topics? images?
How should they be so that gpt can get better results?

**Comment by itmilos** [comment]
Good question, you can do any time of document including videos with MS CS, I recommend going over AI-900 certificate first ref. https://learn.microsoft.com/en-us/certifications/azure-ai-fundamentals/
