### ISSUE TITLE
Error with 'CosmosDB' data

### ISSUE THREAD

**Issue by asathuluri** [Azure-Samples/azure-search-openai-demo#251]
I am trying to update this sample application to work with CosmosDB data. 

- [x ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce

- > added a new index 'Ind1' (with Cognitive skills) for a CosmosDB by using 'Import Data' tab of gptkb-xxx search service that got created by the azure-search-openai-demo
- added 'Semantic configuration' with name 'default'
- Updated webapp - 'App backend' configuration properties 'AZURE_SEARCH_INDEX' with the new index created. And restarted the app
- Reloaded the app-backend URL and tried the 'Chat' and 'Ask a question' feature.

### Any log messages given by the failure
>'Error: sourcepage' is thrown on the Chat window, textbox.

### Expected/desired behavior
> Serve the data from the new index created. 

### OS and Version?
> N/A. I am on window11 but using github codespace. 

### azd version?
> run `azd version` and copy paste here.
azd version 1.0.1

> Thanks! We'll be in touch soon.

**Comment by itmilos** [comment]
Well for index creation you have to follow setup prepdocs secificly sections 

            "id": re.sub("[^0-9a-zA-Z_-]","_",f"{filename}-{i}"),
            "content": section,
            "category": args.category,
            "sourcepage": blob_name_from_file_page(filename, pagenum),
            "sourcefile": filename

**Comment by asathuluri** [comment]
I was pointing the search index to a different data source. demo code was looking for a 'content' field whereas initially my data that is being indexed did not have it. That caused the issue. I was able to fix the issue.

**Comment by asathuluri** [comment]
I am able to resolve the issue (as a temporary workaround) by having a content field in the data that is being indexed. There are other ways to resolving the issue by updating the code to your use case.
