### ISSUE TITLE
Error Running App Locally

### ISSUE THREAD

**Issue by Henson87** [Azure-Samples/azure-search-openai-demo#26]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When starting the app locally via the start.cmd in the app folder, the website does start up but its just a blank white page with. The error message is in the console window. 

### Any log messages given by the failure
>Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
       
Followed By 
       
 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at window.onload (app.js:59:731)

![image](https://user-images.githubusercontent.com/70236759/225981719-d0c85df4-e479-4de1-af8e-8d9e5f164ba8.png)

### Expected/desired behavior
>The start.cmd should fire the website up without issue. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>Windows 10

### Mention any other details that might be useful
Using VS Code
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Henson87** [comment]
So apparently this app is running a python server using the Flask framework. On windows machines Flask looks at the registry to get its mime type for javascript files. Windows by default in the registry treats javascript as text/plain. So to fix this issue just drop in this code in the app.py file 

# fix windows registry stuff
import mimetypes
mimetypes.add_type('application/javascript', '.js')
mimetypes.add_type('text/css', '.css')

**Comment by sshimii** [comment]
I added :
mimetypes.add_type('application/javascript', '.js')
mimetypes.add_type('text/css', '.css')

but still return the question
![image](https://user-images.githubusercontent.com/41730403/233572668-a8f82c02-3226-4d15-a2e5-1fad56ca9a54.png)
