### ISSUE TITLE
unable to deploy openai

### ISSUE THREAD

**Issue by Haroon921** [Azure-Samples/azure-search-openai-demo#269]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I used the terminal to deploy it and I am getting an error for openai. Please see the screenshot below
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/59919959/667a2285-6262-440b-9ebc-3cdaf8565708)

### Any log messages given by the failure
>
{"code":"InvalidTemplateDeployment","message":"The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '3cbbe259-cdeb-44c2-bb04-4c586e18f20b'. See inner errors for details.","details":[{"code":"ApiSetDisabledForCreation","message":"It's not allowed to create new accounts with type 'OpenAI'."}]}
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### azd version?
> run `azd version` and copy paste here.
azd version 1.0.1
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jagdish-kumawat** [comment]
Even I am getting same error. It used to get deployed 10 days back, now it is not working.
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '41c93811-***'. See inner errors for details.
ApiSetDisabledForCreation: It's not allowed to create new accounts with type 'OpenAI'.

**Comment by ArunEPRO** [comment]
This could be because of not having access to Open AI in the subscription.

Please request access via https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7en2Ais5pxKtso_Pz4b1_xUOFA5Qk1UWDRBMjg0WFhPMkIzTzhKQ1dWNyQlQCN0PWcu

If you have access and still facing this, then am not sure - I have not faced such issue.

**Comment by jagdish-kumawat** [comment]
I have access in the subscription. I am able to create manually. Even this solution was running 10 days back, now it has stopped working.

**Comment by dishujindal** [comment]
I am alsp seeing same issue. It worked for me in the past

**Comment by robvet** [comment]
jagish... Thanks a Mil for the suggestion of moving off South Central!

**Comment by TroyHostetter** [comment]
@pamelafox I am getting this on East US as well. Should we continue to retry with this region until it succeeds?

**Comment by pamelafox** [comment]
I was able to successfully provision in East US, so if you are seeing an issue, that may be a permissions error in your account. Is your account enabled for OpenAI? Can you make a deployment in the OpenAI studio for EastUS?
