### ISSUE TITLE
Show how to handle information protection (Document-level access control)

### ISSUE THREAD

**Issue by MazenSiraj** [Azure-Samples/azure-search-openai-demo#274]
Can someone please explain how to handle information protection to preform permissions on documents ?

**Comment by itmilos** [comment]
@MazenSiraj so you want each user to have specific access to specific file ?

**Comment by MazenSiraj** [comment]
Yes. I need let's say for me as Mazen, when I search on some data related to me, like my employment contract info, my salary, or related projects, it appears for me only. At the same time, I need when you, as another user, ask on some private data related to me, it says "I don't know."

I tried to implement permissions on the resource group on Azure Portal, but it showed an Unauthorized error at the response even if just said Hi.

**Comment by EnduroRacer18** [comment]
I'm looking for something similar. I just want to lock it down so only employees can access. I'm very new to Azure Apps.

**Comment by iMicknl** [comment]
This is not supported by this accelerator at the moment. Have a look at the following documentation of Azure Cognitive Search (the underlying solution to ground the prompt with the relevant documents).

https://learn.microsoft.com/en-us/azure/search/search-security-trimming-for-azure-search
https://learn.microsoft.com/en-us/azure/search/search-security-trimming-for-azure-search-with-aad

**Comment by itmilos** [comment]
> @itmilos Yes. I need let's say for me as Mazen, when I search on some data related to me, like my employment contract info, my salary, or related projects, it appears for me only. At the same time, I need when you, as another user, ask on some private data related to me, it says "I don't know."
> 
> I tried to implement permissions on the resource group on Azure Portal, but it showed an Unauthorized error at the response even if just said Hi.

I think you could do this with https://github.com/microsoft/semantic-kernel I would suggest to propose this as feature there.

**Comment by pamelafox** [comment]
Closing this issue since Matt linked to the doc about the access control feature, and there have been no follow-up questions.
