### ISSUE TITLE
SemanticSettings Issue

### ISSUE THREAD

**Issue by erose-nerdio** [Azure-Samples/azure-search-openai-demo#282]
I am trying to update the data in my local clone with the prepdocs.py script. However, when I try to run it with appropriate flags, I get an exception that says the SemanticSettings class does not exist. The class is not found in the azure.search.documents.indexes.models module. However, there is nothing on the internet to imply the class is deprecated, and there is documentation to suggest the class should be in the module: [azure.search.documents.indexes.models.SemanticSettings class | Microsoft Learn](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.semanticsettings?view=azure-python-preview%22https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.semanticsettings?view=azure-python-preview%22).

Am I missing something here?

**Comment by pamelafox** [comment]
That class should be brought in from this line:

```
from azure.search.documents.indexes.models import *
```

That does work for me, but if you wanted to be very explicit, you can import each class separately, like so:

```
from azure.search.documents.indexes.models import (
    SearchIndexerDataContainer,
    SearchIndexerDataSourceConnection,
    SearchIndex,
    SearchIndexer,
    SimpleField,
    SearchableField,
    SemanticSettings,
    SemanticConfiguration,
    PrioritizedFields,
    SearchFieldDataType
)
```

I'm surprised the import * isn't working though, please check your imports and let us know what you discover.

**Comment by pamelafox** [comment]
Closing, assuming resolved.
