### ISSUE TITLE
Add more docs to index

### ISSUE THREAD

**Issue by starlee822** [Azure-Samples/azure-search-openai-demo#286]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Hello, How can I add more docs (pdf) to index after deploy this project to Azure?

**Comment by pamelafox** [comment]
Add the docs to the data folder and then run either prepdocs.ps1 (Windows) or prepdocs.sh (Mac/Linux).

**Comment by Nonis1** [comment]
Hello! After completing the steps to add the documents and running prepdocs.ps1, I am experiencing an issue where the documents are not searchable through the index and the application. I would like to know what the next step should be to query my new PDF documents effectively. Could you please provide guidance on this matter?

**Comment by breannay03** [comment]
Is the only format accepted pdfs? Is it possible to add files in the markdown format?

**Comment by starlee822** [comment]
> Add the docs to the data folder and then run either prepdocs.ps1 (Windows) or prepdocs.sh (Mac/Linux).

Thanks pamelafox, works as expected.
