### ISSUE TITLE
 InvalidTemplateDeployment Error for 'openai' - QuotaId/Feature Required for SKU 'SO'

### ISSUE THREAD

**Issue by mergisi** [Azure-Samples/azure-search-openai-demo#288]
During a recent deployment attempt, we encountered an InvalidTemplateDeployment error. Attached relevant error logs or screenshots.

![Xnip2023-06-08_10-32-08](https://github.com/Azure-Samples/azure-search-openai-demo/assets/6433678/bfcef51a-ec42-4677-ad21-bbf03ed9f4b9)

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by epreisz** [comment]
Looks like the issue was my region. I switched from US EAST 2 to US EAST (which is what I signed  up for when I submitted the OpenAI form) and it was able to deploy the build.

**Comment by mergisi** [comment]
I changed the region settings differently this time and it worked! Thanks.
