### ISSUE TITLE
Principal does not have access to API/Operation

### ISSUE THREAD

**Issue by TimoRiikonen** [Azure-Samples/azure-search-openai-demo#290]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Another person has created the site. My task is to just upload content and to rebuild index.
> azd auth login
> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
> .../scripts/prepdocs.ps1
> I get same result even if I set AZURE_PRINCIPAL_ID="Object id of MY user account"
> I get same result even if I set AZURE_PRINCIPAL_ID="Object id of the environment creator user account"

### Any log messages given by the failure
> Search index gptkbindex already exists
> Processing files...
> Processing 'C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo/data\5616-05en.pdf'
>         Uploading blob for page 0 -> 5616-05en-0.pdf
> Extracting text from 'C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo/data\5616-05en.pdf' using Azure Form Recognizer
> Traceback (most recent call last):
>   File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\prepdocs.py", line 313, in <module>
>    page_map = get_document_text(filename)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\prepdocs.py", line 129, in get_document_text
>    poller = form_recognizer_client.begin_analyze_document("prebuilt-layout", document = f)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
>    return func(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\ai\formrecognizer\_document_analysis_client.py", line 126, in begin_analyze_document
>    return self._client.begin_analyze_document(  # type: ignore
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\ai\formrecognizer\_generated\_operations_mixin.py", line 170, in begin_analyze_document
>    return mixin_instance.begin_analyze_document(model_id, pages, locale, string_index_type, analyze_request, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
>    return func(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\ai\formrecognizer\_generated\v2022_08_31\operations\_form_recognizer_client_operations.py", line 576, in begin_analyze_document
>    raw_result = self._analyze_document_initial(  # type: ignore
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\ai\formrecognizer\_generated\v2022_08_31\operations\_form_recognizer_client_operations.py", line 507, in _analyze_document_initial
>    map_error(status_code=response.status_code, response=response, error_map=error_map)
>  File "C:\Users\timo.riikonen\Documents\Git\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\core\exceptions.py", line 109, in map_error
>    raise error
> azure.core.exceptions.ClientAuthenticationError: (PermissionDenied) Principal does not have access to API/Operation.
> Code: PermissionDenied
> Message: Principal does not have access to API/Operation.

### Expected/desired behavior
> Text extraction succeeds

### OS and Version?
> Windows 11

### azd version?
> 1.0.1

### Versions
> 2023-06-08

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TimoRiikonen** [comment]
Failing command is openai.Completion.create

**Comment by TimoRiikonenIF** [comment]
After running roles.sh to my account it looks like I got to the next line and to the next error.

**Comment by TimoRiikonenIF** [comment]
After running roles.sh and setting the principal id I don't get this error any more.

**Comment by zahava-ro** [comment]
> After running roles.sh and setting the principal id I don't get this error any more.

Where you do get the principal id?

**Comment by TimoRiikonenIF** [comment]
It is user's object I'd

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pamelafox** [comment]
If anyone else is experiencing this issue, please check the "identity" tab of your deployed app, and make sure it shows the correct role assignments for OpenAI.

Here's what it looks like for a functioning app:

<img width="914" alt="Screenshot of Identity tab" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/c651f122-12e1-4481-a4db-2499f1a03f7d">

<img width="1486" alt="Screenshot of role assignments" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/3522f59b-0594-4eee-9418-d47ac19188c9">

Closing this issue as I don't believe there's an issue with the repo.

**Comment by developer992** [comment]
how do i do this? 

> I had to assign an AAD Group to the Cognitive Services OpenAI User Role in the Azure OpenAI resource itself.

**Comment by developer992** [comment]
running roles.ps1 just does this:

 .\scripts\roles.ps1
Environment variables set.
argument --assignee-object-id: expected one argument

WHAT OBJECT ID IS EXPECTING ?

**Comment by coxymla** [comment]
> I had to assign an AAD Group to the `Cognitive Services OpenAI User` Role in the Azure OpenAI resource itself.

I tried this but it didn't work for me. I had to assign the role `Cognitive Services OpenAI Contributor` rather than _User_.
