### ISSUE TITLE
Need more information on how to create Azure Search used in the demo

### ISSUE THREAD

**Issue by mukdenchild** [Azure-Samples/azure-search-openai-demo#292]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Can someone share the json files or postman collections for creating Azure Search with the pdf files used in the demo (index, skillset, and indexer) ?

**Comment by pamelafox** [comment]
The document files are all in the data/ folder. The code that creates the index is in scripts/prepdocs.py and uses the Azure Python SDK to create the index. It does not create a skillset/indexer, it manually adds each document to the index.

**Comment by mukdenchild** [comment]
@pamelafox Thank you for the clarification!
