### ISSUE TITLE
Error in response: "SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON"

### ISSUE THREAD

**Issue by asocorro** [Azure-Samples/azure-search-openai-demo#302]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I rebuilt the index with only one pdf, a corporate annual report:
https://www.keyence.co.jp/pdf/AnnualReport2022.pdf
In Azure, I see the document was split into about 40 "chunks".  I can also successfully query the index in Cognitive Search.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
1.0.1
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Okay great, sorry for the delay in following up, I'll close this now.
