### ISSUE TITLE
handling csv files

### ISSUE THREAD

**Issue by MazenSiraj** [Azure-Samples/azure-search-openai-demo#305]
did anyone used the rrr model in the ask a question mode to deal with csv file?
if yes I am facing an issue that the code is passing a fixed value and am not so sure who to make it dynamic based on the input prompt 
as well as it needs a key field to retrieve data and I need it to be able to go through the whole csv file/s

**Comment by Waro0N** [comment]
You could use the langchain create_pandas_dataframe_agent or csv agent to talk to your CSV data.

**Comment by AmyHei** [comment]
does the csv file or structured data issue fix? I also need to read and retrival my table and answer questions like "what's the best region with the highest sale quaitity? " and give me results support table.

**Comment by pamelafox** [comment]
One approach is to call a service that can generate pandas code to answer questions like that, and run the analysis code in a sandboxed Python environment. That's now possible with dynamic sessions on Azure Container Apps. See this example from @anthonychu's Pycon talk:
https://github.com/anthonychu/20240528-sessions-csv/blob/main/query-csv.ipynb

**Comment by pamelafox** [comment]
The repo includes a CSV parser now:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-10-02
I'll close this issue as there are others specifically about analytics/charts.
