### ISSUE TITLE
How can I import .csv files in addition to pdf?

### ISSUE THREAD

**Issue by dmore123** [Azure-Samples/azure-search-openai-demo#315]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> I would like to import cvs files and not only pdf. I tried with the current settings but it fails. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I discovered two more CSV issues:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/305

https://github.com/Azure-Samples/azure-search-openai-demo/issues/205

Given similarity to 205, let's close this in favor of the earlier one, 205. It looks like 305 may be slightly different.
