### ISSUE TITLE
Links are to single PDF pages

### ISSUE THREAD

**Issue by TimoRiikonenIF** [Azure-Samples/azure-search-openai-demo#327]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Upload large PDF file and search for its content. Press the attached document link.

### Any log messages given by the failure
>

### Expected/desired behavior
> The link would be done to the full PDF and not on single pages of it.

### OS and Version?
> Windows 11

### azd version?
> 1.0.2

### Versions
> June 7, 2023

### Mention any other details that might be useful
Implementation options:
- Enlarge the PDF size threshold so that almost all PDF files could be uploaded without breaking them apart into single pages.
- In addition to importing single pages up, upload the full document and make links point to this document instead.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This was fixed, links go to pages using #1259  browser functionality. There is a regression with that when using integrated vectorization but that's tracked in another issue. Closing!
