### ISSUE TITLE
azd up produce errors

### ISSUE THREAD

**Issue by fbanespo1** [Azure-Samples/azure-search-openai-demo#340]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] documentation issue or request

### Any log messages given by the failure
>ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'd152c8f2-a7c5-4bf4-9147-5d67cff468d3'. See inner errors for details.
ApiSetDisabledForCreation: It's not allowed to create new accounts with type 'OpenAI'

### Expected/desired behavior
>Deployment complete

### OS and Version?
> Windows 11 and Ventura
### azd version?
> run `azd version` and copy paste here.
 azd version
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)
### Versions
>

### Mention any other details that might be useful
after azd up 4 resource and the rg are created but after 5 minutes I am getting the error above

**Comment by tonybaloney** [comment]
> "It's not allowed to create new accounts with type 'OpenAI'" 

This means your subscription does not have Azure OpenAI activated.
Please see the README for instructions on how to register for Azure Open AI access to your subscription and make sure you select US East or West Europe as the region

**Comment by fbanespo1** [comment]
Yes Openai is activated in fact we can create manually.

**Comment by tonybaloney** [comment]
Please try again with US East as the region and if it fails, go to the resource group in the portal and then navigate to "deployments" you'll see the specific error message there.

**Comment by rockstar-0000** [comment]
Hi, I got the same error and the message is as below:

{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'd70178f0-f659-49c3-9035-b50a1ea9fd2e'. See inner errors for details.",
        "details": [
            {
                "code": "ApiSetDisabledForCreation",
                "message": "It's not allowed to create new accounts with type 'OpenAI'."
            }
        ]
    }
}

**Comment by rockstar-0000** [comment]
I did create openai service manually on Azure and then set the azd env as described on the README. And then I tried to run and deploy again, and it worked now. Thanks for your guidance. @tonybaloney
