### ISSUE TITLE
Azure search openai demo - Issue with File Path

### ISSUE THREAD

**Issue by mmuthye** [Azure-Samples/azure-search-openai-demo#358]
Same issue with me. Role assignments are correct. I found that the indexes are not getting created, and while azd up, failing on few steps with below errors -
Start-Process: C:\Users\QTAdmin\Documents\WebCode\QutieBot\scripts\prepdocs.ps1:26
Line |
  26 |  Start-Process -FilePath ($pythonCmd).Source -ArgumentList "-m venv ./ …
     |                          ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not
     | null or empty, and then try the command again.
Installing dependencies from "requirements.txt" into virtual environment
Start-Process: C:\Users\QTAdmin\Documents\WebCode\QutieBot\scripts\prepdocs.ps1:35
Line |
  35 |  Start-Process -FilePath $venvPythonPath -ArgumentList "-m pip install …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.
Running "prepdocs.py"
Start-Process: C:\Users\QTAdmin\Documents\WebCode\QutieBot\scripts\prepdocs.ps1:39
Line |
  39 |  Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prep …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

Thoughts?

_Originally posted by @mmuthye in https://github.com/Azure-Samples/azure-search-openai-demo/issues/79#issuecomment-1600736257_

**Comment by FreddyStraub** [comment]
Got the same problem:

Environment variables set.
Creating python virtual environment "scripts/.venv"
Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:26:25
Line |
  26 |  Start-Process -FilePath ($pythonCmd).Source -ArgumentList "-m venv ./ …
     |                          ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and  
     | then try the command again.
Installing dependencies from "requirements.txt" into virtual environment
Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:35:1
Line |
  35 |  Start-Process -FilePath $venvPythonPath -ArgumentList "-m pip install …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: Das System kann die angegebene Datei nicht finden.
Running "prepdocs.py"
Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:39:1
Line |
  39 |  Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prep …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: Das System kann die angegebene Datei nicht finden.

**Comment by mmuthye** [comment]
> Got the same problem:
> 
> Environment variables set. Creating python virtual environment "scripts/.venv" Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:26:25 Line | 26 | Start-Process -FilePath ($pythonCmd).Source -ArgumentList "-m venv ./ … | ~~~~~~~~~~~~~~~~~~~ | Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and | then try the command again. Installing dependencies from "requirements.txt" into virtual environment Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:35:1 Line | 35 | Start-Process -FilePath $venvPythonPath -ArgumentList "-m pip install … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | This command cannot be run due to the error: Das System kann die angegebene Datei nicht finden. Running "prepdocs.py" Start-Process: C:\Development\Repos\t4p-genaishowcase-demo\scripts\prepdocs.ps1:39:1 Line | 39 | Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prep … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | This command cannot be run due to the error: Das System kann die angegebene Datei nicht finden.


Found the solution - This code is not detecting Python on the machine. So, install python if it is not there. Else set the python location into the PATH environment variable, and you are all set.

**Comment by mmuthye** [comment]
Found the solution - This code is not detecting Python on the machine. So, install python if it is not there. Else set the python location into the PATH environment variable, and you are all set.
