### ISSUE TITLE
deployment with error "MissingApiVersionParameter"

### ISSUE THREAD

**Issue by wuimin** [Azure-Samples/azure-search-openai-demo#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
when I init my environment and set the related environment variables as requested, and run azd up, got the error:

"error": {
    "code": "AuthorizationFailed",
    "message": "The client 'weihong.gu@beigene.com' with object id 'f47a3dc3-8b3e-4578-8e38-14135e261148' does not have authorization to perform action 'Microsoft.Resources/deployments/write' over scope '/subscriptions/ddc66e55-305a-4e39-95b5-898b4da795d3/providers/Microsoft.Resources/deployments/apac-demo' or the scope is invalid. If access was recently granted, please refresh your credentials."

when I open the url it showd, and found the folling information:
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

### Any log messages given by the failure
>
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

any account privilege requested? I'm the owner of resource group, if it's not enough, what permission I need set?
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vhvb1989** [comment]
> any account privilege requested? I'm the owner of resource group, if it's not enough, what permission I need set?

You need to be at least `Contributor` for the Azure Subscription.  This is because the initial deployment is at subscription level for resource groups.
