### ISSUE TITLE
Adding files to /data then running "prepdocs.ps1 issue

### ISSUE THREAD

**Issue by smitzlroy** [Azure-Samples/azure-search-openai-demo#367]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> add docs (.pdf) to /data then run prepdocs/ps1 from the project

### Any log messages given by the failure
>
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11997825/3f9e3aaf-4c96-40d7-985c-4ee5b42dcf14)

### Expected/desired behavior
> for the venv data to process inside the same directory

###Mention any other details that might be useful
I could resolve this by manually copying the contents of the project folder into the newly created "scripts" directory, including requirements.txt

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11997825/5d129e21-758d-4e82-94d8-7fa67ccc5d91)

**Comment by FreddyStraub** [comment]
If cd into AzOpenId and call the file from ./scripts/prepdocs.ps1 it should work.
