### ISSUE TITLE
bicep

### ISSUE THREAD

**Issue by amitlals** [Azure-Samples/azure-search-openai-demo#377]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> built on docker, steps followed and reciecving below error

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  (x) Failed: Downloading Bicep

ERROR: initializing provisioning manager: initializing infrastructure provider: failed resolving IaC provider 'bicep': downloading bicep: stream error: stream ID 1; INTERNAL_ERROR; received from peer
vscode ➜ /workspaces/azure-search-openai-demo (main) $ 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That looks like a network issue downloading the bicep extension, can you try again? I'll close this issue on the assumption that it was a transient issue, but please re-open if you experience it consistently.
