### ISSUE TITLE
Indexing SharePoint document libraries

### ISSUE THREAD

**Issue by TrowersWeb** [Azure-Samples/azure-search-openai-demo#378]
Hi,
I'm trying to integrate with SharePoint online document libraries using the guide provided her https://learn.microsoft.com/en-us/azure/search/search-howto-index-sharepoint-online.  Everything creates, no errors however my index appears to be empty, when I run it no documents appear, obviously there are documents in the library.  Are there any logs anywhere which will provide me some details on what's gone wrong?  

Any help would be appreciated, the demo works no issues, just now I'm trying to hook into SharePoint content I'm having issues.

Thanks.

**Comment by TrowersWeb** [comment]
Got this working.

**Comment by dGanguly1** [comment]
Hi. I'm trying to do the same.Can you please tell me how you got this to work?
How do I make it look at other indexes other than the "gptkbindex" ?

**Comment by pamelafox** [comment]
@dGanguly1 

The AZURE_SEARCH_INDEX environment variable determines which index is used. Change that variable to change the index name.
