### ISSUE TITLE
Query against multiple indexes defined in azure cognitive search service

### ISSUE THREAD

**Issue by dGanguly1** [Azure-Samples/azure-search-openai-demo#380]
I want to modify this code to query my prompt against multiple indexes in azure cognitive search service instead of using the "gptkbindex".
How do I do it? Is it possible?

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@dGanguly1 

See this FAQ regarding the ability to search across multiple indexes in Cognitive Search:
https://learn.microsoft.com/en-us/azure/search/search-faq-frequently-asked-questions#can-i-search-across-multiple-indexes-

There's no built-in functionality in ACS for searching across multiple indexes, but this answer that suggests how one could combine results from multiple searches:
https://learn.microsoft.com/en-us/answers/questions/1104900/azure-cognitive-search-query-multiple-indexes


For that approach, you would need to change the code in a few places, to create multiple search clients.

app.py:

search_client = SearchClient(
    endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net",
    index_name=AZURE_SEARCH_INDEX,
    credential=azure_credential)


chatreadretrieveread.py:

Change run() method to call search on multiple clients and combine results.

It should be doable. Please re-open this issue if you run into a specific issue with implementation.
