### ISSUE TITLE
Is there a way to turn off the "Developer settings" button?

### ISSUE THREAD

**Issue by KellyChesco** [Azure-Samples/azure-search-openai-demo#382]
Is there a way to turn off the "Developer settings" button on the top right of the UX?

### Mention any other details that might be useful

We don't want end users to be able to access these features.

**Comment by pamelafox** [comment]
Yes, that's from the SettingsButton component. You can look for references to it in the various React components, delete them, and rebuild/redeploy.

https://github.com/Azure-Samples/azure-search-openai-demo/blob/46e75e16d88a3f106f3e32bbb75d65617d0b83e3/app/frontend/src/pages/chat/Chat.tsx#L13

**Comment by KellyChesco** [comment]
:) TY Pamela, I almost emailed you on Monday to ask this since its not actually a bug.
