### ISSUE TITLE
Could not provision gpt-35-turbo model 0613 from main.bicep file

### ISSUE THREAD

**Issue by sivi3883** [Azure-Samples/azure-search-openai-demo#384]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I am trying to deploy the gpt-35-turbo model 0613 version to see if this model version follows the prompt instruction more aggressively than 0301 (which is referred in the demo code). I changed the version from 0301 to 0613 in the main.bicep file and ran azd up but only the gpt-35-turbo model 0301 keeps getting deployed. Please let me know how to fix this issue. I also tried removing all the resources and started deploying the resources from the scratch but no luck. 

### Any log messages given by the failure
>

### Expected/desired behavior
> Use the latest gpt-35-turbo model 0613 version as 0301 has issues in following the prompt instruction. 0301 can be tricked to answer questions that are not supplied in the context of the prompt template provided to the model. We want the model to answer only from the supplied contexts (which contains our enterprise recent data) and would like to let the model to say along the lines of "I dont know" if the answer is not available in the supplied context

### OS and Version?
> macOS Monterey 

### azd version?
> run `azd version` and copy paste here.

### Versions
>azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for the issue report, lets merge this into #43 

A code update is in progress for this.
