### ISSUE TITLE
Error: The API deployment for this resource does not exist. 

### ISSUE THREAD

**Issue by phosseini** [Azure-Samples/azure-search-openai-demo#391]
I completed running the `azd up` command without any errors and looks like my app is deployed successfully. However, I keep getting the following error (It's been a while since I completed the deployment, but I still get the error.) Any idea what causes this error?

```
Error: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```

<img width="1373" alt="Screenshot 2023-07-06 at 10 10 22 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/25105263/9594ee78-8c46-4696-b03f-9fbff9abbe39">

### azd version?
`azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)`

PS. I came across [this issue](https://github.com/mckaywrigley/chatbot-ui/issues/498) too, but I can't still figure out how to solve the problem.

**Comment by fakoe** [comment]
This is probably related to:

#388

**Comment by phosseini** [comment]
@fakoe Yup! Problem solved.

**Comment by namratam30** [comment]
I am using existing OpenAI service. Can you tell me how to fix the error.

**Comment by pamelafox** [comment]
If you are getting an error like this, it is probably due to the deployment ID not being specified correctly. I recommend enabling debug logging (see the FAQ in the README about logging) which will show you what URL OpenAI tries to reach, and then you can compare that URL to what the Azure studio shows.
