### ISSUE TITLE
Issues with search query generation for "chat" tab with gpt model

### ISSUE THREAD

**Issue by hanwesh** [Azure-Samples/azure-search-openai-demo#398]
> Please provide us with the following information:
> ---------------------------------------------------------------

![Screenshot 2023-07-09 173140](https://github.com/Azure-Samples/azure-search-openai-demo/assets/4345627/a8f31640-fcfa-4b1a-bc07-6ee8e5ec9e5f)

### Minimal steps to reproduce
> click on the first question, not return the right answer, do it again, it works.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 11

### azd version?
> azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

### Versions
>0cc155b2c8ce788be7b0916f392d8f531a71f6d9

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This is a regression in conversation quality due to the recent change from the (deprecated) davinci model to gpt35-turbo. We need to tweak the prompt and/or do some post-processing to improve the quality of the search queries generated by gpt35-turbo.

The "ask" tab still works reliably, since it doesn't rely on gpt35-turbo to generate search queries.

Another option for you is to use this other sample, which uses cognitive search built into OpenAI:  https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/README_azd.md

**Comment by hanwesh** [comment]
> This is a regression in conversation quality due to the recent change from the (deprecated) davinci model to gpt35-turbo. We need to tweak the prompt and/or do some post-processing to improve the quality of the search queries generated by gpt35-turbo.
> 
> The "ask" tab still works reliably, since it doesn't rely on gpt35-turbo to generate search queries.
> 
> Another option for you is to use this other sample, which uses cognitive search built into OpenAI: https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/README_azd.md

you are right @pamelafox I can see the ASK still working reliably. so what is next on this? will someone tweak the prompt from the team? Thanks

**Comment by pamelafox** [comment]
There was a recent change by @srbalakr that attempted to improve the query generation. I also think the recent change by @pablocastro may have improved it as well. 

But according to recently filed #428, it is still occasionally generating queries with quotes. @akashtalole Do you have the latest version checked out?

**Comment by akashtalole** [comment]
@pamelafox I have noticed that issue #428  occurs intermittently, even though I checked out the latest version today.

**Comment by pamelafox** [comment]
Thanks for confirming. We likely need to do additional prompt engineering or possibly post-processing.

**Comment by akashtalole** [comment]
I tried with this prompt line added in query_prompt_template `Do not return any text inside '' or "" in the search query terms.`

Even in earlier code added post processing to `completion.choices[0].message.content.replace("\"", "")`

Need to test above fix.

**Comment by hanwesh** [comment]
after get the latest version as today, the chat seems back to normal now. Let me do more testing. @pamelafox @akashtalole
