### ISSUE TITLE
Invalid document key: '_________20230101_txt-1'. Keys cannot start with a leading underscore. 

### ISSUE THREAD

**Issue by ikka86** [Azure-Samples/azure-search-openai-demo#400]
If you do "pwsh . \Јscripts\prepdocs.ps1" will change only the Japanese part of the filename in the DATA to underscores.
What is used is a text file.

**Comment by pamelafox** [comment]
Related: https://github.com/Azure-Samples/azure-search-openai-demo/issues/334

cc @tonybaloney We saw this issue when experimenting with non-ASCII filenames, I believe.

**Comment by ikka86** [comment]
@pamelafox 
Thank you.
I have tried but the error is not resolved.

Message: The request is invalid. Details: actions : 0: Invalid document key: '_______20230322_txt-0'. Keys cannot start with a leading underscore. 1: Invalid document key: '_______20230322_txt-1'. Keys cannot start with a leading underscore. 2: Invalid document key: '_______20230322_txt-2'. Keys cannot start with a leading underscore.
Exception Details:      (InvalidDocumentKey) 0: Invalid document key: '_______20230322_txt-0'. Keys cannot start with a leading underscore. Parameters: actions
        Code: InvalidDocumentKey
        Message: 0: Invalid document key: '_______20230322_txt-0'. Keys cannot start with a leading underscore. Parameters: actions     (InvalidDocumentKey) 1: Invalid document key: '_______20230322_txt-1'. Keys cannot start with a leading underscore.
        Code: InvalidDocumentKey
        Message: 1: Invalid document key: '_______20230322_txt-1'. Keys cannot start with a leading underscore. (InvalidDocumentKey) 2: Invalid document key: '_______20230322_txt-2'. Keys cannot start with a leading underscore.
        Code: InvalidDocumentKey
        Message: 2: Invalid document key: '_______20230322_txt-2'. Keys cannot start with a leading underscore.

**Comment by pamelafox** [comment]
We haven't decided the best fix for it yet, but you can try changing line 226 in prepdocs.py create_section function to:

"id": re.sub("[^0-9a-zA-Z_-]","_",f"file-{filename}-{i}"),

That only works if the non-japanese parts of the filenames are unique enough. Otherwise I think we need to hash the filename to make it a unique ID with only ASCII characters.

**Comment by ikka86** [comment]
@pamelafox
Thank you.
I have tried but the error is not resolved.


  File "C:\works\azure-search-openai-demo\scripts\prepdocs.py", line 236
    "id": re.sub("[^0-9a-zA-Z_-]","_",f"file-{ファイル名}-{i}"),{filename}-{i}"),
                                                                                      ^
SyntaxError: EOL while scanning string literal

**Comment by pamelafox** [comment]
It looks like you made a different change than my suggestion, introducing a syntax error. Can you try making the exact change?

**Comment by pamelafox** [comment]
I've proposed a fix in https://github.com/Azure-Samples/azure-search-openai-demo/pull/418

**Comment by pamelafox** [comment]
I've merged my proposed fix from that PR, please try that out @ikka86 and comment on this issue if you still have issues. Thanks for letting us know!

**Comment by ikka86** [comment]
Thanks.
I got the following error on azd up.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 0: invalid start byte

**Comment by pamelafox** [comment]
Can you provide the full error / traceback?
