### ISSUE TITLE
Add option to enable tracing/appinsights

### ISSUE THREAD

**Issue by lenisha** [Azure-Samples/azure-search-openai-demo#401]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> Add option to enable tracing/logs/metrics to flow to App Insights to enable usage reports

**Comment by pamelafox** [comment]
Good idea! For Python apps, the OpenCensus package is the current way to hook into AppInsights, but OpenTelemetry is going to supercede that soon.

This should be the way to do it for OpenCensus, though I haven't tried it yet myself:

https://learn.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python-request#track-flask-applications

**Comment by kishorerv93** [comment]
@lenisha  #415 Here is my code enabling the azure tracing/appinsights

**Comment by pamelafox** [comment]
We've merged a PR (https://github.com/Azure-Samples/azure-search-openai-demo/pull/515) that adds opentelemetry and also updated the README with information about enabling it (it's opt in). Please file an issue if you see issues with it.
