### ISSUE TITLE
Deployment using existing resources is failing

### ISSUE THREAD

**Issue by jacobwaller** [Azure-Samples/azure-search-openai-demo#402]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Have a central openAI instance in Azure with GPT 3 davinci and GPT 3.5 configured
2. Follow the instructions in the readme for using existing resources
3. `azd up`

### Any log messages given by the failure
```
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is [guid]. See inner errors for details.
InsufficientQuota: The specified capacity '1' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - Text-Davinci-003'.
```

### Expected/desired behavior
>
Deployment is successful & uses the existing Davinci deployment

### OS and Version?
> Mac M2 Ventura

### azd version?
> azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Could you go into your Azure OpenAI studio and check the capacity of your current deployments?

<img width="1174" alt="Screenshot 2023-07-10 at 10 10 24 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/14e79eb2-6b1f-4569-88de-a7a6e9d1ffd6">

Usually that error means that your other deployments have too high a capacity, and you need to edit those deployments to have lower capacity.

**Comment by jacobwaller** [comment]
Hey Pamela! Thanks for the quick response. As far as I can see, we only have the two deployments that I'm trying to use. & I've had someone else check the deleted deployments and we have nothing in there either.
![Screenshot 2023-07-10 at 12 16 02 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/5910144/49658849-853c-4241-98fb-cb4c531d40aa)

Is there anything sticking out here?

**Comment by pamelafox** [comment]
Well, that gpt35-turbo says its at 120K TPM, so I would suggest editing that down to 30K. You can click it, then select "edit deployment", and move the slider. I know that the deploy should in theory change that to 30K, but I think it doesn't go in the right order for that to happen.

**Comment by jacobwaller** [comment]
I ended up just removing them from the main bicep file since they already exist as deployed resources. Unfortunately, I don't think this package works very well with existing openAI deployments right now
