### ISSUE TITLE
Add script to enable AAD Auth/Authz

### ISSUE THREAD

**Issue by lenisha** [Azure-Samples/azure-search-openai-demo#404]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>
With the help of AppService Auth enable Authentication and Authorization for specific AAD group in the tenant

**Comment by pamelafox** [comment]
I've enabled AAD for the other sample:
https://github.com/Microsoft/sample-app-aoai-chatGPT/

I did it via preprovision and postprovision hooks, and some scripts to create the app registration.
Unfortunately, I haven't gotten it working on CI/CD yet, but it does work well locally.
Let me know if you'd like a PR to this repo for those changes.

**Comment by wherewith** [comment]
I would love a PR to this repo for those changes!

**Comment by kishorerv93** [comment]
@wherewith  also if you could display the user icon in the headers with the logged in user details.

**Comment by wherewith** [comment]
I think that whatever solution was used on the other sample would be perfect for this repo as a starting point @pamelafox

**Comment by salvafuentes** [comment]
Yes please, it would be great to have some kind of authentication so not everyone can access the deploy.

**Comment by pamelafox** [comment]
PR at https://github.com/Azure-Samples/azure-search-openai-demo/pull/534
Please report back if it works for you.

**Comment by pamelafox** [comment]
We do have documentation now about using AAD but we'd like to automate it with scripts. @mattmsft is going to extend my scripts to work with the document-level access control he just added.

**Comment by zhongshuai-cao** [comment]
This is fantastic! I was hesitant to deploy the app initially and then manually integrate Azure AD later. Unfortunately, the official documentation didn't provide clear steps on how to achieve this using deployment scripts.

**Comment by mattgotteiner** [comment]
Sorry we never closed this - we did eventually do this

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md#setting-up-optional-login-and-document-level-access-control
