### ISSUE TITLE
"Suggest follow-up questions" is not working

### ISSUE THREAD

**Issue by neo475269** [Azure-Samples/azure-search-openai-demo#405]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Select "Suggest follow-up questions" in Developer Settings.  I expect follow-up questions will pop up after chat response but there is no follow-up question.

### Any log messages given by the failure
>

### Expected/desired behavior
>Select "Suggest follow-up questions" in Developer Settings.  I expect follow-up questions will pop up after chat response but there is no follow-up question.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11

### azd version?
> run `azd version` and copy paste here.

### Versions 1.0.2
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for filing, let's merge this issue with the older issue #240 and close this one. Please subscribe to that one.
