### ISSUE TITLE
Issue Running gpt-4 model 

### ISSUE THREAD

**Issue by yeggan** [Azure-Samples/azure-search-openai-demo#408]
Hi @pablocastro @jongio

My team is working on the demo. We have approval and access to gpt-4. However, when we try to deploy we get the following error:

```{"code":"InvalidTemplateDeployment","message":"The` template deployment 'openai' is not valid according to the validation procedure. The tracking id is '74716484-7b27-4f86-a216-52e5a1843bc4'. See inner errors for details.","details":[{"code":"DeploymentModelNotSupported","message":"The model 'Format: OpenAI, Name: gpt-4, Version: 1, Source: ' of account deployment is not supported."}]}```

We are using gpt-4 (0314) version 1. Is there anything we’re missing?

Here are the relevant parameters in our .bicep file:

```param gptDeploymentName string = 'davinci'
param gptDeploymentCapacity int = 20
param gptModelName string = 'gpt-4'
param chatGptDeploymentName string = 'chat'
param chatGptDeploymentCapacity int = 20
param chatGptModelName string = 'gpt-4'```


```module openAi 'core/ai/cognitiveservices.bicep' = {
  name: 'openai'
  scope: openAiResourceGroup
  params: {
    name: !empty(openAiServiceName) ? openAiServiceName : '${abbrs.cognitiveServicesAccounts}${resourceToken}'
    location: openAiResourceGroupLocation
    tags: tags
    sku: {
      name: openAiSkuName
    }
    deployments: [
      {
        name: gptDeploymentName
        model: {
          format: 'OpenAI'
          name: gptModelName
          version: '1'
        }
        capacity: gptDeploymentCapacity
      }
      {
        name: chatGptDeploymentName
        model: {
          format: 'OpenAI'
          name: chatGptModelName
          version: '0314'
        }
        capacity: chatGptDeploymentCapacity
      }
    ]
  }
}```

**Comment by pamelafox** [comment]
The version there is still 0314, can you try changing that to 0613? (We probably need to parameterize that as well, to make it obvious that both have to change at the same time).

**Comment by venkateshkumar** [comment]
Still getting error after changing the version

DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-4, Version: 2, Source: ' of account deployment is not supported.

**Comment by pamelafox** [comment]
@yeggan Can you share if the change worked for you? Trying to find a Bicep that will work for @venkateshkumar - thanks!

**Comment by yeggan** [comment]
I changed my code as follow (based on my available quota) and was able to implement the code.
It works for now. 
Issue #408 can be closed now.

``` param gptDeploymentName string // Set in main.parameters.json
param gptDeploymentCapacity int = 10
param gptModelName string = 'gpt-4-32k'
param chatGptDeploymentName string // Set in main.parameters.json
param chatGptDeploymentCapacity int = 10
param chatGptModelName string = 'gpt-4-32k'
param embeddingDeploymentName string = 'embedding'
param embeddingDeploymentCapacity int = 10
param embeddingModelName string = 'text-embedding-ada-002'
 ```




```module openAi 'core/ai/cognitiveservices.bicep' = {
  name: 'openai'
  scope: openAiResourceGroup
  params: {
    name: !empty(openAiServiceName) ? openAiServiceName : '${abbrs.cognitiveServicesAccounts}${resourceToken}'
    location: openAiResourceGroupLocation
    tags: tags
    sku: {
      name: openAiSkuName
    }
    deployments: [
      {
        name: gptDeploymentName
        model: {
          format: 'OpenAI'
          name: gptModelName
          version: '0314'
        }
        sku: {
          name: 'Standard'
          capacity: gptDeploymentCapacity
        }
      }
      {
        name: chatGptDeploymentName
        model: {
          format: 'OpenAI'
          name: chatGptModelName
          version: '0314'
        }
        sku: {
          name: 'Standard'
          capacity: chatGptDeploymentCapacity
        }
      }
      {
        name: embeddingDeploymentName
        model: {
          format: 'OpenAI'
          name: embeddingModelName
          version: '2'
        }
        capacity: embeddingDeploymentCapacity
      }
    ]
  }
}```

**Comment by venkateshkumar** [comment]
Thanks for the response, Now we are getting different embedding error.

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. 
DeploymentModelNotSupported: The model Format: OpenAI, Name: text-embedding-ada-002, Version: 2, Source:  is not supported in current region.

Any work around for this

**Comment by yeggan** [comment]
You need to check your quota first. 
As mentioned before, I defined the parameters based on my available quota.
From the error, I think you don't have Name: text-embedding-ada-002, Version: 2, in your avaible quota in the region that you are deploying your code. 
Send the request to MS to increase your quota or select another model "param embeddingModelName string"
