### ISSUE TITLE
AppBackend: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by DaniSchwegler** [Azure-Samples/azure-search-openai-demo#409]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Starting the app website an enter a query or use one of the tree default questions, then an error appaers  SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### Any log messages given by the failure
>we can't see any errors in the "log stream"

### Expected/desired behavior
>that the chat will working and answer the question

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11

### azd version?
>azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

### Versions
> #385 main

### Mention any other details that might be useful

> the deployment looks completed
> [gptkbindex] is usable, documents are in the storage account, normal queries from azure portal on search servive working well

**Comment by pamelafox** [comment]
That error sounds like the frontend is receiving an HTML page when it expects a JSON response. 

Can you open the Network tab in the Developer Tools in your browser and inspect the contents of the HTML page? It may show an error.

You may also be able to find an error in the logs in the Advanced Tools of the portal. Please see the bottom of my blog post: 
http://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html

You can also enable a higher level of logging by putting this at the start of app.py:

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('azure')
logger.setLevel(logging.DEBUG)

And re-deploying.

**Comment by DaniSchwegler** [comment]
Hi Pamela

Many thanks for the information, we were able to narrow down the problems with the developer mode.
Is a proxy/firewall history of our company and thus the error message is not correct. Case can be closed.

I have a follow-up question, how exactly can we bring additional PDF's into the process without redeploying everything. Some kind of delta synchronization of new PDF documents?

BR
Daniel

**Comment by pamelafox** [comment]
Great to hear! To upload more PDFs, put them in the data/ folder and run `./scripts/prepdocs.sh` or `./scripts/prepdocs.ps1`. To avoid reuploading existing docs, move them out of the data folder. You could also implement checks to see whats been uploaded before, the code doesnt yet have such checks.
