### ISSUE TITLE
Enabling streaming

### ISSUE THREAD

**Issue by wherewith** [Azure-Samples/azure-search-openai-demo#421]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Would it be possible to enable streaming from the openAI endpoint in this sample, similar to [https://github.com/microsoft/sample-app-aoai-chatGPT/tree/main/static](https://github.com/microsoft/sample-app-aoai-chatGPT)?

**Comment by pamelafox** [comment]
I have a draft PR that adds streaming using the same approach used in that sample:

https://github.com/Azure-Samples/azure-search-openai-demo/pull/481

**Comment by pamelafox** [comment]
I have a new PR that adds optional streaming to the async Quart app: https://github.com/Azure-Samples/azure-search-openai-demo/pull/532

**Comment by pamelafox** [comment]
PR is merged! Streaming is now enabled by default but can be turned off.
