### ISSUE TITLE
Need more info on Sharing Environments

### ISSUE THREAD

**Issue by jnkochhar** [Azure-Samples/azure-search-openai-demo#423]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Steps mentioned in Sharing Environments section of README.md are not very clear. Can detailed steps be provided

### Any log messages given by the failure
> ERROR: getting deployment: error retrieving state: retrieving deployment: no deployments found for environment

### Expected/desired behavior
> 

### OS and Version?
> macOS (Ventura 13.4)

### azd version?
> 1.1.0

### Versions
>

### Mention any other details that might be useful
Steps mentioned in Sharing Environments section of README.md are not very clear. Can detailed steps be provided
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That section should only be followed *after* a successful `azd up` - and is only relevant for sharing deployed azd environments with colleagues or other machines.
