### ISSUE TITLE
Anyone has tried re running the index which is created

### ISSUE THREAD

**Issue by rahulsnc3it** [Azure-Samples/azure-search-openai-demo#425]
I have removed some pdf files from the storage account so wanted to know how can the index which is created will be reflected do we have any method to update the index so that the file which is removed is reflected in the search index

**Comment by zaffaste** [comment]
Hi @rahulsnc3it, I think the best way to remove pdf files is using prepdocs.py with prepdocs.ps1 specifing in the last line (ln39) --remove before closing " and specifing the name of the file after ./scripts/prepdocs.py, this command will remove the file from blob storage and index from indexes.

Line 39 in prepdocs.ps1 should be something like this:
Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prepdocs.py $cwd/data/REPLACE_WITH_THE_NAME_OF_THE_FILE_YOU_WANT_TO_REMOVE.pdf --storageaccount $env:AZURE_STORAGE_ACCOUNT --container $env:AZURE_STORAGE_CONTAINER --searchservice $env:AZURE_SEARCH_SERVICE --openaiservice $env:AZURE_OPENAI_SERVICE --openaideployment $env:AZURE_OPENAI_EMB_DEPLOYMENT --index $env:AZURE_SEARCH_INDEX --formrecognizerservice $env:AZURE_FORMRECOGNIZER_SERVICE --tenantid $env:AZURE_TENANT_ID -v" -Wait -NoNewWindow

then you have to re-run prepdocs.ps1

HtH,
Stefano

**Comment by pamelafox** [comment]
That's right, you can either remove all the docs or a particular doc, via the remove and removeall arguments:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/1a8a1ce93471d7d5d73d177477e8b106475289ca/scripts/prepdocs.py#L285
