### ISSUE TITLE
Search query term generation issue with chatcompletion api

### ISSUE THREAD

**Issue by akashtalole** [Azure-Samples/azure-search-openai-demo#428]
While app is creating search query based on question for cognitive search sometime it generates search query in single or double quotes. Then cognitive search does not return any search results.

**Comment by pamelafox** [comment]
Thanks for filing @akashtalole - this is actually the same issue as we're discussing in https://github.com/Azure-Samples/azure-search-openai-demo/issues/398 so I'm going to close this one.
