### ISSUE TITLE
Support for GPT-4 and 0613

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure-Samples/azure-search-openai-demo#43]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
In this blog post, says that this repo will use GPT-4 models:
https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/working-with-gpt-4-and-chatgpt-models-on-azure-preview/ba-p/3773595

### Any log messages given by the failure
I cannot find anywhere that this REPO is deploying GPT-4 models for Azure OpenAI.

### Expected/desired behavior
Detail in the documentation or update a parameter to switch to use GPT-4

**Comment by AllaeddineD** [comment]
Experiencing the same issue. Did you manage to make it work ?

**Comment by ThomasLambertES** [comment]
same here, got preview access to GPT-4 and i'm looking into deploying in that model.

**Comment by kishorerv93** [comment]
I was actively looking in to it ; if anyone else had already found a way to plug-in. Please update 😀

**Comment by sk1136** [comment]
Any update on this? Can we use this same code with GPT-4 and embeddings. The interface for GPT 3.5 and 4 is different so we can't just change the model name and version number.

**Comment by kishorerv93** [comment]
I'm using GPT-4-32k the whole chatreadretrive code should be changed. I will push the code soon. But note that response will be slower when compared to Gpt-3.5-turbo but quality is really good.

**Comment by ThomasLambertES** [comment]
> I'm using GPT-4-32k the whole chatreadretrive code should be changed. I will push the code soon. But note that response will be slower when compared to Gpt-3.5-turbo but quality is really good.

please do tell us once it's ready, i'm really looking forward to test

**Comment by rabbyn** [comment]
Hi @kishorerv93 , can we now use GPT-4 (or 4-32k) ? Thanks

**Comment by PTTrazavi** [comment]
According to [(Azure OpenAI)](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/whats-new), gpt-35-turbo (version 0613) is available now. Same as gpt-4 (version 0613), they only work with openai.ChatCompletion.create, but not openai.Completion.create.
Can someone modify the chatreadretrieveread.py code so it can work with openai.ChatCompletion.create? Thanks!

**Comment by pamelafox** [comment]
A PR is in progress: https://github.com/Azure-Samples/azure-search-openai-demo/pull/385

**Comment by kishorerv93** [comment]
@AllaeddineD  @PTTrazavi  @rabbyn  Submitted my PR for GPT-4 #394

**Comment by pamelafox** [comment]
This repo got ported to support Chat Completions a while ago (0613). It defaults to 3.5 however, since most don't have access to 4. To use GPT-4 : 

In infra/main.bicep, change chatGptModelName to 'gpt-4' instead of 'gpt-35-turbo'. You may also need to adjust the capacity above that line depending on how much TPM your account is allowed.
