### ISSUE TITLE
Add Azure DevOps pipelines for deployment

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#432]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Do you mean Azure DevOps pipelines? If so, this PR has some examples: https://github.com/Azure-Samples/azure-search-openai-demo/pull/329/files

**Comment by pamelafox** [comment]
This pipeline may work for you: https://github.com/Azure-Samples/todo-python-mongo/blob/main/.azdo/pipelines/azure-dev.yml

**Comment by namratam30** [comment]
> This pipeline may work for you: https://github.com/Azure-Samples/todo-python-mongo/blob/main/.azdo/pipelines/azure-dev.yml

How can we use the docker container given in the repo in this pipeline. (The one present in ".devcontainer" folder)?

**Comment by pamelafox** [comment]
@namratam30 That Docker container is only used for creating the Dev Container (for GitHub Codespaces / VS Code), it is not designed for deployment. Are you looking for a Dockerfile to deploy this somewhere else? That feature is requested here: https://github.com/Azure-Samples/azure-search-openai-demo/issues/173

**Comment by namratam30** [comment]
> > @namratam30 That Docker container is only used for creating the Dev Container (for GitHub Codespaces / VS Code), it is not designed for deployment. Are you looking for a Dockerfile to deploy this somewhere else? That feature is requested here: #173
> 
> Do we need owner access for running the application using DevOps pipeline. We have contributor access and getting error while running the pipeline.
> 
> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription: Deployment Error Details: InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '_**'. See inner errors for details. InsufficientQuota: The specified capacity '60' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - Text-Davinci-003'. InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '**_' of type 'Microsoft.Authorization/roleAssignments'. The client '**' with object id '**' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/**/resourceGroups/rg-testazd/providers/Microsoft.Authorization/roleAssignments/**'.'. InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '**' of type 'Microsoft.Authorization/roleAssignments'. The client '**' with object id '**' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/**/resourceGroups/rg-testazd/providers/Microsoft.Authorization/roleAssignments/**'.'.

@pamelafox  any update on this

**Comment by YutongTie-MSFT** [comment]
@pamelafox May I have any update for this issue? Thanks a lot/

**Comment by vhvb1989** [comment]
I'll create a PR with the Azdo pipeline.
@pamelafox  FYI

**Comment by vhvb1989** [comment]
PR: https://github.com/Azure-Samples/azure-search-openai-demo/pull/488

**Comment by namratam30** [comment]
How to use existing resources in the provision and deployment.

**Comment by namratam30** [comment]
I am able to create and run the DevOps pipeline successfully. Any suggestion on create the rollback plan in case of any error or issue.

**Comment by pamelafox** [comment]
I replied regarding rollbacks here: https://github.com/Azure-Samples/azure-search-openai-demo/issues/673
