### ISSUE TITLE
Getting timeout issue while connecting to gptkb indexer

### ISSUE THREAD

**Issue by rupesh15203** [Azure-Samples/azure-search-openai-demo#433]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I tried to run this demo on custom data. I use the existing openai resource group while deploying the app.
Indexing has been generated for custom data and app is deployed.

### Any log messages given by the failure
> When I try to query from application, I am getting following issue:
`Error: (<urllib3.connection.HTTPSConnection object at 0x7b3b7f655600>, 'Connection to gptkb-7rbi3klczjkre.search.windows.net timed out. (connect timeout=300)')`

### Expected/desired behavior
> 

### OS and Version?
> Windows 11

### azd version?
> azd version 1.1.0

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, interesting. Does this happen consistently, or just once? Is it working for you now?

**Comment by rupesh15203** [comment]
Hi @pamelafox , The issue has been solved. It occurs because of firewall settings at my end
