### ISSUE TITLE
How to change the subscription for deployment

### ISSUE THREAD

**Issue by leksaas** [Azure-Samples/azure-search-openai-demo#435]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
When I first time open azure-search-openai-demo solution like remote-container, I got the option to choose in which subscription I want to create the resources. But now, I want to change subscription, but every time I try to deploy, I don't have the option to select the desired subscription. How to solve that?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That's right! You can learn about other `azd env` commands here:
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-env

Thanks @yeggan - I'll close this issue since I believe that answers the question.
