### ISSUE TITLE
azd up failing to open AI resource

### ISSUE THREAD

**Issue by venkateshkumar** [Azure-Samples/azure-search-openai-demo#436]
We have followed the tutorial and updated GPT4 version in the code 

Failing to create resources for Open AI

Open AI snapshot updated in bicep file.

name: gptDeploymentName
        model: {
          format: 'OpenAI'
          name: gptModelName
          version: '0613'
        }
        sku: {
          name: 'Standard'
          capacity: gptDeploymentCapacity
        }
      }
      {
        name: chatGptDeploymentName
        model: {
          format: 'OpenAI'
          name: chatGptModelName
          version: '0613'
        }

Getting following error.

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'b5c0f524-df7e-4986-8975-acc87ca17afd'. See inner errors for details.
DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-4, Version: 2, Source: ' of account deployment is not supported.

**Comment by pamelafox** [comment]
Can you share the full infra/main.bicep? I'm guessing there's a mismatch between versions/model names. Unfortunately I don't have access to gpt-4 yet so have been unable to try it myself.

**Comment by pamelafox** [comment]
There's now an FAQ about enabling GPT-4, and I tested that it works, so I'll close this issue.
