### ISSUE TITLE
Control plane for existing Cognitive Services OpenAI deployments is inactive. Unable to delete.

### ISSUE THREAD

**Issue by george-moore** [Azure-Samples/azure-search-openai-demo#44]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy an OpenAI service.  Attempt to delete the OpenAI service.

### Any log messages given by the failure
> The control plane for my existing Cognitive Services OpenAI deployments seems to be inactive. I have two deployments for this sample (Chat and DaVinci), and when I click on either of them in the OpenAI Studio, the "Delete Deployment" button is greyed out.  Please see images below.  This is from a deployment 12 hours ago.  There is no action I can take to delete these services in either the Azure Portal or the OpenAI Studio.  I have "purged" any previously deleted deployments via the OpenAI pane in the Azure Portal, so there are no other older deployments still pending.  In addition, when I try to deploy via the CLI, I receive this error message:

ERROR: deployment failed: error deploying infrastructure: failed deploying: starting deployment to subscription: PUT https://management.azure.com/subscriptions/7c9469c0-29ac-424a-85ab-d01f2-xxxx-xxxx/providers/Microsoft.Resources/deployments/openai-georgem-22
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: DeploymentActive
--------------------------------------------------------------------------------
{
  "error": {
    "code": "DeploymentActive",
    "message": "Unable to edit or replace deployment 'openai-georgem-22': previous deployment from '3/22/2023 12:21:06 AM' is still active (expiration time is '3/28/2023 11:24:15 PM'). Please see https://aka.ms/arm-deploy-resources for usage details."
  }
}
--------------------------------------------------------------------------------

### Expected/desired behavior
> The delete button should work, allowing me to clean up any previous OpenAI service deployment.  See below:
![OpenAI Studio 2023-03-22 061144](https://user-images.githubusercontent.com/11613153/226915115-bac74351-764a-427d-b06e-3414677f72fc.jpg)

All Cognitive Services resources are purged for this subscription:
![Purged Resources 2023-03-22 061351](https://user-images.githubusercontent.com/11613153/226915646-c0306709-a540-4731-a25c-ab14a657ff66.jpg)

Current image from the portal showing a successful deployment: 

![OpenAI Succeeded 2023-03-22 061425](https://user-images.githubusercontent.com/11613153/226915672-72934865-1780-463b-9cf3-9279c55de280.jpg)

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by george-moore** [comment]
Where is the "Settings" button in the OpenAI Studio?  I've clicked all around the Studio and can't find anything like this.  Thanks.

**Comment by george-moore** [comment]
@vikramhn, the settings button is not visible on any screen in my OpenAI Studio.

**Comment by vikramhn** [comment]
@george-moore Can you share the screen shot of what you see?

**Comment by george-moore** [comment]
Here is the landing page for my deployments in the OpenAI Studio.  There is no "settings" button.  Thanks.

![OpenAI Portal Screenshot 2023-03-22 094255](https://user-images.githubusercontent.com/11613153/226976810-c38d064b-a03d-45de-a29b-1eaea455ed8a.jpg)

**Comment by pablocastro** [comment]
@george-moore should be addressed by now, but please reactivate if it's still giving you trouble.
