### ISSUE TITLE
Invalid AzureCognitiveSearch configuration detected: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by claudino-kognita** [Azure-Samples/azure-search-openai-demo#440]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

When deployed to Azure, the example works, but when I tryied to run locally, using the same input variables, I am receiving the following error message "Invalid AzureCognitiveSearch configuration detected: `403 Client Error: Forbidden for url: https://AZURE_SEARCH_SERVICE.search.windows.net/indexes/azureblob-index-v3?api-version=2021-04-30-Preview`. Given it works on Azure, the problem is not with my credentials (I used these credentials oustside azure directly on AzureCognitiveSearch SDK and it worked).

Is there any documentation on how to integrate AzureCognitiveSearch with ChatGPT API? I can't find anything detailing the inputs of the data source entry.

### Minimal steps to reproduce
> Install the application following the documentation and export the following environment variables:
```
AZURE_OPENAI_KEY
AZURE_OPENAI_RESOURCE
AZURE_OPENAI_PREVIEW_API_VERSION
AZURE_OPENAI_MODEL
AZURE_OPENAI_MODEL_NAME
AZURE_OPENAI_TEMPERATURE
AZURE_SEARCH_SERVICE
AZURE_SEARCH_INDEX
AZURE_SEARCH_TOP_K
AZURE_SEARCH_CONTENT_COLUMNS
AZURE_SEARCH_TITLE_COLUMN
AZURE_SEARCH_KEY
AZURE_OPENAI_STREAM


AZURE_SEARCH_SERVICE_ENDPOINT
AZURE_SEARCH_INDEX_NAME
AZURE_SEARCH_API_KEY
```

### Any log messages given by the failure
> Just the error message:

```
 "Invalid AzureCognitiveSearch configuration detected: 403 Client Error: Forbidden for url: https://AZURE_SEARCH_SERVICE.search.windows.net/indexes/azureblob-index-v3?api-version=2021-04-30-Preview"
  }
``` 

### Expected/desired behavior
> The API call should succeed, the same as it is on Azure environment

### OS and Version?
> Linux (Ubuntu 22.04)

### azd version?
> Runing python directly, no azd installed

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hi @claudino-kognita A few questions:

1) Are you logged in locally via `azd auth login`? Can you try running that right before you start the local server?
2) I assume AZURE_SEARCH_SERVICE in your URL corresponds to the actual value, and that's your placeholder to avoid sharing the value in this issue.
3) Did you deploy it using `azd up` after logging in with the same credentials?

**Comment by claudino-kognita** [comment]
Thanks for replying.

1. No I am not logged in via azd, I wish it to work outside azure in a
kubernetes pod based on the documentatio there is no need for being logged
in to use the plugins (as I said before, Azure Cognitive Search worked
outside azure without login)

2. You are right (this is the name of the variable from the example)

3. It was deployed with exactly the same credentials (and worked), but not
from me and not from the same machine. I am trying to replicate the
behaviour using just the inputs as the instructions In the readme.

Em qua., 19 de jul. de 2023 20:33, Pamela Fox ***@***.***>
escreveu:

**Comment by pamelafox** [comment]
Hn, so how are you logged in via Azure on that pod? The app will need to get the credentials somehow. When deployed, it gets the credentials from the app's managed identity. Locally, most devs are logged in with the Azure Developer CLI or the Azure CLI, and that's how it gets the credentials. 

You can learn more about AzureDefaultCredential (used by the code) here:
https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python

Also please read through https://github.com/Azure-Samples/azure-search-openai-demo#sharing-environments if it wasn't deployed from your account.

**Comment by claudino-kognita** [comment]
I expect to pass these as environment variables. As it worked calling
Cognitive Search directly using just the environment variables, I expect
the same behaviour for this sdk, as it should be possible to call directly
over requests lib, like a regular API call.

Em qua., 19 de jul. de 2023 20:57, Pamela Fox ***@***.***>
escreveu:

**Comment by claudino-kognita** [comment]
Pamela, can you confirm it calls the API over requests and not using azure
ask is this app (this is why I expect I has no need for azure credential
chain).

Em qua., 19 de jul. de 2023 20:57, Pamela Fox ***@***.***>
escreveu:

**Comment by pamelafox** [comment]
That should work in theory, since AzureDefaultCredential will attempt to look for environment variables. You have all these setup?
https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python

You could try changing line 35 in app.py to explicitly use EnvironmentCredential class, to make sure thats where its getting the creds.

**Comment by claudino-kognita** [comment]
Pamela, are you sure those variables are needed and we are on the same
page? The application I am talking about (and the line 35 of it) could be
seen on this link:
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/e86035d4a9d0563b337e0c75de29b8c4007a9703/app.py#L35

Here you can see just an environment variable being loaded. I found no use
of Azure ask on the whole page.

Em qua., 19 de jul. de 2023 21:13, Pamela Fox ***@***.***>
escreveu:

**Comment by pamelafox** [comment]
Ah, that is a different code sample than this repo, that explains the confusion.
If that's definitely the code you're using, then you're right, it does not use the Azure SDK, it uses AZURE_OPENAI_KEY and AZURE_SEARCH_KEY. Assuming those are set correctly, then I recommend checking your access. Here's what it looks like for me for the search service when I use "View my access": 
 
<img width="1677" alt="Screenshot 2023-07-19 at 8 48 37 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/d9714749-8bbc-45f4-a141-c9e32bd3944f">

You can see in this Bicep file how the roles can be configured programmatically (when deploying with `azd`):
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/e86035d4a9d0563b337e0c75de29b8c4007a9703/infra/main.bicep#L198

We also have a script in *this* repo that can set roles, which you could use for that repo:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/roles.ps1

**Comment by pamelafox** [comment]
Update: I'm not sure that the roles should be needed for that repo's code, given it's using keys. But I'm also surprised by the error message. Please confirm which codebase you're using and check the values of AZURE_OPENAI_KEY and AZURE_SEARCH_KEY. You can print them out in app.py.

**Comment by claudino-kognita** [comment]
Thanks, I checked. They are all ok. I extracted the http request and made
it directly by curl, could confirm the credentials and the values, and the
error kept the same.

Is there any documentation about using Cognitive Search with this API?

Em qui., 20 de jul. de 2023 07:14, Pamela Fox ***@***.***>
escreveu:

**Comment by pamelafox** [comment]
@claudino-kognita I have found documentation here: 
https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line&pivots=rest-api

I'm going to close this issue since it's not about this repository. Feel free to open an issue on the other repository if you're continuing to see issues with that code.

**Comment by Zion-Avantis** [comment]
I had the same issue today.. I just found i was using a Query key instead of an Admin Key on Opensearch key page. I think it shall be shared on the Documentation page.

**Comment by pamelafox** [comment]
@Zion-Avantis Were you using this repo or https://github.com/Microsoft/sample-app-aoai-chatGPT/ ? If you were using this repo, the `azd up` takes care of setting all the necessary keys. If you were using the other repo, please file an issue there with suggested clarification to the README. Thanks!

**Comment by Zion-Avantis** [comment]
I was using the same repo as the author :) I am just answering in case people end up here :)

**Comment by cateixe** [comment]
@Zion-Avantis thank you, I was stuck on that one too.

**Comment by ebecerramicrosoft** [comment]
Thanks! I was stuck on this one for a while now. I agree, it should be mentioned in the documentation to use the Admin key, not a query one.

**Comment by pamelafox** [comment]
If we're talking about https://github.com/microsoft/sample-app-aoai-chatGPT#environment-variables it does say admin key there, but please send a PR to that repo if you think it needs to be mentioned somewhere else as well. Thanks!

**Comment by cateixe** [comment]
@pamelafox you are right, the documentation states this, my bad. Thank you for your help.

**Comment by ZionAvantis** [comment]
Yes, sorry, didn't update here, but shared the issue on other canal and they updated it :) So it's fixed :)

**Comment by SanthoshMansys** [comment]
Where to check and find  AZURE_SEARCH_KEY ? 

I am getting below error 
Traceback (most recent call last):
  File "d:\AIML\AIMLenv\AzureOpenAI\ACS_LLama2_Langchain.py", line 77, in <module>
    relevant_documents=retriever.get_relevant_documents("what is Ansys")
  File "D:\AIML\AIMLenv\lib\site-packages\langchain_core\retrievers.py", line 211, in get_relevant_documents
    raise e
  File "D:\AIML\AIMLenv\lib\site-packages\langchain_core\retrievers.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
  File "D:\AIML\AIMLenv\lib\site-packages\langchain\retrievers\azure_cognitive_search.py", line 98, in _get_relevant_documents
    search_results = self._search(query)
  File "D:\AIML\AIMLenv\lib\site-packages\langchain\retrievers\azure_cognitive_search.py", line 74, in _search
    raise Exception(f"Error in search request: {response}")
Exception: Error in search request: <Response [400]>

**Comment by pamelafox** [comment]
I think you are posting in the wrong repo, as none of those files match ours. Regardless, you can probably find AZURE_SEARCH_KEY by looking in the Azure Portal for your Azure search index and getting the keys from there, then exporting that environment variable in your environment.
