### ISSUE TITLE
connect /chat endpoint to different blob containers for source of knowledge

### ISSUE THREAD

**Issue by mehrdad-zade** [Azure-Samples/azure-search-openai-demo#448]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
- [ x ] documentation issue or request
- [ x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> created a new blob container under the Blob storage and uploaded pdf files through Azure Portal. How to point the /chat endpoint in app.py to interact with this new set of data?

### Any log messages given by the failure
>

### Expected/desired behavior
>
a parameter added to the /chat endpoint to point to the desired blob container

### OS and Version?
> macOS Ventura

### azd version?
> azd version 1.1.0 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@mehrdad-zade The /chat endpoint uses the search index that was setup as part of `azd up`. That search index uses the documents in the /data folder that were indexed as part of `azd up`. If you'd like it to use PDFs in the blob container, you will need to run script/prepdocs.py on those PDFs somehow. One option is to amend that script to connect to the blob container, download each PDF and process it. I think you could also use an indexer if it indexes them with the same fields, but I haven't used an indexer personally. See Pablo's comment on indexers here: https://github.com/Azure-Samples/azure-search-openai-demo/issues/64

**Comment by mehrdad-zade** [comment]
I can run prepdocs on new set of pdf documents and upload them to a new container. 

my question is, how to point the /chat endpoint to interact with the data in the newly created blob container?

**Comment by pamelafox** [comment]
See app.py for how everything is configured:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/eb087331441dfb5fce8cf5b3ecc8a371707f676f/app/backend/app.py#L17

AZURE_STORAGE_ACCOUNT = os.environ.get("AZURE_STORAGE_ACCOUNT") or "mystorageaccount"
AZURE_STORAGE_CONTAINER = os.environ.get("AZURE_STORAGE_CONTAINER") or "content"
AZURE_SEARCH_SERVICE = os.environ.get("AZURE_SEARCH_SERVICE") or "gptkb"
AZURE_SEARCH_INDEX = os.environ.get("AZURE_SEARCH_INDEX") or "gptkbindex"


If you change the storage account or container, you'll want to change those first two environment variables. If you change the search service or index name, you'll want to change the second two environment variables.

For example, you can run:

```
azd env set AZURE_STORAGE_ACCOUNT other-account-name
```

And then re-run azd up.

**Comment by mehrdad-zade** [comment]
thanks this worked. now I can upload different sets of docs under different index and container, and also have the chat session to run against the chosen container/index.
