### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by svijayak1981** [Azure-Samples/azure-search-openai-demo#449]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>azd auth login
azd init -t azure-search-openai-demo
zd env set AZURE_OPENAI_SERVICE {Name of existing OpenAI service}
azd env set AZURE_OPENAI_RESOURCE_GROUP {Name of existing resource group}
azd env set AZURE_OPENAI_GPT_DEPLOYMENT {Name of existing GPT deployment}
azd up

### Any log messages given by the failure
>|=====  | Packaging service backend/root/powercor/app/frontend/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^
SyntaxError: Unexpected token '?'

### Expected/desired behavior
>

### OS and Version?
> Ubuntu 22.04.2 LTS - container (docker image)

### azd version?
> azd version 1.1.0

### Versions
>

### Mention any other details that might be useful
ERROR: failed packaging service 'backend': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '1', Path: '/tmp/azd-prepackage-429392400.sh'. : exit code: 1
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That error indicates that your Javascript engine does not understand "??", also known as the "nullish coalescing operator":
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

Please check your Node version and update it if needed. You can also open this repo up in either GitHub Codespaces or a local VS Code Dev Container, and it will have Node setup correctly for you. Node 14+ supports that ?? operator, but it'd be safer to use Node 16+.

**Comment by pamelafox** [comment]
Closing this now that we've specified the minimum Node version. Please re-open if that change didn't fix the issue.
