### ISSUE TITLE
How to upload our own content and start query against our docs

### ISSUE THREAD

**Issue by lotuskannan2007** [Azure-Samples/azure-search-openai-demo#45]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by macalb69** [comment]
you can put your documents in the .\data folder and launch again the .\prepdocs.ps1 script which process all the new documents, chunks and index them and upload to the blob storage.

**Comment by sissimonster** [comment]
> 

i found out that the blob can be update after changing to my own doc and run .\prepdocs.ps1 script  but the search index remain the same, so when i ask question they will continue show demo doc

**Comment by george-moore** [comment]
I had the exact same issue.  I was able to get around it by starting fresh: delete my local directory and all of my cloud deployments.  1) Run azd init to download the current repo to my local directory.  2) go into the ./data directory, delete all of the existing docs, and copy your own.  3) run azd up to continue with the fresh deployment.  

This will rebuild your search index with your new content and deploy the new index along with all of the other components.

Later, you can then modify the landing page UX to include your custom new example queries under .\app\frontend\src\pages

**Comment by vhvb1989** [comment]
This PR: https://github.com/Azure-Samples/azure-search-openai-demo/pull/35 would allow to add files directly from the web.  You can also try it out.

**Comment by sissimonster** [comment]
> This PR: #35 would allow to add files directly from the web. You can also try it out.

Thanks! have you pull #35 into any branch?

**Comment by dev-pawel** [comment]
while adding a new pdf, running prepdocs.ps1 works for me . How about removing some pdfs? Not only from the blob storage but also from the index etc. Any idea?

**Comment by pamelafox** [comment]
We've documented the data ingestion process here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md

I'll leave this issue open as a request to upload documents from the UI, though I'm not sure that was the original question.

**Comment by pamelafox** [comment]
Closing this issue. If you're interested in user document upload, follow: https://github.com/Azure-Samples/azure-search-openai-demo/issues/1393
