### ISSUE TITLE
azure-search-documents incomplete?

### ISSUE THREAD

**Issue by johnltr** [Azure-Samples/azure-search-openai-demo#450]
Hi,
I am importing the whole project, including azure-search-documents version 11.4.0b6.
But the creating keeps failing: 

  File "C:\*********\prepdocs.py", line 16, in <module>
    from azure.search.documents.indexes.models import SearchIndex, ScoringProfile, CorsOptions, CorsPolicy, \
ImportError: cannot import name 'CorsPolicy' from 'azure.search.documents.indexes.models' (C:\*********\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\models\__init__.py)

If I leave out CorsPolicy, it will fail on others as well:
- FilterableField
- AnalyzeRequest
- AnalyseResult
- KnownTokenFilterName
- IndexDocumentsBatch
- SearchIndexerSchedule
- SearchIndexerDataChangeDetectionPolicy
- SearchIndexerDataDeletionDetectionPolicy

Anyone else experiencing the same?

**Comment by pamelafox** [comment]
Hm, interesting. I haven't experienced the issue, but I wonder if it's related to the use of "import *" in prepdocs.py. Can you try the change I propose in this pull request and see if you still get the error? https://github.com/Azure-Samples/azure-search-openai-demo/pull/452

I think if nothing else, it should at least be a different error.

**Comment by pamelafox** [comment]
I've merged the change to use explicit imports, so I'm going to close this issue. Please comment if that change doesn't fix your issue.
