### ISSUE TITLE
The index 'gptkbindex' for service 'gptkb-qiburks2p7ctm' was not found.

### ISSUE THREAD

**Issue by mansikhalasi** [Azure-Samples/azure-search-openai-demo#465]
Actually I'm getting below error.

azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

Can anyone please help me.?

**Comment by pamelafox** [comment]
There may be an issue with SSL on your device, can you try the suggestions here? https://stackoverflow.com/a/43855394/1347623
Those have worked for me for similar errors.

**Comment by mansikhalasi** [comment]
> There may be an issue with SSL on your device, can you try the suggestions here? https://stackoverflow.com/a/43855394/1347623 Those have worked for me for similar errors.

It's resolved.

**Comment by pamelafox** [comment]
Are you seeing that error when running prepdocs.py or running the app? Can you confirm that prepdocs.py ran successfully for you? That's what makes the embeddings.

**Comment by pamelafox** [comment]
Hm, I thought you said that error was resolved, in your earlier comment? If you're seeing SSL cert issues, please try the solutions at https://stackoverflow.com/a/43855394/1347623

Prepdocs.py must succeed for the app to be able to work, since it needs a search index to query.

**Comment by Michael-luk02** [comment]
I got the below error when i running prepdocs.py.
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: Cannot find nested property 'embedding' on the resource type 'search.documentFields'.
Code:
Message: The request is invalid. Details: Cannot find nested property 'embedding' on the resource type 'search.documentFields'.

**Comment by pamelafox** [comment]
Did you previously create the index before we added the vector fields option? If so, you'd need to delete the index and have prepdocs.py create a new index.
