### ISSUE TITLE
How do I upload new PDF files?

### ISSUE THREAD

**Issue by RajaCodeArchitect** [Azure-Samples/azure-search-openai-demo#466]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please see FAQ that answers that: https://github.com/Azure-Samples/azure-search-openai-demo#faq

**Comment by RajaCodeArchitect** [comment]
> Please see FAQ that answers that: https://github.com/Azure-Samples/azure-search-openai-demo#faq

Hi Pamelafox
 I would like to contribute the code for upload pdf files from browser, please check the below video
 
 https://www.loom.com/share/cd4907b29a1c4f41a1012dbc77bbe21b?t=120&sid=40ecf5c5-0a7e-4e56-b6aa-eadf3be32efe
