### ISSUE TITLE
Feature request: Upload pdf files from browser

### ISSUE THREAD

**Issue by RajaCodeArchitect** [Azure-Samples/azure-search-openai-demo#468]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
You can see this PR for an example of how someone else added an upload page:

https://github.com/Azure-Samples/azure-search-openai-demo/pull/35

We haven't had time to review it yet as it's a large PR, but it may be helpful for you.

**Comment by pamelafox** [comment]
@RajaCodeArchitect I see your comment on https://github.com/Azure-Samples/azure-search-openai-demo/issues/466#issuecomment-1653662499 indicates you already have code for this. If so, I suggest comparing it to the existing PR and seeing how your solution differs. Feel free to open up a new PR if you think yours is better/different in a useful way. Even if we don't have time to review every PR now, they're very helpful for others to see.
