### ISSUE TITLE
Print response one word at a time

### ISSUE THREAD

**Issue by aegismarek** [Azure-Samples/azure-search-openai-demo#472]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Desired behavior

Users are impatient and want instant feedback from the app. ChatGPT offers this by returning the answer word by word as if the AI is 'typing the answer'. What would it take to introduce this feature in this Azure augmented retrieval app with Azure's OpenAI deployment?

**Comment by pamelafox** [comment]
It should be possible, as I have implemented streaming for https://github.com/pamelafox/chatgpt-quickstart and streaming is also available in https://github.com/Microsoft/sample-app-aoai-chatGPT/

I recommend checking out https://github.com/Microsoft/sample-app-aoai-chatGPT/ to see if that sample will work for you. It also performs Cognitive Search on your data, but it does so using built-in functionality to the ChatGPT API.

**Comment by pamelafox** [comment]
I have drafted a PR that adds streaming, see my comment in #421 
I'm going to close this issue in favor of the earlier issue so that we can keep discussion in one place. Thanks!
