### ISSUE TITLE
Error: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by ikka86** [Azure-Samples/azure-search-openai-demo#473]
openai   0.27.8
Python 3.10.11
The version should be correct, but I get an error.

Traceback (most recent call last):
  File "C:\works\azure-search-openai-demo\app\backend\app.py", line 123, in chat
    r = impl.run(request.json["history"], request.json.get("overrides") or {})
  File "C:\works\azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 68, in run
    chat_completion = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

Is the following part of app.py correct in the following way?

  Used by the OpenAI SDK
openai.api_type = "azure"
openai.api_base = f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com"
openai.api_version = "2023-05-15"

  Comment these two lines out if using keys, set your API key in the OPENAI_API_KEY environment variable instead
openai.api_type = "azure_ad"
openai_token = azure_credential.get_token("https://cognitiveservices.azure.com/.default")

"C:\Users\AppData\Local\Programs\Python\Python310\Lib\site-packages\openai\__init__.py"
The installed openai has chatcompletion.

from openai.api_resources import (
    Audio,
    ChatCompletion,
    Completion,
    Customer,
    Deployment,
    Edit,
    Embedding,
    Engine,
    ErrorObject,
    File,
    FineTune,
    Image,
    Model,
    Moderation,
)

**Comment by pamelafox** [comment]
Is it possible you overwrote the openai module with your own variable named openai? You could debug by printing out the value of openai or its contents, like

print(openai)
print(dir(openai))

And also check to make sure you have no local filenames or variables called openai.

**Comment by pamelafox** [comment]
Closing since I don't believe there's an issue with our code.
