### ISSUE TITLE
Additional file type support

### ISSUE THREAD

**Issue by davidwboyd** [Azure-Samples/azure-search-openai-demo#479]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Currently office documents (word, excel, powerpoint) can not be processed.

### Any log messages given by the failure
>

### Expected/desired behavior
Apache Tika easily handles all these document types and many others.   A new version of this utility, which spins up an Apache
Tika service with the built in OCR as a container would be helpful.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Closing this as a duplicate of https://github.com/Azure-Samples/azure-search-openai-demo/issues/181
Thanks for the suggestion re Apache Tika. Feel free to add comments to that issue, thanks!
