### ISSUE TITLE
Running locally - Can not see any changes until run script again

### ISSUE THREAD

**Issue by leksaas** [Azure-Samples/azure-search-openai-demo#490]
When I run solution locally, and do some changes, only way to see the changes is to run the script again. Isn't enough to just save for example some css file and see the changes on local server. Does anyone know how to escape from that? How to easily test changes without running script after each change?

**Comment by pamelafox** [comment]
Good question! We currently have it setup so that the Flask code auto-reloads, but not so that the JS/CSS gets auto-rebuilt. Here's one way to do it:

From app, run start.sh like normal

Once the Flask app is running, start a new terminal, navigate to app/frontend, and run 'npm run watch' 

That seems to update the UI for me after changes.

**Comment by pacific202** [comment]
Could we please add some basic developer documentation to the repo?

- How to configure the app to run locally (as you have answered above)
- How to use source control (github and Azure DevOps)
- How to add new React components (without breaking something else)
- How to add new Approaches (without breaking something else)

**Comment by pacific202** [comment]
I'd like to recommend starting a second page just for Developer details as the one page is starting to get a little long. Happy to set up the PR and get it started once I have a little direction/guidance.

**Comment by miggytrinidad** [comment]
@l

> Good question! We currently have it setup so that the Flask code auto-reloads, but not so that the JS/CSS gets auto-rebuilt. Here's one way to do it:
> 
> From app, run start.sh like normal
> 
> Once the Flask app is running, start a new terminal, navigate to app/frontend, and run 'npm run watch'
> 
> That seems to update the UI for me after changes.

@pamelafox, how about npm run dev? npm run watch for me updates the UI but it build it every time which makes no sense I think(like npm run build)

**Comment by pamelafox** [comment]
Hm, `npm run dev` doesn't seem to be working well right now. Unfortunately, I'm not a vite expert, so I'm going to pair with a colleague next week to come up with the best approach for this repo.

**Comment by pamelafox** [comment]
@pacific202 Thanks for the offer! It's true that it's getting long. The drawback of a secondary page is that people tend not to read them, but it would be nice to get into more details. How about on README.MD, below "Using the app"

### Customizing the app

Learn how to upload your own data, change the UI, tweak the prompts, and more, in our [Developer Guide](DeveloperGuide.md)

And then in DeveloperGuide.md:

## Local development


## Customizing the UI

## Customizing the Prompt

## Replacing the Data


## Running the tests


etc.

I can fill in stuff as well, so whatever you'd like to start off with is welcome.

**Comment by miggytrinidad** [comment]
@pamelafox, any update on the vite issue?

**Comment by pamelafox** [comment]
@miggytrinidad I worked on it today with a colleague, we'll be merging changes soon. The main change you need is to the proxy in vite.config.ts, to proxy all the routes:

https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...pamelafox:azure-search-openai-demo:launchjson?expand=1#diff-51dd08bd8f042256a1f797877561abf304705d65129e3f79488d9c94e0bde44d

Once you have that change, you can run `npm run dev` in one terminal and start.sh in the other, and that will load in the latest versions of files. 

My colleague is working on other improvements as well to launch.json, but I think you were looking mainly to get `npm run dev` working in the terminal.

**Comment by z6dbc** [comment]
What happened to this? I cannot find "launchjson" branch mentioned by @pamelafox in last [comment](https://github.com/Azure-Samples/azure-search-openai-demo/issues/490#issuecomment-1758706290)

**Comment by DevScherer** [comment]
If I run start.sh in /app and open a new terminal in /frontend and execute` npm run dev` I get an error: 

[vite] http proxy error at /auth_setup:
Error: connect ECONNREFUSED ::1:50505
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1283:16) (x2)
    
 Is it CORS permitting the access? I'll have a look into it now..

**Comment by pamelafox** [comment]
I've made a fix in the latest PR and added docs:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1148

It should work with the change to the proxy there (vite.config.ts).

**Comment by pamelafox** [comment]
We now have a compound debug configuration in launch.json and documentation about hot reloading, so I'm closing this.
