### ISSUE TITLE
ERROR TO RUN AZD UP

### ISSUE THREAD

**Issue by phfontes** [Azure-Samples/azure-search-openai-demo#494]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>azd up

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### azd version?
> run `azd version` and copy paste here.
1.1.0

### Versions
>

### Mention any other details that might be useful
Hello
I need help running azd up.
I have already installed all the requirements as described in the readme, however, according to the attached screen, it presents some error about python, it seems not to have found the path.
I don't have much experience, I would like some help :)
![erro](https://github.com/Azure-Samples/azure-search-openai-demo/assets/132704972/083cb292-f900-4268-9ddb-b584b653761e)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vhvb1989** [comment]
Looks like `python` is not found on your system.
How/fromWhere did you install python?
