### ISSUE TITLE
OpenAI East Canada deployment fails to find OpenAI resource as endpoint is different than other regions 

### ISSUE THREAD

**Issue by Pratheek-Dev** [Azure-Samples/azure-search-openai-demo#497]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>azd up

### Any log messages given by the failure
>openai.error.InvalidRequestError: Resource not found
>Error: Subdomain does not map to a resource.

### Expected/desired behavior
> Response from chatcompletion endpoint 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

### Mention any other details that might be useful

> Canada East endpoint is 'https://canadaeast.api.cognitive.microsoft.com', instead of the 'https://{AZURE_OPENAI_SERVICE}.openai.azure.com', despite trying different endpoint variations, the API calls with ChatCompletion fails to find the resource. How do we correctly reference our OpenAI resource in the Canada East endpoint? 
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@Pratheek-Dev I just created a Canada-East OpenAI resource, and it shows the endpoint as following the current template:

![Screenshot 2023-08-03 at 1 35 46 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/10f09f29-d494-4a33-8611-458458bde7ef)

Does your Portal show something different? What does the code in OpenAI studio show as your endpoint?

**Comment by Pratheek-Dev** [comment]
Hi @pamelafox, thanks for the reply. I get the generic endpoint in both the Azure Portal and OpenAI Studio UI - 
<img width="341" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22062532/e439063a-8d42-49b7-8c03-a23e5f8b4266">

**Comment by pamelafox** [comment]
@Pratheek-Dev Is this for GPT 3.5 or GPT 4?

**Comment by Pratheek-Dev** [comment]
@pamelafox This is for GPT3.5 -4k context, we don't have GPT4 approved yet unfortunately

**Comment by pamelafox** [comment]
Thanks, I'm looking into this. I don't honestly know why there are different endpoints, but you're not the first to experience this endpoint discrepancy. In the meantime, you can change app.py to point at the correct endpoint for your model.

https://github.com/Azure-Samples/azure-search-openai-demo/blob/df48d8c23b4d0ae0ec6487cecd715a9db2943f64/app/backend/app.py#L139

**Comment by Pratheek-Dev** [comment]
Hi @pamelafox I tried different combinations of api_base, but I that results in "Subdomain does not map to a resource." error.

This is the combination I used:
`openai.api_type = "azure"
openai.api_base = "https://canadaeast.api.cognitive.microsoft.com/"  #f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com"
openai.api_version = "2023-03-15-preview"`

**Comment by pamelafox** [comment]
@Pratheek-Dev Sorry, just following up on this, did you find an endpoint URI that works? What does it show in your OpenAI studio, in the generated code tab on the right side of the playground?

**Comment by pamelafox** [comment]
I suspect I've figured out the issue since this was first posted. Our infrastructure sets the OpenAI subdomain name:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/core/ai/cognitiveservices.bicep
