### ISSUE TITLE
Updating Index in Azure Cognitive search

### ISSUE THREAD

**Issue by luhgit** [Azure-Samples/azure-search-openai-demo#499]
I was wondering if we can update index/knowledge base? I have a customer scenario where customer has setup testing of chatbot in a couple of phases. In each phase a different number of pdf files are indexed into the knowledge base (Azure Cognitive Search). I could not find any option to do that! 
I tried to delete previously indexed files and put new set of files under `/data` and ran `azd deploy` but nothing changed. 
Going forward I will delete the index and run `azd up` to see if it creates a new index. 
But I was wondering if we have a feature which allows us to deal with data management in an easier way?

**Comment by pamelafox** [comment]
Please read the FAQ question about this and let us know if you have further questions:

https://github.com/Azure-Samples/azure-search-openai-demo#faq
