### ISSUE TITLE
webpage is not responsive for different screen types

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#50]
> Web Page is not compatible with different screen types, guess we should use ```react-responsive``` to make it compatible on different screen sizes

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
It is now responsive, as of the latest release:
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-07-10

Additional improvements are being discussed here:

https://github.com/Azure-Samples/azure-search-openai-demo/issues/1458
