### ISSUE TITLE
Azure OAI Outage

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#505]
Azure OAI Outage in EAST-US effecting emedding models

FYI

Your support case @####$#%$^#&%&$&&$ is related to an ongoing outage in your region.

STATUS: In-Progress 8/8/2023 4:43:29 AM UTC

SUMMARY OF IMPACT: You may experience sporadic issues accessing your resources. This could cause you to experience a 5xx error when calling Davinci model or Ada embedding model in EastUS region.

NEXT STEPS: Azure OpenAI feature team are urgently investigating the root cause and coming up with a plan to resolve as soon as possible. We'll send an update once we know more.

**Comment by pamelafox** [comment]
Thanks for noting this when it happened, closing now since they resolved the outage.
