### ISSUE TITLE
Force chatgpt to only retrieve answer on the enterprise data

### ISSUE THREAD

**Issue by Xoriant-HarshalKulkarni** [Azure-Samples/azure-search-openai-demo#51]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Hi, I am currently working on a use case with regards to some Enterprise data. Can it be made possible to tweak the pipeline so that it only retrieves answer from the data which I provide? What I have seen so far is that the model is giving answer on with respect to the context of the data which I have provided (Eg. Contract docs) as well as anything from the outside world (For eg. What is the height of the Eiffel Tower?). Can we do something to stop this behaviour and restrict any queries from the outside world? Thank you !
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gonzalorecio** [comment]
Maybe the easiest way is to change the `prompt_prefix` variable in file `app/backend/approaches/chatreadretrieveread.py`  to add more system instructions and explicitly tell ChatGPT that "in case the user provides a question that is outside the context of our company, answer 'this question is out of my scope'.". This is a short example, but you can expand this message to be more consistent to force ChatGPT's behaviour to act as you wish.

**Comment by pablocastro** [comment]
Different scenarios require different areas of focus for the prompt and grounding logic, while this sample needs to stay somewhat generic. I suggest following @gonzalorecio's suggestion of adjusting the prompt with instructions to only answer from the sources and only on the topics you want it to talk about. That should help but it won't necessarily be perfect, another thing you can do to further improve this is reject answers that don't have a source citation.
