### ISSUE TITLE
it is not loading the file

### ISSUE THREAD

**Issue by edercarlima** [Azure-Samples/azure-search-openai-demo#510]
### This issue is for a: (mark with an `x`)
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
I ran the scripts to deploy the application to the test signature. After deploying, when running the application, I uploaded a file. However, when clicking "Submit", the file upload is not taking place. There are no error messages during upload. I would like to know if it is necessary to adjust some parameter after deployment to allow the upload.
Upon reviewing the code, it appears that in order to perform the upload, the file needs to be saved locally so it can be split into pages and then pushed to the blob. The relevant snippet is in the "app.py" file, at line 79, where the file is saved in a local directory.  
At line 160, the file is saved in a local directory. (filesave)
My question is the following: when deploying, is there any configuration that needs to be changed to ensure that the file is saved locally and later divided into pages for upload to the blob?

### Any log messages given by the failure
Not messages

### Expected/desired behavior
Not upload file

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 Pro

### azd version?
> run `azd version` and copy paste here.
azd version 1.0.2

**Comment by pamelafox** [comment]
I'm confused by your description of a "Submit" button and file upload. This repository does not have a file upload UI, it only has a script (prepdocs.py). Can you confirm what you mean by that Submit?

**Comment by edercarlima** [comment]
Sorry, I'll send more details.

On GitHub, through the link: https://github.com/Azure-Samples/azure-search-openai-demo/pull/478, I identified that there is a repository that contains code with the functionality to upload files. I download the code through the link https://github.com/RajaCodeArchitect/azure-search-openai-demo/tree/uploadFileFromBrowser. When performing the deploy in my test environment, the previously sent questions arose.

From what I understand from your answer, the version available at https://github.com/Azure-Samples/azure-search-openai-demo/ does not contain this file upload functionality, correct?
In that case, should my doubts be clarified with Rajashekhar?

Note:  Close the issue https://github.com/microsoft/sample-app-aoai-chatGPT/issues/145 wrongly opened

**Comment by pamelafox** [comment]
Ah, I see. I'd suggest leaving comments on the PR in that case, since it can help @RajaCodeArchitect improve the PR.

**Comment by edercarlima** [comment]
Thank you @pamelafox.
I await the feedback from @RajaCodeArchitect about the respondents.

**Comment by pamelafox** [comment]
Closing the issue as it was discussed on the PR. Thanks Raja for the help!
