### ISSUE TITLE
Make default retrieval mode as 'vectors'

### ISSUE THREAD

**Issue by en-coded** [Azure-Samples/azure-search-openai-demo#527]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Update search mode to only "vectors"

### Any log messages given by the failure
>

### Expected/desired behavior
> We are leveraging vector embeddings on the gptkbindex and want to make it as default retrieval model for the frontend application.

**### Here is our current set up:**
1. We are generating vector embeddings using the following parameters - # OpenAI embedding parameters
embedding_model = "text-embedding-ada-002"
embedding_encoding = "cl100k_base"
max_tokens = 8000
2. The embeddings are successfully saved on the gptkbindex index.
3. We have multiple datasources like Cosmos, PDFs and SQL that update gptkbindex.
4. The frontend application is fully customized and we are not providing users the option to make changes to the developer settings.

**### Here are a few questions:**
1. How can we make 'vectors' as the default retrieval mode? If I understand correctly, the current retrieval mode is set to text or vectors + hybrid. 
2. We are using scoring profiles to rank the fields in gptkbindex as we have added custom fields to gptkbindex. Is it recommend that we set weight to the 'embeddings' field to a higher weight than the field 'content' in the scoring profile?
3. Is this where I can update the retrieval modes? 
async def retrieve(self, query_text: str, overrides: dict[str, Any]) -> Any:
        has_text = overrides.get("retrieval_mode") in ["text", "hybrid", None]
        has_vector = overrides.get("retrieval_mode") in ["vectors", "hybrid", None] 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
1.1.0
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Yes, you can set `has_text = False` and `has_vector = True`, if you want to do vectors-only searches.

**Comment by en-coded** [comment]
Thank you @pamelafox!
