### ISSUE TITLE
Deployment error QuotaID/Feature

### ISSUE THREAD

**Issue by MartyHlay** [Azure-Samples/azure-search-openai-demo#53]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Created new folder
Powershell:
Initialized project
Ran azd up
### Any log messages given by the failure
>Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'a2018f19-5034-4e58-a5a5-0ac5655187f0'. See inner errors for details.
SpecialFeatureOrQuotaIdRequired: The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' .

Checked deployment in Azure:
openai status = BadRequest
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '5eec9f89-50fc-442d-9400-37c7a022f82b'. See inner errors for details.",
        "details": [
            {
                "code": "SpecialFeatureOrQuotaIdRequired",
                "message": "The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' ."
            }
        ]
    }
}

### Expected/desired behavior
>Create deployment in Azure

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 pro
### Versions
>10

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by CesarCalvoCobo** [comment]
Same error here , thanks !

**Comment by vhvb1989** [comment]
did you guys requested OpenAI for your subscription? See: https://github.com/Azure-Samples/azure-search-openai-demo#getting-started

**Comment by CesarCalvoCobo** [comment]
Yes , I have already some model deployments there

**Comment by MartyHlay** [comment]
I did request it but I believe one of our other developers did as well. I am able to create openai service from within Azure. But it fails when using power shell.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pablocastro** [comment]
A few reasons for this error:
1. If your subscription wasn't yet approved for OpenAI. Note that approvals are per-subscription, so if you're user account has multiple subscriptions associated with it, you'll want to make sure you're using the one that was approved.
2. If you're deploying in a region that doesn't have the gpt-35-turbo model yet. Right now you can only deploy in South Central US or East US.
3. If you have 2 Azure OpenAI instances in that subscription in that region.

Any chance one of those match your setup?

**Comment by SeaDude** [comment]
I'm having a similar error:

ERROR: deployment failed: error deploying infrastructure: failed deploying to subscription. 

Deployment Error Details:
InvalidTemokateDeployment: The template 'openais' is not valid according to the validation procedure. The tracking id is <guid>. See inner error for details. 
InsufficientQuota: Insufficiant quota. Cannot create/update/move resource 'cog-<guid>'. 

This was encountered when trying to tear down my OpenAI Search Example and rebuild it for reproducibility.

**Comment by SeaDude** [comment]
Believe or not, for my issue above, I had to open an Incognito Chrome browser tab, then open Portal and delete the Resource Group. 

I was then able to delete without issue. 

Read about a similar issue on StackOverflow and tried it!

**Comment by CesarCalvoCobo** [comment]
> A few reasons for this error:
> 
> 1. If your subscription wasn't yet approved for OpenAI. Note that approvals are per-subscription, so if you're user account has multiple subscriptions associated with it, you'll want to make sure you're using the one that was approved.
> 2. If you're deploying in a region that doesn't have the gpt-35-turbo model yet. Right now you can only deploy in South Central US or East US.
> 3. If you have 2 Azure OpenAI instances in that subscription in that region.
> 
> Any chance one of those match your setup?

Thanks for the answer @pablocastro  . In my case, it seems that the reason was the third one. There were already 2 Azure Open AI  instances in this subscription, I deleted one and it´s deploying now correctly . Is there a way to deploy with more than 2 instances? It´s this a limitation of this demo, or it´s a general one ? Thanks again in advance

**Comment by pablocastro** [comment]
Great to hear it worked, @CesarCalvoCobo. The limitation is not of the demo, it's the policy applied to Azure OpenAI resources.
