### ISSUE TITLE
No overlapping region for GPT-4, azure-search-openai-demo and Embeddings

### ISSUE THREAD

**Issue by en-coded** [Azure-Samples/azure-search-openai-demo#531]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy this application in model in (US) East US 2 (eastus2)
I am aware that this application only supports eastus and I am trying to figure out a way to deploy GPT-4.

### Any log messages given by the failure
> DeploymentModelNotSupported: The model Format: OpenAI, Name: text-embedding-ada-002, Version: 2, Source:  is not supported in current region.

We got approved for GPT-4 today. As per the email from Gating Support GPT-4 is available to new customers in these regions: 

• Australia East
• Canada East
• East US 2
• Japan East
• UK South

However, embeddings text-embedding-ada-002 are only supported in East US.

Has anyone successfully deployed this application with gpt-4-32k and text-embedding-ada-002? 

### Expected/desired behavior
>  text-embedding-ada-002 and gpt-4-32k should be supported in at least one common region.
Also, this document needs to be updated as gpt-4-32k is not supported in East US 
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I believe you can use canadaeast for both, I just deployed to that region. You'll need to make a change to the Bicep, as you can see in this PR:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/520/files


If you do end needing multiple OpenAI deployments, then you'll need to make a lot more changes to the Bicep and env variables, starting with creating two separate OpenAI resources:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/76bb57ac5f197c481832bff8b56f068d0cbb270d/infra/main.bicep#L130

But try canadaeast first.

**Comment by en-coded** [comment]
Hi @pamelafox - Thank you for the response!

I am still getting the following errors after updating to Canada East. I have incorporated the changes from https://github.com/Azure-Samples/azure-search-openai-demo/pull/520/files.

I tried to deploy with both gpt-4-32k and gpt-35-turbo. I have attached main.bicep file for your reference.

Here is the error. It looks like formrecognizer is not available in Canada East.

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'RANDOM'. See inner errors for details.
InvalidResourceProperties: The specified SKU 'Standard' of account deployment is not supported in this region 'canadaeast'.
SkuUnavailableInZone: The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone.
InvalidTemplateDeployment: The template deployment 'formrecognizer' is not valid according to the validation procedure. The tracking id is 'RANDOM'. See inner errors for details.
InvalidApiSetId: The account type 'FormRecognizer' is either invalid or unavailable in given region.

TraceID: RANDOM


[main.bicep.zip](https://github.com/Azure-Samples/azure-search-openai-demo/files/12327613/main.bicep.zip)

**Comment by pamelafox** [comment]
Ah, sorry, I should have been more specific: I used canadaeast for my openAI deployment but a different region (eastus2) for everything else. There are 2 prompts for location during azd up, I first set eastus2 and then canadaeast.
<img width="1172" alt="Screenshot 2023-08-12 at 12 37 37 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/14303dd1-9145-4567-9b29-b3c5da3b765a">

You can create a new env with `azd env new` or edit the existing one in .azure/env-name

**Comment by en-coded** [comment]
Hi @pamelafox - Thank you very much for your suggestions! I am able to deploy the application on GPT-4 with embeddings on the regions you recommended. 

Here are the steps I followed:

1. Initiated a new installation of the non-Azure OpenAI applications in East US 2 and Azure OpenAI application in Canada East.
2. Incorporated the changes on https://github.com/Azure-Samples/azure-search-openai-demo/pull/520/files
3. Updated main.bicep to replace gpt-35-turbo with gpt-4-32k

**Comment by en-coded** [comment]
Hi @waqasjavedkhan - I set the regions when deploying the application for the first time. You get two prompts when setting up the application. 

Please refer to the note from @pamelafox - https://github.com/Azure-Samples/azure-search-openai-demo/issues/531#issuecomment-1676071726
