### ISSUE TITLE
Getting error while creating OpenAI service from bicep file.

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#535]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>ERROR: {"code": "InvalidTemplate", "target": "/subscriptions/33809324-8f10-4006-b117-28422528a11b/resourceGroups/GEN_AI_DevOps/providers/Microsoft.Resources/deployments/openai", "message": "Deployment template validation failed: 'The template resource 'cog-xxxxoaidev/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '2286' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 1, "linePosition": 2286, "path": "properties.template.resources[1].type"}}]}
##[error]Script failed with exit code: 1

### Expected/desired behavior
>
OpenAI service should created successfully.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

I am getting below error while creating OpenAI service from my solution-
ERROR: {"code": "InvalidTemplate", "target": "/subscriptions/33809324-8f10-4006-b117-28422528a11b/resourceGroups/GEN_AI_DevOps/providers/Microsoft.Resources/deployments/openai", "message": "Deployment template validation failed: 'The template resource 'cog-xxxxoaidev/' for type 'Microsoft.CognitiveServices/accounts/deployments' at line '1' and column '2286' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 1, "linePosition": 2286, "path": "properties.template.resources[1].type"}}]}
##[error]Script failed with exit code: 1

Here is my main.bicep file content-

module openAi 'core/ai/cognitiveservices.bicep' = if (deployOpenAIResource) {
  name: 'openai'
  scope: openAiResourceGroup
  params: {
    name: !empty(openAiServiceName) ? openAiServiceName : '${abbrs.cognitiveServicesAccounts}${resourceToken}'
    location: openAiResourceGroupLocation
    tags: tags
    sku: {
      name: openAiSkuName
    }
    kind: 'OpenAI'
    deployments: [
      {
        name: gptDeploymentName
        model: {
          format: 'OpenAI'
          name: gptModelName
          version: gptModelVersion
        }
        sku: {
          name: 'Standard'
          capacity: gptDeploymentCapacity
        }
        raiPolicyName: raiPolicyName
      }
      {
        name: chatGptDeploymentName
        model: {
          format: 'OpenAI'
          name: chatGptModelName
          version: gptModelVersion
        }
        sku: {
          name: 'Standard'
          capacity: chatGptDeploymentCapacity
        }
        raiPolicyName: raiPolicyName
      }
      {
        name: embeddingDeploymentName
        model: {
          format: 'OpenAI'
          name: embeddingModelName
          version: '2'
        }
        capacity: embeddingDeploymentCapacity
        raiPolicyName: raiPolicyName
      }
    ]
  }
}
Here is my  cognitiveservices.bicep file content-
param name string
param location string = resourceGroup().location
param tags object = {}

param customSubDomainName string = name
param deployments array = []
param kind string = 'OpenAI'
param publicNetworkAccess string = 'Enabled'
param sku object = {
  name: 'S0'
}

resource account 'Microsoft.CognitiveServices/accounts@2023-05-01' = {
  name: name
  location: location
  tags: tags
  kind: kind
  properties: {
    customSubDomainName: customSubDomainName
    publicNetworkAccess: publicNetworkAccess
  }
  sku: sku
}

@batchSize(1)
resource deployment 'Microsoft.CognitiveServices/accounts/deployments@2023-05-01' = [for deployment in deployments: {
  parent: account
  name: deployment.name
  properties: {
    model: deployment.model
    raiPolicyName: contains(deployment, 'raiPolicyName') ? deployment.raiPolicyName : null
  }

  sku: contains(deployment, 'sku') ? deployment.sku : {
    name: 'Standard'
    capacity: 20
  }
  
}]

output endpoint string = account.properties.endpoint
output id string = account.id
output name string = account.name

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hi @namratam30, have you changed anything from our main.bicep? That error generally means that a parameter is set to an empty string. It sounds like either gptDeploymentName, chatGptDeploymentName, or embeddingDeploymentName is an empty string right now.
I recommend checking https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/main.parameters.json to see that they have default values there, and also checking .azure/YOUR-ENV-NAME/.env to see if any parameters have an empty string there.

**Comment by namratam30** [comment]
its resolved
