### ISSUE TITLE
Fail while deploying open-ai (GPT-4)

### ISSUE THREAD

**Issue by hello-lui** [Azure-Samples/azure-search-openai-demo#538]
After the resource group( rg-openaidatasearch ) is created normally, the following error occurs while deploying the open-ai service.
I ran the below command before azd up to reuse the gpt-4 service (name: ttt) which is currently under another resource group. .. plz help me!!!!

azd env set AZURE_OPENAI_SERVICE ttt
azd env set AZURE_OPENAI_RESOURCE_GROUP rg-openaidatasearch 

azd up
--------------------------------------------------------------------------------

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:

InvalidTemplate: Deployment template validation failed: 'The resource 'Microsoft.CognitiveServices/accounts/op-rpa-openai-je/deployments/gpt-4' at line '1' and column '1700' is defined multiple times in a template. Please see https://aka.ms/arm-syntax-resources for usage details.'.

**Comment by pamelafox** [comment]
It sounds like both your "gptDeploymentName" and "chatGptDeploymentName" are the same value, thus the error. You can actually remove gptDeployment entirely, as I do in: 
https://github.com/Azure-Samples/azure-search-openai-demo/pull/540
