### ISSUE TITLE
GPT does not respond to Korean documents.

### ISSUE THREAD

**Issue by hello-lui** [Azure-Samples/azure-search-openai-demo#543]
English documents are normal, but a message saying that the number of tokens is exceeded occurs for Korean documents.
All installations were completed normally, but when I inquire about Korean documents, only the following answers are repeated.

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/78183626/d935b9c5-4fe6-40ba-8cbc-0a26c68570a0)

The corresponding Korean document is also attached.
[CEOs_Digest_Weekly Report _ 2023.08.14 (n.314).pdf](https://github.com/Azure-Samples/azure-search-openai-demo/files/12378742/CEOs_Digest_Weekly.Report._.2023.08.14.n.314.pdf)

**Comment by pamelafox** [comment]
Thanks for the report, sounds like this may be a limitation in the package we use to estimate token counts (in messagebuilder/modelhelper). FYI @srbalakr

**Comment by srbalakr** [comment]
Ack, let me check.

**Comment by jasonchanhku** [comment]
Hi I notice that this is also the same case for Chinese characters. Is it the same bug?

**Comment by hello-lui** [comment]
> Hi I notice that this is also the same case for Chinese characters. Is it the same bug? Any updates on this?

@jasonchanhku 

I solved this problem. The cause was that the number of tokens occupied by Korean was nearly twice that of English, and it worked normally after distributing from gpt 3.5-turbo to gpt 3.5-turbo 16K.

**Comment by hello-lui** [comment]
@jasonchanhku

I solved this problem. The cause was that the number of tokens occupied by Korean was nearly twice that of English, and it worked normally after distributing from gpt 3.5-turbo to gpt 3.5-turbo 16K.

**Comment by pamelafox** [comment]
We've merged a proposed fix, please let us know if you experience this issue, and provide the exact input if so.
