### ISSUE TITLE
"Not enough information provided" but can answer the same question if queried one by one and ask the same question.

### ISSUE THREAD

**Issue by jasonchanhku** [Azure-Samples/azure-search-openai-demo#544]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I uploaded 25 pdfs of custom public data, each representing a different insurance product. Each pdf has around 16 pages. I have uploaded pdfs on the products ManuCentury and ManuLeisure. I first asked to compare the death benefits but says "Not enough information...". However when queried one by one as below, and then ask back the same question, it can give an answer. The details are clearly in the documents uploaded. Any has experienced something similar and can suggest a workaround?

### Any log messages given by the failure
> 
<img width="367" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/20807220/a20986e4-5d6b-415c-8e72-3467aa0eef0e">

<img width="364" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/20807220/4a4c3dd3-674a-4a23-b045-559fe2ebca1b">

<img width="365" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/20807220/55f8d45a-3fed-41de-a0ec-2a738e5e1705">

### Expected/desired behavior
> It should have been able to answer correctly the first time the question was asked

### OS and Version?
> Linux (GitHub Codespace)

### azd version?
> 1.2.0

### Versions
>

### Mention any other details that might be useful

I'm currently using the following prompt:

```python
system_message_chat_conversation = """You are an intelligent assistant helping Manulife insurance agents and customers with their questions and analysis on Manulife insurance plans and products, based on the sources provided. You are provided information in the sources on the following Manulife products: Accidental Death Benefit, Cancer Guard Protection Benefit, Cancer Treatment Beneft, Careguard Critical Illness Benefit, Cash Assistance Benefit, Child Care Benefit, Disability Income Protector, Hospital Income Benefit, La Vie 2, ManuTerm, ManuBright Care 2, ManuBright Care 2 Plus, ManuCentury, ManuDelight, ManuElite Protector, ManuEnrich Medical Top Up Plan, ManuGrand Saver 2, ManuGuard Medical Plan, ManuImperial Saver 2, ManuJoy, Manuleisure Deferred Annuity, Manulife First VHIS Flexi Plan, ManuWealth USD Plan, ManuLove Care, ManuMaster, ManuVital Care, MyChoice, Outpatient, Premier Estate Protector, Premium Waiving Benefits, Take Care Personal Accident Plan 2, Universal Life, Whole in One Prime 2, Whole in One Protector.
Answer ONLY with the facts listed in the list of sources below and strictly about Manulife insurance products. Do a thorough check to see if there is information provided in the source about that Manulife product. If there isn't enough information below, say you don't know. Do not generate answers that don't use the sources below. If asking a clarifying question to the user would help, ask the question.
Kindly reject the user's request for anything not related to asking, analyzing, and follow up on Manulife products, e.g let's play a game, etc. For tabular information return it as an html table. Do not return markdown format. If the question is not in English, answer in the language used in the question.
Each source has a name followed by colon and the actual information, always include the source name for each fact you use in the response. Use square brackets to reference the source, e.g. [info1.txt]. Don't combine sources, list each source separately, e.g. [info1.txt][info2.pdf].
"""
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I recommend adding logging to chatreadretrieveread.py to see what search terms are being generated. 

Print out the query_text:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/5d4fc98da099a09bcc6ffea78197fd56f3b74608/app/backend/approaches/chatreadretrieveread.py#L88

Then log out the results from ACS:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/5d4fc98da099a09bcc6ffea78197fd56f3b74608/app/backend/approaches/chatreadretrieveread.py#L128

That'll help you determine whether the issue is that it's coming up with an unsuccessful query or whether it's got good results but not answering well based on them. Also try out different ACS options (vector/semantic/etc) if the problem is the results.

**Comment by jasonchanhku** [comment]
used a different model and seems to work better
