### ISSUE TITLE
ERROR: deployment failed: failing invoking action 'provision'

### ISSUE THREAD

**Issue by mratanusarkar** [Azure-Samples/azure-search-openai-demo#547]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I tried it on both Az CLI inside [portal.azure.com](https://portal.azure.com/) as well as in my local system.
> both `azd up` from "Starting from scratch" and "Using existing resources" steps from [README](https://github.com/Azure-Samples/azure-search-openai-demo#installation) throws this error, and deployment fails.

### Any log messages given by the failure
> I am sharing both types of full stack trace that I had observed:
> 
> #### Log Stack 1:
> ```bash
> atanu [ ~ ]$ azd up
> 
> Packaging services (azd package)
> 
>   |       | Packaging service backendExecuting prepackage hook => /tmp/azd-prepackage-1395958083.sh
> 
> up to date, audited 115 packages in 645ms
> 
> 9 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
>   |====== | Packaging service backend
> > frontend@0.0.0 build
> > tsc && vite build
> 
>   |   ====| Packaging service backendvite v4.4.2 building for production...
> ✓ 1237 modules transformed.
> ../backend/static/index.html                           0.72 kB │ gzip:   0.38 kB
> ../backend/static/assets/github-fab00c2d.svg           0.96 kB │ gzip:   0.52 kB
> ../backend/static/assets/OneShot-daa12333.css          0.83 kB │ gzip:   0.39 kB
> ../backend/static/assets/index-49ee3353.css            6.55 kB │ gzip:   2.02 kB
> ../backend/static/assets/NoPage-77feaed1.js            0.29 kB │ gzip:   0.25 kB │ map:     0.41 kB
> ../backend/static/assets/fluentui-icons-b9d535f4.js    4.32 kB │ gzip:   2.01 kB │ map: 2,767.96 kB
> ../backend/static/assets/OneShot-2e72308c.js           7.92 kB │ gzip:   2.16 kB │ map:    20.20 kB
> ../backend/static/assets/index-b2b8058b.js            33.64 kB │ gzip:   7.55 kB │ map:    57.32 kB
> ../backend/static/assets/fluentui-react-f0f9677f.js  214.82 kB │ gzip:  62.44 kB │ map: 1,005.98 kB
> ../backend/static/assets/vendor-69a52085.js          751.19 kB │ gzip: 244.79 kB │ map: 3,613.16 kB
> 
> (!) Some chunks are larger than 500 kBs after minification. Consider:
> - Using dynamic import() to code-split the application
> - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
> - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
> ✓ built in 14.40s
>   (✓) Done: Packaging service backend
>   - Package Output: /tmp/azddeploy3219943768.zip
> 
> Provisioning Azure resources (azd provision)
> Provisioning Azure resources can take some time
> 
>   You can view detailed progress in the Azure Portal:
>   https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2Ffe12275e-abf8-45a8-9864-abd81109256a%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fopenai-demo-1691388953
> 
> 
> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
> 
> Deployment Error Details:
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'ff652c54-89fd-5414-b42e-3e3a51cae9d2' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/ff652c54-89fd-5414-b42e-3e3a51cae9d2'.'.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'f9b51d98-ac78-5be5-9b2e-f4ce79732aed' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/f9b51d98-ac78-5be5-9b2e-f4ce79732aed'.'.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '350252ab-5e40-5e2c-927e-2b15a7893bf4' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/350252ab-5e40-5e2c-927e-2b15a7893bf4'.'.
> SkuUnavailableInZone: The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '305e1ee8-d95d-54c7-8bbb-1f2a357337fe' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/305e1ee8-d95d-54c7-8bbb-1f2a357337fe'.'.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'cc0e9762-7af3-50b9-be07-ba92cbe8de62' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/cc0e9762-7af3-50b9-be07-ba92cbe8de62'.'.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '78ab4854-54f4-5c73-b5a6-a28f86a9a026' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/78ab4854-54f4-5c73-b5a6-a28f86a9a026'.'.
> InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '96f96b6f-82ba-58a9-9e77-a0a5861a1ab8' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-openai-demo/providers/Microsoft.Authorization/roleAssignments/96f96b6f-82ba-58a9-9e77-a0a5861a1ab8'.'.
> LocationNotAvailableForResourceType: The provided location 'southindia' is not available for resource type 'Microsoft.Search/searchServices'. List of available regions for the resource type is 'germanynorth,qatarcentral,polandcentral,swedencentral,ukwest,koreasouth,canadaeast,jioindiawest,westus3,germanywestcentral,norwayeast,switzerlandwest,switzerlandnorth,westus,westus2,eastus,eastus2,northeurope,westeurope,southeastasia,eastasia,northcentralus,southcentralus,centralus,japanwest,japaneast,koreacentral,australiaeast,australiasoutheast,brazilsouth,centralindia,westcentralus,canadacentral,uksouth,francecentral,southafricanorth,uaenorth'.
> LocationNotAvailableForResourceType: The provided location 'southindia' is not available for resource type 'Microsoft.CognitiveServices/accounts'. List of available regions for the resource type is 'global,australiaeast,brazilsouth,westus,westus2,westeurope,northeurope,southeastasia,eastasia,westcentralus,southcentralus,eastus,eastus2,canadacentral,japaneast,centralindia,uksouth,japanwest,koreacentral,francecentral,northcentralus,centralus,southafricanorth,uaenorth,swedencentral,switzerlandnorth,switzerlandwest,germanywestcentral,norwayeast,westus3,jioindiawest,qatarcentral,canadaeast'.
> 
> TraceID: 0dbe57fddf8e14fd626f03f6eb202726
> ```
>
> #### Log Stack 2:
> ```bash
> azd up
> 
> Packaging services (azd package)
> 
>   |       | Packaging service backendExecuting prepackage hook => C:\Users\tsa2cob\AppData\Local\Temp\azd-prepackage-1913210062.ps1
>   |=======| Packaging service backend
> up to date, audited 115 packages in 8s
> 
> 9 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
>   |     ==| Packaging service backend
> > frontend@0.0.0 build
> > tsc && vite build
> 
>   |      =| Packaging service backendvite v4.4.2 building for production...
> ✓ 1237 modules transformed.
> ../backend/static/index.html                           0.73 kB │ gzip:   0.38 kB
> ../backend/static/assets/github-fab00c2d.svg           0.96 kB │ gzip:   0.52 kB
> ../backend/static/assets/OneShot-0a57a895.css          0.83 kB │ gzip:   0.39 kB
> ../backend/static/assets/index-a703ca10.css            6.58 kB │ gzip:   2.03 kB
> ../backend/static/assets/NoPage-d0bd4518.js            0.18 kB │ gzip:   0.18 kB │ map:     0.36 kB
> ../backend/static/assets/fluentui-icons-df61cf1f.js    4.32 kB │ gzip:   2.01 kB │ map: 2,767.96 kB
> ../backend/static/assets/OneShot-43cf0699.js           4.89 kB │ gzip:   1.91 kB │ map:    19.25 kB
> ../backend/static/assets/index-e2fb1672.js            19.08 kB │ gzip:   6.49 kB │ map:    57.32 kB
> ../backend/static/assets/fluentui-react-d3a943c3.js  212.56 kB │ gzip:  61.51 kB │ map: 1,000.16 kB
> ../backend/static/assets/vendor-f4aa6f85.js          443.47 kB │ gzip: 151.43 kB │ map: 1,724.15 kB
> ✓ built in 16.05s
>   (✓) Done: Packaging service backend
>   - Package Output: C:\Users\tsa2cob\AppData\Local\Temp\azddeploy2552801785.zip
> 
> Provisioning Azure resources (azd provision)
> Provisioning Azure resources can take some time
> 
> ? Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter:  1. (Europe) West Europe (westeurope)
> ? Save the value in the environment for future use No
>   You can view detailed progress in the Azure Portal:
>   https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2Ffe12275e-abf8-45a8-9864-abd81109256a%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Foai-demo-dev-1692369939
> 
>   (✓) Done: Resource group: rg-oai-demo-dev
>   (✓) Done: Storage account: stv4zk54o7rhsye
>   (✓) Done: Search service: gptkb-v4zk54o7rhsye
>   (✓) Done: App Service plan: plan-v4zk54o7rhsye
>   (✓) Done: Form recognizer: cog-fr-v4zk54o7rhsye
> 
> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
> 
> Deployment Error Details:
> OperationError: Failed to Update the resource. Provisioning state: Failed
> ResourceProviderError: An error occurred while sending the request.
> 
> TraceID: 5e43686aab8d984127733cb6f955ee3c
> ```

### Expected/desired behavior
> The azure-search-openai-demo should be up and running, but in all my attempts, the deployment fails
> with `ERROR: deployment failed: failing invoking action 'provision'` and different kinds of error stack trace.
>
> - first case, I get Auth error, even though I have full contributor access to the subscription
> - second case, I get deployment failure.

### OS and Version?
> - Windows 10 Enterprise
> - Azure Cloud Shell --> Bash

### azd version?
> azd version 1.2.0

### Versions
> NA

### Mention any other details that might be useful
> NA

**Comment by pamelafox** [comment]
Hmm, that second error is unfortunately quite vague- it looks like it errored when provisioning either App Service or OpenAI. If you click through to the Portal deployment page, does it provide any more details on the error? From that page, you can log a support request, and the support folks can sometimes provide more context. Another thing to try is to run `azd up --debug` and see if the additional logs help pinpoint the issue.

**Comment by mratanusarkar** [comment]
@pamelafox sure, let me check and get back with more details.

**Comment by mratanusarkar** [comment]
@pamelafox I found one of my colleague at Germany succeeded with the settings:
- `Select an Azure location to use:` as `34. (Europe) West Europe (westeurope)`
- `Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter:` as `3. (Europe) France Central (francecentral)`

I attempted a fresh new deployment with a fresh new resource group and cloud space, under an active Az Subscription for which I have the 'Contributor' role. On running `azd up --debug` this time,
still no luck! Here is the error portion from the log stack trace:
```shell
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidResourceLocation: The resource 'cog-phlwt6piytcgo' already exists in location 'eastus' in resource group 'rg-atanu-dev'. A resource with the same name cannot be created in location 'francecentral'. Please select a new resource name.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '66c25f40-818e-5f48-bc90-77cccd95aedc' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/66c25f40-818e-5f48-bc90-77cccd95aedc'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '33a82b47-dcf3-57fd-855f-70c22db8e027' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/33a82b47-dcf3-57fd-855f-70c22db8e027'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'bd99a5e2-4185-5dc9-8ad2-78e293a1fca9' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/bd99a5e2-4185-5dc9-8ad2-78e293a1fca9'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '1b972820-439a-59e4-91d9-1debc112e11e' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/1b972820-439a-59e4-91d9-1debc112e11e'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'f4113f5e-a644-5d4c-988c-78bc576a4065' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/f4113f5e-a644-5d4c-988c-78bc576a4065'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource 'd5980b96-aec6-595f-83a0-6a61d619b05e' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/d5980b96-aec6-595f-83a0-6a61d619b05e'.'.
InvalidTemplateDeployment: The template deployment failed with error: 'Authorization failed for template resource '24ab7668-b23a-5b14-9b3e-51b31cb70a5c' of type 'Microsoft.Authorization/roleAssignments'. The client 'tsa2cob@bosch.com' with object id '8aa35960-f0ab-417d-95b8-31bc85ccf0d7' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/fe12275e-abf8-45a8-9864-abd81109256a/resourceGroups/rg-atanu-dev/providers/Microsoft.Authorization/roleAssignments/24ab7668-b23a-5b14-9b3e-51b31cb70a5c'.'.

TraceID: 00000000000000000000000000000000
2023/09/14 05:02:55 cloudshell.go:14: running in Cloud Shell
```

Could you help me out on why I keep getting "Authorization failed" or the above error, even though I have access?

**Comment by pamelafox** [comment]
Per the [readme](https://github.com/Azure-Samples/azure-search-openai-demo#azure-account-requirements), you need more than Contributor level access. Can you be given RBAC access to that subscription or even to just that resource group?

**Comment by mratanusarkar** [comment]
Hey @pamelafox 
Thanks a lot for all the support.
After getting owner access, and deploying az resources to the above-mentioned regions, the demo works for me inside the corporate framework!

Just one more thing,
Is it possible to work with data sources other than PDF?
I have mentioned the use cases in this issue: #633 

I believe #478 and #633 would be really helpful use cases for many, and looking forward to these features.
In the meantime, if you can help me with a way around for #633 it would be of great help.

Thanks!

**Comment by pamelafox** [comment]
Great, glad you were able to deploy! I'll close this issue as I've replied on the other one.
