### ISSUE TITLE
recent document retrieval issue and max content length

### ISSUE THREAD

**Issue by professorDante** [Azure-Samples/azure-search-openai-demo#568]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> ask for most recent documents with default settings (gives 3). Change the max document retrieval to 5 and ask again.

### Any log messages given by the failure
>

### Expected/desired behavior
>1. Asking same question twice should give same answer (timstamp question).
2. No Max token exceeded

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Mac OSX Monterrey
### azd version?
> run `azd version` and copy paste here.
1.1.0
### Versions
>

### Mention any other details that might be useful
1. Asking for most recent documents gives 3 (question snipped from screenshot) 
2. Changing the doc retrieval to 5 then ask again.
3. Documents are completely different to first answer.
4. Ask again
5. Now gives ' maximum content length exceeded'

![Screen Shot 2023-08-30 at 3 13 02 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/7493788/5e3ec4a3-8722-4df8-9735-bfc47bba02c8)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vprzybylo** [comment]
I'm also experiencing this issue:

Set doc retrieval to 3:
![issue](https://github.com/Azure-Samples/azure-search-openai-demo/assets/32338353/67cb1663-688e-4918-952b-c0f2c2d0f566)

Set doc retrieval to 5 and ask again and I get different files, only 4, and missing one of the docs that only came out when set to 3
![issue2](https://github.com/Azure-Samples/azure-search-openai-demo/assets/32338353/55616502-2271-47c3-ac9a-25577def1786)

Increasing to 6 gives: Error: This model's maximum context length is 4096 tokens. However, you requested 4301 tokens (3277 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.

**Comment by srbalakr** [comment]
This is a bug being tracked. Will fix in app code soon.

**Comment by ganesh25** [comment]
I also got this error, but for two reasons.

First reason: As already mentioned above, when I increase doc retrieval I get this error.

Second reason: I get the error when I keep using the chat session for some time. I assumed it was because of long answers to the questions I asked.

Is it possible to increase the token length so that I don't get it for long chat sessions? @srbalakr

**Comment by pamelafox** [comment]
The code uses the limits in https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/core/modelhelper.py to determine the max token length for your deployed model. If you are trying to have long sessions, you may need to upgrade to using gpt-45-turbo-16K or gpt-4-32K, since that'll increase your token count. As you can see from that code, gpt-35-turbo has a fairly low limit of 4K.

**Comment by ganesh25** [comment]
I upgraded the model to gpt-4 by changing chatGptModelName string in main.bicep file to gpt-4 and also explicitly changed the AZURE_OPENAI_CHATGPT_MODEL env variable to gpt-4, but I'm still getting the 4k limit error. Looks like gpt-4 is still not being used, how can I make sure that it's being used?

**Comment by pamelafox** [comment]
Hm. You could put a print or logging.info statement in the get_token_limit function:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/c01d292e7af0e79e4a56063f34d71e3dc8f32977/app/backend/core/modelhelper.py#L17

That would show you what model it thinks it's using.

**Comment by WhoIsDoctorWho** [comment]
Also stuck on this. I'm thinking about batching and combining results. @srbalakr are there any updates on this?

**Comment by pamelafox** [comment]
@WhoIsDoctorWho Sorry, what error are you specifically encountering?

**Comment by srbalakr** [comment]
@ganesh25 Could you verify if the backend has been successfully provisioned. Gpt 4 should help you with long chat sessions

**Comment by WhoIsDoctorWho** [comment]
@pamelafox the same issue with token limit: 
openai.error.InvalidRequestError: This model's maximum context length is 4096 tokens. However, your messages resulted in 5337 tokens. Please reduce the length of the messages.

I've increased documents count to 10 with gpt-35-turbo model then it fails. 
Is there any way to fix the issue with the gpt-35-turbo?

**Comment by pamelafox** [comment]
We made various fixes to this, so I think this can be closed.
