### ISSUE TITLE
Form Recogniser not giving ideal output of tables consisting symbols (checkmarks and crosses in this case)

### ISSUE THREAD

**Issue by devashish-gopalani-cognoai** [Azure-Samples/azure-search-openai-demo#570]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I had added in a PDF document which had the below table.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/82880314/274416f8-5d29-453c-89da-ad558ad09a5b)

Now the result which I got from Form Recogniser was used in the predocs.py script which converted the table to a HTML table as shown below -

```
Table 4 - Mother, Son, Daughter in Law <table><tr><th rowSpan=2>Ownership of</th><th colSpan=5>Income Of</th></tr><tr><th>Mother</th><th>Son</th><th>Mother + Son</th><th>Mother + Son + Daughter in Law</th><th>Son + Daughter in Law</th></tr><tr><td>Mother</td><td>:selected:</td><td>X * :selected:</td><td>:selected:</td><td>X * :selected:</td><td>X* :selected:</td></tr><tr><td>Son</td><td>:selected:</td><td>V :selected:</td><td>:selected:</td><td>V :selected:</td><td>V :selected:</td></tr><tr><td>Mother + Son</td><td>:selected:</td><td>:selected:</td><td>:selected:</td><td>:selected:</td><td>:selected:</td></tr><tr><td>Mother + Son + Daughter in Law</td><td>:selected:</td><td>:selected:</td><td>:selected:</td><td>:selected:</td><td>:selected:</td></tr></table>          * - Yes, if Son is sole child
```

My question is, from where is that "V" coming from? Is there something we can do so that the "V" which is coming can be avoided?

### Any log messages given by the failure
> NA

### Expected/desired behavior
> Where V has come in the table parsed by form recogniser, ":selected:" should have come.

### OS and Version?
> Linux (Ubuntu 22.04).

### azd version?
> azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

### Versions
> NA

### Mention any other details that might be useful
NA

**Comment by pamelafox** [comment]
@devashish-gopalani-cognoai Does that V happen when you use Form recognizer in the portal as well? Assuming so, please post here: https://learn.microsoft.com/answers/tags/440/document-intelligence
If it only happens with form recognizer called by our script, let us know.

**Comment by devashish-gopalani-cognoai** [comment]
@pamelafox yup, it is happening over there too. I'll raise it over there. Closing this issue.
