### ISSUE TITLE
Control Plane failures for OpenAI Resource Provider ("RequestConflict")

### ISSUE THREAD

**Issue by george-moore** [Azure-Samples/azure-search-openai-demo#59]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create a new OpenAI resource with the Chat and Davinci models.  Now delete the individual OpenAI models in OpenAI Studio, then attempt to delete the parent OpenAI resource in the Azure Portal. I am unable to delete the parent (empty) OpenAI resource in the Azure Portal until a multi-hour timeout window has passed. Until the internal issue resolves itself, I receive an "RequestConflict" error message from the Cognitive Services Resource Provider.  Please see typical error message below.

I have no other OpenAI resources deployed or in process of deployment, so I do not understand why there would be a "RequestConflict" upon an empty OpenAI resource.

**This makes it essentially impossible for me to use OpenAI because any cleanup operation or entirely new deployment can take hours for the Cognitive Services Conflict timeout to resolve.**  This is 100% reproducible for every deployment.  Since I only have quota for one deployment at a time, this entirely blocks me.  Please provide me with a workaround to this issue, perhaps with an additional quota so that I can still deploy a new resource while the deleting of the old resource times-out.

As an aside, even when it's working properly, it can still take >10 minutes to create a new OpenAI deployment via the Cognitive Services RP. Why does it take so long to create these resources?  I can create an entirely new Virtual Machine in <2 minutes, so why is this RP so slow?

### Any log messages given by the failure
>
Here is a typical error message from the Azure Portal:

_Executed delete command on 1 selected items
Succeeded: 0, Failed: 1, Canceled: 0.
Error details
[cog-k2mxpzdim5yjs](https://ms.portal.azure.com/#resource/subscriptions/7c9469c0-29ac-424a-85ab-d01f2cexxxxx/resourceGroups/rg-openai-operator/providers/Microsoft.CognitiveServices/accounts/cog-k2mxpzdim5yjs): Cannot modify resource with id '/subscriptions/7c9469c0-29ac-424a-85ab-d01f2cexxxxx/resourceGroups/rg-openai-operator/providers/Microsoft.CognitiveServices/accounts/cog-k2mxpzdim5yjs' because the resource entity provisioning state is not terminal. Please wait for the provisioning state to become terminal and then retry the request. (Code: RequestConflict)_

### Expected/desired behavior
> Delete operations should immediately delete the resources without internal conflicts.

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by george-moore** [comment]
I received this message from Azure Livesite:

Impact Statement: Starting at 06:00 UTC on 27 March 2023, you have been identified as a customer using Azure Open AI Service who may see latency when performing resource operations and model deployments.

Current Status: A recent deployment applied to a backend instance that Azure Open AI services relies on, introduced a code regression. This resulted in those instances becoming unhealthy and ultimately manifesting in users experiencing the issues mentioned above.

We have developed and are currently in the process of deploying a hotfix to mitigate the failures. We expect this step to take approximately 8 hours. We are continuing to monitor our telemetry to validate success.

Further updates will be provided in 8 hours, or earlier if events warrant.

**Comment by pablocastro** [comment]
Sorry about this, George. Since the team is on it, resolving this as there's nothing else to do in the sample itself.
