### ISSUE TITLE
Rate limited on the OpenAI embeddings API, sleeping before retrying...

### ISSUE THREAD

**Issue by rehat22** [Azure-Samples/azure-search-openai-demo#594]
I can deploy my solutions but for a large dataset the embeddings api keeps showing the following - Rate limited on the OpenAI embeddings API, sleeping before retrying....
This increases the deployment time by a-lot. Any solutions ?

**Comment by pamelafox** [comment]
This PR has an approach for reducing that: https://github.com/Azure-Samples/azure-search-openai-demo/pull/556

**Comment by pamelafox** [comment]
PR is now merged, closing this. Please try the latest changes.

**Comment by rehat22** [comment]
thank you!
