### ISSUE TITLE
Random text concatenation errors

### ISSUE THREAD

**Issue by seef-leroux** [Azure-Samples/azure-search-openai-demo#595]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When I click on the sample questions on the landing page, it sometimes happens. I get the error even when I replace the sample questions.

### Any log messages given by the failure
>TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### Expected/desired behavior
>

### OS and Version?
>Windows 10

### azd version?
> azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please check the logs to find the full traceback, we can't determine the issue from that error alone. The end of http://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html has details on how to find production error logs.

**Comment by seef-leroux** [comment]
Thank you. I don't think it was with the build; I think I accidentally broke the semantic configurations when I experimented with indexing. I have figured out that I can recreate the problem if I enable the setting 'Use semantic ranker for retrieval'. When I untick it, the error does not occur.
Can you perhaps tell me or share a screenshot of what the semantic configurations of my index must be?
Thanks!

**Comment by pamelafox** [comment]
You can see prepdocs.py for how the search index would have been set up originally.

Here's what my configuration looks like:
![Screenshot 2023-09-05 at 12 47 18 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/75b97d0b-f62f-4f30-add3-1176ad0bcc51)

![Screenshot 2023-09-05 at 12 47 24 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/c4b25f65-0ab8-4057-a41b-4d4db3dc8273)

Enabling semantic ranker triggers this bit of code, by the way:

```
if overrides.get("semantic_ranker") and has_text:
    r = await self.search_client.search(query_text,
              filter=filter,
              query_type=QueryType.SEMANTIC,
              query_language="en-us",
              query_speller="lexicon",
              semantic_configuration_name="default",
              top=top,
              query_caption="extractive|highlight-false" if use_semantic_captions else None,
              vector=query_vector,
              top_k=50 if query_vector else None,
              vector_fields="embedding" if query_vector else None)
```

**Comment by seef-leroux** [comment]
Thanks for your help so far. I have changed my index settings to the default, and I still get the same error when I enable semantic ranker. When I run the app locally and recreate the problem, Visual Studio Code logs the following errors:
ERROR:root:Exception in /chat
Traceback (most recent call last):
  File "C:\Users\azure-search-openai-demo\app\backend\app.py", line 100, in chat
    r = await impl.run(request_json["history"], request_json.get("overrides") or {})
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 130, in run       
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) async for doc in r]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 130, in <listcomp>
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) async for doc in r]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by pamelafox** [comment]
Okay, so it looks like doc[self.sourcepage_field] is None. That's doc["sourcepage"] if you didn't override KB_FIELDS_SOURCEPAGE environment variable. Can you check your index to make sure you always specified sourcepage in the uploaded chunks?

**Comment by seef-leroux** [comment]
Ah. How do I check my index for that? This is what my index looks like:
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/142386050/492f5990-6ecd-42c4-abe6-92a90391b8db)
What I have done is added my own data directly to the blob, because prepdocs.py gave an encryption error. In a previous attempt, I broke them down in page size chunks, which worked ok, but I have now added full documents to test.
Is it possible that the semantic search needs a number in the filename that it can interpret as sourcepage?

**Comment by pamelafox** [comment]
You can try searching with "*" in the explorer:

![Screenshot 2023-09-05 at 2 46 52 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/e0322e53-c752-4912-9c89-4f5397d673fa)

The sourcepage field contains the filename with a page number added in, like "Northwind_Health_Plus_Benefits_Details-3.pdf"

Perhaps you didn't add that field to yours?

**Comment by seef-leroux** [comment]
No, I did not add the field. Is there a way to run an indexer on manually uploaded data to index the page number?

**Comment by seef-leroux** [comment]
Ok, I have implemented a 'workaround' (by doing it the way I should have done it in the first place). I implemented the fix from #73 (I've updated the requirements.txt file in scripts/requirements.txt to include PyCryptodome==3.17), and now all my documents successfully uploads and indexes, so I don't have to manually work with the index.
My question that remains is this: How do I clean up a messy index? Can I run an indexer on it to refresh it?

**Comment by pamelafox** [comment]
When I've updated an index in the past, I first cleared out the index entirely (with prepdocs --removeall) and then re-populated it. I haven't tried to clear out just parts of it, but you could modify the removeall functionality to filter based on null sourcepage, perhaps?

```
def remove_from_index(filename):
    if args.verbose: print(f"Removing sections from '{filename or '<all>'}' from search index '{args.index}'")
    search_client = SearchClient(endpoint=f"https://{args.searchservice}.search.windows.net/",
                                    index_name=args.index,
                                    credential=search_creds)
    while True:
        filter = None if filename is None else f"sourcefile eq '{os.path.basename(filename)}'"
        r = search_client.search("", filter=filter, top=1000, include_total_count=True)
        if r.get_count() == 0:
            break
        r = search_client.delete_documents(documents=[{ "id": d["id"] } for d in r])
        if args.verbose: print(f"\tRemoved {len(r)} sections from index")
        # It can take a few seconds for search results to reflect changes, so wait a bit
        time.sleep(2)
```

You could experiment with the right query in the explorer. Afraid I'm not an ACS expert, so if you're unable to figure out a filter, we can ask for help from ACS team like @srbalakr

**Comment by seef-leroux** [comment]
I would rather try prepdocs --removeall and repopulate it before I experiment with a query. I have tried running the command, and it ends without errors but does not seem to do anything. It ends rather quick without any verbose feedback.

**Comment by pamelafox** [comment]
Okay, I recommend modifying prepdocs.sh or prepdocs.ps1 (whichever you call on your system) with the --removeall flag and running that. That takes care of passing in all the correct environment variables / arguments, versus running prepdocs.py directly. We should probably add an FAQ about this.

**Comment by seef-leroux** [comment]
Ok, I will start one, because I am not sure hot to modify it. I thought I just ran it in the terminal with --removeall.
