### ISSUE TITLE
Key for storage account using --storagekey

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure-Samples/azure-search-openai-demo#6]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Edit predocs.ps1 add an --storagekey but the function upload_blobs will fail with: "Unsopported key"
It is mandatory to use that type of key, because the normal user needs 2FA. The standard code will not work.
You need to add the --storagekey but it does not work.

I edited upload_blobs
```blob_service = BlobServiceClient(account_url=f"https://{args.storageaccount}.blob.core.windows.net", credential="mykey")```

and it works. 
Can you try using --storagekey and see if it works?
Cheers!

**Comment by pablocastro** [comment]
Thanks for reporting, using --storagekey should work now. Fixed in https://github.com/Azure-Samples/azure-search-openai-demo/commit/86c6e398a9a3ed8ffc0f93ca5d98cbb9e95c8f58
