### ISSUE TITLE
Getting Error: Can't instantiate abstract class HtmlCallbackHandler with abstract methods on_agent_action, on_llm_new_token

### ISSUE THREAD

**Issue by atinesh-s** [Azure-Samples/azure-search-openai-demo#60]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
While using ReadRetrieveReadApproach (rrr) [readretrieveread.py](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/readretrieveread.py) or ReadDecomposeAsk (rda) [readdecomposeask.py](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/readdecomposeask.py) I am getting error as mentioned below at line `cb_handler = HtmlCallbackHandler()`

### Minimal steps to reproduce
> 
```
# app/backend
from langchainadapters import HtmlCallbackHandler
from langchain.callbacks.base import CallbackManager

cb_handler = HtmlCallbackHandler()
cb_manager = CallbackManager(handlers=[cb_handler])
```
[langchainadapters.py](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/langchainadapters.py)

### Any log messages given by the failure
> TypeError: Can't instantiate abstract class HtmlCallbackHandler with abstract methods on_agent_action, on_llm_new_token

### OS and Version?
> Python 3.8 - AzureML

**Comment by pablocastro** [comment]
Doesn't repro for me. Did you update the version of langchain by any chance or are you running exactly the one specified in requirements.txt? Also you mention you're running on Python 3.8, we've only tested this in Python >= 3.10, maybe that makes a difference?

**Comment by cforce** [comment]
Pleas reopen as  langchain==0.0.78 has  security vulnerability and shall not be used at all any more.
Upgrade shall be done to at least v0.0.131. Even if demo code, this shall be fixed asap.
