### ISSUE TITLE
Logging in this environment

### ISSUE THREAD

**Issue by paypay1981** [Azure-Samples/azure-search-openai-demo#600]
I am trying to debug the backend program using logging module.
I would like to record a debug message in "async def chat()" by adding following code In app.py.
However, it doesn't work.
~~~~~~~~
async def chat():
    if not request.is_json:
        return jsonify({"error": "request must be json"}), 415
    request_json = await request.get_json()
    approach = request_json["approach"]
    logging.critical("hoge")## added
    try:
--snip--
~~~~~~

**Comment by pamelafox** [comment]
Please try using the app logger:

```
app.logger.warn("hoge")
```


If you want to see debug/info level warnings, you can add this line to create_app:

```
logging.basicConfig(level=logging.DEBUG)
```

**Comment by paypay1981** [comment]
Thank you for your response.

```
def create_app():
    if os.getenv("APPLICATIONINSIGHTS_CONNECTION_STRING"):
        configure_azure_monitor()
        AioHttpClientInstrumentor().instrument()
    app = Quart(__name__)
    app.register_blueprint(bp)
    app.asgi_app = OpenTelemetryMiddleware(app.asgi_app)
    logging.basicConfig(level=logging.DEBUG)## ADDED
    app.logger.warn("hoge1")## ADDED

    return app

```
```
async def chat():
    if not request.is_json:
        return jsonify({"error": "request must be json"}), 415
    request_json = await request.get_json()
    approach = request_json["approach"]
    app.logger.warn("hoge2")## ADDED
    try:
```

**Comment by paypay1981** [comment]
I closed by mistake so reopen.

**Comment by pamelafox** [comment]
Are you looking locally or in production? Locally, check the logs in your terminal. In production, you'll need to download the default_docker logs. See bottom of http://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html

**Comment by paypay1981** [comment]
When I am looking, I can find the logs that I added in my terminal. In production, I cannot find the logs in the default_docker_logs.
Thank you for your support. Maybe I am missing something.

**Comment by pamelafox** [comment]
Here's a screencast where I download the logs:
https://www.youtube.com/watch?v=czKyKV3RCEw

**Comment by paypay1981** [comment]
Thank you so much for the screencast. Now I can download default_docker_logs. However, I cannot find the log out put that I added(SEE "ADDED" line) in default_docker_logs.
Is it possible to add the code as follows in your environment and see if you can get the log output you added?

```
async def chat():
    if not request.is_json:
        return jsonify({"error": "request must be json"}), 415
    request_json = await request.get_json()
    approach = request_json["approach"]
    app.logger.warn("hoge2")## ADDED
    try:
```

**Comment by pamelafox** [comment]
I can do that when I have the chance. Make sure you added that to chat_stream() if you're using the latest branch with streaming.

**Comment by paypay1981** [comment]
Noted. I'll make sure that and try switching to the latest branch.
As I can find the logs when running locally but not in production, maybe it is about logging setting or logging level.
Sorry, I am azure development beginner.

**Comment by pamelafox** [comment]
No worries, it's not intuitive at all. I've put together a longer screencast where I add logging and find the logs in production. I ended up needing to wait several minutes for the new deploy to take effect, and then several more minutes for the logs to show up.

Video should be ready on YouTube soon:
https://www.youtube.com/watch?v=f0-aYuvws54

**Comment by pamelafox** [comment]
Also opened a PR to make it easier: https://github.com/Azure-Samples/azure-search-openai-demo/pull/610

**Comment by paypay1981** [comment]
Problem solved, after switching to the latest environment and added the code in you PR #610.
I appreciate your kind support.
