### ISSUE TITLE
Which prompt template and temperature?

### ISSUE THREAD

**Issue by seef-leroux** [Azure-Samples/azure-search-openai-demo#604]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
I want to change the prompt template and temperature. I have found it in a couple of files though. Which files are the correct ones in which I can change the prompt template and temperature?
### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I think this readme faq should help: "What is the difference between the Chat and Ask tabs?"

https://github.com/Azure-Samples/azure-search-openai-demo#faq

**Comment by pamelafox** [comment]
Closing, comment if that didn't help you find the files.
