### ISSUE TITLE
Multiple chats with specific context

### ISSUE THREAD

**Issue by riccardobrue** [Azure-Samples/azure-search-openai-demo#607]
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> I would ask if is possible to develop or any guidance to obtain the following features:
- Multiple chats with a chat selector menu, like the common ChatGPT UI (the chats will be stored into a DB and maybe there will be an account relationship);
- Have the possibility to upload a file inside a chat, such file knowledge will be available only inside the specific chat and not outside;
- Have the possibility to upload a file for a distributed knowledge (available for all the chats);
- Delete chat specific knowledge (from Azure Cognitive Search?) when a chat is deleted;
- Have the possibility to remove a file knowledge in the distributed context though an administrator menu (just an idea).

I see that something like #478 is considered, this should be another step into a more flexible UI.

**Comment by pamelafox** [comment]
We now have persistence chat history with CosmosDB as well as user-uploaded files. There is no chat-specific file upload at this point, so please open that as a separate issue if needed. I'll close this as I think we addressed the main requests.
