### ISSUE TITLE
Application Error Cannot open the application

### ISSUE THREAD

**Issue by angangxuxu** [Azure-Samples/azure-search-openai-demo#612]
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/31648760/8a056212-0632-4b80-8220-237d2392aae2)

**Comment by pamelafox** [comment]
Interesting, the error seems to indicate a problem loading gunicorn.conf.py. Can you make sure that gunicorn.conf.py exists? It should look like: 
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/gunicorn.conf.py

You can also try waiting 10 minutes to see if this has to do with App Service not being quite ready. It can take 5-10 minutes for the full deployment to end, even after azd has "finished".

**Comment by angangxuxu** [comment]
@pamelafox I'm sure this file exists locally, How to check this file on Azure? I think it may have been encrypted before uploading, My computer has encryption software installed.

**Comment by pamelafox** [comment]
Oh interesting. If your app was running, then you could use "SSH" from the Azure Portal to poke around the files. However, when your app fails to start, "SSH" is generally unavailable. One approach is to go into App Settings and put some very simple startup command in there that won't fail (like `sleep` perhaps?). Then once the server restarts, you could SSH in and see the file contents.

Are you able to turn off the encryption software? Or use GitHub codespaces to do the deploy?

**Comment by angangxuxu** [comment]
I use GitHub codespaces to do the deploy, It succeeded. Thanks so much.
