### ISSUE TITLE
How to run the code without Owner permission in subscription level

### ISSUE THREAD

**Issue by manunair1990** [Azure-Samples/azure-search-openai-demo#619]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

### Any log messages given by the failure
>

### Expected/desired behavior
> To run this code without owner permission in subscription level. It should be runnable with Resource group contributor permission if  all the resources are already created. 

### OS and Version?
> Windows 11.

### azd version?
> azd version 1.3.0

### Versions
>

### Mention any other details that might be useful
As i am working with this code for a quiet long time. I didnt see any way to run this code without owner permission in azure in subscription level. As i am working with already created resource group and resources, I believe, i dont need owner permission at subscription level to run this code. I have contributor permission at the resource group level. I know this is a duplicate question, but i didnt find any answers to "HOW TO RUN THE CODE USING RESOURCE GROUP CONTRIBUTOR PERMISSION ONLY". How to run the code without using Principal ID, Tenant ID like things. Pls help me with that. Thanks in advance.

**Comment by pamelafox** [comment]
As per #4, it's not currently possible to use `azd up` to deploy this code:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/4

That's because the bicep files set up roles, and those roles can only be set up if you have the level access described in https://github.com/Azure-Samples/azure-search-openai-demo#azure-account-requirements

We'll keep trying to make it easier to deploy, but I don't have anything to share right now. You can try to make all the resources yourself and set up all the env variables that are used in app.py, but it may be a little painful. 

Could you instead use the "Use your data" app from the studio, perhaps? I don't think it requires as many permissions.
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data

Please continue the discussion in #4.

**Comment by manunair1990** [comment]
@pamelafox 
Thanks for the explanation. I referred to the github code that you mentioned. 
There also its written like
(Preview) Sample Chat App with AOAI
Deploying with the Azure Developer CLI
IMPORTANT: In order to deploy and run this example, you'll need an Azure subscription with access enabled for the Azure OpenAI service. You can request access [here](https://aka.ms/oaiapply). You can also visit [here](https://azure.microsoft.com/free/cognitive-search/) to get some free Azure credits to get you started. Your Azure Account must have Microsoft.Authorization/roleAssignments/write permissions, such as [User Access Administrator](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#user-access-administrator) or [Owner](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#owner).

So, cant we run these codes without owner roles?

**Comment by pamelafox** [comment]
Ah, so it also requires a higher level of access. Can your employer grant you the [RBAC role](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#role-based-access-control-administrator-preview) to an existing resource group? That would be enough access to azd up to that group.

**Comment by ayus786** [comment]
> Ah, so it also requires a higher level of access. Can your employer grant you the [RBAC role](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#role-based-access-control-administrator-preview) to an existing resource group? That would be enough access to azd up to that group.

Hi @pamelafox , Is there any alternative to this?

**Comment by pamelafox** [comment]
If you cannot create roles, then you'll need to use keys. You could try https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator which has similar functionality to this one and can be deployed with keys only.
