### ISSUE TITLE
How to add System Identities(User) manually for backend service.

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#634]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
I can not create roles from the application. I am using existing OpenAI service. Can anyone tell me how to add  Syatem identities (roles) for backend service manually. Basically i want to add these role manually. Here is the code for reference-
// SYSTEM IDENTITIES
module openAiRoleBackend 'core/security/role.bicep' = {
  scope: openAiResourceGroup
  name: 'openai-role-backend'
  params: {
    principalId: backend.outputs.identityPrincipalId
    roleDefinitionId: '5e0bd9bd-7b93-4f28-af87-19fc36ad61bd'
    principalType: 'ServicePrincipal'
  }
}

module storageRoleBackend 'core/security/role.bicep' = {
  scope: storageResourceGroup
  name: 'storage-role-backend'
  params: {
    principalId: backend.outputs.identityPrincipalId
    roleDefinitionId: '2a2b9908-6ea1-4ae2-8e65-a410df84e7d1'
    principalType: 'ServicePrincipal'
  }
}

module searchRoleBackend 'core/security/role.bicep' = {
  scope: searchServiceResourceGroup
  name: 'search-role-backend'
  params: {
    principalId: backend.outputs.identityPrincipalId
    roleDefinitionId: '1407120a-92aa-4202-b7e9-c0e197c71c8f'
    principalType: 'ServicePrincipal'
  }
}
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
We have the existing script that sets up the roles for a user:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/roles.sh

You would need to enable managed identity for your app service app in the Identity tab, copy that principal id, and run it in the script.

<img width="584" alt="Screenshot 2023-09-14 at 5 53 46 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/adc41544-0ac1-48e7-82ed-3e3b9b0e3b54">

**Comment by namratam30** [comment]
I can't run the script as i don't have access. Is there anyway to create this identity from Azure portal.

**Comment by pamelafox** [comment]
* First, make sure that your app service app has Managed identity enabled:

  ![Screenshot 2023-09-15 at 11 41 00 AM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/10d85fc6-b7e3-448a-b348-ad483e6ce0ba)

* Then click the "Azure role assignments" button on that screen.
  
  ![Screenshot 2023-09-15 at 11 42 11 AM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/0507dc76-f975-4d1d-b37d-4d10a7f04034)

* Select "+ Add role assignment" from that screen.
   * For scope, select "Resource group".
   * For role, select "Cognitive Services OpenAI user".

  ![Screenshot 2023-09-15 at 11 42 51 AM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/f865f555-cf6c-4dd8-aa0e-2e74565308f3)

* Repeat for roles "Storage Blob Data Reader" and "Search Index Data Reader".

* When done, your role assignments should look like:
  ![Screenshot 2023-09-15 at 11 43 54 AM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/32b6e4ee-c5bf-489d-b46a-e1f5eff39f79)

Please let us know if that worked for you. I'm curious why you'd be able to do that in the Portal but not able to do it via the script, I thought the permissions would be the same.

**Comment by manunair1990** [comment]
> We have the existing script that sets up the roles for a user:
> 
> https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/roles.sh
> 
> You would need to enable managed identity for your app service app in the Identity tab, copy that principal id, and run it in the script.
> 
> <img alt="Screenshot 2023-09-14 at 5 53 46 AM" width="584" src="https://user-images.githubusercontent.com/297042/267980600-adc41544-0ac1-48e7-82ed-3e3b9b0e3b54.png">

Hi @pamelafox 

I tried to run the code with existing resources created by the owner. And i have RBAC role in the Resource group level. But i couldn't get access to enable managed identity for my app service in the Identity tab and though couldn't copy that principal id. Then how can i run the code with only RBAC role to the resource group. Please help me.

**Comment by ayus786** [comment]
> * First, make sure that your app service app has Managed identity enabled:
>   ![Screenshot 2023-09-15 at 11 41 00 AM](https://private-user-images.githubusercontent.com/297042/268367915-10d85fc6-b7e3-448a-b348-ad483e6ce0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDExMjMsIm5iZiI6MTcwODk0MDgyMywicGF0aCI6Ii8yOTcwNDIvMjY4MzY3OTE1LTEwZDg1ZmM2LWI3ZTMtNDQ4YS1iMzQ4LWFkNDgzZTZjZTBiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzNiMjVlOTJjYzI3YTdlMjNmZDk0M2U4OWUwYTMxYmI5OTljYzNlMmM2ZjYzODM4ZWMxNzM5ZDU5Yzc1MTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O55idIANBzuiOchM8vqdoAixF630VmcUEsjS4fyC5ec)
> * Then click the "Azure role assignments" button on that screen.
>   ![Screenshot 2023-09-15 at 11 42 11 AM](https://private-user-images.githubusercontent.com/297042/268368056-0507dc76-f975-4d1d-b37d-4d10a7f04034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDExMjMsIm5iZiI6MTcwODk0MDgyMywicGF0aCI6Ii8yOTcwNDIvMjY4MzY4MDU2LTA1MDdkYzc2LWY5NzUtNGQxZC1iMzdkLTRkMTBhN2YwNDAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2NhMDA4NjI5MGVkMzcwYzk1MThhZTVlZjIyNjdhMjc2N2QwZDJlN2FjOGI4OGQwYTRhNmNiYzIzYTZhZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.erdbQ5oipm6t8m47Xp5lllkJtNRoLWDhp8MRQr_pnlg)
> * Select "+ Add role assignment" from that screen.
>   
>   * For scope, select "Resource group".
>   * For role, select "Cognitive Services OpenAI user".
>   
>   ![Screenshot 2023-09-15 at 11 42 51 AM](https://private-user-images.githubusercontent.com/297042/268368242-f865f555-cf6c-4dd8-aa0e-2e74565308f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDExMjMsIm5iZiI6MTcwODk0MDgyMywicGF0aCI6Ii8yOTcwNDIvMjY4MzY4MjQyLWY4NjVmNTU1LWNmNmMtNGRkOC1hYTBlLTJlNzQ1NjUzMDhmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWM3MWJkNWRjYWVmYjI5MDM2ZGYzZjM4ODA5MTU1ZGEyYzA4YTQ2ODA1NTZhODM3M2UwZjY4ZTQ1NWQ3M2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S1NpnbeZdbyEP6R3lj7UL10Xs97ooXAOqJCqnB8CFKc)
> * Repeat for roles "Storage Blob Data Reader" and "Search Index Data Reader".
> * When done, your role assignments should look like:
>   ![Screenshot 2023-09-15 at 11 43 54 AM](https://private-user-images.githubusercontent.com/297042/268368371-32b6e4ee-c5bf-489d-b46a-e1f5eff39f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDExMjMsIm5iZiI6MTcwODk0MDgyMywicGF0aCI6Ii8yOTcwNDIvMjY4MzY4MzcxLTMyYjZlNGVlLWM1YmYtNDg5ZC1iNDZhLWUxZjVlZmYzOWY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGRlOGRjMTkzYmVhNWRmZjNhN2FiN2QwMDcxN2NlNGM0YjQxOGIwZWQ0MmFjNDE4NTg5NzQxNzI4ZDE3Mjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6aKlABhRbVgj7l8qWzax0-p4EDMH30O43XVhJMPtt8s)
> 
> Please let us know if that worked for you. I'm curious why you'd be able to do that in the Portal but not able to do it via the script, I thought the permissions would be the same.

It is working but it's giving responses outside of the resources provided.

**Comment by pamelafox** [comment]
@ayus786 Please see this guide for tips on debugging low quality answers:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/customization.md#improving-answer-quality

I haven't experienced it giving responses outside of the resources provided, but that can vary across domain, so you may need to do additional prompt engineering or try GPT-4.
