### ISSUE TITLE
How to integrate Python Enterprise Logging with this solution using APIM

### ISSUE THREAD

**Issue by mattjames1978** [Azure-Samples/azure-search-openai-demo#636]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Is it possible to have some guidance on how to add the API management layer for logging to the pyton code for this deployment
https://github.com/Azure-Samples/openai-python-enterprise-logging
For example 

import openai

openai.api_type = "azure"
openai.api_base = "https://xxxxxxxxx.azure-api.net/" # APIM Endpoint
openai.api_version = "2023-05-15"
openai.api_key = "APIM SUBSCRIPTION KEY" #DO NOT USE ACTUAL AZURE OPENAI SERVICE KEY

response = openai.Completion.create(engine="modelname",  
                                    prompt="prompt text", temperature=1,  
                                    max_tokens=200,  top_p=0.5,  
                                    frequency_penalty=0,  
                                    presence_penalty=0,  
                                    stop=None) 
When generating text, prompts the API gateway is not called.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattjames1978** [comment]
Closing as resolved myself while waiting..

**Comment by GLubomirov** [comment]
> Closing as resolved myself while waiting..

Hi, can you please elaborate on how you got it working

**Comment by mattjames1978** [comment]
Hi @GLubomirov, thanks for reaching out. Integrating APIM with Open AI was tricky but the break through for me was adding openai URL prefix to the APIM. See screen shot below but navigate to APIM management service, API, click on the openai service and then settings.

<img width="794" alt="APIM Prefix" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/97545090/46bd0f24-e142-453c-bed9-fa46ed00cb1f">

The next bit was adding APIM endpoint and subscription key to app.py on the web app. I added them as environment variables to keep them secure.

I had to comment out one of the modules. One thing to bear in mind is we had to take Azure AD out of the equation but I want to add this back at some stage as the web app is only secured by the subscription key so lowers security.

But below are the changes, make sure you add the three parameters too for subscription key, APIM endpoint and API version

Comment out 

#comment out below when adding APIM
@bp.before_request
async def ensure_openai_token():
    if openai.api_type != "azure_ad":
        return
    openai_token = current_app.config[CONFIG_OPENAI_TOKEN]
    if openai_token.expires_on < time.time() + 60:
        openai_token = await current_app.config[CONFIG_CREDENTIAL].get_token(
            "https://cognitiveservices.azure.com/.default"
        )
        current_app.config[CONFIG_OPENAI_TOKEN] = openai_token
        openai.api_key = openai_token.token
##

then add below, this is based on new code from main repo.

So just uncomment and comment out the lower section.

 # Used by the OpenAI SDK
    #uncomment when adding APIM
    if OPENAI_HOST == "azure":
        #   openai.api_type = "azure"
        #   openai.api_base = APIM_ENDPOINT
        #   openai.api_version = APIM_VERSION
        #   openai.api_key = APIM_SUBSCRIPTION_KEY
        #   current_app.config[CONFIG_OPENAI_TOKEN] = APIM_SUBSCRIPTION_KEY

 #comment out below when adding APIM         
        openai.api_type = "azure_ad"
        openai.api_base = f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com"
        openai.api_version = "2023-07-01-preview"
        openai_token = await azure_credential.get_token("https://cognitiveservices.azure.com/.default")
        openai.api_key = openai_token.token
        # Store on app.config for later use inside requests
        current_app.config[CONFIG_OPENAI_TOKEN] = openai_token
    else:
        openai.api_type = "openai"
        openai.api_key = OPENAI_API_KEY
        openai.organization = OPENAI_ORGANIZATION

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/97545090/c4d02b81-9aec-45c8-ab2f-1b650dd0d6b7)

Parameters also need adding to application settings on web app in main.bicep

add to main.bicep
// APIM params

param apim_endpoint string = ''
param apim_subscription_key string = ''
param apim_version string = ''

Application settings:
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/97545090/0970a663-016c-4a29-a238-2db62627395b)

main.parameters.json

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/97545090/a7d0ef89-a750-4d36-b9e3-c1546cba1b8d)

**Comment by GLubomirov** [comment]
Thanks a lot, for the detailed response. I don't think this info is available anywhere else

**Comment by mattjames1978** [comment]
No it isn't and I struggled figuring it out myself! If you get stuck give us a shout!

**Comment by pamelafox** [comment]
Thank you @mattjames1978 for generously sharing your approach with other developers. We're actually considering adding APIM as an optional resource to the infrastructure, given its usefulness.

**Comment by mattjames1978** [comment]
No worries @pamelafox, happy to help and will keep an eye out when the new feature is added.
I am currently building a new environment into uk south so we can take advantage of 0613.
Cheers
Matt

**Comment by pamelafox** [comment]
@GLubomirov @mattjames1978 We're discussing APIM integration in this sample and are wondering how customers are using it. What are your goals in using APIM? Are you using it to monitor token usage? AAD? Rate limiting usage? Load balancing between instances?
We'd love to hear more!

**Comment by mattjames1978** [comment]
@pamelafox the main use case for us was to improve security and enable enterprise logging to allow us to log what the users were inputting into the chat. To improve the chat completion model.

**Comment by GLubomirov** [comment]
@pamelafox currently the interest is mainly in providing robust monitoring and auditing. There's a lot of exploration going on, on what the tech is capable of and what options there are to control and improve the model output. There's also demand for ways  to detect inaccurate or suboptimal information provided by the model. However I also get questions about security, scalability and concerns about open ai quotas and limits.

**Comment by zeltml01** [comment]
> if OPENAI_HOST == "azure":
>     #   openai.api_type = "azure"
>     #   openai.api_base = APIM_ENDPOINT
>     #   openai.api_version = APIM_VERSION
>     #   openai.api_key = APIM_SUBSCRIPTION_KEY
>     #   current_app.config[CONFIG_OPENAI_TOKEN] = APIM_SUBSCRIPTION_KEY

Hey mattjames- I'm REALLY struggling to add APIM support. Any thoughts ?

**Comment by mattjames1978** [comment]
Did you follow the guidance I shared at the top? What error messages are you getting? Any info you can share on the issue will help troubleshoot.

**Comment by zeltml01** [comment]
> Did you follow the guidance I shared at the top? What error messages are you getting? Any info you can share on the issue will help troubleshoot.

Hey Matt, yes- I'm not getting errors, but there's nothing within the APIManagementGateway Logs. I have logging and byte size up to the level it should be and I'm using a tier of APIM which should allow the logs to be happening.

**Comment by mattjames1978** [comment]
Ok, are you able share a screen shot of your logging settings on the api management side? There is a test option from memory to generate output

**Comment by mattjames1978** [comment]
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/97545090/2cf434f8-c603-4fb0-851c-a18b2b28111e)
