### ISSUE TITLE
Error:The API deployment for this resource does not exist. 

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#645]
> Please provide us with the following information:
> ---------------------------------------------------------------
 I am getting error 
**Error: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again**
Can you help me to fix the error
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
The error is probably due to the deployment ID not being specified correctly in your environment variables. First, print out the values of your environment variables in app.py. Then, I recommend enabling debug logging (see the FAQ in the README about logging) which will show you what URL OpenAI tries to reach, and then you can compare that URL to what the Azure studio shows.

**Comment by namratam30** [comment]
Can you suggest app settings based on these deployment-
<img width="290" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/35361021/87009450-7e8a-4ae5-bfc3-d01f39bcdef6">

**Comment by pamelafox** [comment]
It looks like you named the deployments after their models, so that'd probably be:
AZURE_OPENAI_CHATGPT_DEPLOYMENT="gpt-35-turbo"
AZURE_OPENAI_CHATGPT_MODEL="gpt-35-turbo"
AZURE_OPENAI_EMB_DEPLOYMENT="text-embedding-ada-002"
AZURE_OPENAI_EMB_MODEL_NAME="text-embedding-ada-002"
