### ISSUE TITLE
Remove documents from index

### ISSUE THREAD

**Issue by ganesh25** [Azure-Samples/azure-search-openai-demo#646]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I want to remove a specific doc or remove all docs from the blob storage and the index.

1) Navigate to scripts folder in terminal
2) Run -> prepdocs.py '..\data\*' --storageaccount mystorageaccount --container mycontainer --searchservice mysearchservice --index mysearchindex --removeall (or --remove myblobname)

### Any log messages given by the failure
Sometimes I got this error:
[27548:0918/164439.480:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[27548:0918/164439.480:ERROR:disk_cache.cc(205)] Unable to create cache
Other times, there was no messages after execution

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### azd version?
> run `azd version` and copy paste here.
1.3.0

### Versions
>

### Mention any other details that might be useful
both -remove and --removeall does not work, although I tried running prepdocs.py with the args as mentioned in code
> 
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Can you share the full error? I'm wondering what it was trying to do right before that error.  

Are you running from Terminal, VS Code, Mac, or Windows? I see VS Code related errors here: https://github.com/microsoft/vscode/issues/180794

**Comment by mhalomari** [comment]
Hi,
I removed files from storage and index using a different approach and it worked:

1. Copied the files/documents that I want to remove to the data folder.
2. I added "--remove" just before the end of the last line in prepdocs.ps1 then run "pwsh ./scripts/prepdocs.ps1"
`Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prepdocs.py `"$cwd/data/*`" --storageaccount $env:AZURE_STORAGE_ACCOUNT --container $env:AZURE_STORAGE_CONTAINER --searchservice $env:AZURE_SEARCH_SERVICE --openaiservice $env:AZURE_OPENAI_SERVICE --openaideployment $env:AZURE_OPENAI_EMB_DEPLOYMENT --index $env:AZURE_SEARCH_INDEX --formrecognizerservice $env:AZURE_FORMRECOGNIZER_SERVICE --tenantid $env:AZURE_TENANT_ID --remove -v" -Wait -NoNewWindow`

hope this helps.

**Comment by ganesh25** [comment]
@pamelafox - I am running on Anaconda prompt 

This is pretty much the full error: 
(tfgpu) C:\OpenAIProject\Code\testapp\scripts>prepdocs.py '..\data\01_Introduction.pdf' --storageaccount mystorageaccount --container mycontainer --searchservice mysearchservice --index mysearchindex --remove

(tfgpu) C:\OpenAIProject\Code\testapp\scripts>
[4060:0919/162912.378:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[4060:0919/162912.379:ERROR:disk_cache.cc(205)] Unable to create cache

@mhalomari - This works, but partially! 

If I use the --remove argument for a specific, it removes the relevant sections in the index, but does not remove its blob in the container. 
If I use --removeall, it removes all the blobs from container and all the sections from the index.

Do you face the same issue with --remove argument, that it only removes from the index?

**Comment by mhalomari** [comment]
It worked for me and removed files from containers and sections from index. I would recommend you check the function definition for read_files in prepdocs.py where you can see it calling:
`if args.remove:  
remove_blobs(filename)  
remove_from_index(filename)`

> @mhalomari - This works, but partially!
> 
> If I use the --remove argument for a specific doc, it removes the relevant sections in the index, but does not remove its blob in the container. If I use --removeall, it removes all the blobs from container and all the sections from the index.
> 
> Do you face the same issue with --remove argument, that it only removes from the index?

**Comment by ganesh25** [comment]
I had implemented the entire pdf upload )for citations) earlier and the blobs obviously don't have the page numbers in its filename, since its one file. This is why remove_blobs function wasn't working for me (it had a lambda function that checks for page numbers in filename. I removed that and it works now. Thanks!

**Comment by bduric** [comment]
The remove instructions don't work in my case. I made the changes to the file and called the scripts. It checks if file exists and if so no action taken. If .md5 file removed it would actually add the file again. so in short steps taken.
1. made changes as instructed
2. run the script
no file removed or added
in second attempt tried to remove md5 file and ran the script outcome was file added.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/122842745/af356630-328d-439d-84dd-e5ce6844183d)
