### ISSUE TITLE
Feedback to the responses will be helpful ( Like and Dislike Button) for the Answer

### ISSUE THREAD

**Issue by kishorerv93** [Azure-Samples/azure-search-openai-demo#65]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pablocastro** [comment]
In this sample there's no mechanism to take action on the feedback data if we collected it, and expanding the sample to cover that it's out of scope (we need to keep the size of this example on check :)).
