### ISSUE TITLE
how can we add msal or oidc authentication to this, also some rbac?

### ISSUE THREAD

**Issue by thwayant** [Azure-Samples/azure-search-openai-demo#654]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
Is there some documentation or git repo which has implemented auth and rbac, i have searched for it in microsoft docs but couldn't find anything with enough detail to work from, has anyone have idea/template for auth and rbac with azure ad.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
There are two PRs that involve AAD auth:

https://github.com/Azure-Samples/azure-search-openai-demo/pull/624 which includes a README on setting up auth.

https://github.com/Azure-Samples/azure-search-openai-demo/pull/534 which adds automation for AAD setup

The README also contains some links to auth tutorials.

Please take a look at those options to see if they cover the kind of auth features you're looking for.
We will likely be merging #624 soon, and then working on automating the auth setup for it.

**Comment by thwayant** [comment]
> There are two PRs that involve AAD auth:
> 
> #624 which includes a README on setting up auth.
> 
> #534 which adds automation for AAD setup
> 
> The README also contains some links to auth tutorials.
> 
> Please take a look at those options to see if they cover the kind of auth features you're looking for. We will likely be merging #624 soon, and then working on automating the auth setup for it.

Thank you, this is very helpful.
