### ISSUE TITLE
Unable to retrieve the entire document in the citations.

### ISSUE THREAD

**Issue by suma-sai-paluri** [Azure-Samples/azure-search-openai-demo#655]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I uploaded new documents in the data folder and made all the required prompting changes and resource allocation changes based on my needs and deployed the system . The run was successful and could see the UI with all the features working as desired except the the documents which are retrieved from the search are not the entire documents.
>

### Any log messages given by the failure
N/A
>

### Expected/desired behavior
When the chat approach or ask a question approach is asked a question it should respond based on the documents which are retrieved and cite these documents at the end of the response message. I would like the citations provided contain the entire document without effecting the thought process which shows the chunks of the document which was used in arriving to the answer. Is this feature of retrieving the entire document possible ?  
>

### OS and Version?
> Windows 11

### azd version?
> azd version 1.2.0

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
>  Can someone help me to provide the entire documents in the citation not the parts which the model used to build answers on. Did anyone successfully retrieve the entire documents?  If yes please help me with the possible changes I should make to achieve it or a Github link .Thank you in advance.

**Comment by pamelafox** [comment]
It's currently set up to include a citation for the document and page number, and clicking the citation opens up that page. Are you trying to get it to open the whole document? If so, you'd need to modify prepdocs.py to also upload the whole document, and then just remove the page number from the link.

**Comment by suma-sai-paluri** [comment]
Thank you for your reply, Just to make sure that I understood your directions ,the following is the task I should do: I should upload individual pages of the documents and also the entire documents (in a way the entire documents are  not included in the next process of extracting the data using form recognizer creating embeddings as they would be redundant). And remove the page number from the link. 

Excuse me for asking a review on my understanding, I am a newbie in this area. Thank you for your time.

**Comment by kylgrn** [comment]
@pamelafox , do you have any more specifics you can share about what to edit in the prepdocs.py to make this happen?

**Comment by suma-sai-paluri** [comment]
Hi @kylgrn, please share the code if you find the solution for this issue. It would be of great help. Thank you

**Comment by pamelafox** [comment]
Sure, here's a branch where I upload the whole file and link to it: https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...pamelafox:azure-search-openai-demo:wholefile?expand=1

**Comment by suma-sai-paluri** [comment]
Hi @pamelafox . Thank you for your reply i have cloned the latest repo (22a45dc) and made the changes which made in the following repo and tried deploying a new app. The app was deployed successfully but now I am unable to retrieve no responses in the chat scenario  and could get the response in ask scenario but could n't look at the citations at all. I could see the following message being displayed in the citation section of  ask scenario:
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

![Screenshot 2023-10-03 180126](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/34f49952-8bce-48f2-bf29-268774933b17)

I am unable to understand is it becuase of cloning the latest repo or due to the changes? 

Thank you

**Comment by pamelafox** [comment]
The "not found" means that the blob filename didn't match what's in blob storage. Please check your App Service logs (see the FAQ about it in the README) and see what filename it tried to load versus what's in storage.

**Comment by pamelafox** [comment]
I am probably going to send a PR to make a change that will load the whole document and jump to the page, as we've discovered that #pageN jumps to a page in all the browsers we've tested. (Still testing Safari)

cc @charris-msft

**Comment by suma-sai-paluri** [comment]
Thank you @pamelafox , I will be looking forward for the new update, I would also like to let you know that I encountered this error using Microsoft edge work ,Microsoft edge. The following is the situation in the chat scenario, it is not providing responses with new cloned repo[22a45dc](url).
![Screenshot 2023-10-04 092554](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/8295331b-7863-4241-aa44-0dd405a63ee2)

**Comment by pamelafox** [comment]
The change to show the whole document has been rolled out, so I'm closing this issue. Please file new issues for any other issues.
