### ISSUE TITLE
Chat with time range/dates interval

### ISSUE THREAD

**Issue by ivanvaccarics** [Azure-Samples/azure-search-openai-demo#661]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N.A.

### Any log messages given by the failure
>N.A.

### Expected/desired behavior
I'm implementing a chat system using your repository but the files uploaded are resumes (CVs). I would be interested in carrying out temporal/dates searches such as "Give me all the candidates with no more than 5 years of experience in project management" or "All graduates in computer engineering from 2010 to 2015". I managed to generate a cognitive search query like "Not more than 5 years of experience" but the results returned from the cognitive search do not satisfy this constraint. I know that this information must be written in the data stored in cognitive search but at the moment it doesn't work. Can you help me cover this case?

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
It seems like this could be covered a few ways:

1) When extracting data, extract dates specifically and store it in Cog Search as an additional field, then pass those dates into Cog Search. You may want to use ChatGPT functions to ask it to return dates that you could then pass as a filter.
2) Massaging the prompt to try to get ChatGPT to narrow the results. I assume that's not working well now.

**Comment by ivanvaccarics** [comment]
Hi @pamelafox yes I used one of the approach you suggested now. I extracted the information during the predocs phase by using a Completion phase on the text and then I used these metadata as filterable element of the cognitive search. In this way, from the frontend, i can filter them. Thanks a lot.

**Comment by suma-sai-paluri** [comment]
Hi @ivanvaccarics thats very interesting to hear about your development. I'd like to learn more about it. Do you have any additional details or perhaps a link to the repository where you've implemented this? Thanks for sharing your insights!"

**Comment by ivanvaccarics** [comment]
> Hi @ivanvaccarics thats very interesting to hear about your development. I'd like to learn more about it. Do you have any additional details or perhaps a link to the repository where you've implemented this? Thanks for sharing your insights!"

Hi @suma-sai-paluri no, the code is not public. Basically what I suggest you is to perform a request to the openAI model when you have extracted the data (from the prepdocs.py) script to extract the metadata you are interested. Be carefoul of course for token limits.

**Comment by suma-sai-paluri** [comment]
Hi @ivanvaccarics ,Thank you for replying.  I understand that the code for the prepdocs.py script is not public, but I was wondering if you would be able to give me some more guidance on how to use the openAI model to extract the metadata I am interested in. I am just not sure how to structure my request to the model to get the specific metadata I need. I would be very grateful for any help you can provide. Thank you for your time and consideration.

**Comment by ivanvaccarics** [comment]
Hi @suma-sai-paluri yes i can help you. Please provide me an example of the text and the metadata you want to extract. I can suggest to you a prompt for the extraction.

**Comment by suma-sai-paluri** [comment]
Hi @ivanvaccarics thank you for your quick response. I have a large amount of offer documents in Italian and each document is 15 -25  pages long. I have to retrieve results for queries such as "how many offers are made to the company called aaaaaa for the past five year" or "Provide me the list of all offers greater than 10000euros".  I am struggling to find a way to extract this kind of information(the amount/dates)  efficiently, given the length of the documents. Could you suggest me a way in which i could retrieve this information effectively and create an index?
Thanks a lot for offering help.

**Comment by ivanvaccarics** [comment]
Hi @suma-sai-paluri what I suggest you is to perform a query to the chatpgt-35-turbo model (or the model you are using) with a prompt like:

"
Given the following text: {file_text}

Extract the following information: amount, year of the invoice, company name (and other info you need).
Reply only in JSON format with the following structure: {"amount": , "company_name": "", "year": }
"

This is the approach I would try if I encountered a problem like yours. Then you can use the single key as element of the index (like the content of the embedding) and then perform a filter from the FE directly on the cognitive search.

Hope to help you.

**Comment by suma-sai-paluri** [comment]
Hi @ivanvaccarics thank you for your suggestion regarding the prompt. I understand that we should use this prompt in predocs.py folder and get the json of the info I need. I am unable to understand how to impart this json  in the index of the which is already existing index? How to incorporate the retreived json text in the index?
can you let me know how you created index with the json you have obtained ?
Thank you for helping me.

**Comment by suma-sai-paluri** [comment]
Hi @ivanvaccarics . Based on your inputs I was successful with the first step of Using chatgpt model and obtain json script . But i was unable to index them properly into the azure cognitive search index . Can you please help me with the ways to integrate this json elements in the index. I am unable to integrate it . 
Thank you in advance

**Comment by ivanvaccarics** [comment]
hi @suma-sai-paluri  you need to delete the index and change the prepdocs.py script to add the new element to the index. Please have a look to the code where the elements of the index are managed (in the sections part and in the creation of the index).

**Comment by suma-sai-paluri** [comment]
Hi@ivanvaccarics i tried doing it but was unable to correctly point the acquired json script to the index elements therefore the results retrieved aren't point to the element in FE of copgnitive search. Here below I am attaching the pieces of code . Can you please let me know where I am going wrong?
The first image is extracting the json script using gpt-35-turbo.
![Screenshot 2023-11-17 102246](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/7edf282c-7a48-4976-b0d3-6ca3281bee7e)
I have build index the following way:
![Screenshot 2023-11-17 102113](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/9b786707-ff8e-4c36-80dc-fa6ae8d2ce39)


![Screenshot 2023-11-17 102127](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/b1c92e2a-4ccb-4dc3-a102-8b0b95120f38)
![Screenshot 2023-11-17 102153](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/e2e03934-1150-4c21-9daa-7427703f20c8)
