### ISSUE TITLE
Deploy only the backend to Azure App service

### ISSUE THREAD

**Issue by DSgUY** [Azure-Samples/azure-search-openai-demo#662]
Hi, I create the azure app service and configure my external gitlab and my branch.

The problem is that I have the app in: app/backend folder (similar git arquitecture of this repo + some scrapping and ETL folders).

How I can config the Azure App Service to deploy what is inside app/backend? As Oryx search for requirements.txt in the root folder.
I want to keep my git structure and not create a new repository with the content of backend?

I tried with .yaml .deployment and also with adding Application settings in Configuration Settings.

My app is working in Azure Apps but I manually need to merge changes in the build of the frontend, etc.

Thanks.

**Comment by pamelafox** [comment]
We recommend deploying using the Azure Developer CLI since everything is setup that way. If you are trying to deploy a different way, you should consult the infra/ folder to see what gets configured on App Service - you'll need to mimic that with your way of deploying.
