### ISSUE TITLE
Unable to deploy multiple apps under the same app service plan using this architecture

### ISSUE THREAD

**Issue by suma-sai-paluri** [Azure-Samples/azure-search-openai-demo#665]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Hi i have deployed the application once on my data. But now i want two applications under the same resource group one running and one for me to experiment. But I unable to deploy two apps under the same app service plan as the program is either forcing me to create a new plan or the deployment is failing. I tried changing the tags and making changes in predocs.py but it is not working.

### Any log messages given by the failure
>

### Expected/desired behavior
>Can someone help me in deploying two applications under the same app service plan in this architecture?

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> azd version 1.3.0

### Versions
>

### Mention any other details that might be useful

> It would be of great help if someone could help with detailed answer or snippets of code.
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@suma-sai-paluri I see you closed this, did you come up with an approach that worked for you?

**Comment by TjerkSuperSterk** [comment]
@pamelafox @suma-sai-paluri I'm facing the same issue, what was the solution for this?

**Comment by suma-sai-paluri** [comment]
Hi @pamelafox @TjerkSuperSterk  I did not find a permanent fix but i leveraged the possibility of changing the app service plan for the app. After running azd up a new app is being created under a new app service plan always, therefore after the creation of the app i went to the azure portal and changed the app service plan to already existing one.

**Comment by TjerkSuperSterk** [comment]
@suma-sai-paluri  Did you changed the app service plan in the .ENV file? Since I already tried to change the following in the .env but it still takes the old Neppo web app name and plan.. 

AZUREAPPSERVICE_APP_NAME = ""
AZURE_SERVER_APP_ID=""
AZURE_SERVER_APP_SECRET=""
