### ISSUE TITLE
Error ./start.ps1 'Starting Backend'

### ISSUE THREAD

**Issue by l8rpeace** [Azure-Samples/azure-search-openai-demo#666]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> _from root _folder Run__ azd up
> cd app
> ./start.ps1

### Any log messages given by the failure
>Starting backend
>
> 
>
>./backend_env/scripts/python.exe
>Usage: python -m quart run [OPTIONS]
>Try 'python -m quart run --help' for help.
>
> 
>
>Error: While importing 'main', an ImportError was raised:
>
> 
>
>Traceback (most recent call last):
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\quart\cli.py", line 175, in locate_app
>    module = import_module(module_name)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\main.py", line 1, in <module>
>    from app import create_app
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\app.py", line 30, in <module>
>    from approaches.readdecomposeask import ReadDecomposeAsk
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\approaches\readdecomposeask.py", line 7, in <module>
>    from langchain.agents import AgentExecutor, Tool
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\__init__.py", line 6, in <module>
>    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
>    from langchain.agents.agent import (
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\agents\agent.py", line 16, in <module>
>    from langchain.agents.tools import InvalidTool
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\agents\tools.py", line 8, in <module>
>    from langchain.tools.base import BaseTool, Tool, tool
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\tools\__init__.py", line 60, in <module>
>    from langchain.tools.powerbi.tool import (
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\tools\powerbi\tool.py", line 12, in <module>
>    from langchain.chains.llm import LLMChain
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\chains\__init__.py", line 40, in <module>
>    from langchain.chains.llm_math.base import LLMMathChain
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\langchain\chains\llm_math\base.py", line 9, in <module>
>    import numexpr
>  File "C:\Users\XXX\OpenaiChatProj\MarketplaceGPT\app\backend\backend_env\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
>    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
>ImportError: DLL load failed while importing interpreter: The specified module could not be found.

### Expected/desired behavior
> Local App starts, site should be navigable through localhost IP url and port

### OS and Version?
> Windows 11 pro

### azd version?
> azd v1.3.0

### Versions
> of this code? this was a fresh pull of this repo on 2023-09-21 at ~9 AM pacific

### Mention any other details that might be useful
> Python 3.11
> Node v18.17.1
> Not sure if this is a Langchain problem during the creation of the Python backend environment for running locally and, if so, how to amend the code to fix it. Tried wiping out the .env and starting again declaring the variables, running azd up. azd up worked successfully and the remote site in Azure actually works as expected every time. frontend build also appears to be successful in the log but no way to verify after this error while starting backend.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, well, you could remove langchain and the langchain-dependent code, since the two primary approaches linked from the website do not use langchain.

That'd require:
* removing langchain from https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/requirements.txt
* deleting approaches/readdecomposeask.py and approaches/readretrieveread.py
* removing references to those approaches in app.py https://github.com/Azure-Samples/azure-search-openai-demo/blob/f3cc2ad9c7de12aaa575cd5c4252efe1eaa400bd/app/backend/app.py#L30

You could also use GitHub Codespaces to develop, which shouldn't have an issue installing langchain. You can also try searching on the web or langchain issue tracker to see if other Windows users have had that error.

**Comment by pamelafox** [comment]
This is no longer an issue as the app code doesn't require langchain any more.
