### ISSUE TITLE
Automated setup for login and document level access control

### ISSUE THREAD

**Issue by mattmsft** [Azure-Samples/azure-search-openai-demo#669]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

It's difficult to setup the optional login and document level access control system due to the large amount of manual provisioning steps. Automate this so when you run `azd up` the necessary setup is performed.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
PR: https://github.com/Azure-Samples/azure-search-openai-demo/pull/891
