### ISSUE TITLE
Clear Chat button causes reappearing message

### ISSUE THREAD

**Issue by mattmsft** [Azure-Samples/azure-search-openai-demo#670]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
* Start a chat session by clicking on a suggested questions
* Get a response for one of the suggested questions
* Click the "Clear Chat" button
* Click on another suggested question
* Observe the old response that was cleared come back, before being replaced by the new response

### Any log messages given by the failure
* None, only visual

### Expected/desired behavior
* Cleared messages do not come back

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
* Reproducible on Windows 11 and Linux (Codespaces) hosts

### azd version?
> run `azd version` and copy paste here.
azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

### Versions
* Reproducible on main branch

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattmsft** [comment]
[Repro Video](https://1drv.ms/v/s!An-81_3EOirQnjO1eBPkUKUJiEjA?e=xDoQaT)

**Comment by nisar-snsw** [comment]
I'm able to reproduce the issue with the documentation seen on this issue. Can someone confirm that this is indeed fixed?

**Comment by pamelafox** [comment]
No, I cannot replicate. Please upload a video or GIF. Thanks!
