### ISSUE TITLE
Functions call response exceeds token length limit of 32

### ISSUE THREAD

**Issue by KesavarajaRK** [Azure-Samples/azure-search-openai-demo#672]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

### Any log messages given by the failure
> ERROR:root:Exception in /chat
Traceback (most recent call last):
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\app.py", line 109, in chat
    r = await impl.run_without_streaming(request_json["history"], request_json.get("overrides", {}))
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 223, in run_without_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(history, overrides, should_stream=False)
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 115, in run_until_final_call
    chat_completion = await openai.ChatCompletion.acreate(
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\backend_env\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\backend_env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "D:\Codes\SS-azure-search-openai-demo\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error processing your request. Sorry about that! You can retry your request, or contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 if you keep seeing this error. (Please include the request ID c6f75d34-b461-4127-ac18-4faa5672aafb in your email.) {
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 if you keep seeing this error. (Please include the request ID c6f75d34-b461-4127-ac18-4faa5672aafb in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

### Expected/desired behavior
> Trying to chat with open AI ends with this error.

### OS and Version?
> Windows 11 Pro 22H2

Using
param chatGptModelName string = (openAiHost == 'azure') ? 'gpt-35-turbo' : 'gpt-3.5-turbo'

### azd version?
> 1.3.0

### Versions
> gpt-35-turbo and version '0613'

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Can you set logging level to DEBUG in create_app() in app.py? That way you can see the URL that the OpenAI package tries to reach, and you can compare that URL to what you see in the Azure OpenAI studio.

**Comment by KesavarajaRK** [comment]
Made it to debug mode and here is the response.
 DEBUG:openai:message='Request to OpenAI API' method=post path=https://cog-i3bfirsmqnde4.openai.azure.com/openai/deployments/chat/chat/completions?api-version=2023-07-01-preview
 DEBUG:openai:api_version=2023-07-01-preview data='{"model": "gpt-35-turbo", "messages": [{"role": "system", "content": "Below is a history of the conversation so far, and a new question asked by the user that needs to be answered by searching in a knowledge base about Request proposal.\\nYou have access to Azure Cognitive Search index with 100\'s of documents.\\nGenerate a search query based on the conversation and the new question.\\nDo not include cited source filenames and document names e.g info.txt or doc.pdf in the search query terms.\\nDo not include any text inside [] or <<>> in the search query terms.\\nDo not include any special characters like \'+\'.\\nIf the question is not in English, translate the question to English before generating the search query.\\nIf you cannot generate a search query, return just the number 0.\\n"}, {"role": "assistant", "content": "Health plan cardio coverage"}, {"role": "user", "content": "does my plan cover cardio?"}, {"role": "assistant", "content": "Show available health plans"}, {"role": "user", "content": "What are my health plans?"}, {"role": "user", "content": "Generate search query for: What is the currency for the for the RFP for the provision of FINANCIAL AUDIT OF THE \\u201c9F0759.02 \\u2013 WWF MWIOPO POLICY WORKS\\u201d PROJECT?"}], "temperature": 0.0, "max_tokens": 32, "n": 1, "functions": [{"name": "search_sources", "description": "Retrieve sources from the Azure Cognitive Search index", "parameters": {"type": "object", "properties": {"search_query": {"type": "string", "description": "Query string to retrieve documents from azure search eg: \'Health care plan\'"}}, "required": ["search_query"]}}], "function_call": "auto"}' message='Post details'
 INFO:openai:message='OpenAI API response' path=https://cog-i3bfirsmqnde4.openai.azure.com/openai/deployments/chat/chat/completions?api-version=2023-07-01-preview processing_ms=1089.217 request_id=f9577fbb-c847-49eb-9b4c-1301d4d701db response_code=200
 ERROR:root:Exception in /chat
 Traceback (most recent call last):
   File "/tmp/8dbbf1cc345989e/app.py", line 109, in chat
     r = await impl.run_without_streaming(request_json["history"], request_json.get("overrides", {}))
   File "/tmp/8dbbf1cc345989e/approaches/chatreadretrieveread.py", line 223, in run_without_streaming
     extra_info, chat_coroutine = await self.run_until_final_call(history, overrides, should_stream=False)
   File "/tmp/8dbbf1cc345989e/approaches/chatreadretrieveread.py", line 126, in run_until_final_call
     query_text = self.get_search_query(chat_completion, history[-1]["user"])
   File "/tmp/8dbbf1cc345989e/approaches/chatreadretrieveread.py", line 276, in get_search_query
     arg = json.loads(function_call["arguments"])
   File "/opt/python/3.10.12/lib/python3.10/json/__init__.py", line 346, in loads
     return _default_decoder.decode(s)
   File "/opt/python/3.10.12/lib/python3.10/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/opt/python/3.10.12/lib/python3.10/json/decoder.py", line 353, in raw_decode
     obj, end = self.scan_once(s, idx)
 json.decoder.JSONDecodeError: Unterminated string starting at: line 2 column 19 (char 20)

Looks like completion api-version=2022-12-01 is given in OpenAI Studio and the app is using 2023-07-01-preview. 
How can I modify the version usage in the App?

**Comment by KesavarajaRK** [comment]
Found an solution. Issue is with this line. 

![issue](https://github.com/Azure-Samples/azure-search-openai-demo/assets/115058367/baa1e02d-0b59-439b-a856-c4e0c9db8b19)

For chat completion max_tokens are given as 32. Increased that and got the result.

**Comment by pamelafox** [comment]
Thank you for sharing! @srbalakr Can you check this out and update the max_tokens accordingly? https://github.com/Azure-Samples/azure-search-openai-demo/blob/c8b8486d68527026b0660a3a75cc4e5e376793c1/app/backend/approaches/chatreadretrieveread.py#L124
It sounds like 32 isn't enough for at least their responses with the new function calls approach.

**Comment by KesavarajaRK** [comment]
I have given a pull request regarding the fix. Modified the code to max_tokens=self.chatgpt_token_limit.
https://github.com/Azure-Samples/azure-search-openai-demo/pull/681

**Comment by KesavarajaRK** [comment]
Thanks for your response. Let me try your suggestion tomorrow and come back.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KesavarajaRK** [comment]
@srbalakr I configured function_call='none' and max_tokens = 32, I can see the response instead of Error.

**Comment by KesavarajaRK** [comment]
@srbalakr I configured function_call='none' and max_tokens = 32, I am able to see the response instead of

**Comment by pamelafox** [comment]
@KesavarajaRK I think we're also hoping to see why you were getting malformed JSON with the function_call. When you do have function_call enabled, can you see what is being returned? You can change this line in app.py:

logging.basicConfig(level=os.getenv("APP_LOG_LEVEL", "ERROR"))

to:

logging.basicConfig(level=os.getenv("APP_LOG_LEVEL", "DEBUG"))

And that should hopefully show you the OpenAI calls.

**Comment by pamelafox** [comment]
@KesavarajaRK Checking to see if you were able to add logging to see what the malformed JSON was.

**Comment by KesavarajaRK** [comment]
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/115058367/fc37aff6-b1a2-409c-a278-7c85d0da42fb)
Error is with chat completion message. 
I printed the JSON response from chat completion. 
 {
  "id": "chatcmpl-86Z2KNQ3s4dM5rhyQ5GAnzmNtk1nN",
  "object": "chat.completion",
  "created": 1696575340,
  "model": "gpt-35-turbo",
  "prompt_annotations": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [
    {
      "index": 0,
      "finish_reason": "length",
      "message": {
        "role": "assistant",
        "function_call": {
          "name": "search_sources",
          **"arguments": "{\n  \"search_query\": \"currency RFP provision FINANCIAL AUDIT 9F0759.02 WWF MW"**
        }
      },
      "content_filter_results": {}
    }
  ],
  "usage": {
    "completion_tokens": 32,
    "prompt_tokens": 283,
    "total_tokens": 315
  }
}

The arguments key in response has stringfied response which is not complete. Due to which we are not able to parse it as JSON and get the error.

**Comment by pamelafox** [comment]
Okay, I see, due to the nature of the question, ChatGPT felt it couldn't fit the response into 32 tokens. @srbalakr What's the drawback of increasing the token count? Or is there another approach?

**Comment by pamelafox** [comment]
We've now merged your PR, with an adjustment of max_tokens to 100. Thank you for filing and for the PR!
