### ISSUE TITLE
 Error communicating with OpenAI: URL has an invalid label

### ISSUE THREAD

**Issue by al34n1x** [Azure-Samples/azure-search-openai-demo#676]
When running `azd up` as part of the extracting text document, I get the following error message for every single PDF

`Error communicating with OpenAI: URL has an invalid label. --> skipping file
Processing`

I'm not an Azure-OpenAI user, I'm leveraging my OpenAI account.

When running from Azure, or even locally, I'm not getting a proper response to my prompts.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

This is the kind of response that I'm getting

![Screenshot 2023-09-26 at 19 35 05](https://github.com/Azure-Samples/azure-search-openai-demo/assets/9869723/7ccbb645-5dda-4b74-bb9f-e33379f0563d)

Thank you!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@carlotta94c Can you look into this, as they're using non-Azure OpenAI?

My general recommendation for debugging OpenAI errors is to set logging mode to debug in prepdocs.py:


logging.basicConfig(logging.DEBUG)


That will then show you the URL that OpenAI is trying to access, and you can compare that URL to what you expect it to be.

**Comment by mattmsft** [comment]
Do these instructions work for you?
https://github.com/Azure-Samples/azure-search-openai-demo#using-a-non-azure-openai-instance

> [Using a non-Azure OpenAI instance](https://github.com/Azure-Samples/azure-search-openai-demo#using-a-non-azure-openai-instance)
> To use an existing non-Azure OpenAI account, follow these steps before running azd up

> Run azd env set OPENAI_HOST openai
> Run azd env set OPENAI_ORGANIZATION {Your OpenAI organization}
> Run azd env set OPENAI_API_KEY {Your OpenAI API key}
> Run azd up
> You can retrieve your OpenAI key by checking [your user page](https://platform.openai.com/account/api-keys) and your organization by navigating to [your organization page](https://platform.openai.com/account/org-settings). Learn more about creating an OpenAI free trial at [this link](https://openai.com/pricing). Do not check your key into source control.

**Comment by al34n1x** [comment]
@pamelafox I'd try that and get back to you guys. Thanks!

@mattmsft I did follow those instructions. I'm even able to run other prompts and get responses from OpenAI. 


![Screenshot 2023-09-26 at 19 38 03](https://github.com/Azure-Samples/azure-search-openai-demo/assets/9869723/281924d1-dc70-41a4-a7f3-0c1d493596cd)

**Comment by landslidelabs** [comment]
I have the same error messages when using the latest version of the code base. I tried deploying from previous commit f3cc2ad9c7de12aaa575cd5c4252efe1eaa400bd and then everything works as expected.

**Comment by al34n1x** [comment]
Hi @landslidelabs, Thanks for your input. I tried your workaround but still getting the same error messages, even though I'm getting some TLS handshake errors with this commit. 

```
"{"type":"consoleMessage","timestamp":"2023-09-27T09:32:46.659403+02:00","data":{"message":"fetching token: failed to authenticate: server response error:\n Get \"https://login.microsoftonline.com/common/discovery/instance?api-version=1.1\u0026authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fcfd3592b-79fb-4abd-850c-2d42c8e31a1c%2Foauth2%2Fv2.0%2Fauthorize\": net/http: TLS handshake timeout\n""
```

**Comment by al34n1x** [comment]
Finally, I got it working by leveraging a two-week commit [2b92b50](https://github.com/Azure-Samples/azure-search-openai-demo/commit/2b92b50fb385b33286fba85091f953bc58195f05). 
Seems that the current code base introduces some issues when interfacing with OpenAI APIs.

Thank you!

**Comment by gabrielSoudry** [comment]
I confirmed, thank you @al34n1x, with this commit it works.

**Comment by pamelafox** [comment]
Thanks @wdfox ! Sorry about the regression, we don't have a great way to automatically test the shell scripts for different environment configurations. Fix is now merged, so you should be able to pull from main and try it.
