### ISSUE TITLE
Error starting backend locally

### ISSUE THREAD

**Issue by lshang0311** [Azure-Samples/azure-search-openai-demo#682]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Deploy to Azure - success
> 2.  Followed the steps in **Running locally**. 
        Step 3 failed (./start.sh)

### Any log messages given by the failure
>   File "/home/azure_samples/azure_search_openai_demo/app/backend/main.py", line 1, in <module>
    from app import create_app
  File "/home/azure_samples/azure_search_openai_demo/app/backend/app.py", line 29, in <module>
    from approaches.chatreadretrieveread import ChatReadRetrieveReadApproach
  File "/home/azure_samples/azure_search_openai_demo/app/backend/approaches/chatreadretrieveread.py", line 8, in <module>
    from approaches.approach import Approach
  File "/home/azure_samples/azure_search_openai_demo/app/backend/approaches/approach.py", line 4, in <module>
    from core.authentication import AuthenticationHelper
  File "/home/azure_samples/azure_search_openai_demo/app/backend/core/authentication.py", line 25, in <module>
    class AuthenticationHelper:
  File "/home/azure_samples/azure_search_openai_demo/app/backend/core/authentication.py", line 61, in AuthenticationHelper
    def get_auth_setup_for_client(self) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable
Failed to start backend

> 

### Expected/desired behavior
> Run locally 

### OS and Version?
>  Linux (Ubuntu 20.04.5 LTS)

### azd version?
> run `azd version` and copy paste here.

### Versions
> azd version 1.3.1 (commit b5030da0f29ffe98664c40450187fd8a4cb0d157)

### Mention any other details that might be useful
`azd env get-values` from terminal shows empty for Openai API:
OPENAI_API_KEY=""
OPENAI_HOST="azure"
OPENAI_ORGANIZATION=""

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Can you check your Python version? (python3 --version)
It looks like you may be using Python 3.8 or lower, this repository is currently only compatible with Python 3.9 or higher. Could you upgrade your Python version? 3.8 is fairly old at this point.

**Comment by lshang0311** [comment]
> Can you check your Python version? (python3 --version) It looks like you may be using Python 3.8 or lower, this repository is currently only compatible with Python 3.9 or higher. Could you upgrade your Python version? 3.8 is fairly old at this point.

I upgraded to 3.10 and working in a virtual environment. However, I still got the same error.

**Comment by lshang0311** [comment]
Thank you @pamelafox It is the Python version. I've upgraded Python to 3.10 and it works.

**Comment by pamelafox** [comment]
Great! Closing this, as we don't intend to support 3.8, given its age.
