### ISSUE TITLE
Select existing Azure Active Directory (AAD) groups for document-level authentication instead of creating new ones.

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#684]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

I was attempting to test document-level authentication and observed that we are creating sample groups. Is there a method to add/choose previously created groups and configure Azure Data Lake Storage Gen2 (ADLS Gen2) to enable document-level authentication?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vrajroutu** [comment]
@mabasile-MSFT Could you please share some insights on this?

**Comment by vrajroutu** [comment]
`async def get_group(self, group_name: str):  
    if not self.graph_headers:  
        token_result = await self.credentials.get_token("https://graph.microsoft.com/.default")  
        self.graph_headers = {"Authorization": f"Bearer {token_result.token}"}  
    async with aiohttp.ClientSession(headers=self.graph_headers) as session:  
        logging.info(f"Searching for group {group_name}...")  
        async with session.get(  
            f"https://graph.microsoft.com/v1.0/groups?$select=id&$top=1&$filter=displayName eq '{group_name}'"  
        ) as response:  
            content = await response.json()  
            if response.status != 200:  
                raise Exception(content)  
            if len(content["value"]) == 1:  
                group_id = content["value"][0]["id"]  
            else:  
                raise Exception(f"Group {group_name} not found")  
    logging.info(f"Group {group_name} ID {group_id}")  
    return group_id  
`
In the above `adlsgen2setup.py`  to retrive group id's from the group names in `sampleacls.json`



`{  
    "files": {  
        "Benefit_Options.pdf": {  
            "directory": "benefitinfo"  
        },  
        "employee_handbook.pdf": {  
            "directory": "employeeinfo"  
        },  
        "Northwind_Health_Plus_Benefits_Details.pdf": {  
            "directory": "benefitinfo"  
        },  
        "Northwind_Standard_Benefits_Details.pdf": {  
            "directory": "benefitinfo"  
        },  
        "PerksPlus.pdf": {  
            "directory": "benefitinfo"  
        },  
        "role_library.pdf": {  
            "directory": "employeeinfo"  
        }  
    },  
    "directories": {  
        "employeeinfo": {  
            "groups": ["All-KGPCO-IT"]  
        },  
        "benefitinfo": {  
            "groups": ["AADGRUP-1", "AADGRUP-2"]  
        },  
        "/": {  
            "groups": ["AADGRUP-2"]  
        }  
    },  
    "groups": [  
        "AADGRUP-1",  
        "AADGRUP-2"  
    ]  
}  
`

**Comment by vrajroutu** [comment]
Also noticed this error when trying to login to the webapp.

Redirect URI is set properly to `https://<your-endpoint>.azurewebsites.net/redirect` in the `client app`

<img width="636" alt="Screenshot 2023-09-28 at 1 05 41 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/d04c72a5-ee4f-4665-83b4-96b903960534">

**Comment by mattmsft** [comment]
> @mattmsft Could you please share some insights on this?

What you can do is change the display names in the sampleacls.json folder.
 
So instead of GPTKB_AdminTest, replace it with your actual group display name.

**Comment by mattmsft** [comment]
> Also noticed this error when trying to login to the webapp.
> 
> Redirect URI is set properly to `https://<your-endpoint>.azurewebsites.net/redirect` in the `client app`
> 
> <img alt="Screenshot 2023-09-28 at 1 05 41 AM" width="636" src="https://user-images.githubusercontent.com/22155528/271179663-d04c72a5-ee4f-4665-83b4-96b903960534.png">

I have personally not seen this error. Try navigating to https://<your-endpoint>.azurewebsites.net/auth_setup and please share what is set for 'redirectUri' under 'auth' in 'msalConfig'. Also please check if useLogin is set to true

**Comment by vrajroutu** [comment]
@mattmsft  As per the instructions i did setup `https://<your-endpoint>.azurewebsites.net/redirect` in app-registrations `client-app`

**Comment by mattmsft** [comment]
Hello @vrajroutu ,

Unfortunately, there are currently many manual steps required to setup auth and even a small mistake can cause a problem. We are planning on automating this in the future more extensively.

I am asking to do some manual troubleshooting because even small errors may be missed.
1. Navigate to `https://<your-endpoint>.azurewebsites.net/auth_setup` and share the following information:
    1. What is the `redirectUri` under the `auth` section?
1. Navigate to your app manifest in the Azure portal https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#configure-the-app-manifest
2. Please share the following information
    1. Under `"replyUrlsWithType"`, is there an entry that corresponds to the following:
```
{
	"url": "https://your-endpoint.azurewebsites.net/redirect",
	"type": "Spa"
},
```
Is there an entry in the manifest with the following value?
```
"oauth2AllowIdTokenImplicitFlow": true,
```

**Comment by vrajroutu** [comment]
@mattmsft  i figured the issue. It is now working as expected. Thanks for your contribution

Here is the output of `https://<your-endpoint>.azurewebsites.net/auth_setup`

`{"loginRequest":{"scopes":[".default"]},"msalConfig":{"auth":{"authority":"https://login.microsoftonline.com/xxxxxxxxxxx","clientId":"xxxxxxxxxxx","navigateToLoginRequestUrl":false,"postLogoutRedirectUri":"/","redirectUri":"/redirect"},"cache":{"cacheLocation":"sessionStorage","storeAuthStateInCookie":false}},"tokenRequest":{"scopes":["api://xxxxxxxxxxxx/access_as_user"]},"useLogin":true}`



@mattmsft  It is now working as expected. I think global tenant admin should `Grant admin consent`

**Comment by mattmsft** [comment]
> @mattmsft i figured the issue. It is now working as expected. Thanks for your contribution
> 
> Here is the output of `https://<your-endpoint>.azurewebsites.net/auth_setup`
> 
> `{"loginRequest":{"scopes":[".default"]},"msalConfig":{"auth":{"authority":"https://login.microsoftonline.com/xxxxxxxxxxx","clientId":"xxxxxxxxxxx","navigateToLoginRequestUrl":false,"postLogoutRedirectUri":"/","redirectUri":"/redirect"},"cache":{"cacheLocation":"sessionStorage","storeAuthStateInCookie":false}},"tokenRequest":{"scopes":["api://xxxxxxxxxxxx/access_as_user"]},"useLogin":true}`
> 
> @mattmsft It is now working as expected. I think global tenant admin should `Grant admin consent`

This is interesting - does your tenant admin have a policy that new apps require consent?
https://learn.microsoft.com/en-us/microsoft-365/admin/misc/user-consent?view=o365-worldwide

**Comment by vrajroutu** [comment]
@mattmsft Yes, I guess this is a policy that requires any new app provisioned in Azure to be approved by an admin to grant admin consent, at least in our organization

**Comment by mattmsft** [comment]
Thank you very much for your follow up. I will close this issue as your problem is resolved.

Our next steps:
1. Document that a policy setup by your tenant admin can make admin consent required, regardless of app setup.

I appreciate your troubleshooting here!
