### ISSUE TITLE
Updating the documents in the Data folder without re-deploying. 

### ISSUE THREAD

**Issue by dan-angelson** [Azure-Samples/azure-search-openai-demo#685]
If the only thing I need to change is the documents in the Data folder, is there any way to update the app without taking it down and re-deploying from scratch?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MayankSingh173** [comment]
@pamelafox There's no question like "How can we upload additional PDFs without redeploying everything?" in FAQs.

**Comment by pamelafox** [comment]
That is now available in a standalone guide here: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md#indexing-additional-documents
