### ISSUE TITLE
TypeError errors with Python 3.8

### ISSUE THREAD

**Issue by niceysj2** [Azure-Samples/azure-search-openai-demo#69]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> After install I ran start.ps1 and the web service is not runining.  

### Any log messages given by the failure
> PS C:\Users\niceysj\app> .\start.ps1

Loading azd .env file from current environment

Creating python virtual environment "backend/backend_env"

Restoring backend python packages

Requirement already satisfied: azure-identity==1.13.0b3 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 1)) (1.13.0b3)
Requirement already satisfied: Flask==2.2.2 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: langchain==0.0.78 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 3)) (0.0.78)
Requirement already satisfied: openai==0.26.4 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 4)) (0.26.4)
Requirement already satisfied: azure-search-documents==11.4.0b3 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 5)) (11.4.0b3)
Requirement already satisfied: azure-storage-blob==12.14.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from -r requirements.txt (line 6)) (12.14.1)
Requirement already satisfied: six>=1.12.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-identity==1.13.0b3->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: azure-core<2.0.0,>=1.11.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-identity==1.13.0b3->-r requirements.txt (line 1)) (1.26.3)
Requirement already satisfied: msal<2.0.0,>=1.20.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-identity==1.13.0b3->-r requirements.txt (line 1)) (1.21.0)
Requirement already satisfied: cryptography>=2.5 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-identity==1.13.0b3->-r requirements.txt (line 1)) (40.0.1)
Requirement already satisfied: msal-extensions<2.0.0,>=0.3.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-identity==1.13.0b3->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: importlib-metadata>=3.6.0; python_version < "3.10" in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Flask==2.2.2->-r requirements.txt (line 2)) (6.1.0)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Flask==2.2.2->-r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: click>=8.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Flask==2.2.2->-r requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Flask==2.2.2->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Flask==2.2.2->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: PyYAML<7,>=6 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (6.0)
Requirement already satisfied: pydantic<2,>=1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (1.10.7)
Requirement already satisfied: requests<3,>=2 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: numpy<2,>=1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (1.24.2)
Requirement already satisfied: SQLAlchemy<2,>=1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (1.4.47)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (0.5.7)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from langchain==0.0.78->-r requirements.txt (line 3)) (8.2.2)
Requirement already satisfied: tqdm in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from openai==0.26.4->-r requirements.txt (line 4)) (4.65.0)
Requirement already satisfied: aiohttp in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from openai==0.26.4->-r requirements.txt (line 4)) (3.8.4)
Requirement already satisfied: isodate>=0.6.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-search-documents==11.4.0b3->-r requirements.txt (line 5)) (0.6.1)
Requirement already satisfied: azure-common~=1.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-search-documents==11.4.0b3->-r requirements.txt (line 5)) (1.1.28)
Requirement already satisfied: msrest>=0.7.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-storage-blob==12.14.1->-r requirements.txt (line 6)) (0.7.1)
Requirement already satisfied: typing-extensions>=4.0.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from azure-core<2.0.0,>=1.11.0->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: PyJWT[crypto]<3,>=1.0.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from msal<2.0.0,>=1.20.0->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: cffi>=1.12 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from cryptography>=2.5->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (1.15.1)
Requirement already satisfied: portalocker<3,>=1.6; python_version >= "3.5" and platform_system == "Windows" in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from msal-extensions<2.0.0,>=0.3.0->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: zipp>=0.5 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from importlib-metadata>=3.6.0; python_version < "3.10"->Flask==2.2.2->-r requirements.txt (line 2)) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from Werkzeug>=2.2.2->Flask==2.2.2->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: colorama; platform_system == "Windows" in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from click>=8.0->Flask==2.2.2->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from requests<3,>=2->langchain==0.0.78->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from requests<3,>=2->langchain==0.0.78->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from requests<3,>=2->langchain==0.0.78->-r requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from requests<3,>=2->langchain==0.0.78->-r requirements.txt (line 3)) (1.26.15)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))) in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from SQLAlchemy<2,>=1->langchain==0.0.78->-r requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.78->-r requirements.txt (line 3)) (1.5.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.78->-r requirements.txt (line 3)) (3.19.0)
Requirement already satisfied: typing-inspect>=0.4.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.78->-r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from aiohttp->openai==0.26.4->-r requirements.txt (line 4)) (22.2.0)
Requirement already satisfied: requests-oauthlib>=0.5.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from msrest>=0.7.1->azure-storage-blob==12.14.1->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: pycparser in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from cffi>=1.12->cryptography>=2.5->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (2.21)
Requirement already satisfied: pywin32>=226; platform_system == "Windows" in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from portalocker<3,>=1.6; python_version >= "3.5" and platform_system == "Windows"->msal-extensions<2.0.0,>=0.3.0->azure-identity==1.13.0b3->-r requirements.txt (line 1)) (306)
Requirement already satisfied: packaging>=17.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from marshmallow<4.0.0,>=3.3.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.78->-r requirements.txt (line 3)) (23.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.78->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\niceysj\app\backend\backend_env\lib\site-packages (from requests-oauthlib>=0.5.0->msrest>=0.7.1->azure-storage-blob==12.14.1->-r requirements.txt (line 6)) (3.2.2)
WARNING: You are using pip version 20.1.1; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\niceysj\app\backend\backend_env\scripts\python.exe -m pip install --upgrade pip' command.

Restoring frontend npm packages

up to date, audited 122 packages in 833ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Building frontend

> frontend@0.0.0 build
> tsc && vite build

vite v4.1.1 building for production...
✓ 1250 modules transformed.
../backend/static/index.html                    0.49 kB
../backend/static/assets/github-fab00c2d.svg    0.96 kB
../backend/static/assets/index-6b2c2cfa.css     7.46 kB │ gzip:   2.20 kB
../backend/static/assets/index-3d122da9.js    625.76 kB │ gzip: 204.86 kB │ map: 5,057.29 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

Starting backend

Traceback (most recent call last):
  File "./app.py", line 12, in <module>
    from approaches.chatreadretrieveread import ChatReadRetrieveReadApproach
  File "C:\Users\niceysj\app\backend\approaches\chatreadretrieveread.py", line 10, in <module>
    class ChatReadRetrieveReadApproach(Approach):
  File "C:\Users\niceysj\app\backend\approaches\chatreadretrieveread.py", line 51, in ChatReadRetrieveReadApproach
    def run(self, history: list[dict], overrides: dict) -> any:
TypeError: 'type' object is not subscriptable

### Expected/desired behavior
>

### OS and Version?
> Windows Server 2022 

### Versions
>Powershell 7

### Mention any other details that might be useful
![Error](https://user-images.githubusercontent.com/129363234/228796419-7aa8fe51-d46b-4c19-b29c-1aeb64743c35.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pablocastro** [comment]
@niceysj2 can you check what version of Python you have installed? This error can happen with older (<=3.9?) versions of Python when there was no syntax for generic type hints out of the box.

**Comment by niceysj** [comment]
> @niceysj2 can you check what version of Python you have installed? This error can happen with older (<=3.9?) versions of Python when there was no syntax for generic type hints out of the box. Ideally you'd be using Python 3.10, that's what we tested the sample with.

Thanks very much.
After upgrade to Python3.10 installation went well!!!
Thanks.

**Comment by pamelafox** [comment]
Closing as we won't be supporting Python 3.8.
