### ISSUE TITLE
The request is invalid. Details: Cannot find nested property 'oids' on the resource type 'search.documentFields'.

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#690]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

When running the `prepdocs.sh` script and attempting to index documents from Azure Data Lake Storage Gen2 (ADLS Gen2), I encounter the following error

```
Batch Completed. Batch size  3 Token count 537
        Got an error while reading vcontracts/testing-contract.pdf -> () The request is invalid. Details: Cannot find nested property 'oids' on the resource type 'search.documentFields'.
Code:
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vrajroutu** [comment]
@mabasile-MSFT  FYI;  Did you notice this issue?

**Comment by pamelafox** [comment]
cc @mattmsft

**Comment by vrajroutu** [comment]
@mattmsft @pamelafox 

I've identified the issue: 'oid's and 'group id's are not being created in Cognitive Search. To resolve this, you should execute the following command:

`./scripts/manageacl.ps1 --acl-action enable_acls`

before running:

`./scripts/prepdocs.sh`

Please update the documentation accordingly to include these steps for users encountering similar issues

**Comment by mattmsft** [comment]
> @mattmsft @pamelafox
> 
> I've identified the issue: 'oid's and 'group id's are not being created in Cognitive Search. To resolve this, you should execute the following command:
> 
> `./scripts/manageacl.ps1 --acl-action enable_acls`
> 
> before running:
> 
> `./scripts/prepdocs.sh`
> 
> Please update the documentation accordingly to include these steps for users encountering similar issues

Hi @vrajroutu ,

Sorry you ran into this problem. I attempted to document this issue in the LoginAndAcl.md readme, but I can try to improve the documentation
