### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by sunnygambit** [Azure-Samples/azure-search-openai-demo#696]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
tried Quart_cors and added the below code. but still getting cors error:

CORS_SETTINGS = {'allow_origin': '*'}
def create_app():
    if os.getenv("APPLICATIONINSIGHTS_CONNECTION_STRING"):
        configure_azure_monitor()
        AioHttpClientInstrumentor().instrument()
    app = Quart(__name__)
    app = cors(app, **CORS_SETTINGS)
    app.register_blueprint(bp)
    app.asgi_app = OpenTelemetryMiddleware(app.asgi_app)
    # Level should be one of https://docs.python.org/3/library/logging.html#logging-levels
    logging.basicConfig(level=os.getenv("APP_LOG_LEVEL", "ERROR"))
    return app
>

### Any log messages given by the failure
Access to fetch at 'https://app-backend-3utgcchwhv4yw.azurewebsites.net/chat_stream' from origin 'https://enablixmaster.ebxlocal.com:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I haven't tried out Quart CORS yet. I wanted to add CORS configurability to this repo anyway, so I will try it out soon and report back. You can also try putting the exact URI instead of *, since * should typically be avoided.

**Comment by pamelafox** [comment]
From a quick glance of the docs, I suspect that you need to explicitly allow POST, like this example:

```
@app.route('/', methods=["POST"])
@route_cors(
    allow_headers=["content-type"],
    allow_methods=["POST"],
    allow_origin=["https://quart.com"],
)
async def handler():
    data = await request.get_json()
    ...
```

**Comment by pamelafox** [comment]
Actually, I think we need to set CORS on App Service instead. I will have a PR soon.

**Comment by pamelafox** [comment]
See my PR here: https://github.com/Azure-Samples/azure-search-openai-demo/pull/717

**Comment by sunnygambit** [comment]
@pamelafox I did same as you did in create_app function but didn't work. I don't know why. Thanks

**Comment by pamelafox** [comment]
You also need the Bicep change, `azd env set ALLOWED_ORIGIN`, and to re-run azd up.

**Comment by pamelafox** [comment]
Check CORS tab in Azure Portal for your App Service. If you followed steps, you should see the custom origin listed.
