### ISSUE TITLE
Postprovision hook fails if repository is cloned to a path containing spaces

### ISSUE THREAD

**Issue by amithkk** [Azure-Samples/azure-search-openai-demo#70]
### This issue is for a: (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

- Clone the repository to a path with spaces (example - `C:\Ex Path\azure-openai-search`) with `azd init -t azure-search-openai-demo` 
- Run `azd up`. Observe that the post-provision script fails

### Any log messages given by the failure

- `prepdocs.py: error: unrecognized arguments: Path\azure-openai-search/data/*`

### Expected/desired behavior

- Sample works when cloned to a path with spaces

### OS and Version?

Windows 11

### Additional comments

This is caused due to the $cwd variable not being quoted in the powershell launch script

**Comment by jmasengeshomsft** [comment]
This is still a problem
