### ISSUE TITLE
once we modify after our initial deployment it keeps on pulling the original file 

### ISSUE THREAD

**Issue by mkhazen** [Azure-Samples/azure-search-openai-demo#714]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I deleted a lot of the original data and uploaded new files/data for my use case - if i deploy the app it works fine , but once after a successful deployment, if i try to re-deploy the app it keeps on pulling the data PDF forms from the original Azure sample - how can we stop this?

### Any log messages given by the failure
>

### Expected/desired behavior
> should not pull back after a second deploy the original files we have deleted

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
To clear out the old data, you need to remove it. You can do that by specifying --removeall to prepdocs.py (in prepdocs.sh/prepdocs.ps1) or --remove with a specific document name. If you're already uploaded your own data, you may want to --remove one doc at a time.

**Comment by mattmsft** [comment]
Are you calling “ azd init -t azure-search-openai-demo” every time? Or calling azd up from the same repo every time

**Comment by mkhazen** [comment]
yes i stop initializing and his has stopped it from downloasing

**Comment by pamelafox** [comment]
The `azd init` command should only be run once, it is essentially the same as doing a git clone. Is your issue resolved now?
