### ISSUE TITLE
Unexepected charges

### ISSUE THREAD

**Issue by Aloncarrasco** [Azure-Samples/azure-search-openai-demo#715]
I started the server with azd up, and it created the azure resources for cognitive search. It keeps on adding me more money to pay even though I deleted all the reseources created. How can i know if it will actually stop charging me?? 

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
make the auth login.
execute azd up

### Any log messages given by the failure
>

### Expected/desired behavior
The azure should stop charging me with a service which i am not using. I dont really understand how to fix this problem.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Sorry to hear @Aloncarrasco, can you provide more details on where you're seeing the budget usage? Have you tried filing a support request in the Azure Portal? Sometimes they have more access to accounts and can provide more insight. (And if you're being charged accidentally, perhaps you can ask for a refund).

**Comment by Aloncarrasco** [comment]
I am on the 'Cost Management + Billing' section. The 'cost analysis' section showed it was from cognitive search. I deleted the resources some time ago but the charges increased. If they keep on increasing i am probably leaving a ticket or contacting microsoft support.
