### ISSUE TITLE
what is KB_FIELDS_CONTENT, KB_FIELDS_CATEGORY, KB_FIELDS_SOURCEPAGE ?

### ISSUE THREAD

**Issue by novoforce** [Azure-Samples/azure-search-openai-demo#72]
I was trying to run the notebook present in notebooks folder.

Could anyone tell me what is: KB_FIELDS_CONTENT, KB_FIELDS_CATEGORY, KB_FIELDS_SOURCEPAGE variables present in the notebook ?

**Comment by davidcervigon** [comment]
Matches the fields in Azure Search index, I think
![image](https://user-images.githubusercontent.com/98492389/228952595-c4b0ddc9-5b5e-4842-94a0-848cfea52c03.png)

**Comment by pablocastro** [comment]
These variables indicate the names of the fields with each of those roles (which field has the main content, which one indicates the category, and which one is the name of the source file). They are in variables to make it easy to change if you want to point this to your own index.

**Comment by mkhazen** [comment]
If i need to extract the document file name (metadata) does the sourcefile or sourcepage contain this data or should i create a new index  to include the following: { "name": "metadata_storage_name", "type": "Edm.String", "searchable": false, "filterable": true, "sortable": true  },
