### ISSUE TITLE
The command is wrong in readme.md it should be `azd env set ALLOWED_ORIGIN https://<your-domain.com>`

### ISSUE THREAD

**Issue by sunnygambit** [Azure-Samples/azure-search-openai-demo#722]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks! Fixing in https://github.com/Azure-Samples/azure-search-openai-demo/pull/723
