### ISSUE TITLE
Existing OpenAI resource - missing openai key env step

### ISSUE THREAD

**Issue by DAVMUNDY** [Azure-Samples/azure-search-openai-demo#727]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Looking at the steps to use your own/existing OpenAI service, I assume the steps below are missing setting the OpenAI API key? 
azd env set OPENAI_API_KEY xxxxxxx

`[Existing OpenAI resource](https://github.com/Azure-Samples/azure-search-openai-demo#existing-openai-resource)
Run azd env set AZURE_OPENAI_SERVICE {Name of existing OpenAI service}
Run azd env set AZURE_OPENAI_RESOURCE_GROUP {Name of existing resource group that OpenAI service is provisioned to}
Run azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT {Name of existing ChatGPT deployment}. Only needed if your ChatGPT deployment is not the default 'chat'.
Run azd env set AZURE_OPENAI_EMB_DEPLOYMENT {Name of existing GPT embedding deployment}. Only needed if your embeddings deployment is not the default 'embedding'.`

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
For Azure OpenAI, we use managed identity and set the access roles in main.bicep, even for existing resources. We only support the use of keys for non-Azure OpenAI (since that's all they support), and that's detailed here: https://github.com/Azure-Samples/azure-search-openai-demo#using-a-non-azure-openai-instance

You can learn more about keyless auth for Azure OpenAI in my blog post here:

http://blog.pamelafox.org/2023/09/best-practices-for-openai-chat-apps-go.html

**Comment by DAVMUNDY** [comment]
Thanks Pamela, that makes sense! I thought the key was being used when I saw the env variables.

**Comment by DAVMUNDY** [comment]
thanks for prompt response
