### ISSUE TITLE
Limited openAiResourceGroup location options(Westeurope not included)

### ISSUE THREAD

**Issue by suma-sai-paluri** [Azure-Samples/azure-search-openai-demo#732]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I have previously deployed using this repository. However, there used to be an option for the "westeurope" region, but now it seems to be unavailable. Consequently, when we attempt to deploy using the repositories like [22a45dc](https://chat.openai.com/c/url) and [22a45dc](https://chat.openai.com/c/url), it becomes confusing when we reach the step where we need to select a region of openAiResourceGroupLocation because all of our resources are located in "westeurope."

Could you please advise me on what I should select in my particular case? Additionally, I'm curious about why there are only a few locations available in the options. Does this have any impact on the deployments? If not, why aren't more locations included? Your inputs will be of great help
![Screenshot 2023-10-04 153741](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/fa31fb0d-d251-48a9-8e8f-569cadb741ac)
. Thank you.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That list is based on https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability - westeurope isn't an option for latest version of models, so you'll need to pick a different one for the OpenAI resources.

**Comment by suma-sai-paluri** [comment]
Thank you @pamelafox  for your prompt response. Can i change the version of the models and the locations to the list in the main.bicep file and work on the latest repos?
