### ISSUE TITLE
Setup access control for each department to chat on their own data

### ISSUE THREAD

**Issue by nselvase** [Azure-Samples/azure-search-openai-demo#736]
### **This is not an issue but more of trying to understand the possibility of how can we setup access control for each department to chat on their own data (without seeing other department data) using one centralized chat app.

Can you suggest some ideas to implement this feature ?**

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nselvase** [comment]
Thank you for directing to this documentation. Very helpful.

**Comment by pamelafox** [comment]
Great, I'll close this issue, please open a new one if you have additional questions or run into issues implementing it. We hope to automate the authentication setup in the future.
