### ISSUE TITLE
prepdocs refactor

### ISSUE THREAD

**Issue by mattgotteiner** [Azure-Samples/azure-search-openai-demo#747]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Supporting indexers in addition to a manual approach

**Comment by mattmsft** [comment]
1. azd up doesn't have to re-index if you already indexed

**Comment by mattmsft** [comment]
2. think more about exposing manual vs. indexer approach

**Comment by mattmsft** [comment]
transition away from global -> class based interface
