### ISSUE TITLE
How to keep the Azure deployed Application with Ongoing Updates. 

### ISSUE THREAD

**Issue by waqasjavedkhan** [Azure-Samples/azure-search-openai-demo#750]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
@pamelafox I deployed this application in Azure. I would like to keep my version of the application up-to-date with ongoing changes to this project. What is the best way to keep my version of the application up to date? 

I cloned this project in Github Codespaces and deployed it in an Azure tenant. And I have uploaded my own PDF dataset in my version/deployed/cloned application. I only want to keep the application up-to-date without replacing the PDF dataset. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Here's what I suggest:

1. Pull latest changes from upstream/main (this repo) using the sync button on your fork of the repo
2. Delete the postprovision hooks from azure.yaml to avoid re-indxing
3. Run "azd deploy". You may sometimes need to run "azd up" if infra/ files have changed, but most of time you only need to deploy new code. 

Let me know if thats unclear.

**Comment by pamelafox** [comment]
For step 2, you'd delete lines 23-34 in azure.yaml:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/7b2e88733f1557aa5480f0b1324aee73ac4e2845/azure.yaml#L23
It then shouldn't matter that you're seeing new docs, since the prepdocs script shouldn't run.

cc @mattmsft who is thinking about ways to improve the prepdocs process.

**Comment by zhongshuai-cao** [comment]
For me as I am actively developing customization on top of this great repo, I keep doing git rebase if I am free or see major updates...

I doubt if there are any better approaches...
