### ISSUE TITLE
Not all pages containing chunk are displayed in PDF preview when chunk spans several pages

### ISSUE THREAD

**Issue by Timmate** [Azure-Samples/azure-search-openai-demo#763]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> Each chunk can span a few pages, but not more than 2 with the standard settings (i.e., chunk size, etc.). When a chunk is used to answer the user's question and that chunk spans two pages, both pages should be displayed in the PDF preview when clicking on the citation for that chunk. Currently, only the page where such a chunk begins is showed.

### OS and Version?
> Windows 10. Linux (Debian)

**Comment by pamelafox** [comment]
We are thinking of changing the UI to display the entire PDF with an anchor link to jump to the page, so I think that would end up addressing this issue as well.

**Comment by plasma-vision** [comment]
@pamelafox That would be a much better way to do it. Is there a branch where this feature is being worked on?

**Comment by pamelafox** [comment]
Ah, I made the change in https://github.com/Azure-Samples/azure-search-openai-demo/pull/840 and merged to main on Friday, so I'll close this issue now.
