### ISSUE TITLE
Removing Thought Process from UI

### ISSUE THREAD

**Issue by marcosclub** [Azure-Samples/azure-search-openai-demo#769]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> How can we remove "thought process" from the UI? Thanks!!!
<img width="354" alt="Captura de pantalla 2023-10-10 a las 11 19 07" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/119492742/72146576-881d-43c5-b789-f7f2eb0e6bc0">

### OS and Version?
> macOS 

### azd version?
> 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This branch shows how to do it:

https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...pamelafox:azure-search-openai-demo:rm-thoughtprocess?expand=1

You need to remove the icon as well as the tab.

**Comment by marcosclub** [comment]
Thank you, Pamela!

**Comment by erg-hzhou** [comment]
@pamelafox do you know where I can find the steps or docs to remove "thoughtprocess" icon and tab? Thanks
