### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 2 column 3 (char 4)

### ISSUE THREAD

**Issue by sreesankar12** [Azure-Samples/azure-search-openai-demo#774]
![Screenshot from 2023-10-09 16-23-25](https://github.com/Azure-Samples/azure-search-openai-demo/assets/117965671/be3a985a-183b-4170-a170-fc887c1468c2)
azd version 1.3.1

When i tried to print the data .it is observed that an incomplete json data is received.
arguments key in the first json data misses an ending double quote and a closing bracket.
which is stored to search query.
while tried to load this json using json.loads() this error occures.
is there anything i should do ?

This occurs rarely.
The package is doing exceptionally good.Thanks to all collaborators.

```
  File "/home/sayone/Documents/azureaichatbot/app/backend/approaches/chatreadretrieveread.py", line 251, in run_with_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(
  File "/home/sayone/Documents/azureaichatbot/app/backend/approaches/chatreadretrieveread.py", line 140, in run_until_final_call
    query_text = self.get_search_query(chat_completion, history[-1]["user"])
  File "/home/sayone/Documents/azureaichatbot/app/backend/approaches/chatreadretrieveread.py", line 295, in get_search_query
    arg = json.loads(function_call["arguments"])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 2 column 3 (char 4)
[2023-10-09 15:52:40 +0530] [49575] [INFO] 127.0.0.1:36380 POST /chat_stream 1.1 500 - 2899037
```

**Comment by pamelafox** [comment]
Interesting, when this happened before (https://github.com/Azure-Samples/azure-search-openai-demo/issues/672), it was due to the search query exceeding 32 tokens, but your search query doesn't seem to be 32 tokens long. I'm curious, does it help if you increase max_tokens in the first ChatCompletion.acreate call to a higher number?

**Comment by sreesankar12** [comment]
max_tokens was 32 ,updated to 64 now.Lets see if occures again.
Also is there anyway to include more detail in the response ?

**Comment by pamelafox** [comment]
@sreesankar12 To include more details in response, I suggest tweaking the prompt to tell ChatGPT to be more verbose, descriptive, include more details, etc. You can also change "top" (documents to retrieve) to a higher number to see how that improves response.

@srbalakr I also received this error today from the query generation call to ChatGPT, so I think we should increase it from 32. Is there any drawback to a higher max token, besides using up more budget? Is the concern that it will generate keyword searches that don't work well with Azure Cognitive Search?

**Comment by pamelafox** [comment]
Here's an example response which shows this error - likely due to "async" being a non-standard word that can't be tokenized easily:

``
{
  "id": "chatcmpl-8AL0tTberM6X2JsSgqdIOvsUHYvBM",
  "object": "chat.completion",
  "created": 1697474747,
  "model": "gpt-35-turbo",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [
    {
      "index": 0,
      "finish_reason": "length",
      "message": {
        "role": "assistant",
        "content": "search_sources({\n  \"search_query\": \"writing tests using async\"\n})",
        "function_call": {
          "name": "search_sources",
          "arguments": "{\n  \"search_query\": \""
        }
      },
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "usage": {
    "prompt_tokens": 260,
    "completion_tokens": 29,
    "total_tokens": 289
  }
}
```

**Comment by pamelafox** [comment]
We've merged a PR that increases max_tokens to 100 which seems to work well for all the high-token queries I've seen. I'll close this issue. If anyone encounters in the future with max_tokens =100, please share your query. Thanks!

**Comment by sreesankar12** [comment]
Hi @pamelafox ,
Are we using azure AI search only in step 2 of chatreadretriveread.py while chating with the bot ?
just experimenting with a different model for such search results.
