### ISSUE TITLE
Existing OpenAI resource, "The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' ."

### ISSUE THREAD

**Issue by gabrielSoudry** [Azure-Samples/azure-search-openai-demo#776]
I just want to deploy an demo app without having access to Azure OpenAI using my OpenAI account. 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
azd init -t azure-search-openai-demo
azd env set OPENAI_API_TYPE openai
azd env set OPENAI_API_KEY <MY_KEY>
azd env set OPENAI_ORGANIZATION My ORganisation id
azd up

### Any log messages given by the failure
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is '5ed3e53d-3eef-43e1-ac88-8b23090f746c'. See inner errors for details.
SpecialFeatureOrQuotaIdRequired: The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' .

### Expected/desired behavior
To not deploy openai azure, I'm sorry if I missed a point

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Ubuntu 22.04

### azd version?
> run `azd version` and copy paste here.
> azd version

### Versions
azd version 1.4.1 (commit 1cbed85cf47ed235b5ed31868eda79619525bfcc)

Seem related to : 
https://github.com/Azure-Samples/azure-search-openai-demo/pull/507

**Comment by pamelafox** [comment]
It looks like you didn't set the correct env vars? Our readme suggests different ones:

https://github.com/Azure-Samples/azure-search-openai-demo#openaicom-openai

Specifically, OPENAI_HOST, not OPENAI_API_TYPE. Did you get OPENAI_API_TYPE from some document?

**Comment by gabrielSoudry** [comment]
I'm sorry, I'm totally blind thank you very much 😔🙏🙏
