### ISSUE TITLE
Token Errors when using oid and group id check enabled

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#777]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
<img width="1229" alt="Screenshot 2023-10-12 at 12 28 29 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/a6e37186-e703-4f63-bef5-52b4097e5818">

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

`{
    "error": "invalid_client",
    "error_description": "AADSTS500116: The reply uri specified in the request is not a valid URL. Allowed schemes: '*'.\r\nTrace ID: 30ef56ba-316c-46fe-bb75-8767e39a4a00\r\nCorrelation ID: d53vsvr51-30f8-4cf6-bf1e-83e55a6s4db5c5\r\nTimestamp: 2023-10-12 04:28:06Z",
    "error_codes": [
        500116
    ],
    "timestamp": "2023-10-12 04:28:06Z",
    "trace_id": "30ef56ba-316c-46fe-bb75-8767e39a4a00",
    "correlation_id": "d53vsvr51-30f8-4cf6-bf1e-83e55a6s4db5c5"
}`

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vrajroutu** [comment]
CC : @mattmsft

**Comment by mattmsft** [comment]
HI @mattjames1978 thanks for the feedback. I agree that combining the [built-in authorization](https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) and the login on the page is ideal. We can consider adding the ability to link these two methods as a future enhancement. I will file an issue about this.

Agreed that enforcing oid and group security filters via an environment variable would be a useful enhancement. I will file an issue about this as well.

**Comment by mattmsft** [comment]
@vrajroutu can you please let me know if you only encounter this error when those boxes are checked, or do you encounter this error consistently when the boxes are unchecked?

**Comment by mattjames1978** [comment]
Perfect thanks @mattmsft, one other thing to mention and the behaviour I am seeing. When enabling both checkboxes when I search the documents as expected it says sorry it doesn't have anything to search. However it does exactly the same thing for a user that is a member of the admin group. I have checked the container and the acls for read and execute and they have been set to the group by the script. 
So looks like it is denying access to all regardless of members of the group. 

Let me know your thoughts on this and I will carry on testing. 
Thanks
Matt

**Comment by mattmsft** [comment]
@mattjames1978 Have you validated the access control has propogated the index? You can test this with the following command as documented [here](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/LoginAndAclSetup.md#manually-managing-document-level-access-control)

./scripts/manageacls.ps1 --document [name-of-pdf.pdf] --acl-type [oids or groups]--acl-action view: Prints access control values associated with either User IDs or Group IDs for a specific document.

Example to view all Group IDs from the Benefit_Options PDF: ./scripts/manageacls.ps1 --document Benefit_Options.pdf --acl-type oids --acl-action view.

**Comment by vrajroutu** [comment]
Hi @mattjames1978,

 I am encountering the same error. Previously, when I enabled the checkboxes for object IDs (oid's) and group IDs (group id's), I was able to successfully retrieve the information. However, after implementing the latest code, this functionality is no longer working.


@mattmsft  i see this error when selected the checkboxes and ask questions and i have also verified and group id's are properly populated for documents in search index

**Comment by vrajroutu** [comment]
@mattjames1978  If you `Rightclick` --> `inspect` --> `Network`; you will notice the same error

**Comment by mattmsft** [comment]
OK - based on your description it sounds like this may be a regression. I will manually test this again. Thanks for testing this.

**Comment by mattmsft** [comment]
I can reproduce the issue. Will work on a fix

**Comment by mattjames1978** [comment]
Thanks both, not validated the indexing yet but sounds like it might be ok. 
Will await a fix

**Comment by mattmsft** [comment]
@mattjames1978 @vrajroutu  please let me know if your issue is fixed. The PR referenced above has been merged

**Comment by vrajroutu** [comment]
@mattmsft 

I can confirm that the token issue has been resolved. However, the main issue still persists when the user selects the OID security filter and GroupID security filter. The response received is simply "`I do not know.`" Interestingly, when these two filters are unchecked, the results are displayed normally.

I have conducted a search in Cognitive Search and can confirm that the documents do have GroupIDs assigned to them.

Could you please advise if there is anything else I need to verify or any additional steps I should take to troubleshoot this issue?

**Comment by vrajroutu** [comment]
<img width="848" alt="Screenshot 2023-10-12 at 2 39 26 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/80a08904-bef1-4225-83fa-0661f3efe562">


FYI

**Comment by mattmsft** [comment]
@vrajroutu if you [enable group claims](https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-fed-group-claims) on the client application, you'll be able to see the exact group ids the application is getting back for the logged in user in the developer settings tab under token claims. If there are too many to display, use the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) with the following URI to list the user's groups:
https://graph.microsoft.com/v1.0/me/transitiveMemberOf?$select=id,displayName

if you've made a recent change to group membership, it may take some time to propogate / require a login / logout in the browser completely.

**Comment by vrajroutu** [comment]
It worked after logging in with a new browser. However, I encountered another issue. I am currently using the same Client ID in Azure WebApp Authentication for AD Auth to access the application, but it is failing after the recent change. I believe that consolidating this authorization component with Azure WebApp Auth would be a sweet combination. :)

closing this for now.

**Comment by mattmsft** [comment]
Thanks - please track the improvements issue for updates. Appreciate your patience and troubleshooting here. Thanks for all your feedback.
