### ISSUE TITLE
Follow-up questions are not reliably rendered as links

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/azure-search-openai-demo#783]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

The prompt currently instructs ChatGPT to render follow-up questions with angle brackets `<<` and `>>`.  Unfortunately, ChatGPT does not format the questions in a reliable manner. Sometimes it puts them inside angle brackets as requested, but it often puts them in a numbered list. That means the UI is not always able to render them as clickable links.

I've discussed follow-up questions with colleagues working on similar codebases, and we've identified three approaches to receiving follow-up questions in a well structured way so that they can become links in the UI:

* Post-processing the response to look for the variations in how ChatGPT responds. That's fairly brittle however. (Approach used by [the Javascript sample](https://github.com/Azure-Samples/azure-search-openai-javascript/blob/67dac3efd39145cc0c28835d41c5c39e1e48b428/packages/chat-component/src/utils/index.ts#L47)) 
* Using the "function call" feature of ChatGPT to receive a list of follow-up questions in the response.  (Which I just prototyped for this repo [in a branch](https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...pamelafox:azure-search-openai-demo:followup?expand=1))
* Make an additional call to ChatGPT to specifically ask it to generate follow-up questions. (Approach used by [the C# sample](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/b14d971be1a9305ad9c76351967138d9f132ef74/app/backend/Services/ReadRetrieveReadChatService.cs#L33))

Each approach adds complexity in different parts of the codebase, so we haven't determined which way is the best.

**Comment by pamelafox** [comment]
I've made additional changes to the followup-questions branch:

https://github.com/Azure-Samples/azure-search-openai-demo/compare/main...pamelafox:azure-search-openai-demo:followup?expand=1

It does work now, but the code is fragile due to parsing JSON chunks. I'd like to clean up that code before proposing it be used here.

**Comment by sreesankar12** [comment]
Hi @pamelafox Can we use this changes on followup questions.
I would like to get followup question suggestion on all the answers. does this help ?

**Comment by pamelafox** [comment]
@sreesankar12 Actually, I came up with a slightly simpler approach that still seems to work, see: https://github.com/Azure-Samples/azure-search-openai-demo/pull/832/files

**Comment by pamelafox** [comment]
That approach is now merged into main.
