### ISSUE TITLE
Proof Key for Code Exchange is required for cross-origin authorization code redemption

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#785]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
After updating the `authConfig.ts` file with the latest changes, if you have added the Client ID as an authorization in Azure WebApp, you may encounter the following error during login:

`AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.`

<img width="637" alt="Screenshot 2023-10-12 at 4 11 34 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/1e78e03f-6b9e-48e3-a75c-219218dc0113">

`client id app registration is added as authentication in Azure WebApp`

<img width="966" alt="Screenshot 2023-10-12 at 4 12 27 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/ba777168-db62-488d-92c3-9eef9c9b78a9">

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattmsft** [comment]
According to this SO post, you need to add a Web section in addition to the Single Page section

https://stackoverflow.com/questions/64692600/aadsts9002325-proof-key-for-code-exchange-is-required-for-cross-origin-authoriz

Does this solve your issue? I will try to reproduce this as well

**Comment by vrajroutu** [comment]
@mattmsft 

It worked after updating the settings to below in client app.

<img width="1091" alt="Screenshot 2023-10-12 at 6 13 56 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/03218c08-e964-4311-824f-a7c91264819f">


and

<img width="675" alt="Screenshot 2023-10-12 at 6 14 26 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/c500554d-e288-47e0-a10f-e2e942cb3cc5">

**Comment by mattmsft** [comment]
@vrajroutu  thanks, are you OK to close this issue?

**Comment by Keatnuxsuo** [comment]
Why is this not added into the Readme file?

**Comment by pamelafox** [comment]
I'll add it in a PR today!

**Comment by pamelafox** [comment]
https://github.com/Azure-Samples/azure-search-openai-demo/pull/2224 has various updates for the login doc.
