### ISSUE TITLE
Change azure cognitive search plan.

### ISSUE THREAD

**Issue by rehat22** [Azure-Samples/azure-search-openai-demo#788]
How can i change the azure cognitive search plan to free or basic version ?

**Comment by pamelafox** [comment]
Before running `azd up`, run:

`azd env set AZURE_SEARCH_SERVICE_SKU basic`

The free tier won't work as it doesn't support managed identity. ([See other possible values](https://learn.microsoft.com/azure/templates/microsoft.search/searchservices?pivots=deployment-language-bicep#sku))

**Comment by rehat22** [comment]
thank you
