### ISSUE TITLE
How to remove the content from the chat knowldege ?

### ISSUE THREAD

**Issue by sreesankar12** [Azure-Samples/azure-search-openai-demo#792]
Hi i have previously uploaded a pdf about some data and an now i wanted to remove it from its knowledge.
I deleted the files from blob storage. Still it is answering the question from that data.
how to solve this ?
do i need to delete the gptkb index and azd  up again with correct data in data folder ?

**Comment by pamelafox** [comment]
Another option is to pass in `--remove DocName.pdf` to prepdocs.py by adding that to the command at the bottom of prepdocs.ps1 or prepdocs.sh

**Comment by sreesankar12** [comment]
as i deleted the files already is this way possible ?

**Comment by pamelafox** [comment]
I believe so, that argument calls a function that removes the data from the search index, not the blob store.

**Comment by sreesankar12** [comment]
Great Thanks!

**Comment by sreesankar12** [comment]
visa_applications-0.pdf was undelted back to strage before this attempt.
//tried by adding --remove visa_applications-0.pdf (name of pdf i uploaded) and --remove visa_applications.pdf (single page name) both gave the following error.

Running "prepdocs.py"
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Processing files...
Using local files in ./data/*
./scripts/prepdocs.sh: 28: --remove: not found

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '127', Path: './scripts/prepdocs.sh'. : exit code: 127

**Comment by pamelafox** [comment]
Can you share the full command where you added --remove?

**Comment by sreesankar12** [comment]
--remove visa_applications-0.pdf``

this is what i added at the end of prepdocs.sh

**Comment by pamelafox** [comment]
Okay, I figured it out, you need to change what's passed in at beginning, like:

```
./scripts/.venv/bin/python ./scripts/prepdocs.py \
'./data/Benefit_Options.pdf' $adlsGen2StorageAccountArg $adlsGen2FilesystemArg $adlsGen2FilesystemPathArg \
$aclArg  --storageaccount "$AZURE_STORAGE_ACCOUNT" \
--container "$AZURE_STORAGE_CONTAINER" --searchservice "$AZURE_SEARCH_SERVICE" \
--openaiservice "$AZURE_OPENAI_SERVICE" --openaideployment "$AZURE_OPENAI_EMB_DEPLOYMENT" \
--openaimodelname "$AZURE_OPENAI_EMB_MODEL_NAME" --index "$AZURE_SEARCH_INDEX" \
--formrecognizerservice "$AZURE_FORMRECOGNIZER_SERVICE" --openaimodelname "$AZURE_OPENAI_EMB_MODEL_NAME" \
--tenantid "$AZURE_TENANT_ID" -v --remove
```

Notice second line starts with './data/Benefit_Options.pdf' - put your path there.

**Comment by sreesankar12** [comment]
Should I place the PDF file back in the data folder to make this work?

**Comment by pamelafox** [comment]
Yes, it does need to be there for it to work, I just tested.
