### ISSUE TITLE
How to Index Tables 

### ISSUE THREAD

**Issue by ima49** [Azure-Samples/azure-search-openai-demo#794]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Hi, I want to index a document and I've created an index in Cognitive Search with the following fields:
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/110237649/77657663-5cf5-4896-802e-20fc586ebfb5)
where 'title' is the title of a paragraph and 'content' the content of the paragraph;
now I have also tables that I want to index; each tables have different columns so nothing standard; how can I index the tables?

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm. Currently, the chat and ask approaches in app/backend/approaches are going to search for content in the content field. If you put anything in another field, you would need to modify those approaches to search in other fields as well. Is that what you're thinking of doing? Have you considered finding a way to put it in the content field?

**Comment by ima49** [comment]
> Hm. Currently, the chat and ask approaches in app/backend/approaches are going to search for content in the content field. If you put anything in another field, you would need to modify those approaches to search in other fields as well. Is that what you're thinking of doing? Have you considered finding a way to put it in the content field?

Hi @pamelafox, now I put the tables (in html format) in the 'content' field, but it does not seem a good way because when I ask the bot to answer questions about the tables, the answer is not good.

**Comment by pamelafox** [comment]
Okay, if it's not working well, then it sounds like you do need another approach. I haven't tried to index tables myself, but a colleague indexed excel CSVs using dataframes, their approach may be helpful:
https://github.com/teterouge/AOAI-AzureSearch-Excel

Also CCing @srbalakr from the Azure Cognitive Search team in case he has other ideas.

**Comment by zhongshuai-cao** [comment]
Thanks for sharing this solution @pamelafox !

I have been using the raw text as it is more compact than json for embedding index, but I would like to give it a try to see how better GPT model itself handle json vs csv strings.

This brings two questions which I am trying to solve:

1. how to render this json format, or the excel directly, so a non developer user can actually and visually consume the raw data.
2.  I am still gradually learning cognitive search with very small lr, maybe 2e-5, so it was painful for me to update my own project, adding new fields, making new fields searchable where the button gray out and I only know to wipe and reindex everything after change. It could be great if there are documentations or referenced for further development on cognitive search part.

**Comment by ima49** [comment]
@pamelafox thank you for sharing, I'll try and let you know

**Comment by pamelafox** [comment]
The repo now has JSON and CSV parsing, plus additional docs, so I'm going to close this issue.
