### ISSUE TITLE
Is my retrieved data kept private, or can it (as it is sent to OpenAI) be used by others?

### ISSUE THREAD

**Issue by PDiracDelta** [Azure-Samples/azure-search-openai-demo#809]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N/A

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> N/A

### OS and Version?
> N/A

### azd version?
> N/A

### Versions
> N/A

### Mention any other details that might be useful

I understand from graphic below that documents are sent (perhaps in embedded form?) to OpenAI. Does this come with a potential data privacy risk? Can OpenAI "read" and "use" my data in the sense that my company secrets somehow might be revealed to someone else but the user, for instance through incorporation in OpenAI's training data?
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11943051/4346b2bf-4e58-4b3c-bdb8-7d7bc80625f3)

image source: [ML6](https://blog.ml6.eu/leveraging-llms-on-your-domain-specific-knowledge-base-4441c8837b47)

**Comment by pamelafox** [comment]
This repository defaults to Azure OpenAI, which has strict privacy considerations. You can read about them here:

https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy

Note especially these bullet points:

```
Your prompts (inputs) and completions (outputs), your embeddings, and your training data:
are NOT available to other customers.
are NOT available to OpenAI.
are NOT used to improve OpenAI models.
```

If you are using the option to use non-Azure OpenAI, then you will need to read up on openai.com about their privacy approach:
https://openai.com/enterprise-privacy

Hope that helps.
