### ISSUE TITLE
Same demo with c# backend

### ISSUE THREAD

**Issue by aplongh** [Azure-Samples/azure-search-openai-demo#81]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

First of all, thanks for the GREAT demo. We had very little trouble getting it up and running. Is there any chance there could be a similar demo in c# for the backend? Or get some assitance on how we can create this ourselves? Sorry if this is not the place to post the question. Please advice me in case there is another forum.

Thanks in advance.

**Comment by pablocastro** [comment]
We now have a C# / .NET version here: https://github.com/Azure-Samples/azure-search-openai-demo-csharp
