### ISSUE TITLE
Enhancing User Experience with Access to Original Files

### ISSUE THREAD

**Issue by zhongshuai-cao** [Azure-Samples/azure-search-openai-demo#819]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>
### Description:
Post-retrieval of the initial answer, it's likely users might wish to access the entire document for a comprehensive view. To elevate this user experience, I propose the following enhancements:

### Direct Download Link:
Providing users with a direct link to download the original file ensures they can access the complete content whenever needed.

### Improved Analysis Panel Interaction:
An even more seamless experience would be to upload only the original PDF file, and within the analysis panel, display the PDF, auto-scrolling directly to the relevant page number.

Implementing these changes could make the system more intuitive and user-friendly, thereby improving overall user satisfaction.

**Comment by pamelafox** [comment]
I have a branch that does this, will be sending PR soon.

**Comment by pamelafox** [comment]
PR sent- https://github.com/Azure-Samples/azure-search-openai-demo/pull/840

**Comment by achandmsft** [comment]
@zhongshuai-cao I am Arun Sekhar, the Principal Product Manager for Azure AI Developer Experiences in Microsoft. I would love to chat with you to understand your requirements and get your feedback around our repo. Please email me at achand at microsoft dot com if you are ok to have a brief chat with me. Looking forward to chatting with you!
