### ISSUE TITLE
Cannot import name 'HnswParameters' which requires Azure.Search.Documents v11.5.0-beta.5 which is not available

### ISSUE THREAD

**Issue by PDiracDelta** [Azure-Samples/azure-search-openai-demo#826]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> download the repo, install all python packages and run `python scripts/prepdocs.py`

### Any log messages given by the failure
> ImportError: cannot import name 'HnswParameters' from 'azure.search.documents.indexes.models'

### Expected/desired behavior
> No error

### OS and Version?
> Windows 10

### azd version?
> azd version 1.4.2 (commit 694107efa395b8562abcdf1f246792bbea72ad9c)

### Versions
> 69c41476f4f62485fa76569183474e4fd11c801f

### Mention any other details that might be useful
> 'HnswParameters' is in Azure.Search.Documents v11.5.0-beta.5 
> however, 11.5 is not available yet in Python. 11.4 is, but doesn't contain HnswParameters and a bunch of other parameters.

**Comment by pamelafox** [comment]
Hm, our requirements.txt specifically pins azure-search-documents==11.4.0b6
That's available in pre-release: https://pypi.org/project/azure-search-documents/#history
Is there a reason your system didn't download that version?

**Comment by PDiracDelta** [comment]
> Hm, our requirements.txt specifically pins azure-search-documents==11.4.0b6 That's available in pre-release: https://pypi.org/project/azure-search-documents/#history Is there a reason your system didn't download that version?

My bad, I misunderstood how the python setup was handled. I now selected `scripts/.venv/scripts/ptyhon.exe` as the interpreter and the error is gone.
