### ISSUE TITLE
Deployment Error: formrecognizer

### ISSUE THREAD

**Issue by raffertyuy** [Azure-Samples/azure-search-openai-demo#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> New installation in GitHub Codespaces
> `azd up`

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/1037626/229401297-650d8888-a9d3-421d-a6eb-87d45eb3d9a9.png)

### Expected/desired behavior
> Successful deployment

### OS and Version?
> GitHub Codespaces

### Versions
> Version as of April 3, 2023

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nimishrao** [comment]
I had the same error please go to Manage Deleted Resources on the Azure portal (under Cognitive Services) and purge your existing Form recognizer resource (automatic purging takes some time). The code will then create a new one for you.

**Comment by raffertyuy** [comment]
Awesome, thanks @nimishrao ! Didn't know formrecognizer had this function
