### ISSUE TITLE
CosmosDB - not being used nor created anymore ?

### ISSUE THREAD

**Issue by ThomasLambertES** [Azure-Samples/azure-search-openai-demo#838]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create new codespace (or other), do standard procedure, and i see that it's not creating the cosmos DB anymore

### Any log messages given by the failure
>

### Expected/desired behavior
> Since Readme states still that data is being stored in cosmos, i expected this to be the case. I have a DB created from previous commit, and it is not sending conversation history anymore, i thought this was my mistake on code, but after recreating from scratch a new instance, it did not create the DB so i'm supposing this is something that was deprecated?

### OS and Version?
Git codespaces

### azd version?
azd version 1.4.2

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Where does it state that in the Readme? As far as I'm aware, this sample has never used Cosmos.

**Comment by ThomasLambertES** [comment]
my bad.... you can delete this issue, i created a 

sample-app-aoai-chatGPT

in the past, and this created the cosmosDB and thus also mixed my cables.

Please excuse me for this mistake
