### ISSUE TITLE
Trying to update index but getting error

### ISSUE THREAD

**Issue by sunnygambit1989** [Azure-Samples/azure-search-openai-demo#839]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
**Request** 
curl --location --request PUT 'https://gptkb-3utgcchwhv4yw.search.windows.net/indexes/gptkbindex?api-version=2023-10-01-Preview' \
--header 'Content-Type: application/json' \
--data-raw '{
    "@search.action": "merge",
    "id": "file-Security_In_Enablix_pdf-536563757269747920496E20456E61626C69782E706466-page-7",
    "permissions": [
        "sunny.kumar@enarerblix234.com",
        "82344+ebwqeqx1@gmail.com",
        "dikshit.luthra@enwrewrablix.com"
    ]
}'
>
**ERROR**
{
    "error": {
        "code": "",
        "message": "The request is invalid. Details: The property 'id' does not exist on type 'Microsoft.Azure.Search.V2023_10_01_Preview.IndexDefinition'. Make sure to only use property names that are defined by the type."
    }
}
 Id as key defined .
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sunnygambit1989** [comment]
@pamelafox Can you please help here. It's urgent

**Comment by pamelafox** [comment]
@sunnygambit1989 Please rotate your key, you exposed it in the issue report. You may also want to delete email addresses as well to avoid spam-bots.

As for the question, I haven't used the API but it looks like you're trying to use:
https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents

I think your JSON isn't matching what they show, which is an object with a "value" key and that key's value is a list of documents to update. I suggest trying to change to match the examples there.

**Comment by sunnygambit1989** [comment]
yes @pamelafox How can i rotate the key?

**Comment by sunnygambit1989** [comment]
@pamelafox i tried that too. same error just replace id by value in the error given above.

{
    "error": {
        "code": "",
        "message": "The request is invalid. Details: Cannot find nested property 'value' on the resource type 'Microsoft.Azure.Search.V2023_10_01_Preview.IndexDefinition'."
    }
}

**Comment by sunnygambit1989** [comment]
@pamelafox  Thank you . It worked

**Comment by pamelafox** [comment]
Great, you can rotate/re-generate keys in the Portal for the search service, under keys:
![Screenshot 2023-10-20 at 12 45 01 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/ede49682-1cd8-4e74-8c7d-7d76e08412a6)
