### ISSUE TITLE
Unable to complete deployment due to a previous deleted version of formrecognizer in the softdelete state

### ISSUE THREAD

**Issue by alf233** [Azure-Samples/azure-search-openai-demo#84]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Unable to complete deployment due to a previous deleted version of formrecognizer in the softdelete state

### Any log messages given by the failure
>
ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'formrecognizer' is not valid according to the validation procedure. The tracking id is 'xxxxxxxxxxxxxxxxxx'. See inner errors for details.
FlagMustBeSetForRestore: An existing resource with ID '/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-MIPGPT/providers/Microsoft.CognitiveServices/accounts/cog-fr-yf62qdrpvjeuo' has been soft-deleted. To restore the resource, you must specify 'restore' to be 'true' in the property. If you don't want to restore existing resource, please purge it first.
### Expected/desired behavior
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alf233** [comment]
Resolved by purging from Forms Recognizer delete items

**Comment by TimoRiikonenIF** [comment]
Form recognizer is not up yet.
Resolve by deleting the resource group.
