### ISSUE TITLE
Error: Token tenant 50e5a815-5d7a-4cfc-af9a-d6ab3d6641de does not match resource tenant

### ISSUE THREAD

**Issue by aplongh** [Azure-Samples/azure-search-openai-demo#85]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I previously published to Azure and everything works fine. However I am trying to run the solution in my local PC, but I keep getting the error: "Error: Token tenant 50e5a815-5d7a-4cfc-af9a-d6ab3d6641de does not match resource tenant". Am I missing any configuration? In able to debug and better understand the demo, I am trying to debug from VS Code. I have included ALL env variables in the launch.json file in the "env" section, as I have been unable to figure out how to configure the working directory for the .env file.

Any suggestion as to how to correctly configure for local development, will be GREATLY appreciated.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aplongh** [comment]
I have nailed it down to this line in app.py: azure_credential.get_token("https://cognitiveservices.azure.com/.default").

Where retrieving the Token, it shows the TenantId in which the user is created, instead of using the TenantId of the resources (they are different). Any idea as to how I can get the correct TenantId?

**Comment by aplongh** [comment]
Solved. Before debbuging the app, I had to set the account with 'az account set --subscription "subscription name"' and then login using 'az login'.

**Comment by ahmedsza** [comment]
Unfortunately getting the same error, and the workaround not working for me :-(

**Comment by aplongh** [comment]
try this: 
az login
az account set --subscription "subscription name"
az login
azd login

**Comment by Pave87** [comment]
Im having this issue and suggested solution wont help.

**Comment by ahmedsza** [comment]
this workaround worked for me (and a colleague)
in app.py around line 33
change 
azure_credential = DefaultAzureCredential()
to
azure_credential = AzureCliCredential()



You will need to add this around line 14
from azure.identity import AzureCliCredential

you will need to make sure you logged in with azure cli to appropriate sub. for whatever reason on my machine I have issues with defaultazurecredential

**Comment by Pave87** [comment]
I tested with 2 computers but still getting same error.

**Comment by aplongh** [comment]
Strangely, my own solution stopped working for me. It turns out that the solution only works if there are no other instances of Visual Studio Code open. In my case, the solution started working again when I closed all open instances of Visual Studio Code, opened only the one with this project and executed the az and azd instructions.

Anyways, tired of this problem, we "enhanced" the solution so that it authenticates using ApiKeys, ConnectionStrings, etc, instead of relying on the connected user to azure.

Hope this helps.

**Comment by PawanKumar18** [comment]
I encountered the above error, and unfortunately, none of the possible solutions provided above are working for me.

**Comment by damienaicheh** [comment]
Hi, the problem on my project related to Azure Open AI was that I forgot to specify the Auth type to ApiKey so by default the sdk try to authenticate with some other Azure mecanism or worth it doesn't know how to do it. Check on your sdk if you have the ability to set this kind of properties to force the authentication using the one you want.

**Comment by pamelafox** [comment]
@PawanKumar18 It's not working for this app? Are you logged in with a different tenant than the one that hosts the resources?

**Comment by PawanKumar18** [comment]
Hello @pamelafox , Yes, It is not working for this app when I try to run it locally. I'm logged into the same tenant as the host resource. The application runs when I hardcode the OpenAI token.
