### ISSUE TITLE
Ability to change knowledge base from within the UI.

### ISSUE THREAD

**Issue by M0inUddin** [Azure-Samples/azure-search-openai-demo#850]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> I want to able to change knowledge bases from the settings panel like I have HR, Legal and Support Doc which are indexed and in the blob storage. But as the user desire he/she can change which doc to access it can be one or many.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
First let me understand your index. Do you have a single index for all those docs, or an index for each style of doc?

If you have a single index, then you would likely want to set "category" on each document, and then add each category to a dropdown in the settings. The backend already parses "category" and passes it as a filter to Azure Cognitive Search, so the frontend just needs to pass it.

If you have multiple indices, then you would want to put the indices in the dropdown instead, and pass the index to the backend and through to the Azure Cognitive Search .search() call.

**Comment by pamelafox** [comment]
If you haven't indexed them yet, then prepdocs.py has a --category argument that you can set. So, you could modify prepdocs.ps1 or prepdocs.sh to pass in --category and only run on that category's set of files, and then do that for each category.

If you already indexed them, then you'd need to go through the index and update the field on each chunk in the index. We don't have a script for that, so you'd need to write one. Probably easier to start the index from scratch and run prepdocs for each category.

**Comment by pamelafox** [comment]
Glad you got it working! We'll look into adding a dropdown to the UI in the future to make it easier to switch indexes or categories.

**Comment by pavsingh7** [comment]
> Glad you got it working! We'll look into adding a dropdown to the UI in the future to make it easier to switch indexes or categories.

Hi @pamelafox. Firstly, thanks for the contributions to this repo. 

How low down is this feature in the priority list. Or has there been any PR's relating or demonstrating this feature as of late. Thank you in advance :)
