### ISSUE TITLE
few shot reversed in get_messages_from_history

### ISSUE THREAD

**Issue by AMusarella** [Azure-Samples/azure-search-openai-demo#851]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I noticed that the few shot messages are inserted in reverse order within the conversation, is this a desired behaviour? By not specifying the index in the append_message function, they are all inserted in the first position, reversing the list.

### Expected/desired behavior
> You can quickly fix this by changing the line 338 of chatreadretrieveread.py to "for shot in reversed(few_shots):" or by specifying the index in append_message

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for catching that! I don't think that was intentional, I've sent a PR with a fix: https://github.com/Azure-Samples/azure-search-openai-demo/pull/852
