### ISSUE TITLE
Incorrect Responses When Authorization is Enabled.

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#854]
> Please provide us with the following information:

When a user asks questions based on the information they have access to, GPT is able to provide accurate responses. However, in the course of a conversation, if the user asks a question about information they should not have access to or is simply testing the model's authentication checks, the model may provide incorrect responses and cite documents that the user has access to.

A temporary workaround for users testing this feature is to always clear the chat to ensure they do not receive vague or incorrect responses to questions regarding data they do not have access to.

Has anyone else observed this behavior?
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

- Ask Questions on the data you have access to with Auth Enabled.
-  Get the Responses.
- Do not clear the chat
- Ask questions on the data you do not have access to
- Get the response. ( Vague Hallucination ) 
- Clear the Chat
- Ask qyestions on the data you do not have access to
-  Empty Response
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vrajroutu** [comment]
@mattmsft  Have you observed this issue?

**Comment by mattmsft** [comment]
Thanks for reporting this. We'll investigate. This seems to be in the category of hallucination, not just authorization related

**Comment by vrajroutu** [comment]
@mattmsft @pamelafox  

New `GPT4` model and `openai sdk 1.0` is the fix for this bug.
