### ISSUE TITLE
Reduce costs with free SKUs

### ISSUE THREAD

**Issue by matsuobasho** [Azure-Samples/azure-search-openai-demo#855]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Examine `readme`

### Mention any other details that might be useful
In the Costs section you write
`To reduce costs, you can switch to free SKUs for Azure App Service and Form Recognizer by changing the parameters file under the infra folder.`

What keys in the `main.parameters.json` would we change and what values should we use for the free SKUs?  Adding this information would really help out someone experimenting with this service to avoid surprise charges.  Absence of this info is a deterrent to testing this cognitive search feature.  

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tonybaloney** [comment]
The parameters in `main.parameters.json` are the defaults, you can override a couple to get a cheaper deployment.

- `formRecognizerSkuName` can be `F0` (free tier)
- The App Service SKU is set in `main.bicep` but it's already Basic 1 (B1) SKU which is a small SKU. I don't know if the app would work in a smaller SKU, the smallest is F1, change this line https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/infra/main.bicep#L130 to get that outcome

**Comment by pamelafox** [comment]
I just merged a change that makes it possible to use the free tier:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1166

See doc here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_lowcost.md
