### ISSUE TITLE
How to add new files and make them searchable without deploying

### ISSUE THREAD

**Issue by PDiracDelta** [Azure-Samples/azure-search-openai-demo#859]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> prompt the chatGPT with "does joris like bagels?". It should say there are no relevant sources for this info. Then, create a file called "joris likes bagels.pdf" containing 2 pages of repeated text "joris likes bagels". Then run `.\scripts\prepdocs.ps1`.

### Any log messages given by the failure
>

### Expected/desired behavior
> when I prompt the chatGPT "does joris like bagels?" it should refer to that file. 
> However, It still says there are no relevant sources.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
> 

### Mention any other details that might be useful

> I read in the FAQ https://github.com/Azure-Samples/azure-search-openai-demo#faq that this should _upload_ the files. It doesn't explicitly say this also embeds, indexes, and makes the files available for searching, but I assumed it does so automatically. This may not be true, so **what additional (to running prepdocs.ps1) steps do I need to take?**. Suggestion to add it to the FAQ.
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11943051/72c76fda-29bc-4460-b4f9-ab7aedbbf1dd)

**Comment by pamelafox** [comment]
That should work, in theory - we've actually done presentations where we've uploaded a doc and asked a question after.
A few things to check:
* Did ./scripts/prepdocs show that it processed the new file?
* Does your search index show results for the search query? (You can query your index in Azure Portal)

**Comment by PDiracDelta** [comment]
> That should work, in theory - we've actually done presentations where we've uploaded a doc and asked a question after. A few things to check:
> 
> * Did ./scripts/prepdocs show that it processed the new file?
Yes.
> * Does your search index show results for the search query? (You can query your index in Azure Portal)
Yes.

I just discovered that it **is** registered as supporting content, but the chat doesn't understand the text.
I would test more (e.g. adding periods in between the repetitions) but need to remove the existing files first. Is [this ](https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents)the easiest way to do that? (it's a bit cumbersome on large scale but works for this test).
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11943051/cf44265e-92fa-4dee-8c26-c79eb2124b25)

**Comment by pamelafox** [comment]
See my comment here re removing- https://github.com/Azure-Samples/azure-search-openai-demo/issues/714#issuecomment-1743651101

Also, its strange that it responded like that.

**Comment by felixwcf** [comment]
Hmm... the Q&A for this one seems to have disappeared from the FAQ section...

**Comment by pamelafox** [comment]
I wrote a whole doc instead: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md

Please let me know if anything's missing from that.
