### ISSUE TITLE
Triggering the AOAI content filter results in a "Type error" in the frontend

### ISSUE THREAD

**Issue by leongj** [Azure-Samples/azure-search-openai-demo#869]
@tonybaloney -- I thought I should actually surface this as an issue out of the other thread.

If you ask a question in the frontend that triggers the content filter (e.g. "how do I make a bomb?") You get a "type error" in the frontend. (Please confirm)

I think this is because:
- the exception occurs in the OpenAI completion call
- that call is async and not actually called until _after_ execution of /chat has completed (return a 200) and streaming has started. (I noticed this stepping through debug)
- this means the exception is not caught by the except block in /chat, as you would expect it to at first glance.
- so the backend has returned the start of a stream, but no actual content because the first completion call (query generation) has errorred.
- the frontend receives an empty stream which fails type validation and hence you get a type error (instead of the actual helpful exception message)

This is what I _think_ is happening, but I'm still new to Quart and really still learning Python TBH. Be really keen to get your view.

I was also musing on how to solve it, I read that there was a generic catchall error handler in Flask, but not sure if there is one in Quart (@bp.error_handler?) Tried that but didn't work, another option would be to try/except in chatreadretrieveread around the completion blocks and return a legitimate (stream!) response, and when I realised that was a tuple of [extra_info, coroutine] I thought: this is getting too hard 😄!!

Hope you can shed some light.

_Originally posted by @leongj in https://github.com/Azure-Samples/azure-search-openai-demo/issues/849#issuecomment-1780969274_

**Comment by pamelafox** [comment]
I have sent out a PR with a proposed fix, please take a look and see if that works for you. I'm not sure if we should be telling the user that they triggered the content safety filter, or just saying there's been an error - that's a bit of a UI decision - so I've defaulted to not revealing the full error message.

**Comment by leongj** [comment]
Awesome! Thanks so much Pamela for looking at this so quickly. It was interesting to see that issue/question about exception handling in Quart. Curious to see what they say.
