### ISSUE TITLE
Where is the code located that makes the answers have the sources and look like Bing?

### ISSUE THREAD

**Issue by SirRacha** [Azure-Samples/azure-search-openai-demo#873]
Where is the code located that makes the answers have the sources and look like Bing?

I am trying to locate the way the responses are formatted and cannot find it in the "frontend" folder.  Any help would be appreciated!

I want to identify how to get answers to have the data source links and to suggest new questions.

Thanks!

**Comment by pamelafox** [comment]
I think you'll find what you're looking for in this component:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/components/Answer/Answer.tsx

That renders the citation and follow-up questions.

**Comment by SirRacha** [comment]
Thanks @pamelafox!
