### ISSUE TITLE
Offensive and Harmful Content Filter and Redirection to HR

### ISSUE THREAD

**Issue by hichamhammouchi** [Azure-Samples/azure-search-openai-demo#887]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In order to handle offensive and self-destructive language and redirect it to HR, is there a way to create custom responses to hateful, offensive and self-destructive questions, other than the content filter in Azure OpenAI? 

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/76973438/2466a138-fd86-4ffe-891e-225a2cfd1f1f)

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/76973438/77c1bfa3-fd3d-4d92-9870-338350945d7c)

### Expected/desired behavior
> In the context of internal enterprise assistant, create custom responses when harmful and offensive language is used and redirect to HR (could be hardcoded message) instead of an error or generic response as the above. I tried the content filters in the Azure OpenAI studio but it just return an error when set to strict

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.
NA
### Versions
> GPT-4-32k

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Good question! Assuming you have the latest changes from main, you can start off by changing error_dict in app.py to:


def error_dict(error: Exception) -> dict:
    if isinstance(error, openai.error.InvalidRequestError) and error.code == "content_filter":
        return {"error": "Your message contains content that was flagged by the OpenAI content filter."}
    return {"error": ERROR_MESSAGE.format(error_type=type(error))}

That caught the first example, but I need to do additional testing for the Ask tab and your second example, which likely requires parsing out the content safety results.

**Comment by pamelafox** [comment]
I sent a PR in https://github.com/Azure-Samples/azure-search-openai-demo/pull/896

**Comment by hichamhammouchi** [comment]
Thank you @pamelafox for the update. However, the intended behavior is to have adaptive responses based on the question (chat) and then depending the emotion/sentiment of the question either close the session (too offensive and hateful) or generate adequate GPT-like answer if the user needs help such as in the case of suicidal thoughts.

Not sure if the intended behavior is clear! but the idea is to add some level intelligence into the answers to the mentioned types of questions
