### ISSUE TITLE
ERROR: failed running pre hooks

### ISSUE THREAD

**Issue by somayaji-a** [Azure-Samples/azure-search-openai-demo#89]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I ran the `azd init` command as outlined in the readme. All the resources were successfully provisioned in Azure, and the 'chunking' seems to have worked as expected (see log notes below). The issue occurs after that when the script gets to the deploy phase. It always ends at building the front end with error shown below. Retrying with `azd deploy` results in the same, and trying to run it locally also fails at the same step.

### Any log messages given by the failure
> 
When running `azd deploy`, I get the following:
```
vscode ➜ /workspaces/azure-search-openai-demo/new (main) $ azd deploy
Executing predeploy hook => /tmp/azd-predeploy-1125170420.sh

up to date, audited 122 packages in 4s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> frontend@0.0.0 build
> tsc && vite build

vite v4.1.1 building for production...
✓ 1250 modules transformed.
Killed

ERROR: failed running pre hooks: 'predeploy' hook failed with exit code: '137', Path: '/tmp/azd-predeploy-1125170420.sh'. : exit status 137
```

When running `./start.sh` locally, I get the following:
```
...
Restoring frontend npm packages


up to date, audited 122 packages in 4s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Building frontend


> frontend@0.0.0 build
> tsc && vite build

vite v4.1.1 building for production...
✓ 1250 modules transformed.
Killed
Failed to build frontend
```

### Expected/desired behavior
> I would expect the build to complete and the web client to open up after this. Haven't been able to reach that step yet

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

macOS on VSCode using the VSCode Remote Container. Container info below:

```
ARG VARIANT=bullseye
FROM --platform=amd64 mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
RUN export DEBIAN_FRONTEND=noninteractive \
     && apt-get update && apt-get install -y xdg-utils \
     && apt-get clean -y && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://aka.ms/install-azd.sh | bash
```

```
{
    "name": "Azure Developer CLI",
    "build": {
        "dockerfile": "Dockerfile",
        "args": {
            "VARIANT": "bullseye"
        }
    },
    "features": {
        "ghcr.io/devcontainers/features/python:1": {
            "version": "os-provided"
        },
        "ghcr.io/devcontainers/features/node:1": {
            "version": "16",
            "nodeGypDependencies": false
        },
        "ghcr.io/devcontainers/features/powershell:1.1.0": {},
        "ghcr.io/devcontainers/features/azure-cli:1.0.8": {}
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "ms-azuretools.azure-dev",
                "ms-azuretools.vscode-bicep",
                "ms-python.python"
            ]
        }
    },
    "forwardPorts": [
        5000
    ],
    "postCreateCommand": "",
    "remoteUser": "vscode",
    "hostRequirements": {
        "memory": "8gb"
    }
}
```

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by somayaji-a** [comment]
Note - this looks to be an issue with the remote container only. I was able to get it working with no problems when I did not use the VS Code Container.

**Comment by cmilin** [comment]
I am using VS Code on Ubuntu and I am facing similar issues. What was your workaround to run ./start.sh locally?

**Comment by dshrotri** [comment]
I'm trying to deploy from codespace and I'm getting this issue
how can I solve it?

**Comment by pamelafox** [comment]
Closing as this seems like an obsolete issue.
