### ISSUE TITLE
Support more file types like .docx, .xlsx, .yaml, .ts, .js to support code generation

### ISSUE THREAD

**Issue by GrimJay** [Azure-Samples/azure-search-openai-demo#895]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Add a .doc file and run prepdoc.py.  The file will not process
>

### Any log messages given by the failure
Document type is not supported.
>

### Expected/desired behavior
File is indexed.
>

### OS and Version?
> Windows 11

### azd version?
> azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7).

### Versions
python 3.11
>

### Mention any other details that might be useful
.doc and .yaml files are indexed in the Azure OpenAI Chat Playground.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for the feedback! It's a popular request, so I'll merge this into https://github.com/Azure-Samples/azure-search-openai-demo/issues/895

**Comment by pamelafox** [comment]
See today's release:

https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-02-15b
