### ISSUE TITLE
Issue when upgrading to GPT-4

### ISSUE THREAD

**Issue by seef-leroux** [Azure-Samples/azure-search-openai-demo#904]
Good morning!

I have deployed a gpt-4-42k model and I want to redeploy the app to test it (The previous model was gpt-35-turbo). When I run 'azd up' I get the following error:
>

InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'a0ea588d-1d3f-4ae8-b109-6b3be8a4fa59'. See inner errors for details.
SpecialFeatureOrQuotaIdRequired: The current subscription does not have feature required by this model 'Format: OpenAI, Name: gpt-4, Version: 0613' and SKU 'Standard'.
>

The model has a new name, so I am not sure if a successful run of 'azd up' will give me the opportunity to specify the model, or if I should change it in the main.parameters.json file:     "chatGptDeploymentName": {
      "value": "${AZURE_OPENAI_CHATGPT_DEPLOYMENT=chat}"
Or perhaps I should call the deployment 'chat'?

Your help is appreciated!

**Comment by zaffaste** [comment]
I don't know if it was just a typo but the model name is gpt-4-32k not 42k.
You have to update .\infra\main.bicep file on line 61 with something like this:
`param chatGptModelName string = (openAiHost == 'azure') ? 'gpt-4-32k' : 'gpt-3.5-turbo'`

HTH,
Stefano

**Comment by mattjames1978** [comment]
I have tried both and I think it is a limitation in the subscription. I have submitted a quota increase form to Microsoft to see if they can enable GPT 4 in my subscription so will let you know if it gets enabled or not. But think it is a restriction on the subscription on Model version.

**Comment by zaffaste** [comment]
Have you checked region availabilty for GPT 4 model?
[https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-model-availability](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-model-availability)

**Comment by mattjames1978** [comment]
yes I am using UK South and it was on the list from what I could see

**Comment by seef-leroux** [comment]
Thanks for the replies so far. I do have GPT4 available on my subscription. The 42k was just a typo.
