### ISSUE TITLE
support gpt4 model 

### ISSUE THREAD

**Issue by huqianghui** [Azure-Samples/azure-search-openai-demo#91]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```

- [X] feature request
```
support gpt4 to complete context 

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by itsamk** [comment]
GPT-4 support is not available (at least not General Availability) through Azure OpenAI service. I believe it will be available down the line and the prompt-response structure implemented in this app should directly apply to it. 
Currently, you can [join the waitlist](https://openai.com/waitlist/gpt-4-api) and use GPT-4 based Chat API directly instead of using the Azure OpenAI service. You can modify the application backend to point to the same.

**Comment by huqianghui** [comment]
hi itsamk, 

thank you for your response.
GPT-4 is avaiable for some customers already.
Please see more information about the Announcements: https://azure.microsoft.com/en-us/blog/introducing-gpt4-in-azure-openai-service/.

And the gpt-4's prompt format is different with the chatgpt, like below:
messages = [{"role":"system","content":"You are an AI assistant that helps people find information."},{"role":"user","content":"hello"}],

**Comment by itsamk** [comment]
Good to hear it's becoming available through Azure as well. Regarding the prompt-response structure, it's the same. You can check here for reference - https://platform.openai.com/docs/guides/chat

**Comment by huqianghui** [comment]
Hi itsamk, thank you for you response.
I aggree with you that the prompt-response structure, it's the same. (using OpenAI Python v0.27.0)
But in the current version, the prompt is still chagpt's old version(using openai,0.26.4) as below：


history_text = """<|im_start|>user""" +"\n" + h["user"] + "\n" + """<|im_end|>""" + "\n" + """<|im_start|>assistant""" + "\n" + (h.get("bot") + """<|im_end|>""" if h.get("bot") else "") + "\n" +

**Comment by ThomasLambertES** [comment]
Did you get to update this ? would replacing the prompt-response from old one to new solve the issue?

**Comment by DanoneCraig** [comment]
is there any update? 
Error: The completion operation does not work with the specified model, gpt-4

**Comment by kishorerv93** [comment]
@DanoneCraig  @ThomasLambertES Here is the PR for GPT-4 #394

**Comment by pamelafox** [comment]
Using GPT-4 is now documented in the README. Thanks @vrajroutu for sharing your PR.
