### ISSUE TITLE
List of allowed locations for Gpt-35-turbo 0613 version

### ISSUE THREAD

**Issue by suma-sai-paluri** [Azure-Samples/azure-search-openai-demo#929]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>In the latest repo the allowed locations fot the openai resource group is as follows:
@description('Location for the OpenAI resource group')
@allowed(['canadaeast', 'eastus', 'eastus2', 'francecentral', 'switzerlandnorth', 'uksouth', 'japaneast', 'northcentralus','australiaeast'])
And it uses gpt 35 turbo 0613 version, openai.api_version: "2023-07-01-preview". 
why are other locations which are specified in the azure portal that have access to gpt 35 turbo 0613 are not included in the allowed locations?
The list of Locations at which gpt 35 turbo 0613 is available according to the azure portal:
Australia East
Canada East
East US
East US 2
France Central
Japan East
North Central US
Sweden Central
Switzerland North
UK South
[](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models)
Can we know the reason why the remaining resource group locations are not available?
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I think the only discrepancy is sweden, right? That's because we use the same region to deploy an Ada embedding model, and it doesn't seem to be supported in sweden: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#embeddings-models

**Comment by suma-sai-paluri** [comment]
Yes Pamela, but the model is available on openai studio and the documentation documentation doesn't show it. If both gpt-35-turbo(0613) and ada -embedding-002 models are present in swedencentral can we edit the file and deploy the application?
![Screenshot 2023-11-08 155148](https://github.com/Azure-Samples/azure-search-openai-demo/assets/145546506/1ce8d221-4b38-4ffe-99d2-bedddb620628)

**Comment by pamelafox** [comment]
Ah, thanks for letting us know! I've proposed this PR to add it:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/935

Have you tested yourself with swedencentral on this repo? If not, I'll do a test deploy.

**Comment by suma-sai-paluri** [comment]
Hi @Pamela I have tested deploying the repo using swedencentral and it is working.
