### ISSUE TITLE
Application Error after spining up the new instance

### ISSUE THREAD

**Issue by waqasjavedkhan** [Azure-Samples/azure-search-openai-demo#940]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
I spin up a new instance in US East and getting the following error. I waited for over 30 mins and getting this error. 

<img width="646" alt="Screen Shot 2023-11-09 at 7 23 11 pm" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/81873144/ad39f859-f43c-4976-ba16-cec6480eee37">

@pamelafox Sorry to bug you again. How should I investigate this issue and download logs to share them with you for remediation? 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
The most recent error is "ModuleNotFoundError: No module named 'uvicorn'" so uvicorn is not getting installed. I assume app/backends/requirements.txt still lists uvicorn? Can you check the deployment center logs to see if it successfully installed uvicorn? 

Deployment logs: https://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html

**Comment by pamelafox** [comment]
It looks like you are using our standard main.bicep, from a quick look at the file. Did you run `azd up` before all this? You could try running `azd provision` again. The lack of environment variables is very peculiar.

**Comment by pamelafox** [comment]
`azd up` first does `provision`, then `deploy`. I'm really confused as to why you wouldnt see any of the environment variables from main.bicep. It might be easier to start over, with `azd env new` and then `azd up` again.
