### ISSUE TITLE
Bug in prepdocslib with handling large PDF files

### ISSUE THREAD

**Issue by rebeccaleeasml** [Azure-Samples/azure-search-openai-demo#960]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for handling very large PDF file with pages more than ~400 or 500
```
- [ ] search index only shows 1000
- [ ] code fix is available

```

### Minimal steps to reproduce
> You can load a very large PDF file, and no matter what you do, the search index only shows 1000

### Code which has problem, the 2nd MAX_BATCH_SIZE will override the 1st, and 3rd will override the 2nd, the last wins
> /scripts/prepdocslib/searchmanager.py has
    async def update_content(self, sections: List[Section]):
        MAX_BATCH_SIZE = 1000
        section_batches = [sections[i : i + MAX_BATCH_SIZE] for i in range(0, len(sections), MAX_BATCH_SIZE)]

        async with self.search_info.create_search_client() as search_client:
            for batch in section_batches:
                documents = [
                    {
                        "id": f"{section.content.filename_to_id()}-page-{i}",
                        "content": section.split_page.text,
                        "category": section.category,
                        "sourcepage": BlobManager.sourcepage_from_file_page(
                            filename=section.content.filename(), page=section.split_page.page_num
                        ),
                        "sourcefile": section.content.filename(),
                        **section.content.acls,
                    }
                    for i, section in enumerate(batch)
                ]

### Code fix
>    async def update_content(self, sections: List[Section]):
        MAX_BATCH_SIZE = 1000
        section_batches = [sections[i : i + MAX_BATCH_SIZE] for i in range(0, len(sections), MAX_BATCH_SIZE)]

        async with self.search_info.create_search_client() as search_client:
            j = 0
            for batch in section_batches:
                documents = []
                for i, section in enumerate(batch):
                    k = i + j*MAX_BATCH_SIZE
                    #print(f"k {k}, i {i}, j {j}")
                    documents.append(
                        {
                            "id": f"{section.content.filename_to_id()}-page-{k}",
                            "content": section.split_page.text,
                            "category": section.category,
                            "sourcepage": BlobManager.sourcepage_from_file_page(
                                filename=section.content.filename(), page=section.split_page.page_num
                            ),
                            "sourcefile": section.content.filename(),
                            **section.content.acls,
                        }
                    )
                j = j + 1

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks so much for report, I've sent PR here: https://github.com/Azure-Samples/azure-search-openai-demo/pull/971
