### ISSUE TITLE
Chat history feature

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure-Samples/azure-search-openai-demo#977]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Expected/desired behavior
Currently chat history is not persisted. In an enterprise environment its critical to provide the ability to review/audit chat history.  
Chat with your data repo has this feature: https://github.com/microsoft/sample-app-aoai-chatGPT

**Comment by apiontek** [comment]
It looks like there was a [PR 259](https://github.com/Azure-Samples/azure-search-openai-demo/pull/259) related to this, but several months back. I haven't tried it myself but I wonder if the approach is sound or if there's a reason it hasn't been included.

**Comment by michbalazs** [comment]
This would be really helpful. Any update ?

**Comment by pamelafox** [comment]
We now have a chat history feature that stores it in IndexedDB:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md#enabling-chat-history

I'll close this issue, but if you want Cosmos DB persistence, please subscribe/star/comment on this issue:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/977
