### ISSUE TITLE
Unable to deploy sample code. Hangs on Search Service (Both VS Containers and Local)

### ISSUE THREAD

**Issue by BoostN** [Azure-Samples/azure-search-openai-demo#978]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Created new VS Code Dev Container. I selected East US 2, using my main Azure Subscription. I get the same error using VS Code Containers or just buy following the deploy local option.

### Any log messages given by the failure
> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'appserviceplan' is not valid according to the validation procedure. The tracking id is 'e809393d-1add-4cb1-8e4e-5b44dfea8ef9'. See inner errors for details.
ValidationForResourceFailed: Validation failed for a resource. Check 'Error.Details[0]' for more information.
SubscriptionIsOverQuotaForSku: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

TraceID: e3eb2ebe7062a79d8608e88384a5a291

### Expected/desired behavior
> The app to run

### OS and Version?
> Windows 11

### azd version?
> run `azd version` and copy paste here.

### Versions
>azd version 1.5.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Looks like it's hanging on app service, can you try a region where you have less app service plans already?

**Comment by BoostN** [comment]
> Looks like it's hanging on app service, can you try a region where you have less app service plans already?

Thank you for the fast reply, I have 0 app services deployed. We're a newer Azure user with only 1 resource group. I've manually deployed the OpenAI service with a search service and successful had the OpenAI Azure playground working fine, but using this tutorial I'm unable to get a deployment going so far.

**Comment by pamelafox** [comment]
Ah okay, are you on the trial subscription? You may need to upgrade to a pay-as-you-go subscription. You could try changing the app service sku to free tier but I suspect you'd run into other issues after that.

**Comment by BoostN** [comment]
> Ah okay, are you on the trial subscription? You may need to upgrade to a pay-as-you-go subscription. You could try changing the app service sku to free tier but I suspect you'd run into other issues after that.

I am on trial using the provided credits. If I do pay as you go will lose my credits?

**Comment by pamelafox** [comment]
Hm, I think you might, per https://azure.microsoft.com/en-us/free/free-account-faq/

"Can I skip the 30 days and just start with pay-as-you-go pricing?
Yes. You can sign up directly for [pay as you go](https://azure.microsoft.com/en-us/pricing/purchase-options/pay-as-you-go/). This will enable you to immediately use services beyond the free amounts at pay-as-you-go rates. You'll still get monthly free amounts of popular services for 1[2](https://azure.microsoft.com/en-us/free/free-account-faq/#F2) months2 and more than 55 services that are always free, but you won't receive the $200 credit."


So we can try to get it up on free plan. To change the app service sku, change this param of appserviceplan to F1:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/59b8cbd1a8bad3008572cf82a5494b653faf6a0b/infra/main.bicep#L134

Then, inside the params for app service:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/59b8cbd1a8bad3008572cf82a5494b653faf6a0b/infra/main.bicep#L145

add:

    use32BitWorkerProcess: true
    alwaysOn: false

**Comment by BoostN** [comment]
Thank for for that, running --debug flag on azd up I notice the following as it's going:

`  |   ====| Creating/Updating resources (Search service)2023/11/21 09:57:07 main.go:48: Response: ==> REQUEST/RESPONSE (Try=1/121.6794ms, OpTime=122.1831ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/4bf4ec0c-9be3-4a2a-8b97-4d76531d862e/resourcegroups/rg-azureai-demo1/deployments/appserviceplan/operations?api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources/v1.0.0 (go1.21.0 X:loopvar; Windows_NT),azdev/1.5.0 (Go go1.21.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: 6ac1af21a5962ce30a7da79222f6dc14
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 Not Found
   Cache-Control: no-cache
   Content-Length: 99
   Content-Type: application/json; charset=utf-8
   Date: Tue, 21 Nov 2023 15:57:07 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: 6ac1af21a5962ce30a7da79222f6dc14
   X-Ms-Failure-Cause: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: e9b5b548-c70c-458d-bb38-04cdeec79e95
   X-Ms-Routing-Request-Id: REDACTED

2023/11/21 09:57:07 main.go:48: Retry: response 404
2023/11/21 09:57:07 main.go:48: Retry: exit due to non-retriable status code
2023/11/21 09:57:07 azure_resource_manager.go:325: getting subscription deployment operations: deployment not found`

The job ends with the same overall error. When I look at the resource group dashboard, I can see only 3 services are created:

Document Intelligence, Search Service, and Storage Account. That lead me to believe the OpenAI Service isn't getting created properly, so I created that manually and set that using the instructions within the documentation, and it failed still with the same error.

**Comment by BoostN** [comment]
It seems upgrading to the Developer paid service has resolved my issues. Thank you for the help!

**Comment by pamelafox** [comment]
Okay, sorry it took a few tries! It seems that using the free trial isn't fully compatible with all the resources our infrastructure requires.
