### ISSUE TITLE
Unable to create Two App Services that use the SAME AI search (diff Index), Form Recognizer and OpenAI services, Through two diff deployment configs and codes

### ISSUE THREAD

**Issue by hicham-aigp** [Azure-Samples/azure-search-openai-demo#982]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Overwrite the `resourceToken` values in the main.bicep file for the modules `module appServicePlan` and `module backend` then run the `azd up` to deploy the app. 

### Any log messages given by the failure
> No error, just the new App Service doesn't work, but the existing one gets overwritten

### Expected/desired behavior
> Have Two segregated APP Services for two Different use cases but using the same backend services (search, form recognizer and openai)

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.
NA

### Versions
> NA

### Mention any other details that might be useful

I have already deployed a version of the app with indexed documents and everything is working as expected. But when i try to create another Service APP under a different name (hardcoded) and use the existing services (AI search, OpenAI, Form Recognizer and Storage Acc) within the same resource group, the final deployment gets the default value generated by the **resourceToken** in the main.bicep config. 

Everything goes well, the creation of the new index, processing and indexing of the new docs, but when it reaches `azd deploy` I don't know where the backendUri or app service endpoint gets overwritten! 
I looked into the .env variables but eveything in my code points to the new app-service name

![depl_code](https://github.com/Azure-Samples/azure-search-openai-demo/assets/151678483/9ace3915-1b8c-48ab-857c-af4499f8a6b5)
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/151678483/08fd4f30-5941-4a14-b406-66f53bc9d12a)

Did someone manage to deploy two different App Services with the same backend services ?
> ---------------------------------------------------------------

**Comment by hicham-aigp** [comment]
@pamelafox Any idea on how to accomplish this or what to change in the main bicep ? Thank you

**Comment by pamelafox** [comment]
So typically what I do is create multiple azd environments, and then use azd environment variables to reuse resources from the other environment.

If you run `azd env new` it'll create a new environment, and then you can use `azd env set` to set environment variables for what to reuse, as described here:
https://github.com/Azure-Samples/azure-search-openai-demo#deploying-with-existing-azure-resources

I haven't tried the approach you describe so am not sure why that's going awry, but there's an earlier issue with folks running into issues with similar approaches.
https://github.com/Azure-Samples/azure-search-openai-demo/issues/154

**Comment by hicham-aigp** [comment]
Thank you @pamelafox. It did work. I had to create a new env then change in the **main.bicep** in the backend module
`tags: union(tags, { 'azd-service-name': 'backend' })`
To
`tags: union(tags, { 'azd-service-name': 'backendlux' })`

Then in the `azure.yaml` in **line 7** change backend to **backendlux**

Thanks

**Comment by hicham-aigp** [comment]
Thank you @pamelafox. It did work. I had to create a new env then change in the **main.bicep** in the backend module
`tags: union(tags, { 'azd-service-name': 'backend' })`
To
`tags: union(tags, { 'azd-service-name': 'backendlux' })`

Then in the `azure.yaml` in **line 7** change backend to **backendlux**

Thanks
