### ISSUE TITLE
Chat answering to sample date after deleting it from storage

### ISSUE THREAD

**Issue by vperez-cognifit** [Azure-Samples/azure-search-openai-demo#987]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I used Northwind data first, then deleted it from storage and uploaded my own pdfs.
> Then I asked about Northwind data and it gives answers, it also shows the .pdf sources with the information

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
> azd version 1.5.0

### Mention any other details that might be useful
I deleted the Northwind files from the storage, and also run 'azd up' several times...

Thanks!

**Comment by pamelafox** [comment]
You need to remove it from the search index as well, please read our guide here:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/data_ingestion.md#removing-documents

**Comment by vperez-cognifit** [comment]
Thanks! I removed all and reuploaded my files!
