### ISSUE TITLE
How to change cognitive search service?

### ISSUE THREAD

**Issue by FabianAltendorfer** [Azure-Samples/azure-search-openai-demo#988]
Hi all,

I have a question regarding the Azure OpenAI Cognitive Search Service.

I've deployed to Azure and automatically selected the pricing tier "Standard" for the Cognitive Search Service, which gives me around 25GB of storage.
In my demo-usecase, I only need 18MB with one index, so the free-tier would be enough. However, I can't change the pricing tier of the cognitive search engine in Azure. Any suggestions on how I can transfer my service from a cognitive search service in pricing tier standard to a cognitive search service with another pricing tier?

Thanks, Fabian

**Comment by pamelafox** [comment]
We describe how to change the sku here:
https://github.com/Azure-Samples/azure-search-openai-demo/tree/main#existing-azure-ai-search-resource

However, as mentioned there, the free sku is not compatible as it doesnt support managed identity. You'd have to change code to use keys in order to use it.

**Comment by pamelafox** [comment]
I just merged a change that makes it possible to use the free tier:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1166

See doc here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_lowcost.md
