### ISSUE TITLE
DeploymentNotFound: Deployment 'monitoring' could not be found

### ISSUE THREAD

**Issue by nisc-clyde** [Azure-Samples/azure-search-openai-demo#990]
Upon constructing the repository within the VSCode environment on Windows, the terminal presents the following error:

**ERROR: Deployment failed: Action 'provision' execution failed, error encountered during the deployment of infrastructure: while deploying to subscription:**

**Deployment Error Details:**
**DeploymentNotFound: The deployment 'monitoring' could not be located.**

How might this issue be rectified?

> The error occurs after enter the `azd up`

**Comment by mirojs** [comment]
Same issue from the Codespaces:

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
DeploymentNotFound: Deployment 'monitoring' could not be found.

**Comment by pamelafox** [comment]
Can you try changing this line:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/5de99a33cb6c614b3587ff821d7bfabfa943597a/infra/main.bicep#L113

to just "core/monitor/monitoring.bicep"? i.e. remove the "./" in front of that path?

**Comment by pamelafox** [comment]
Ah, actually, change line 125 to:

module applicationInsightsDashboard 'backend-dashboard.bicep' = if (useApplicationInsights) {

**Comment by mirojs** [comment]
Still go the same error after employing the above changes.

**Comment by pamelafox** [comment]
You made both the changes from https://github.com/Azure-Samples/azure-search-openai-demo/pull/991 ?

Hm. You could also try enabling Application Insights before running azd up:

```
azd env set AZURE_USE_APPLICATION_INSIGHTS true
```

We will make that default for everyone soon as cost is low and it's quite helpful.

**Comment by mirojs** [comment]
After enabling the Application Insights, everything works like a charm!

Happy Black Friday Deals :)

**Comment by pyang-1981** [comment]
I don't think this issue is successfully solved. I am using the newest code.
