### ISSUE TITLE
Unauthorized Access Token Error when using AzureKeyCredential for Azure OpenAI API

### ISSUE THREAD

**Issue by saisescapades** [Azure-Samples/azure-search-openai-demo#994]
I am using managed identity to connect to all Azure resources (such as blob storage, cognitive search, etc.) except the Azure OpenAI service, as it is hosted on a separate azure subscription. I would like to use the Azure OpenAI key for the same. I have made the following changes:

1. Import AzureKeyCredential from azure.core.credentials.
2. Create a separate AzureKeyCredential with the API key for Azure OpenAI API calls.
3. Remove the ensure_openai_token function and the @bp.before_request decorator.

I have made sure that my API key works, and this approach used to work before. However, after some of the latest commits that have been made in the repo, I am just not able to get this to work. Any help will be much appreciated.

Highlights of my code changes below:

` 
      
    # Keep DefaultAzureCredential for Cognitive Search and Blob Storage  
    azure_credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True)  
  
    # Create a separate AzureKeyCredential with your API key for Azure OpenAI API calls  
    azure_openai_credential = AzureKeyCredential("your_api_key")  
  
    # ...  
  
    # Set up clients for AI Search and Storage  
    search_client = SearchClient(  
        endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net",  
        index_name=AZURE_SEARCH_INDEX,  
        credential=azure_credential,  
    )  
    blob_client = BlobServiceClient(  
        account_url=f"https://{AZURE_STORAGE_ACCOUNT}.blob.core.windows.net", credential=azure_credential  
    )  
    blob_container_client = blob_client.get_container_client(AZURE_STORAGE_CONTAINER)  
  
    # Used by the OpenAI SDK  
    if OPENAI_HOST == "azure":  
        openai.api_type = "azure_ad"  
        openai.api_base = f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com"  
        openai.api_version = "2023-07-01-preview"  
        openai.api_key = azure_openai_credential.key  # Use the AzureKeyCredential for OpenAI API calls  
    else:  
        openai.api_type = "openai"  
        openai.api_key = OPENAI_API_KEY  
        openai.organization = OPENAI_ORGANIZATION`
        
Below is the error I get:

ERROR:root:Exception while generating response stream: Invalid response object from API: '{ "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." }' (HTTP response code was 401)
Traceback (most recent call last):
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\app.py", line 142, in format_as_ndjson
    async for event in r:
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 264, in run_with_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\approaches\chatreadretrieveread.py", line 130, in run_until_final_call
    chat_completion = await openai.ChatCompletion.acreate(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 219, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_requestor.py", line 384, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_requestor.py", line 738, in _interpret_async_response
    self._interpret_response_line(
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[File Path Removed]\source\repos\azure-search-openai-demo\app\backend\backend_env\Lib\site-packages\openai\api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{ "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." }' (HTTP response code was 401)

**Comment by pamelafox** [comment]
I'm guessing the issue is this line:

openai.api_type = "azure_ad"  

It should be "azure" if you're using a key.

**Comment by beouk** [comment]
@saisescapades This is exactly what I'm after, would you be able to fork your changes?

**Comment by Shanthababu** [comment]
Excellent, Thanks!

**Comment by Rishabh7121999** [comment]
> I'm guessing the issue is this line:
> 
> openai.api_type = "azure_ad"
> 
> It should be "azure" if you're using a key.

Hello Pamela, I'm getting the same error. But instead I'm working with Azure Embeddings and creating a Vectorstore in CosmosDB.

```
azure_embeddings = AzureOpenAIEmbeddings(
    deployment="xyz",
    model="text-embedding-ada-002",
    openai_api_base="https://xyz.openai.azure.com/",
    openai_api_type="azure",
    )
    
vectorstore_page= AzureCosmosDBVectorSearch.from_documents(
    loaded_doc,
    azure_embeddings,
    collection=collection_page,
    index_name=INDEX_NAME,
)

AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com/), or have expired.'}
```
My code runs while using Huggingface embeddings.

I'm following Langchain's Azure CosmosDB implementation. They've used similar kind of embedding.

https://python.langchain.com/docs/integrations/vectorstores/azure_cosmos_db
