### ISSUE TITLE
Migrating to the OpenAI Python API library 1.x

### ISSUE THREAD

**Issue by bharatsb** [Azure-Samples/azure-search-openai-demo#996]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

OpenAI recently released a new version of the OpenAI Python API library on November 6th, 2023. The new SDK is a complete rewrite and is not backward compatible. It is recommended to upgrade this sample app to the new library version to ensure compatibility and leverage the latest features and improvements.

- OpenAI migration guide: https://github.com/openai/openai-python/discussions/742
- Azure OpenAI migration guide: https://aka.ms/oai/v1-python-migration
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for filing! We do need to make this upgrade, yes. Feel free to send a PR if you make the change yourself, otherwise we'll tackle it.

**Comment by tonybaloney** [comment]
I'll do this and submit a PR.

**Comment by bharatsb** [comment]
@tonybaloney Thank you handling this one and submitting the PR.
