### ISSUE TITLE
What files and content need changing when deploying with own material?

### ISSUE THREAD

**Issue by mronnlun** [Azure-Samples/azure-search-openai-demo#999]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Remove files from data folder and add own pdf documents
> Run azd up
> Textbox watermark and example questions are around Northwind employee benefits

### Expected/desired behavior
> Unclear what needs to be changed, apart from text in ui, to support own content. E.g. does text in chatreadretrieveread.py and retrievethenread.py need changing?

Would it be possible to create a folder with files with these texts instead of having them embedded in code?

**Comment by pamelafox** [comment]
Is it still unclear after reading through https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/customization.md ?

There is a separate issue about putting customizable aspects of the UI in a JSON file:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/650

**Comment by mronnlun** [comment]
This is now clear to me and if #650 moves forward then this can be closed.

**Comment by pamelafox** [comment]
Okay, I'll close this in favor of the earlier issue then.
